### ISSUE TITLE
Typing "gd" crashes

### ISSUE THREAD

**Issue by TimothyKrell** [onivim/oni2#1010]
When typing `gd` the editor immediately crashes. I'm assuming this is a bug. I was thinking this was the hotkey to jump to definition. Is that correct?

**Comment by bryphe** [comment]
Ouch, thank you for catching this and logging it @TimothyKrell . 

Looks like a bug with `libvim` (we have a 'callback' when `gd` is pressed, so that we can tie it into the VSCode extension integration - but it seems there is a bug in `libvim`, where, if no callback is specified, it crashes).

**Comment by bryphe** [comment]
Fixed the root cause here: https://github.com/onivim/libvim/pull/175

Next step though is to wire up this up to our language features

**Comment by TimothyKrell** [comment]
Awesome!

**Comment by bryphe** [comment]
`gd` now navigates to definition, when available in #1026
