### ISSUE TITLE
Bug: Quickopen not showing full set of results

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1037]
I just tried out the latest `master`, and am not seeing the full set of results in Quickopen:

Typing in `Diag`, I'd expect to see 4 files - but I only see two on `master`:

__Actual:__
![image](https://user-images.githubusercontent.com/13532591/70726827-8b4ca080-1cb3-11ea-9288-1cf49f877d73.png)

__Expected:__
![image](https://user-images.githubusercontent.com/13532591/70727921-5b060180-1cb5-11ea-9106-f1da031524fa.png)

I bisected and found:
- [`02e19ff`] (#1030) - not working
- [`9cfd7642`] (#1029) - working

So it looks like there was potentially a regression in #1030 - could you please take a look at this @glennsl ?

**Comment by bryphe** [comment]
Actually, I'm still seeing some inconsistent results with `9cfd7642` too... I went back to `b18bb5b9` and things are working consistently there. So there's a possibility it could be related to #1027 too

**Comment by glennsl** [comment]
Ok, so the problem is that I forgot that reaching `iterationsPerFrame` would cancel processing of the current "chunk". Previously the tail of the chunk would be put back on the "queue" each iteration to be taken off again on next iteration, but that doesn't work with a proper FIFO queue.

There are a few ways we can deal with this though:

1. Don't store chunks at all, but push items on the queue individually when adding a chunk. I don't know why this wasn't done to begin with. My guess is it's just because it was easier, but maybe there are other reasons. This would be the simplest option.

2. Store the "current" chunk separately from the queue.

3. Push the remainder onto the beginning of the queue to be processed last. Changing the order of processing shouldn't matter much since the filtered items are ranked anyway.

**Comment by bryphe** [comment]
> Previously the tail of the chunk would be put back on the "queue" each iteration to be taken off again on next iteration, but that doesn't work with a proper FIFO queue, so currently it's just forgotten.

Ah, nice catch - thank you for the investigation!

> Don't store chunks at all, but push items on the queue individually when adding a chunk. I don't know why this wasn't done to begin with. My guess is it's just because it was easier, but maybe there are other reasons. This would be the simplest option.

Originally I didn't have `chunks` (there'd be a `list(item)`), but the list + list concatenation was expensive when pushing large number of items. So the only concern was perf - if pushing items on the queue individually doesn't degrade perf, then it seems like the best approach 👍 

My preference is option 1, since it seems like the easiest solution - just need to make sure perf is OK for large folder structures. Option 2 would be a good fallback.

For perf, we have this benchmark to track filtering a lot of items:
https://github.com/onivim/oni2/blob/a6810a55b045311446542523d3877894756496a0/bench/lib/FilterJobBench.re

It would be worth adding a simple benchmark to measure `addItems` (right now, that's outside of the 'bench') and just compare the before and after with option 1 - this was where the bottleneck was that prompted 'chunking'.

**Comment by glennsl** [comment]
Oh wow, pushing items on the queue individually is actually several orders of magnitude slower. That is surprising. Good call on adding a benchmark for it. Pushing onto the queue should be O(1), so I really wonder what makes it so expensive.

I went with Option 3, as that's by far the easiest one. Basically a one-liner. But it isn't entirely intuitive and is based on an assumption that might not hold over time. So I added a comment to compensate :grin:

**Comment by glennsl** [comment]
I guess the proper thing to do is to create an immutable queue implementation that allows chunks to be pushed onto it and abstract away the whole chunkiness from the processing. That would also be significantly less error-prone than using a mutable data structure in the immutable `Job` framework.

**Comment by bryphe** [comment]
> Oh wow, pushing items on the queue individually is actually several orders of magnitude slower. That is surprising. Good call on adding a benchmark for it. Pushing onto the queue should be O(1), so I really wonder what makes it so expensive.

Woah, thanks for comparing the before and after!

> I guess the proper thing to do is to create an immutable queue implementation that allows chunks to be pushed onto it and abstract away the whole chunkiness from the processing. That would also be significantly less error-prone than using a mutable data structure in the immutable Job framework.

Great idea - would be nice to abstract that implementation detail, as it adds extra complexity across the job processing.

**Comment by glennsl** [comment]
Cool, I added a technical task for it.
