### ISSUE TITLE
Split view code completion dropdown duplicated

### ISSUE THREAD

**Issue by williamtstanley** [onivim/oni2#1045]
When editing in a split I see my code completion dropdown displayed at both my current cursor position AND my former one in the other split.

<img width="1645" alt="Screen Shot 2019-12-14 at 9 18 16 AM" src="https://user-images.githubusercontent.com/12862939/70852337-1618d100-1e55-11ea-92b3-681149913c4c.png">

**Comment by bryphe** [comment]
Thanks for logging the issue @williamtstanley and the screenshot!

Embarrassing... getting a fix out now 👍
