### ISSUE TITLE
UX - Polish: Completion Improvements

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1057]
We have some code completion now!
![image](https://user-images.githubusercontent.com/13532591/70870244-a8000700-1f45-11ea-88f3-6cdc89489f1f.png)

...but there are several UX issues we need to fix:
- There is no way to cycle through the completion items. We should handle the `suggestNextItem` and `suggestPrevItem` commands.
- Only a max of five items are shown (a lot of the same issues as the Menu!) - we should show a scrollbar and the full set of items.
- There are some formatting issues with the control, as shown above - we should either expand or clamp the text.

**Comment by yunti** [comment]
Could we make the icon in front of the completion option less prominent (or an option to remove it?). In some themes (ie the included one dark pro), it's bright pink. (
<img width="160" alt="image" src="https://user-images.githubusercontent.com/1826271/71814674-0e73d300-3075-11ea-9e8b-3871a21fe954.png">
