### ISSUE TITLE
running :e command on a directory crashes program

### ISSUE THREAD

**Issue by jplew** [onivim/oni2#1070]
## Problem

When I run `:edit ~/my/project` the whole program crashes.

According to the docs (https://onivim.github.io/docs/using-onivim/working-with-files), this is because `:e` is meant for opening files only, and `:cd` is intended for directories. Nonetheless, since this is the habit we've developed from using vim, this common error should be handled.

## Expected Behaviour

Running the edit command on a directory should fail gracefully, by either opening the directory in the Explorer section (like vim's netrw directory listing), or give a helpful message like: "You cannot use :edit on a directory. Did you mean :cd ~/my/project?"

## Reproduction

1. type `:edit ~/path/to/a/directory`

## My setup

**Onivim version:** MacOSX v2.0.2.0

**Comment by bryphe** [comment]
Thanks for logging the issue @jplew !

> Running the edit command on a directory should fail gracefully, by either opening the directory in the Explorer section (like vim's netrw directory listing), or give a helpful message like: "You cannot use :edit on a directory. Did you mean :cd ~/my/project?

Indeed - our plan is to have an explorer experience in this case (a useful scenario would be copying and pasting between explorers in splits). In the short term, though, we definitely should not crash.

This seems to reproduce on the packaged builds, but not the executable directly, which is interesting. In other words - if I run via `open -a Onivim2.app`, I can reproduce it, but running the executable directly via `Onivim2.App/Resources/MacOS/Oni2` does not exhibit it.

**Comment by bryphe** [comment]
Somehow, we're actually hitting this case in `FileExplorerStore`:

https://github.com/onivim/oni2/blob/776d87d72f902b2d4e3178f1f86488745ec80982/src/Store/FileExplorerStore.re#L33

It might have something to do with sandboxing when run via finder/`open`.

**Comment by jplew** [comment]
thanks for addressing that so fast :)

You guys are making huge strides, keep up the great work. Really looking forward to adopting Onivim as my main editor!
