### ISSUE TITLE
MacOS: Using the OS's mechanism for opening a file

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#1085]
I'm trying to set Oni2 as my main editor for other programs to launch as well based on extension. For example, opening a file from Alfred using Onivim2. Onivim2 will open, but without the file.

On the command line, it would be the same as `open -a /Applications/Onivim2.app ~/.zshrc`. The OS opens the program and tells it to open the file. But, Onivim2 is ignoring the request for opening the file. This is particular to macOS.

I can create Alfred actions to do it properly on the command line for me, but in the long run Onivim2 should work with the OS and it's methods of launching the file as well.

**Comment by leematos** [comment]
I attempted this today, and used --args to do so. The behavior varied:

- With a file:

 open -a /Applications/Onivim2.app --args /Users/lbot/.bash_profile

it renders the file but no sidebar:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/359140/75122804-730fdf00-566f-11ea-8956-358d799f9721.png">

If I pass in a folder, it renders the full app (ignore the messed up onilogo, was testing the logos on my branch:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/359140/75122823-963a8e80-566f-11ea-91f0-0280ff644a5f.png">

**Comment by raguay** [comment]
Try to use "Open with..." from Finder (or most other Finder type programs).
It doesn't open the file, just launches Oni2. Also, set Oni2 as your
default editor for a file extension and try to open that file by double
click. Again, it just opens the program. Oni2 should support these methods
of opening a file if it is to be a main stream editor.

**Comment by raguay** [comment]
Just a note of thanks. It is working great for me now. Thank you so much.
