### ISSUE TITLE
Reason for license change

### ISSUE THREAD

**Issue by mbitokhov** [onivim/oni2#11]
I just noticed that oni2 is licensed under a non-commercial license while oni is licensed under MIT. Out of curiosity, is there an official reason for the license change?

**Comment by davidpumpkins** [comment]
maybe this will help? https://github.com/onivim/oni2/blob/master/docs/MOTIVATION.md#a-new-model-for-sustainability

**Comment by mbitokhov** [comment]
Ah. I'm sorry, I didn't notice that file. That explains it nicely, thanks. I'm excited to see the progress of Oni2

**Comment by bryphe** [comment]
Yes, apologies I didn't communicate this out better! Some details here too around our ideas / plan: https://www.reddit.com/r/neovim/comments/ae7ef6/question_about_oni_2_license/ednq9hz

**Comment by vlcinsky** [comment]
Please, add these links to README.md as it is natural question of many adopters.
