### ISSUE TITLE
Logging: Test logging from multiple processes

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1107]
PR #1103 disables logging-to-a-file from the syntax server, but in theory we should be able to handle logging to a file from both:
https://github.com/onivim/oni2/pull/1103#issuecomment-568808838

This tracks implementing + testing the `open_out_gen` solution cross-platform, or, alternatively, setting up the syntax server to log to a separate file.

**Comment by glennsl** [comment]
FYI: Timber uses `open_out_gen` now, so this should no longer be an issue.

**Comment by bryphe** [comment]
Closing this, since with multi-core we won't need to log to multiple files.
