### ISSUE TITLE
Crash - Search: 'One-based index cannot be zero'

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1108]
When searching the Oni2 repro with a query like `state`, we hit a crash:

```
 Exception Invalid_argument("One-based index cannot be zero"):
Raised at file "src/Index.re", line 8, characters 14-82
Called from file "src/UI/SearchPane.re", line 59, characters 8-41
Called from file "list.ml", line 88, characters 20-23
Called from file "list.ml", line 88, characters 32-39
Called from file "list.ml", line 88, characters 32-39
Called from file "list.ml", line 88, characters 32-39
```

Past the `One-based index` error, there may also be a `StackOverflow` error.

**Comment by glennsl** [comment]
Interesting. The [offending piece of code](https://github.com/onivim/oni2/blob/master/src/UI/SearchPane.re#L57-L61) used to be 

```
Some((Index.ofInt1(hit.charStart), Index.ofInt1(hit.charEnd))),
```

and now is:

```
      Some((
        Index.fromOneBased(hit.charStart),
        Index.fromZeroBased(hit.charEnd),
      ))
```

So seems like they both should be zero-based and that there's an off-by-one error where this is used instead.

**Comment by bryphe** [comment]
Thanks for looking at it, @glennsl !
