### ISSUE TITLE
How to close the "find in files pane"

### ISSUE THREAD

**Issue by jfrolich** [onivim/oni2#1124]
Great work on Oni2, has come a long way since I last checked it out! Trying it as my main editor for ReasonML now.

I have no idea how to hide the "Find in files" pane 🤷‍♂️ Makes it significantly less usable for me because I need to restart after every time I use find in files. Probably a good one to document for other people that are looking for it (or add a UI affordance).

Talking about it it would be really cool to have the command pallete prefilled with all possible command + the associated keybindings (a bit like superhuman), so the less used vim commands are more easily discovered.

**Comment by kinglouie** [comment]
Clicking the icon in the sidebar should close the pane

**Comment by jfrolich** [comment]
Of course 🙈

**Comment by glennsl** [comment]
> Talking about it it would be really cool to have the command pallete prefilled with all possible command + the associated keybindings (a bit like superhuman), so the less used vim commands are more easily discovered.

It's planned. Coming soon :)
