### ISSUE TITLE
Extension - elixir-ls: Noisy autocompletion

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1133]
From discord:
> Perhaps no priority, but I am using Elixir in my backend, and the extension is working almost but the autocomplete triggers all the time, so tabbing to indent inserts code all the time (also I can't seem to select other options than the default option in the autocomplete list).

https://discordapp.com/channels/417774914645262338/417774914645262341/661439681900183562

It looks like we are not properly respecting completion settings (triggerCharacters) - we should examine what `triggerCharacters` are being used and ensure that we are respecting the language configuration settings.

**Comment by jfrolich** [comment]
It's actually this one:
https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls (it's the more elaborate extension).

**Comment by bryphe** [comment]
Thanks for the correction - updated title 👍

**Comment by bryphe** [comment]
Along with #2139 , this should be fixed now in #2202 . Let me know if you still see issues -

**Comment by dirksierd** [comment]
Unfortunately I can't get Elixir-LSP working on my OniVim-instance.
I'm runny pretty much a clean install macOS, just downloaded OniVim prerelease-build and installed the extension from inside the app.

I checked all available OniVim-documentation to figure out where I can read messages from the Development Console, but haven't had any success yet.

Thoughts?

<img width="593" alt="Schermafbeelding 2020-08-23 om 19 18 19" src="https://user-images.githubusercontent.com/68561/90984485-93b0e700-e575-11ea-87b0-cc43f9284415.png">

**Comment by bryphe** [comment]
Hi @dirksierd -

How are you launching Onivim? I wonder if this is related to https://github.com/onivim/oni2/issues/1161 - where when Onivim is not launched from the terminal, it's not getting the full-path.

A couple of ideas to try:
1) If you run `elixir --version` in the terminal, is it available?

2) If you add Onivim 2 to your path (Mac+Shift+P): 
![image](https://user-images.githubusercontent.com/13532591/91107602-8275e200-e62a-11ea-8df5-ed1c3742becb.png)

And then run `oni2 .` in your elixir project, from terminal, does it work? Running Onivim 2 from the terminal may workaround #1161 , and help the extension find the `elixir `command.

**Comment by dirksierd** [comment]
That actually works!

**Comment by bryphe** [comment]
@dirksierd - great news! Good idea to remove that folder.

> Is there somewhere I can check the output-logs to do some more debugging myself? It also still shows the elixir-lsp-elixir-ls is not compatible error.

Thanks for reminding me... We don't show this in the UI currently (although, it should show in the output if you run Onivim with the `-f --debug` arguments). Logged #2365 to track.

Glad that after removing the folder, autocompletion started working
