### ISSUE TITLE
Dec 31 is almost over....

### ISSUE THREAD

**Issue by pianocomposer321** [onivim/oni2#1140]
When is the alpha channel actually going to be open?

**Comment by bryphe** [comment]
Sorry for the delay of a more formal announcement, got a bit behind this week! Shooting to have a video + blog post for Friday.

We'll be shipping the alphas out of the same early access portal: https://v2.onivim.io/early-access-portal

**Comment by pianocomposer321** [comment]
Ok. Thanks. From all the other issues, it looks like you still have quite a bit of work to do. :-)
I'll check out the portal on Friday.

**Comment by bryphe** [comment]
> From all the other issues, it looks like you still have quite a bit of work to do. :-)

Totally! We have the basics in place, but still a lot of surface area left - tracking it here: https://github.com/onivim/oni2/issues/1058

**Comment by pianocomposer321** [comment]
Another question, how might I get an installer? On the Github main page, it says that the status is alpha, but there are still no listings in the releases section. The early access portal is only for if you need to buy a commercial license, as I understand.

**Comment by bryphe** [comment]
Finally got the collateral out:
- Post: https://www.patreon.com/posts/32839297
- Video: https://www.youtube.com/watch?v=eNNH1gBMaeY

So I'll close this out. Will follow up w/ the installer question in #1154
