### ISSUE TITLE
Launching from Python with subprocess.run() or os.system() leaves language highlight server running HOT.

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#1144]
# What I did:

I have a [fman](https://fman.io/) extenstion for launching my current editor specified in a file [Open With Editor](https://github.com/raguay/OpenWithEditor). In order to use it with Oni2, I had to add a line to launch the editor using the commandline. Since the modules are written in Python, I used the subprocess.run() command using the path `/Applications/Onivim2.App/Contents/MacOS/Oni2`.

# What happened:

It launches the editor just fine and doesn’t take up much memory or cpu. But, when I exit the editor in any way (`qall`, `wqall`, etc), the process `Oni2_editor —syntax-highlight-service` goes berserk and has to be forceably killed. I didn’t realize this at first and ran several instances (about 4) in this manner. Four of those services were left running at 90% cpu (I had a terminal with htop filtering for Oni2). The system would not respond to anything at all and I had to force power down.

# What I would expect:

Upon exiting the editor, it should kill any subprocess that it launches! When a subprocess sees it’s orphaned, it should terminate itself and not go berserk.

# Recreating:

I’ve tried to recreate this on a command line, but it doesn’t happen. Not sure what about the execution process is going astray for the Python subprocess, but it will not mimic on a normal command line.

**Comment by bryphe** [comment]
Thanks for all the details, @raguay ! I'll see if I can reproduce this. 

It sounds like a bug in our syntax highlight service - a case where the read threads start spinning in that particular case. It's curious that it only manifests via `subprocess.run` vs the command line.

**Comment by raguay** [comment]
Yes. It doesn’t seem to make sense to me at all. I’ve been having issues with rogue processes, mostly the macOS iconservicesagent going nuts. But, I found the culprit in Path Finder program. That company hasn’t found a solution yet.

I doubt it’s the same thing or even related, but I have been having many issues an I’ve finally resolved most of them. Since both are available on Linux as well, it would be interesting to see if it manifests on that OS as well. If not, it might be a macos issue as well.

**Comment by raguay** [comment]
Okay. I’ve done small scripts in python, python3, and ruby using their versions of running a subprocess. None of the small processes has any issue with oni2. It is only showing up when done from a subprocess inside of fman (which runs each extension in a subprocess). Therefore, it is looking like an issue in running in too deep of a subprocess stack (or something like that). I’ll poke at the author of fman about it.

**Comment by raguay** [comment]
I just mentioned this to the author of fman for his ideas as well. I have just update my Alfred workflow that uses the same files for launching my editor (https://github.com/raguay/MyAlfred/blob/master/Alfred%204/My%20Editor%20Workflow.alfredworkflow). But, it doesn't leave the syntax highlighter running. That one is a JSX script ran in a subprocess in Alfred.

Therefore, it is definitely a fman only issue that doesn't make any sense to me.

**Comment by raguay** [comment]
Okay, by experimenting I’ve found out all the weirdness of it. If I use `os.system()` to launch it, a zombie child is left. If I use `subprocess.run()` without a shell (default behavior), a zombie child is left. If I use `subprocess.run()` with a full command line string and the `shell=True`, then it exits like normal and no issues!

Therefore, I have my fman plugin fixed and working fine, but it could still be a potential issue for someone else when running the editor from a subprocess. Also, shouldn’t the `os.system()` be the same as running `subprocess.run()` with the `shell=True` flag enabled?

**Comment by bryphe** [comment]
Wow, thank you for the great investigation and all the details, @raguay !

Really glad you found a workaround in the meantime.!

> Therefore, I have my fman plugin fixed and working fine, but it could still be a potential issue for someone else when running the editor from a subprocess. 

For sure - it sounds like there still could be a bug in our syntax highlight server. As you mentioned, once the parent process is gone, the child process should quit too. So I'll keep this open to investigate-

**Comment by raguay** [comment]
I just did a fresh compile and changed my fman plugin to use the old method of running Oni2. It closed the process properly this time. Therefore, my test case is now passing. Thanks.

**Comment by bryphe** [comment]
Thanks for confirming! That’s great news - thanks for the fix @CrossR 🎉
