### ISSUE TITLE
macOS visual difference between nightly and build from source

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#1147]
There are two differences I spotted between the nightly build from the early access website and a source build.

1. On the nightly build the window titlebar gets rendered as if macOS is in light mode, if i build from source, the titlebar is rendered in dark mode, which would be the correct style since my system is also set to dark mode.

2. The window resize bug introduced by SDL (#896) is still present in the nightly, if I build from source the window content gets rendered but gets stretched as long as it is resized.

**Comment by bryphe** [comment]
The titlebar should be fixed now in #988 (it's custom themed, so should be consistent in both build from source & nightly build). Thanks for logging the issue, @kinglouie 

The window resize bug (#896 ) is still present - I'll close this one, but we'll use #896 to track the resize issue.
