### ISSUE TITLE
Will installers be made in releases?

### ISSUE THREAD

**Issue by pianocomposer321** [onivim/oni2#1154]
I tried once to build from source, and some of the prerequisites failed to install. It would be MUCH more convenient to have installers made and put in the releases section. I understand that they are available in the early access portal, but that's only if you need to pay for a license. I would be using it for personal reasons, not commercial.

**Comment by CrossR** [comment]
The current plan is to have builds available for everyone later on, with them being bonuses for backers at the start.

That could change, but that is how its working right now. There is obviously a tradeoff between giving builds out to show of what we've built, and giving thanks to our supporters for supporting us building this by giving them exclusive access to the builds.

**Comment by pianocomposer321** [comment]
When is later on?

**Comment by bryphe** [comment]
> When is later on?

This is TBD, but at least a couple milestones out.

We have several intermediate goals we want to tackle before we broaden out distribution: https://v2.onivim.io/index.html#timeline

> I tried once to build from source, and some of the prerequisites failed to install

Might be worth asking on our Discord! Someone may have seen the issue before and be able to help.

**Comment by pianocomposer321** [comment]
Ok, so I tried building again, and it appeared to be working. All the dependencies installed correctly, and the health check passed. However, when I tried to run it using "esy run", the window opens up, and then after a few seconds, crashes. Making a release version also fails.

**Comment by pianocomposer321** [comment]
I just checked the timeline, and I see that auto-closing pairs will not be implemented until March. I just got a pretty sweet VsCode setup, so I guess I can live with the vscodevim extension until March, at least. I will be looking forward to the final release as well!

**Comment by pianocomposer321** [comment]
So has it been decided yet? Will installers be made for the March 31 alpha build?

**Comment by pianocomposer321** [comment]
Any Update?

**Comment by pianocomposer321** [comment]
@bryphe It's certainly several milestones out now ;-). Is there any update on when this will be available as an installable package?

**Comment by CrossR** [comment]
I believe Trial Builds are on the timeline now: https://v2.onivim.io/index.html#timeline

**Comment by pianocomposer321** [comment]
@CrossR by trial builds do you mean a version with less functionality for people who are thinking about buying a commercial license to try it out before paying? Because if so, that's not what I mean. I mean a build for the free version, for those people who don't require a license because they'll be using it for personal projects only.

**Comment by bryphe** [comment]
>  I mean a build for the free version, for those people who don't require a license because they'll be using it for personal projects only.

No plans for unrestricted builds. We will have trial versions at some point: https://onivim.github.io/docs/other/faq#is-there-a-trial-version

Still thinking through what the delta would be in the trial - it could be the SublimeText way of basically an "Unregistered" text in the title and an occasional nag message, or there could be some functionality limited (ie, number of extensions installed). I'll have more info when we're closer to that point.

In the meantime - building from source would be the way to go: https://onivim.github.io/docs/for-developers/building
