### ISSUE TITLE
Extensions - Merge user configurations

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1157]
We've done work to set up extension configuration (#1106, #1111, #1119), but we're missing the last step of merging the user's configuration settings with the extension defaults.

This is blocking the Rust extension (and likely several others that require a configured toolchain, like the C++ extension)

Reported from Discord: https://discordapp.com/channels/417774914645262338/424012160696582144/662783028912717824

**Comment by glennsl** [comment]
Should be fixed by https://github.com/onivim/oni2/pull/1489
