### ISSUE TITLE
Command Palette and Quick Open not opening on chord keypress

### ISSUE THREAD

**Issue by Spirarel** [onivim/oni2#1160]
## What?
`Shift + CMD + P` and `CMD + P` do not trigger either of their UI elements to appear.
## Versioning
macOS 10.14.6
Onivim 2.0.3.0
## Notes
I posted to the discord under 'questions' it seems another user running Wayland is having the same issue.

**Comment by bryphe** [comment]
Thank you for logging the issue @Spirarel ! Sorry you hit this.

A couple questions:
- What keyboard layout are you using? 
- Are you running from 'Finder'?
- Do other inputs work?
- Do you have any custom configuration (`configuration.json` or `keybindings.json`), or this is just straight out-of-the-box?

**Comment by Spirarel** [comment]
- I'm using U.S. though I've tried it in bépo and Japanese, to no effect.
- I suppose I'm technically running from the finder–I open the app through the shortcut created on the app-view (f4)
- I can type in vim commands and get in and out of insert mode just fine.
- Straight out of the box. I can't even open the settings file, which leads me to believe cmd might not be propagating.

**Comment by yunti** [comment]
I have the same issue, onvim: 0.3.0 and macos 10.15
Quick open and command palette don't open but vim command and sneak shortcuts work ok. 
Launching from spotlight, finder mission control doesn't affect the issue. 
As above normal vim editing works ok.
