### ISSUE TITLE
Windows - CRLF line endings don't seem configurable / don't autodetect

### ISSUE THREAD

**Issue by lypanov** [onivim/oni2#1163]
As of now it seems that set ff/ffs unix/unix,dos doesn't appear to change anything about the saved file format. No matter what I tried I can't get a file to save without Windows line endings. Is there some setting I've missed or is this a bug?

**Comment by bryphe** [comment]
Thank you for logging the issue, @lypanov !

Indeed, we're missing this right now - we should be leveraging Vim's faculty for handling extensions. In addition, we should show the current line ending mode in the status bar.

**Comment by ijzerbroot** [comment]
If I may add to this one. it's not just that all files have CRLF but the behaviour is actually a bit more complicated than that.
On Windows, creating a new file in Oni2 and not setting anything will lead to Oni thinking the format is "dos" but the file will have \r\r\n line-endings (so: CRCRLF). Setting to ff=unix will lead to CRLF (so only Windows-style).
Consequently when a new file is created in oni (or an existing file edited and saved with ff=dos) it will have empty lines inserted after each line if you try to open it in another editor (I tried vscode and sublime).
This leads to having to set ff=unix in Oni to create CRLF files.
Setting ff=dos leads to files with lots of empty lines.

Unfortunately for me this is quite a showstopper for actual usage as not all my files are in git and line-endings do matter for bash-scripts.

**Comment by mrkishi** [comment]
I'm observing @ijzerbroot's behavior in `libvim` itself. I've cloned it and added this simple `write` test:

```c
#include "libvim.h"

int main(int argc, char **argv) {
	vimInit(argc, argv);

	// no difference:
	// vimBufferOpen("collateral/lines.txt", 1, 0);

	for (int i = 1; i < argc; ++i) {
		vimExecute(argv[i]);
	}

	vimExecute("w");
}
```

Compiling with `esy build; esy '@test' build`, with `original.txt` being an `lf`-ended test file:

```bash
cp original.txt collateral/lines.txt
./write.test.exe 'edit collateral/lines.txt' 'set ff=unix'
# lines.txt has crlf line endings

cp original.txt collateral/lines.txt
./write.test.exe 'edit collateral/lines.txt' 'set ff=dos'
# lines.txt has crcrlf line endings
```

Setting `fileformats` and `[no]binary` before opening the file makes no difference either.

**Comment by ijzerbroot** [comment]
Hello!

Just wondering if this issue is on the radar somewhere. Considering how well Oni2 otherwise already works, this is (for me) the main blocker for using it as a daily editor on Windows.
With it not honoring unix-style line-endings I can't locally edit bash-scripts on windows and have them work in WSL or Docker.

**Comment by CrossR** [comment]
All of the `daily-editor-blocker` ones are on the radar to be looked into and fixed before we move from Alpha into beta, so this will be picked up at some point!

**Comment by bryphe** [comment]
Thanks all for the help and the notes - indeed, there was a bug in libvim - https://github.com/onivim/libvim/pull/195

Working on picking it up and bringing it into Onivim 2

**Comment by ijzerbroot** [comment]
@bryphe Awesome! I honestly felt a bit nasty for pushing the issue since you're all already busy enough but this will be a game-changer for me 😋 Thanks for taking the time!
