### ISSUE TITLE
Command to trigger completion

### ISSUE THREAD

**Issue by romuloalves** [onivim/oni2#1172]
Could exist a command to trigger the completion.

I would use it, for example, when I didn't start typing but want to see the variables available to use inside de function I'm in...

I think it could be `Ctrl+Enter`, like other editors.

**Comment by Murtrag** [comment]
The way I do that in Vim is ctrl + n / ctrl + p(Already reserved for sth else) / ctrl + x to choose.
But doesn't work.

**Comment by bryphe** [comment]
We've actually hooked up both `Ctrl+Enter` and `Ctrl+N` as keyboard shortcuts, so this should be fixed by #2321  

We still need keyword completion though for files that don't have language support / a language extension installed. Tracking that here: https://github.com/onivim/oni2/issues/1862
