### ISSUE TITLE
Slash doasn't work in combination(d/<sth>, y/<sth>, c/<sth>)

### ISSUE THREAD

**Issue by Murtrag** [onivim/oni2#1176]
Hi
I find this key combinations(d/<sth>, y/<sth>, c/<sth>) really useful on a daily work with Vim, but unfortunately It doesn't work in Onivim2 
I'm not sure if this place is a good one to report bugs/suggestions so forgive me please.

**Comment by bryphe** [comment]
Looks like this was fixed by: https://github.com/onivim/oni2/pull/2680
