### ISSUE TITLE
Code completion 

### ISSUE THREAD

**Issue by luke-goddard** [onivim/oni2#1187]
Is code completion meant to work out of the box, tried on two different computers?
How do I enable it?

**Comment by CrossR** [comment]
What languages have you tried it for? We only ship with built in support for a few languages (ReasonML, JavaScript, TypeScript, CSS I think) and then for others you'd need an extension + any dependencies of that extension. 

That usually means installing some form of native binary for that language such as `clangd` for C/C++ or `gopls` for Go etc. Installing extensions is outlined [here](https://onivim.github.io/docs/configuration/extensions), although its worth considering that there is some ongoing work on setting up/merging extension configs for extensions, which blocks some extensions working at the mo (i.e. Rust lang server depends on you setting up paths, but that is currently being worked on).

General progress can be tracked here: https://github.com/onivim/oni2/issues/1058

**Comment by luke-goddard** [comment]
That makes sense, it was Python code so not type script.  The most frustrating thing about oni is the lack of documentation. Thanks for the ultra-fast response though :)
