### ISSUE TITLE
Entering insert mode and leaving it using escape does not move the cursor like vim does.

### ISSUE THREAD

**Issue by despairblue** [onivim/oni2#1194]
I made a video comparing neovim and oni2:

[i-escape.zip](https://github.com/onivim/oni2/files/4049855/i-escape.zip)

Basically doing `i` -> `escape` should move the cursor one character to the left, but doesn't in oni2.

**Comment by Apostolique** [comment]
Ah! That's the behavior I got from vscode vim (Cursor moving to the left.). I thought that was a bug.
