### ISSUE TITLE
Configuration.json file path if wrong on Windows

### ISSUE THREAD

**Issue by Samonitari** [onivim/oni2#120]
Hi!

After successfully building Oni on Win (10), it cannot be started:
Error message: 
`Fatal error: exception Sys_error("/mnt/g/Works/WorkForVS2017/oni2/assets/configuration/configuration.json: No such file or directory")`

No surprise that /mnt does not exists here.
By the way, earlier build (Feb.21) was able to start.

Keep up the good work please, I am thrilled by this project, and love the Oni(1)! 👍

**Comment by CrossR** [comment]
Hey!

I think I was the one that broke this....Copying over a message I sent on discord:

>Apparently a consequence of me swapping the bootstrap script from sh to bash means that I broke Windows support via cygwin? I don't fully know how, tho its possible its something to do with WSL etc?
>
>Turns out swapping to bash means the bootstrap paths aren't passed through cygpath so they are never made back into Windows specific formats, so we end up with /mnt/c/Users/ryan/.... paths, rather than C:/Users/Ryan/...

I'll swap it back to `sh` and just fix the script to remove the `bash` specific syntax. Long-term, doing this in js (since we bundle node) may be easier.

**Comment by Samonitari** [comment]
Thanks!

Quick fix worked.

Although trying to open package.json did crashed it again, because `oni2\src\textmate_service\lib\index.js` does not exists.
Where does oni2 store its last state, because now Oni2 stuck in this state - it reopens the last file by default?
Should I open an issue because of missing textmate stuff

I can help with testing regularly at least.
Maybe I can even do the packaging for OpenSuse (later, if first release is in sight)

**Comment by CrossR** [comment]
Ah! @Akin909 has mentioned this already actually, I think currently the recent textmate stuff is missing from the bootstrap script, so that will fail as well...

We need to add the building of that code into the bootstrap script, since currently it looks for a file that doesn't exist.

**Comment by Samonitari** [comment]
I see the revert landed in commit 51a2732
Thanks!
