### ISSUE TITLE
HealthCheck: Add health-check for extension host

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1213]
From @CrossR 's comment / investigation in #1212 - it'd be helpful for us to have a health check for the extension host initializing. This could help us identify build issues like #1212 more quickly.

We could create a health check that:
- Runs the extension host service
- Verifies we get some set of extensions activated
- Closes the extension host service
- Verifies the service closes

**Comment by CrossR** [comment]
As an extension to this, it would be nice if we could do some end-to-end testing of some set of extensions. Say run a script that installs a native client, then installs the Oni2 extension then runs some set input to exercise a completion is visible and actionable.

Would help us keep an eye on any issues, and also let us be more confident when someone asks "Does X language work?".

**Comment by bryphe** [comment]
> As an extension to this, it would be nice if we could do some end-to-end testing of some set of extensions. 

Definitely! We actually have some of this, in our integration tests:
- [LanguageCssTest.re](https://github.com/onivim/oni2/blob/master/integration_test/LanguageCssTest.re)
- [LanguageTypeScriptTest.re](https://github.com/onivim/oni2/blob/master/integration_test/LanguageTypeScriptTest.re)

These tests essentially run a 'headless' Onivim 2 (no UI), send input, and validate the state is what we expect. But they do validate some of the built-in extensions (simple validations - verify we get some diagnostics, and that we get completions), and they are run cross-platform as part of the build.

Is that similar to what you had in mind?

It'd be great to extend these with `Language<X>Test.re` to install additional extensions + validate them cross-platform as we unblock additional extensions.

**Comment by CrossR** [comment]
>It'd be great to extend these with Language<X>Test.re to install additional extensions + validate them cross-platform as we unblock additional extensions.

Yep, thats what I was thinking, I'd forgotten we had some already for some of the language servers. Extending it to cover a decent set of popular languages would be nice.

**Comment by bryphe** [comment]
We now fail the build if the extension host isn't installed, so this isn't really needed anymore (but would be great to have more language-integration tests!)
