### ISSUE TITLE
version mismatch between app and cli tool

### ISSUE THREAD

**Issue by snoblenet** [onivim/oni2#1221]
I've deleted all traces of Onivim2 for Mac, including in the `/usr/local/bin` directory, and re-installed with a fresh DMG download from the Early Access page.

When I select About Onivim in the app, it says it's version 0.3.0.

When I type `oni2 --version` at the CLI, it says it's version 2.0.3.0.

**Comment by glennsl** [comment]
Also, the usage printout says `2.0.2.0`, just for an extra bit of variation :laughing: 

That one's still hard-coded, and the `--version` prepends `2.` to the actual build number, which it probably shouldn't. I think it would be both easier and simpler to just consider `Onivim 2` the product name.

**Comment by snoblenet** [comment]
Ah. LOL. `version 2.0.3.0 === Onivim2, version 0.3.0`. Got it. :-)

**Comment by bryphe** [comment]
Thanks for the feedback @snoblenet ! 

> Also, the usage printout says 2.0.2.0, just for an extra bit of variation 😆

Ah, nice catch @glennsl , I missed this extra hard-coded place. 😄 I'll remove it for now to avoid confusion...

> I think it would be both easier and simpler to just consider Onivim 2 the product name.

Agreed! 👍
