### ISSUE TITLE
Add keybinding filter for more Vim modes

### ISSUE THREAD

**Issue by snoblenet** [onivim/oni2#1234]
In Neovim, this works well for me: `nmap - :NERDTreeFind<CR>`.

So in Onivim2, I tried: `{ "key": "-", "command": "explorer.toggle", "when": [["normalMode"]]}`

However, it has no effect.

Thoughts?

**Comment by CrossR** [comment]
I think your when clause may be wrong, using this seems to work for me:

```json
  { "key": "-", "command": "explorer.toggle", "when": "editorTextFocus" },
```

I think the docs around the when clause do need updating though...

**Comment by snoblenet** [comment]
Thanks. That works in normal mode, but means I cannot insert a hyphen in insert mode.

**Comment by CrossR** [comment]
Ah! That is true... we should probably just add a `normalMode` clause (or just the same as vim in general)

```
  { "key": "-", "command": "explorer.toggle", "when": "editorTextFocus && ! insertMode" },
```

Should work, and works in insert mode and the command menus, but the text box of the finder menu doesn't seem happy with it, which is odd considering it just a text box, and adding `!textInputFocus` doesn't help either.

I'll update this issue title to refer to adding new modes for the various vim modes. `normal`, `insert`, `visual` probably make the most sense to start with.

**Comment by snoblenet** [comment]
works a charm thanks
