### ISSUE TITLE
File Explorer - Windows: FocusNodeLoaded gets in infinite loop

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1238]
When opening a file, it seems the 'FocusNodeLoaded' action gets in an infinite loop (the logic that expands out the focused node in the file explorer).

Simple repro on Windows:
- Open Onivim 2
- Open Quickopen (`Control+p`)
- Type `Notification` 
- Open `Notification.re`

Here's a gif of the repro:
![editor](https://user-images.githubusercontent.com/13532591/72817904-6850cd00-3c1f-11ea-8e66-7a783d277320.png)

I suspect that the logic may not be accounting for the pathing in Windows - ie, the different path characters (`/` vs `\`). 

I also wonder if there should be some resiliency - ie, try X times to focus the node, and stop on failure. 

The editor is still usable, because the event is dispatched every frame, but it triggers a re-render every time which will hurt performance / battery life.

@glennsl - do you have any pointers on where to start looking at this?

**Comment by glennsl** [comment]
Is it particular to that file, or does it happen with any or most files?

The most likely suspect is `FsTreeNode.findNodesByPath`, and within that the `Utility.Path` functions. So adding a few unit tests for those, or just replacing it with `Fp`, as is the plan, seems like a good idea.
