### ISSUE TITLE
can't purchase the early access

### ISSUE THREAD

**Issue by cotko** [onivim/oni2#1246]
Hi, I have a mastercard that I use all the time and it never failed for any online purchase till now. When I try to purchase the license key, I get the error saying `your card is not supported` (and receive a SMS to my phone by the bank that it rejected the purchase).

My bank is using 3d secure and I successfully used the card with other web stores etc. that also use stripe API (I tend to notice whether site uses stripe/braintree etc. because of type of work I do..)

I it possible that you just need to enable this on your site, stripe has testing cards for this listed [on their documentation ](https://stripe.com/docs/payments/3d-secure) to check the 3d secure flows? Otherwise I'll need to borrow a working card from somewhere:)

**Comment by bryphe** [comment]
Hi @cotko ,

Really sorry about that! Thank you for all the details. I'll double-check our flow and make sure we're set up for 3d secure payments.

In the meantime - we do have a [PayPal link](https://www.paypal.me/outrunlabs/25usd) that you could use as well, if that's easier. That flow doesn't generate a key, but send me an e-mail at bryphe@outrunlabs.com and I'll make sure you get it.

Thanks for supporting the project!

I'll close this once I've verified w/ the test card that the 3d secure flow works 👍

**Comment by glennsl** [comment]
bump

**Comment by bryphe** [comment]
Thanks for the bump @glennsl ! Sorry for the lack of updates.

I'm actually investigating an alternate provider: https://paddle.com/  - seems like it has some extra features and more flexible checkout options than the way we're using Stripe today.

**Comment by bryphe** [comment]
I just rolled out the Paddle integration - so hopefully [3d secure](https://paddle.com/blog/what-paddle-is-doing-for-psd2/) is better supported. I'll close this for now - but we can track issues with Paddle in new issues.
