### ISSUE TITLE
Indentation is inconsistent with Vim and VSCode

### ISSUE THREAD

**Issue by Raikiri** [onivim/oni2#1253]
Small quirks of indentation are very hard to get right, however, they're crucial for both migration from editors and general workflow convenience. In my opinion, Oni2 does the job pretty well for its current state, but there's a couple of related things that it seems to do incorrectly. For example, if in VSCode or in neovim I hit: ```"{", <enter>, "}", <up>, <enter>```, it creates a new scope block and adds an indentation within it. However, Oni2 in this case just keeps the same indentation as the outer scope which means that I have to add indentation manually.

Same thing happens if I do this: ```"{", <enter>, "}", <up>, <esc>, "o"```. In this example "o" adds a line into the new scope block and it has no indentation appended either.

**Comment by bryphe** [comment]
Was just going through some of the auto-indent issues - and I believe this particular issue to be fixed now (with the auto-closing pairs behavior).

If not - let me know what filetype you're seeing this on 👍 

![2021-03-19 16 17 58](https://user-images.githubusercontent.com/13532591/111850915-c8e4a400-88ce-11eb-867b-e42b1dc866c2.gif)
