### ISSUE TITLE
Support file and folder drag-and-drop

### ISSUE THREAD

**Issue by Raikiri** [onivim/oni2#1254]
It would be convenient to have behaviour similar to what VSCode does where if you drag and drop a file from explorer onto the editor, it just opens it. If you drag and drop a folder, it opens it as a workspace.

**Comment by bryphe** [comment]
Related to #586 - @zbaylin is adding primitives to Revery to support this.

**Comment by zbaylin** [comment]
The first part has been in Oni for a while now, but the directory/folder dropping I'm adding in #2155!

**Comment by zbaylin** [comment]
Since #2155 is merged, I'm going to close this now. Let us know if you have any other issues!
