### ISSUE TITLE
Having menu in window caption

### ISSUE THREAD

**Issue by Raikiri** [onivim/oni2#1255]
VSCode has in my opinion a vital feature for any modern editor: a menu that's embedded into the window caption to save space:
![image](https://user-images.githubusercontent.com/1657728/73115020-36c06480-3f85-11ea-9b60-ed4fbb924a89.png)
It respects UI theme too.

I think it might be worth implementing something similar in Oni2 once it gets its own menu.

**Comment by bryphe** [comment]
We now have a (basic) menu implemented on Windows in #2849 👍  Will be ongoing work to add / augment it with more commands.
