### ISSUE TITLE
Same weird font rendering as seen in Firefox (Debian 10)

### ISSUE THREAD

**Issue by marcelocra** [onivim/oni2#1260]
Hey there. I saw a [similar issue](https://github.com/onivim/oni2/issues/774), but not sure if this should be a dup or not. The file tree is really fonky in Debian 10, just like Firefox.

**Comment by bryphe** [comment]
Hi @marcelocra !

We just changed our font rendering to use Skia (https://github.com/onivim/oni2/pull/1206)- so it could be improved. Would you mind checking in the latest build?

**Comment by szbergeron** [comment]
@marcelocra are you by any chance using fractional scaling on Kde on Wayland?

**Comment by marcelocra** [comment]
@bryphe 
Thanks for the response and sorry for the delay. It is better now :).

@szbergeron  
No, I'm not. I'm using Cinnamon on X.
