### ISSUE TITLE
Opening Multiple windows on macOS: Not able to bring up the first window`

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#1268]
# Setup

Open two different Oni2 windows. Use `<cmd>+tab` and try to bring the first window to the top.

# Expected Results

`<cmd>+tab` should be able to be used to switch between the two windows. 

# Actual Results

Only the last opened window can be brought to the front using `<cmd>+tab`.  You have to hunt down the other window from the stack of window and click on it to ever see it. Or, close the Oni2 window that will come forward and then you can cycle around to the other one.

Not sure if this is related or not, but using alternate Docks causes the exact same behavior. Since I don’t ever use the macOS Dock, I’m not sure if it does or not. But, I’m sure it will behave in the same manner.

The `uBar` Dock replacement program has the same functionality, but causes a new window to be open every time it is used to bring up an existing window to the front. This is very annoying. 

While the `Keyboard Maestro` “dock” (application list window) will only bring the last opened Oni2 window and never the first one. But, at least it doesn’t open a new window! `ActiveDock` behaves in a similar manner to `Keyboard Maestro` except only the first window opened is brought to the foreground.

**Comment by leematos** [comment]
Can you elaborate on how you are opening two Oni2 windows? On my Mac I'm not able to get multiple running to validate this.

-If I click on the app in my normal doc, I get one instance. I can't start another
-If I open one from my applications folder, and then a dev build, I get two separate instances running, and both are in my cmd+tab options.

<img width="1167" alt="Screen Shot 2020-02-23 at 8 05 45 PM" src="https://user-images.githubusercontent.com/359140/75123715-02b98b80-5678-11ea-82dd-9e94ea85b10b.png">

**Comment by raguay** [comment]
The extra launching was due to a new Dock replacement. Not the normal Dock.
I sent him a notice about it.

But, When I have two instances of Oni2 running, I can only bring to the
front the last one. Both are viewable in the cmd+tab and dock, but only the
last one opened is brought to the front. The other one has to be manually
fronted by moving the other windows and clicking on it.

**Comment by raguay** [comment]
The current build of Oni2 allows me to switch between multiple instances of the Oni2 editor using cmd-tab just like I would expect. Thanks for that!

But, on the uBar and ActiveDock Dock replacement programs, clicking on the icon brings the application forward and launches a new copy of the application. On programs that are replacements for cmd-tab handle things correctly. I would assume it was a failure of the Dock replacement programs, but no other program I have (over 100) has this problem.

**Comment by zbaylin** [comment]
I think this is an issue with us specifying `Oni2` as the executable in the `Info.plist` for Oni. We're working on migrating the executable to `Oni2_editor` for a separate issue, and I'll be curious to see if you have the same issues once that happens.

I'll keep you posted! Sorry you're having this issue!

**Comment by zbaylin** [comment]
@raguay I downloaded and tested the new builds with uBar and it seems to work as expected now. As for the multi-window/instance bug, since this isn't supported behavior as of now, I think we should close this issue for now. If you have another issue with the dock replacements, I would recommend opening a new issue since this one is only tangentially about that.

Thanks again!

**Comment by raguay** [comment]
Thanks. I'm traveling right now and can't test the new build. But, I will
put it through the works when I get home. It's the only editor I use right
now.

Thanks.
