### ISSUE TITLE
viml commands are interpreted in reverse order

### ISSUE THREAD

**Issue by tristil** [onivim/oni2#1272]
`experimental.viml` commands in `configuration.json` are processed in reverse order. This also happens with `files.exclude`.

e.g.

```json
{
  "experimental.viml": [
    "do this first",
    "do this second"
  ]
}
```

would be evaluated as `do this second`, `do this first`

**Comment by bryphe** [comment]
Wow, already fixed in #1273 , with a test - thank you @tristil!
