### ISSUE TITLE
Editor doesn't scroll viewport far enough to show the cursor when positioned on last character of a line

### ISSUE THREAD

**Issue by tmarkettos** [onivim/oni2#1275]
If I type a line of text, there's one more character outside the viewport that I can't see:

![image](https://user-images.githubusercontent.com/12303948/73352014-1dbafa80-4288-11ea-9fac-02c80e479148.png)

In this example there's a character 'w' in 'two' that's off the right side of the display, along with the cursor.  The cursor can go outside the viewport and I can't see it or the characters that I'm typing.
If I move the cursor back into the right side of the viewport there's one character to the right of it that I can't see.  I can only see that character if I delete enough so that the whole line fits inside the viewport.

I've also had this happen when creating a new file where the file contents are entirely off screen, so it looks like I'm typing blind but if I save the file the keystrokes do appear in it.

Route to duplicate:
1. Start Onivim2
2. `:e /tmp/foo.txt`
3. Type a line of text

Fairly stock MacOS Mojave, fresh download of 2020-01-29 nightly, no configuration changes.

Possibly related to #760

**Comment by raguay** [comment]
I might add that the highlighting of match {} totally messes up when one brace is too far to the right to be seen. We really need a horizontal scroll bar!

**Comment by bryphe** [comment]
This issue should be fixed now with #2597 - feel free to open a new issue though if you're still seeing weirdness here 👍
