### ISSUE TITLE
getting "dune: I dont know about package" error in 'esy bootstrap command'

### ISSUE THREAD

**Issue by dineshKumar777** [onivim/oni2#1281]
I got the latest source and tried to build but getting the mentioned error. To verify, I tried the same in new machine but still getting same error for different package.
Anyway to rectify this?
esy version: 0.6.2

```
D:\oni2_2\oni2>esy bootstrap
info building @opam/ppxfind@opam:1.3@262387fc
info building esy-skia@github:revery-ui/esy-skia#91b10c9@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/ppxfind@opam:1.3
    # esy-build-package: pwd: C:\Users\vdinesh\.esy\3\b\opam__s__ppxfind-opam__c__1.3-08e0991b
    # esy-build-package: running: "dune" "build" "-p" "ppxfind" "-j" "4"
    Info: Creating file dune-project with this contents:
    | (lang dune 1.11)
    Error: I don't know about package ppxfind (passed through
    --only-packages/--release)
    error: command failed: "dune" "build" "-p" "ppxfind" "-j" "4" (exited with 1)
    esy-build-package: exiting with errors above...

  building @opam/ppxfind@opam:1.3
esy: exiting due to errors above
```

In another machine. getting error as above for ``` mmap@opam:1.10 ``` pack

**Comment by dineshKumar777** [comment]
Any updates on this..? 
Tried again today with latest but getting the same error 😑

**Comment by CrossR** [comment]
What OS is this on? Would also be worth deleting both the `_esy` and `C:\Users\...\.esy` folders, and pulling down the latest master.

I've not seen this error before, which is odd. Doesn't look to really be related to skia at all, but who knows.

**Comment by glennsl** [comment]
Closing due to staleness
