### ISSUE TITLE
Skia+Wayland blue window

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#1283]
New (afaik) in #1206 
![2020-02-01-115730_grim](https://user-images.githubusercontent.com/7364398/73595773-3b879a00-44ea-11ea-987a-31ed6987b0d9.png)

**Comment by bryphe** [comment]
Fixed now with https://github.com/revery-ui/revery/pull/751 - thanks for your help testing, and for catching this, @szbergeron !
