### ISSUE TITLE
Ligature stylistic sets support

### ISSUE THREAD

**Issue by opeik** [onivim/oni2#1294]
Hi,

[From the Fira Code wiki:](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets)
> Stylistic sets allow you to access additional, optional parts of the font on a per-feature basis. In Fira Code, they allow you to enable/disable alternative character variants.

This makes switching font features quick and easy compared installing additional fonts. Would you consider adding this to Onivim2?

**Comment by bryphe** [comment]
Related to: #584  (which is specific to ligatures)

Would be great to have this feature. We'd need to extend our [`reason-harfbuzz`](https://github.com/revery-ui/reason-harfbuzz) library to add an API to specify [OpenType Features](https://harfbuzz.github.io/shaping-opentype-features.html) during shaping, and then pick up those via a configuration setting.
