### ISSUE TITLE
How can I build this project from source ?

### ISSUE THREAD

**Issue by raaffaaeell** [onivim/oni2#1300]
Hello, I'ld like to try this project in some way before buying the license. Ever since the first alphas went out I thought these branches would work following the guide, but no. Over the past month I tried 3 times and always the bootstrap process throws an error.

```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: reason-libvim@github:onivim/reason-libvim#3782892
    # esy-build-package: pwd: /home/rafael/.esy/3/b/reason_libvim-6080df6b
    # esy-build-package: running: 'refmterr' 'dune' 'build' '-p' 'libvim'
        discover src/c_flags.sexp,src/cxx_flags.sexp,src/flags.sexp
    -L/home/rafael/.esy/3/i/libvim-8.10869.29-f30ea932/lib
          ocamlc src/bindings.o
    bindings.c: In function 'libvim_vimInit':
    bindings.c:264:22: warning: passing argument 1 of 'vimSetGotoCallback' from incompatible pointer type [-Wincompatible-pointer-types]
      264 |   vimSetGotoCallback(&onGoto);
          |                      ^~~~~~~
          |                      |
          |                      void (*)(gotoRequest_T) {aka void (*)(struct <anonymous>)}
    In file included from bindings.c:1:
    /home/rafael/.esy/3/i/libvim-8.10869.29-f30ea932/include/libvim.h:115:38: note: expected 'GotoCallback' {aka 'int (*)(struct <anonymous>)'} but argument is of type 'void (*)(gotoRequest_T)' {aka 'void (*)(struct <anonymous>)'}
      115 | void vimSetGotoCallback(GotoCallback gotoCallback);
          |                         ~~~~~~~~~~~~~^~~~~~~~~~~~
        ocamlopt src/vim.cmxs (exit 2)
    (cd _build/default && /home/rafael/.esy/3/i/ocaml-4.8.1000-e74c5c0d/bin/ocamlopt.opt -w -40 -g -shared -linkall -I src -o src/vim.cmxs src/vim.cmxa)
    /usr/bin/ld: cannot find -lICE
    /usr/bin/ld: cannot find -lSM
    /usr/bin/ld: cannot find -lXt
    collect2: error: ld returned 1 exit status
    File "caml_startup", line 1:
    Error: Error during linking
    error: command failed: 'refmterr' 'dune' 'build' '-p' 'libvim' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building reason-libvim@github:onivim/reason-libvim#3782892
```

Is it possible to build just cloning or theres something else ? 

I'm on linux, cannot get past the bootstrap process

**Comment by glennsl** [comment]
Yes, it should be possible. You seem to be missing some prerequisites though, libice, libsm and libxt, all related to X11/Xorg. Which linux distro and window system are you using?

**Comment by glennsl** [comment]
Have you followed the build instructions in https://onivim.github.io/docs/for-developers/building, and in particular installed the prerequisite dependencies listed on https://github.com/revery-ui/revery/wiki/Building-&-Installing?

**Comment by raaffaaeell** [comment]
I'll check all the dependencies again, I'm currently on fedora 30, will get back to this issue once I make sure I installed it all, I just opened because of the error pointing to somthing in libvim (which I could build properly)

**Comment by raaffaaeell** [comment]
After going through the revery dependencies for fedora, I had to install the xorg-devel one, but still the same error

**Comment by glennsl** [comment]
Are you sure it's the same error? Does it still list these?
```
    /usr/bin/ld: cannot find -lICE
    /usr/bin/ld: cannot find -lSM
    /usr/bin/ld: cannot find -lXt
```

**Comment by raaffaaeell** [comment]
After a bit of google, I can see these are already installed at /usr/lib64/

Should I add this one to the $PATH ?

**Comment by glennsl** [comment]
No, you shouldn't need to do anything like that. We have a CI machine that uses a CentOS docker image. I would think the steps you need to do would be very similar to this: https://github.com/onivim/oni2/blob/master/scripts/docker/centos/Dockerfile

**Comment by glennsl** [comment]
I see that lists libICE-devel, libSM-devel and libXi-devel separately. Perhaps we're missing some dependencies int he documentation. Could you try installing those?

**Comment by raaffaaeell** [comment]
Indeed it worked, I had to install all those fedora dependencies plus these, now I'll see if the rest of the procedure works, thank you very much

**Comment by glennsl** [comment]
Great! I'm not sure if these are revery dependencies or exclusive to oni2, but seems we need to update some doc or other. @bryphe?

**Comment by raaffaaeell** [comment]
Can confirm, after installing these 3 you mentioned (plus the other 1 I was missing) it could bootstrap/build and create a release. Sadly I wont be able to use much now, but later I'll try it for sure, been waiting for months for this, probably buy it once I get the money

Thank you very much

**Comment by CrossR** [comment]
>Great! I'm not sure if these are revery dependencies or exclusive to oni2

It looks to be `libvim` related, so probably just Oni2. The Oni2 Linux deps are basically just the ones I noticed when building in Ubuntu, so its very likely there is missing things for other distributions.

**Comment by glennsl** [comment]
Alright, thanks @CrossR. I'll add them to the oni2 docs then.

**Comment by glennsl** [comment]
Fixed by https://github.com/onivim/oni2/pull/1301
