### ISSUE TITLE
Git: There are no available repositories after installing extension

### ISSUE THREAD

**Issue by raaffaaeell** [onivim/oni2#1304]
When I try to open a .java file after installing the redhat extensio, it keeps showing this message after each character inserted

https://marketplace.visualstudio.com/items?itemName=redhat.java

It shows installed, shows in the --list-extensions, but this message keep stacking

![screenshot](https://imgur.com/knSBenU.png)

**Comment by CrossR** [comment]
I'm able to reproduce in a just a normal text file, if I open it up in somewhere that isn't a git repo.

I would guess that we are running some check / asking for info from the Extension host without a check, so we constantly ask for the git status when there is no git repo for some files.

**Comment by glennsl** [comment]
Yeah, we execute the `git.refresh` command on every `BufferUpdate`, which is wrong for several reasons:

1. `BufferUpdate` is way too frequent, but we don't have any `BufferSaved` event yet, do this is the best approximation I could find.
2. Hard-coding `git.refresh` will obviously only work for the git extension, not any other SCM extensions. There has to be some other mechanism to trigger a "refresh", but I have no clue what that is yet.

**Comment by glennsl** [comment]
As a workaround for now, we could probably just check whether are any repositories before triggering the refresh.

**Comment by raaffaaeell** [comment]
Silly me, unfortunately I didnt add the git repo so I could test the extension, when I get back from work I'll try it. Is it possible that this was preventing it from starting ? Cause whenever it tried to complete, it always showed this message

**Comment by glennsl** [comment]
No, that shouldn't have any effect on it. It's not even an error, just an informational message. It's much more likely that there's some other cause, as there's plenty of holes in the extension support we provide at this point. The best way to see the extension has failed is to turn on logging, either with `-f` to print to the console or using `--log-file <filename>` to write to a file. It should say something along the lines of "Failed to activate extension redhat.java" if something went terribly wrong. If there's no other log message to indicate what might have gone wrong you could try adding `--debug` to get more detailed logging, or `--trace` to get excruciatingly detailed logging.

**Comment by raaffaaeell** [comment]
The only things related to java that I can find with these flags is this

[WARN]    +55ms Oni2.Extensions.ExtHostClient : Unhandled message - [MainThreadWorkspace:$startFileSearch]: ["*.java",null,null,1]
[WARN]     +2ms Oni2.Extensions.ExtHostClient : Unhandled message - [MainThreadWorkspace:$startFileSearch]: ["{src, test}/**/*.java",null,null,1]
[WARN]    +14ms Oni2.Extensions.ExtHostClient : Unhandled message - [MainThreadOutputService:$register]: ["Language Support for Java",false,{"$mid":1,"path":"/home/rafael/output_logging_20200207T164814/2-Language Support for Java.log","scheme":"file"}]
[WARN]     +0ms Oni2.Extensions.ExtHostClient : Unhandled message - [MainThreadOutputService:$register]: ["Language Support for Java",false,null]
[WARN]    +22ms Oni2.Extensions.ExtHostClient : Unhandled message - [MainThreadExtensionService:$localShowMessage]: [3,"Activating extension 'java' failed: The language client requires VS Code version ^1.40.0 but received version 1.33.4."]

**Comment by glennsl** [comment]
Hmm, yeah i don't know how much effort we need to put in to upgrade the extensions host, but this could become a problem with many extensions over time. @bryphe?

**Comment by glennsl** [comment]
Fixed in #1310. Not a proper fix, really, but it does do away with this issue at least. Thanks for reporting!
