### ISSUE TITLE
[Mac / Windows] Weird scaling when resizing the window.

### ISSUE THREAD

**Issue by mhanberg** [onivim/oni2#1318]
Whenever I resize the window, the content stretches or squishes until you release the cursor.

![oni2-resizing-bug](https://user-images.githubusercontent.com/5523984/74170128-6bc1ed80-4bfa-11ea-8891-5094d0424f13.gif)

**Comment by bryphe** [comment]
Thanks for the gif and logging the issue, @mhanberg !

This is SDL2's 'default' handling for resize - it stretches the framebuffer, and then once the resize gesture is compelte, it gives us a `WindowResized` event.

We'll need to hook into a handler that updates us as the window is resized - looks like there is a suggestion here: https://stackoverflow.com/questions/34967628/sdl2-window-turns-black-on-resize/34996764

**Comment by SeparateRecords** [comment]
The weird scaling seems to be fixed on macOS for me, although it's still present on Windows. Should this issue be closed or is there more investigation needed?

**Comment by bryphe** [comment]
Thanks @SeparateRecords for the update! Indeed, this should be fixed on Mac now with @zbaylin 's change: https://github.com/revery-ui/revery/pull/1077
