### ISSUE TITLE
[Mac] Sidebar items are not clickable

### ISSUE THREAD

**Issue by mhanberg** [onivim/oni2#1319]
The project drawer, scm, and extension side bar menus do not open when clicked. Oddly the search does appear. I have noticed this in several builds from the last couple weeks.

![oni2-sidebar-bug](https://user-images.githubusercontent.com/5523984/74170482-f6a2e800-4bfa-11ea-8018-98e0f24217ae.gif)

**Comment by bryphe** [comment]
Ah, looks like this may be the same issue as #1216

**Comment by bryphe** [comment]
This should be fixed now with #1322 . Feel free to re-open if that is not the case 👍
