### ISSUE TITLE
Remember folder and file(s) from last session

### ISSUE THREAD

**Issue by eliasnystrom** [onivim/oni2#1326]
It would be great if Oni would remember what folder or file(s) were open in the last session and automatically open them the next time it launches, in order for the user to get up to speed quicker. This would help reduce `cd:`-ing to the same path.

**Comment by glennsl** [comment]
Thanks for reporting, but as this is covered by #640 I'll close this as a duplicate. You may want to give that an upvote to increase its priority.

Also somewhat related to #906
