### ISSUE TITLE
Enhancement: Native textmate service

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#133]
For our textmate syntax / VSCode theme support, we rely on the [`vscode-textmate`](https://github.com/microsoft/vscode-textmate) module. This was very helpful because it got us up-and-running and parsing syntaxes very quickly - however, it means we are delegating syntax highlighting to a separate Node process (not desirable for either perf or memory).

`vscode-textmate` is, in essence, a wrapper around the [`oniguruma`](https://github.com/kkos/oniguruma) C regex library.

What would be ideal is to have a ReasonML version of `vscode-textmate` that talks to `oniguruma` via th OCaml C FFI - we'd be able to host that in-proc (minimizing buffer duplication).

**Comment by Akin909** [comment]
@bryphe is this a duplicate of #161?

**Comment by bryphe** [comment]
Putting this on backlog
