### ISSUE TITLE
Default navigation menu font is ugly

### ISSUE THREAD

**Issue by Sheepolution** [onivim/oni2#1338]
The font used for the navigation menu, tabs, command palette and more, has always looked weird to me.

I took a screenshot along with Sublime Text to compare the fonts. To me, Sublime Text's menu font looks way cleaner and I have less trouble reading it (besides that it's darker).
![image](https://user-images.githubusercontent.com/2232780/74668160-ea8fcb00-51a4-11ea-9543-57adc5dd6c8f.png)

At first I thought this was because the Onivim font is smaller, but when I compare the fonts better, I found that they're the same size.. Except that Onivim's font has wider spacing.
![image](https://user-images.githubusercontent.com/2232780/74668557-be287e80-51a5-11ea-9919-8767e87a8378.png)

Still, I don't like the current font. Especially the 'e'.

I'd like to open this issue as a way for others to share their opinion on this. Perhaps I'm the only one who thinks this. If that's the case I hope in the future it will be possible to configure this font.

**Comment by glennsl** [comment]
You seem to be using a version of Oni2 that's at least several months old. We've recently switched rendering engine, partly to get better text rendering. And I think we've even changed font since then. Would you try with the latest nightly to see how that works for you?

**Comment by Sheepolution** [comment]
Whoops, sorry about that.
I updated Onivim, but the problem still stands.
Here are some more screenshots:
Onivim2 / Sublime Text / VS Code
![image](https://user-images.githubusercontent.com/2232780/74675365-af48c880-51b3-11ea-9640-25e3632b1810.png)
![image](https://user-images.githubusercontent.com/2232780/74675650-41e96780-51b4-11ea-85d5-9f458194faeb.png)

Well, I'm not sure how this happened, but it looks even worse.
The 'e' is now all blurry. And at the top/bottom there are these pixels sticking out.

The latter also appears in the font for extensions (which seems to be a different and bigger font). I have to say that the extension icons could use a clean up as well, but that should probably be its own issue.
![image](https://user-images.githubusercontent.com/2232780/74676052-609c2e00-51b5-11ea-93a4-6e5101bef096.png)

**Comment by glennsl** [comment]
Yeah, that's definitely worse. The font was changed about a month ago, in #1182, but just at a convenient way to get additional styles. The legibility of the UI font doesn't seem to have been given much weight yet, and I think the font rendering improvements with Skia has mostly been focused on the editor font.

I'm not sure what requirements we have for the UI font (@bryphe?), but suggestions for good alternative fonts to try would certainly be appreciated. Preferably ones that are freely licensed.

**Comment by Sheepolution** [comment]
@glennsl I downloaded the newest version and see changes have been made to the font. In my opinion it looks fine and this issue can be closed.

**Comment by bryphe** [comment]
Thanks for the update, @Sheepolution !
