### ISSUE TITLE
Go to definition opening an empty file

### ISSUE THREAD

**Issue by Sloff** [onivim/oni2#1343]
Hi, when using "gd" to go to the definition of something it opens the correct file, but the file looks empty. When manually opening the file everything looks ok.

This happens with the latest release on Windows 10 and only when the definition is in a different file, it works when the definition is in the same file

**Comment by Sloff** [comment]
PS, I've only tested this on Typescript files

**Comment by Sloff** [comment]
Just retested, and it seems to be happening when in the same file as well

**Comment by bryphe** [comment]
Ah, I think this is a bug with the way we are handling URLs on Windows. It looks like we're not properly converting to a windows-style path. Thanks for opening the issue!
