### ISSUE TITLE
Can't support Chinese ? 

### ISSUE THREAD

**Issue by AlawnCN** [onivim/oni2#1345]
See the picture, The  left side is oni2  ,  The right side is macvim , They opened the same file

<img width="1273" alt="Xnip2020-02-20_15-31-54" src="https://user-images.githubusercontent.com/49110973/74911432-8ca6f180-53f7-11ea-91f6-089920165102.png">

**Comment by glennsl** [comment]
Closing as duplicate of #1091. Thanks for the screenshot though!
