### ISSUE TITLE
Input: Add keybinding for next / previous error

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1349]
Would be really convenient to jump to previous / next error in the active editor (or across projects).

For parity with VSCode:

- `editor.action.marker.next` - next marker, in a file (Default <F8>)
- `editor.action.marker.nextInFiles` - next marker, across files (Default <Cmd+F8>) 
- `editor.action.marker.prev` - previous marker, in file (Default <Shift+F8>)
- `editor.action.marker.prevInFiles` - previous marker, across files (Default <Shift+Cmd+F8>)

**Comment by glennsl** [comment]
Closing in favor of using #1423 for all keybinding enhancements.
