### ISSUE TITLE
Attempting to paste (ctrl+c) a path into the `:cd` command freezes the editor

### ISSUE THREAD

**Issue by JasoonS** [onivim/oni2#1354]
On ubuntu 19.10, pasting with (ctrl+c) a path into the `:cd` command freezes the editor.

I'm not sure if you intend to allow pastin into those commands (ones activated by the `:` command), but it would be nice to have. 

But freezing the editor shouldn't happen.

**Comment by bryphe** [comment]
This was fixed along with #496 in https://github.com/onivim/oni2/pull/1506
