### ISSUE TITLE
No new EA builds since 21 Feb ?

### ISSUE THREAD

**Issue by ijzerbroot** [onivim/oni2#1369]
I noticed that the most recent EA build (for Windows at least) is still from the 21st.
Have the daily builds stopped ?

**Comment by bryphe** [comment]
Thanks for logging the issue, @ijzerbroot !

Indeed, there were a couple bugs with our release pipeline... some new dependencies weren't ported over (it's close to what we have in GitHub here - but some extra environments for code signing).

Worked through the issues, and builds are [up-to-date again](https://v2.onivim.io/early-access-portal) 🤞 

![image](https://user-images.githubusercontent.com/13532591/75400935-80b6a600-58b5-11ea-81d0-450e81fcb474.png)

**Comment by bryphe** [comment]
I'll close this out since the release pipeline is fixed now-
