### ISSUE TITLE
VSCode themes not applied consistently (with how VSCode does it)

### ISSUE THREAD

**Issue by DaniRey** [onivim/oni2#1370]
When using a VSCode theme, certain elements are not styled the way VSCode does. This mainly concerns the Explorer, the Tabs and the bar on the bottom.

For Dark themes, this seems to be no issue, but for light themes, the contrast on those elements is problematic.

Please see attached Screenshot, taken with "Winter is Coming (Light)" from https://vscodethemes.com/e/johnpapa.winteriscoming applied to both editors.

![themes_not_applied_consistently](https://user-images.githubusercontent.com/7700482/75327435-ab383d00-587c-11ea-961b-ea93912a7b66.png)

**Comment by tatchi** [comment]
@glennsl Couldn't this issue be closed now?

**Comment by glennsl** [comment]
Ah, yes! Seems like I fat-fingered the close word on that PR. Thanks for the heads up!

**Comment by DaniRey** [comment]
Thanks @glennsl for fixing this so quickly
