### ISSUE TITLE
Rendered whitespaces do not scroll with the code when using tabs

### ISSUE THREAD

**Issue by Blackhawk-TA** [onivim/oni2#1387]
When render whitespaces is enabled and a file uses tabs instead of spaces, the rendered whitespaces do not scroll with the code. Instead they stay at the same position. This problem does not occur when spaces instead of tabs are used.

OS: Windows 10 1909
Oni2: Built 2 days ago from GitHub source code

Before scrolling down:
![grafik](https://user-images.githubusercontent.com/36313322/75610818-0dab6a80-5b15-11ea-94c6-ced6d5f2cd3d.png)

After scrolling down 3 lines:
![grafik](https://user-images.githubusercontent.com/36313322/75610825-26b41b80-5b15-11ea-8dda-c409c52dcefe.png)

**Comment by bryphe** [comment]
Thanks for the bug report and the screenshots, @Blackhawk-TA ! Can repro 👍
