### ISSUE TITLE
Performance: Long Lines

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#139]
There's a bug right now where we are drawing _every token of a line_ - you can imagine when a file has very long lines - or a single long line - this would be a performance killer!

We need to optimize both the minimap and surface to pick out only the renderable tokens, and skip other ones.

In addition, we should disable syntax highlighting for very long lines (as VSCode does)

**Comment by somebody1234** [comment]
Seems like maybe the syntax highlighting length limit would be nice as a user configuration option?
