### ISSUE TITLE
Just bought onivim... macOS 10.15, app does not boot.

### ISSUE THREAD

**Issue by safaiyeh** [onivim/oni2#1397]
<img width="588" alt="Screen Shot 2020-03-02 at 8 36 37 AM" src="https://user-images.githubusercontent.com/8675043/75696749-ef528580-5c60-11ea-88b7-ab2d95f304a1.png">

**Comment by bryphe** [comment]
Hi @safaiyeh ,

Sorry about the crash on launch! 

Some questions:
- I'm assuming you installed with the `dmg`?
- How are you launching the app? Via Finder?
- Do you see a window pop-up at all and disappear? Or just nothing at all? 

We could try getting some log output - if you run this command and share the output:

`/Applications/Onivim2.app/Contents/MacOS/Oni2 -f --trace --debug` 

might give us clues about where things are going wrong.

**Comment by safaiyeh** [comment]
• Yes I installed with the `dmg`.
• I tried via Finder & Spotlight Search.
• Nothing at all, usually the icon bounces on the dock indicating it is opening. No bounce.

Logs:
```
/Applications/Onivim2.app/Contents/MacOS/Oni2 -f --trace --debug
dyld: Library not loaded: @executable_path/../Frameworks/libffi.6.dylib
  Referenced from: /Applications/Onivim2.app/Contents/MacOS/Oni2_editor
  Reason: no suitable image found.  Did find:
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: open() failed with errno=13
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: stat() failed with errno=1
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: open() failed with errno=13
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: stat() failed with errno=13
	file system relative paths not allowed in hardened programs
```

**Comment by bryphe** [comment]
Thanks for the details and the log output, @safaiyeh ! Really appreciate it.

Doing some investigation... seems like a similar issue to these:
- https://forums.developer.apple.com/thread/115451
- https://forums.developer.apple.com/message/365393#365393

And in particular... the discussion in this issue looks like RStudio hit something similar: https://github.com/rstudio/rstudio/issues/4597

Seems like the new hardened-runtime is causing us to fail when loading our `libffi.6.dylib`, because we're using an `@executable_path`-relative path to load it (like RStudio).

The strange part is I'm unable to reproduce this on a 10.14 Mac Mini, or a 10.15 Macbook pro. It seems like an entitlement issue like this should fail consistently.

**Comment by safaiyeh** [comment]
Great thanks for looking into this! Let me know when I can test a build with the fix

**Comment by bryphe** [comment]
Thank you for the help grabbing those logs, @safaiyeh ! Fingers crossed that entitlement fixes it 🤞 

Will update here once the builds make it through our release pipeline and are out with the new entitlement-

**Comment by bryphe** [comment]
I verified the latest builds on the portal now have the `com.apple.security.cs.allow-dyld-environment-variables` entitlement:

![image](https://user-images.githubusercontent.com/13532591/75884623-0bc5fd80-5dda-11ea-8dcf-b7a44ab015ae.png)

Let me know if you're still seeing issues getting the app to start. 

If there's still a crash - would be helpful to see if there are any new logs from: `/Applications/Onivim2.app/Contents/MacOS/Oni2 -f --trace --debug`

Thanks for the help troubleshooting!

**Comment by safaiyeh** [comment]
hmm I downloaded the latest build I am getting the same error

```
/Applications/Onivim2.app/Contents/MacOS/Oni2 -f --trace --debug
dyld: Library not loaded: @executable_path/../Frameworks/libffi.6.dylib
  Referenced from: /Applications/Onivim2.app/Contents/MacOS/Oni2_editor
  Reason: no suitable image found.  Did find:
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: open() failed with errno=13
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: stat() failed with errno=1
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: open() failed with errno=13
	/Applications/Onivim2.app/Contents/MacOS/../Frameworks/libffi.6.dylib: stat() failed with errno=13
```

**Comment by bryphe** [comment]
Bummer, that's disappointing - thank you for trying again and sharing the logs, @safaiyeh !

I created a thread at the apple developer forums the other day: https://forums.developer.apple.com/thread/129795 - I'll see if they have any other ideas.

Alternatively, I'm investigating to see if we can switch to static linking and ditch these dylibs - avoiding this problem entirely.

**Comment by rosenquist** [comment]
Not sure if this helps but I had the same issue and it was due to `libffi.6.dylib` being quarantined by the anti-virus SW.

**Comment by bryphe** [comment]
Thanks @rosenquist ! That is very helpful. It looks like we aren't notarizing it properly, so GateKeeper is flagging it.

We code-sign + notarize all of our builds that we release - that [notarization process](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) should be validating all of our dynamic libs. 

However, I checked the latest notarization logs, and not all of our dylibs were included in the notarization ticket:
```

  "ticketContents": [
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/rls",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/Oni2_editor",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/rg",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/node",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/Frameworks/libharfbuzz.0.dylib",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/Frameworks/libSDL2-2.0.0.dylib",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/rls",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/Oni2",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/rg",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/node",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/MacOS/Oni2_editor",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/Resources/node/node_modules/node-pty/build/Release/pty.node",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/Frameworks/libSDL2-2.0.0.dylib",
      "digestAlgorithm": "SHA-256",
      "arch": "x86_64"
    },
    {
      "path": "Onivim2.app.zip/Onivim2.app/Contents/Frameworks/libharfbuzz.0.dylib",
      "digestAlgorithm": "SHA-256",
    }
   ]
```

Notably... `libffi.6.dylib` wasn't ticketed. So it makes sense that GateKeeper would flag it - all the `dylibs` need to be included in the ticket for it to be valid.

Still not clear to me why this reproduces for some users, and not others.

**Comment by bryphe** [comment]
To avoid these issues in the future - I'm going to statically link and avoid bundling the `dylibs` - I'm working through that right now. 

These are already statically linked now:
- (`libonig`) https://github.com/onivim/oni2/pull/1416
- (`libffi`) https://github.com/onivim/oni2/pull/1414

And I'm working on statically linking harfbuzz and SDL2 as well.

These will still get validated as part of the notarization service (as part of `Oni2_editor`). But will help avoid any fragility in the `dyld` process.

**Comment by safaiyeh** [comment]
Yup just confirmed `libffi.6.dylib` was quarantined by my anti virus software.

I grabbed the latest build and it works now, thanks for working through all this @bryphe

**Comment by bryphe** [comment]
Great news! Thank you @safaiyeh and @rosenquist for all your help investigating and troubleshooting with me - really appreciate it.

**Comment by bryphe** [comment]
Hi @safaiyeh @rosenquist - just curious, were you using a third-party anti-virus software?

I'd like to test our builds with the AV you were using to make sure we don't hit this again. Thanks for the help!

**Comment by safaiyeh** [comment]
Hi @bryphe the anti-virus was Cylance

**Comment by bryphe** [comment]
Thanks @safaiyeh !

**Comment by rosenquist** [comment]
yup, same here
