### ISSUE TITLE
Terminal causes hard crash with yarn list

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1402]
(MacOS Catalina,
Nightly commit:a5e6fb52)

When opening the terminal and trying `yarn list` the terminal briefly displays the output (a little bit garbled) but then hard crashes Oni.

Let me know if you need anymore details to help isolate the issue.
Thanks.

**Comment by yunti** [comment]
This works fine now with last nights revery update. Thanks

**Comment by glennsl** [comment]
Will close it then. Thanks for reporting back @yunti!
