### ISSUE TITLE
commands ignored after hitting <ESC> for insert and block visual mode

### ISSUE THREAD

**Issue by irevived1** [onivim/oni2#1411]
to repro the issue, in normal mode, do 10ia\<ESC\>
we are expected to see 'aaaaaaaaaa' in the editor, but currently we only get 'a' instead.  the 10 gets forgotten after hitting \<ESC\>

similarly in visual block mode.
example text:

lne1
lne2
lne3

in normal mode, cursor on first line do ^(Ctrl+v)jjAi\<ESC\>
expected output should be

line1
line2
line3

but got

lne1
lne2
lne3i

instead.

If this issue can be fixed then that would be great.  Thanks.

**Comment by massltoff** [comment]
Same issue #809

**Comment by glennsl** [comment]
Closing as duplicate of #809. Since it's referenced there, the additional information given here isn't lost.
