### ISSUE TITLE
Mouse cursor placement error

### ISSUE THREAD

**Issue by tofulm** [onivim/oni2#1418]
Depending on the indentation, the mouse cursor is wrong
![oni](https://user-images.githubusercontent.com/2989137/75958029-a0ecf300-5ebb-11ea-88c3-da98d9acd867.gif)

**Comment by DanielPower** [comment]
This occurs whenever there are tabs. In terms of mouse positioning, a tab seems to be treated as multiple characters when it comes to positioning.

This also affects underlining keywords. The underline gets offset depending on the number of tab characters before that point on the line.
![image](https://user-images.githubusercontent.com/12166320/76172094-11726900-6175-11ea-941e-bd13c707691a.png)

**Comment by DanielPower** [comment]
This is literally Neovim...
