### ISSUE TITLE
terminal crashes on unicode U+FFFD

### ISSUE THREAD

**Issue by smolin** [onivim/oni2#1422]
Early access user here --- I want to use the program k9s (https://github.com/derailed/k9s) but it reliably crashes onivim2 (downloaded this morning 2020/03/05, latest commit https://github.com/onivim/oni2/commit/cc79c6febdaa74eb4e5fc9dd41669715f6ffd9ba)

I tracked it down to a single unicode character, U+FFFD "REPLACEMENT CHARACTER" ( https://en.wikipedia.org/wiki/Specials_(Unicode_block) )

This command reproduces the crash:

    'echo -e "\xef\xbf\xbd"`

Great progress! Keep up the great work.

**Comment by bryphe** [comment]
Thank you @smolin ! Really appreciate the investigation and the simple repro. 👍 

On OSX, I see a crash in Skia's text rendering code: ```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   App                           	0x0000000109c82c7c GrAtlasTextContext::makeDrawTextBlob(GrTextBlobCache*, GrGlyphCache*, GrShaderCaps const&, GrTextUtils::Paint const&, SkScalerContextFlags, SkMatrix const&, SkSurfaceProps const&, char const*, unsigned long, float, float) const + 348 (GrAtlasTextBlob.h:411)
1   App                           	0x0000000109c82a72 GrAtlasTextContext::drawText(GrContext*, GrTextUtils::Target*, GrClip const&, SkPaint const&, SkMatrix const&, SkSurfaceProps const&, char const*, unsigned long, float, float, SkIRect const&) + 194 (GrAtlasTextContext.cpp:327)
2   App                           	0x0000000109bc8d5a GrRenderTargetContext::drawText(GrClip const&, SkPaint const&, SkMatrix const&, char const*, unsigned long, float, float, SkIRect const&) + 362 (GrRenderTargetContext.cpp:230)
3   App                           	0x0000000109cce33b SkGpuDevice::drawText(void const*, unsigned long, float, float, SkPaint const&) + 347 (SkGpuDevice.cpp:1621)
4   App                           	0x0000000109a07fc9 SkCanvas::onDrawText(void const*, unsigned long, float, float, SkPaint const&) + 217 (SkCanvas.cpp:273)
5   App                           	0x0000000109a08acc SkCanvas::drawText(void const*, unsigned long, float, float, SkPaint const&) + 188 (SkTraceEvent.h:337)
6   App                           	0x0000000109fa1f28 skia_wrapped_stub_91_sk_canvas_draw_text + 56 (skia_generated_stubs.c:826)
7   App                           	0x00000001099373f5 camlSkiaWrapped__Skia_generated_stubs__fun_3060 + 85
```

So it seems we're passing it something corrupt or invalid in this case. Looking to see what sort of string we're handing over to Skia
