### ISSUE TITLE
[bug] esy create-release needs privlege escalation in order to properly run

### ISSUE THREAD

**Issue by SolarAquarion** [onivim/oni2#1449]
It may have something to do with fuse, but i don't know

**Comment by glennsl** [comment]
This is a bit short on information to be actionable. I also seem to remember something like this being solved on Discord a while back. Is this still an issue? And if so, could you provide more context, like the a description of environment (OS etc.), the concrete error message, logs, instruction to reproduce etc.

**Comment by glennsl** [comment]
Closing due to staleness
