### ISSUE TITLE
:vnew and :new showing welcome page instead of empty buffer

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#1455]
Title is pretty much self explanatory, I would expect an empty buffer when using `:new` or `:vnew` like it is in vim.

**Comment by DanielPower** [comment]
It seems to me that `:new` and `:vnew` actually create another view of the currently open file.

**Comment by kinglouie** [comment]
you're right with your observation but the intended behaviour of these commands is to create a new split with an empty buffer. For opening the same file in a new split there is `:split` and `:vsplit`

**Comment by DanielPower** [comment]
Ah, you're right! Then yes, `:new` and `:vnew` should definitely open empty buffers. Thanks, I didn't realize there were separate commands.
