### ISSUE TITLE
terminal - some remaining garbled output

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1456]
A small piece of remaining garbled output in the terminal (this is the Sorin prompt from the fish shell). 

<img width="122" alt="image" src="https://user-images.githubusercontent.com/1826271/76415486-2fb4b080-6391-11ea-9ccc-595a243503bc.png">

vs in iterm2

<img width="139" alt="image" src="https://user-images.githubusercontent.com/1826271/76334137-874c1100-62ea-11ea-86c1-dd28c4207b6c.png">

**Comment by CrossR** [comment]
Is the same font being used in both?
Or it could be that we are missing powerline (or similar) symbols.

**Comment by leavengood** [comment]
I have a similar custom prompt, it uses the chevron character: ❱, unicode \U+FFE2\U+FFB1.

**Comment by leavengood** [comment]
If I switch to the Menlo font in `configuration.json` that character renders properly in an editor window. The terminal does not change the font when the config changes (another bug I suppose), but if I start a new terminal with Menlo as the font I get blank rendering:

<img width="540" alt="Screen Shot 2020-03-10 at 1 40 36 PM" src="https://user-images.githubusercontent.com/637/76342289-bfe0f000-62d4-11ea-84e7-e2ae8ebb74e9.png">

I still get blank rendering for Menlo even if I change from the chevron to `>` in my prompt.

**Comment by leavengood** [comment]
I call it chevron but I guess the real name is "Heavy Right-Pointing Angle Bracket Ornament": https://www.compart.com/en/unicode/U+2771

😄

**Comment by yunti** [comment]
I'm also getting the blank screen issue (looks like a separate problem).  I can get it to appear repeatedly by opening a second terminal in the same current window.

**Comment by yunti** [comment]
@CrossR yes as far as I know it's the same font used in both. Updated with a new screenshot from oni which seems closer apart from the chevrons.

**Comment by opeik** [comment]
I'm having the same issue, seemingly with the same character.
<img width="899" alt="Screen Shot 2020-04-20 at 14 47 57" src="https://user-images.githubusercontent.com/11566773/79722134-17cc3700-8316-11ea-8aba-71e96c8b62d0.png">

**Comment by yunti** [comment]
@zbaylin I presume this could now work with the recent unicode support added to the editor?

**Comment by bryphe** [comment]
Looks like we need font-fallback hooked up in Revery terminal: https://github.com/revery-ui/revery-terminal - but then this should be working! @zbaylin - do you think you add the fallback for us here: https://github.com/revery-ui/revery-terminal/blob/3cb342fd67819c9262c19046bf5446eaa17ea4d3/src/lib/TerminalView.re#L162 ?
