### ISSUE TITLE
Issues with system clipboard

### ISSUE THREAD

**Issue by glennsl** [onivim/oni2#1460]
[From reddit](https://www.reddit.com/r/onivim/comments/fgn4a6/issue_with_system_clipboard/):

I just installed Onivim 0.3.6 on windows 10 and I really like the concept ! It seems to be just the right amount of both vim and vscode. I would like to use it more in the near future.

I have an issue with the system clipboard though. My settings are the defaults, and even though yanking from Onivim seems to find its way to the system clipboard, it does not go the other way around. I.e. if I copy any text from any other application (let's say hello world) and paste it in Onivim, I get the following behaviors :

- using the p key : it copies a newline character : CRLF

- using Ctrl+Shift+P command "Clipboard: Paste" : it copies the text without the first 2 characters ! llo world !

- Ctrl+V works only in insert mode which does not correspond to vim's paste behavior being available from normal mode

- from insert mode, <c-r>* : nothing

When I was using vim, I used set clipboard=unnamed and it worked as expected, using the * register. I tried to set this in my init.vim file but in vain (the only difference is that Ctrl+V writes ^[)

The documentation seems to be speaking about setting the system clipboard but not the other way around.

**Comment by CrossR** [comment]
I think (confusingly) this is referring to Oni1, since we don't (that I know of?) have version numbers past `0.3.0` here, and they talk about an `init.vim` being loaded which implies neovim (and that its being loaded at all is different to current Oni2).

**Comment by glennsl** [comment]
Oh, good catch. I have no idea what the support policy even is for Oni1, and wouldn't be able to provide any help anyway. I'll just close this then and let someone else handle it :)

**Comment by simon-budin** [comment]
I am the reddit user who posted it, and I managed to install [this old version of Oni ](https://github.com/onivim/oni/wiki/Installation-Guide#windows) from the corresponding repository. My bad, I thought there would be some installer of the new version available.

**Comment by glennsl** [comment]
No worries @simon-budin. There are early access builds available to backers., but you can also [build it yourself from source](https://onivim.github.io/docs/for-developers/building) if you want.
