### ISSUE TITLE
Cannot install. Error on esy bootstrap comand.

### ISSUE THREAD

**Issue by OlegBrony** [onivim/oni2#1474]
When I ran `esy bootstrap` for the first time, I saw in console that it cannot find nasm module. I installed it and saw some other errors. I went to [this](https://github.com/revery-ui/revery/wiki/Building-&-Installing#for-ubuntu-you-may-need-these-additional-packages) link and install all packages in the list. now I see [this](https://gist.github.com/OlegBrony/183729a42eab5880b93061768a0592f1) error and don't know how to fix it. OS - Mint.

**Comment by glennsl** [comment]
You also need to install `clang`. it seems  Not sure why that is as it's not needed on our Ubuntu CI box, but perhaps there's some subtle difference between Ubuntu and Mint.

I've updated the potential requirements on Ubuntu to include `clang`, just in case.

**Comment by OlegBrony** [comment]
is it python package? how can I install it? just `sudo apt install clang`?

**Comment by glennsl** [comment]
It's a C compiler toolchain. I would assume that's the install command, yes.

**Comment by glennsl** [comment]
I'm assuming that installing `clang` has fixed this. I've also added `clang` to the list of requirements for Ubuntu to prevent these issues in the future.
