### ISSUE TITLE
Show filename before path in "Open File" instead of path

### ISSUE THREAD

**Issue by vsashyn** [onivim/oni2#1482]
Hi guys! Thank you for a great project!

When I use "Open file" and have lots of nesting folders, my path fill all available space so I can't see the exact name of the file. 
<img width="413" alt="Screenshot 2020-03-18 at 19 33 54" src="https://user-images.githubusercontent.com/4557935/77002654-852a2800-6964-11ea-84ce-8357bfeceb42.png">
For example in VSCode the filename stands before path so you can clearly see it.
<img width="608" alt="Screenshot 2020-03-18 at 19 34 43" src="https://user-images.githubusercontent.com/4557935/77002768-ba367a80-6964-11ea-9e0f-fa7e4f7d1c1c.png">

I wondered if it makes sense as UI improvement. If yes - I would be glad to make a PR.

**Comment by glennsl** [comment]
Thanks! I think we've agreed that this is how we want it. Just need to get around to actually doing it.

**Comment by glennsl** [comment]
Related: #758

**Comment by bryphe** [comment]
Fixed with https://github.com/onivim/oni2/pull/3251:
