### ISSUE TITLE
Node.exe child process survives exiting Oni2

### ISSUE THREAD

**Issue by malfario** [onivim/oni2#1485]
Platform: Windows 10 Pro x64 10.0.18362

This only happens when closing Oni2 from the window's X (close) button.
Closing Oni2 with any of Vim's `:q` command variants successfully kills the child node process.

**Comment by bryphe** [comment]
Nice catch @malfario , thank you for logging the issue and the details.

Indeed, it looks like in the window-X-close case, we're missing our cleanup code path that shuts down processes like the extension host.

**Comment by malfario** [comment]
Glad to help. Keep the great work!
Cheers!
