### ISSUE TITLE
Window freezes on Ctrl + Shift + P and searching - Windows 10

### ISSUE THREAD

**Issue by Cy-Tek** [onivim/oni2#1486]
Hi, every time I open the editor on my Windows machine, hit Ctrl + Shift + P, and then start to search for *theme*, my whole window crashes and I have to force quit the application and restart it. The odd thing is that when opening from my Git Bash terminal everything works correctly, but when opening from Powershell, Command Prompt, or just the application itself, I can reproduce the issue.

**Attached below is my log file of the most recent crash:**
[log.txt](https://github.com/onivim/oni2/files/4361575/log.txt)
[onivim2-crash.log](https://github.com/onivim/oni2/files/4361576/onivim2-crash.log)

**Comment by glennsl** [comment]
Could you try it again with `--trace` and `OCAMLRUNPARAM=b` set?

I'm not entirely sure how environment variables work on Windows, but on a Unix you'd do:

```
OCAMLRUNPARAM=b Oni2 -f --trace
```

That should hopefully print a stack trace in `onivim2-crash.log` and even more details in the normal log.

**Comment by CrossR** [comment]
Just to put what I mentioned on Discord in a more permanent location:

I think when running via Git bash, there is a chance Oni2/Ocaml/something thinks its running in a Unix-like environment. This is somewhat shown that @Cy-Tek mentioned that swapping themes in the CLI launched version didn't persist to the explorer launched version, but does with either of Powershell/Cmd.

If that is the case, I expect the issue is user extensions causing a freeze, as when launching from Git bash, none of them would be loaded since they live in `%LOCALAPPDATA%` and not `~/.config`.

**Comment by bryphe** [comment]
Thanks for log and the issue, @Cy-Tek !

> If that is the case, I expect the issue is user extensions causing a freeze, 

I think this is a reasonable hypothesis - looking at the logs, I see a few extensions:
- whizkydee.material-palenight-theme-1.9.7
- vadimcn.vscode-lldb-1.4.5
- sldobri.daily-6.0.3
- serayuzgur.crates-0.4.7
- s-nlf-fh.glassit-0.1.6
- rust-lang.rust-0.7.0
- octref.vetur-0.23.0
- ms-vscode.go-0.13.0
- ms-vscode.cpptools-0.26.3
- matklad.ra-lsp-0.0.1
- kosz78.nim-0.6.4
- josef.rouge-theme-2.0.2
- hdevalke.rust-test-lens-0.3.1
- gerane.theme-seafoam-pastel-light-0.0.5
- gerane.theme-batman-0.0.6
- daylerees.rainglow-1.5.2
- chiragpat.tomorrow-and-tomorrow-night-operator-mono-theme-0.0.6
- brofox86.theme-espresso-soda-light-3.0.1

I suspect there must be one that is sending us contributed commands that break us  - that `Invalid_argument` exception might be coming from the filtering (highlight indices) or picking out a substring.

Running via `Oni2.exe -f --debug --trace --log-file=log.txt` would be helpful! Might give us a better stacktrace plus some clues.

**Comment by Cy-Tek** [comment]
Hey @bryphe ! Here's the log file created with the command that you gave me above :) I'm also going to work on removing all of my extensions and see if it works properly at that point.
[log.txt](https://github.com/onivim/oni2/files/4369426/log.txt)

**Comment by Cy-Tek** [comment]
I can confirm that removing all of my extensions located in %LOCALAPPDATA% does in fact fix the issue that I was running into, so it appears that you guys' analysis are correct as far as that goes, though I do wonder which one specifically is causing the issue.

**Comment by glennsl** [comment]
@Cy-Tek A good way to find out would be to add them back one by one. There are extension errors in the log, but it's hard to tell if they're related. Knowing which extension to look for errors from would be very helpful.

**Comment by Cy-Tek** [comment]
@glennsl I haven't found the exact extension yet, but one that you may want to look at it the `chiragpat.tomorrow-and-tomorrow-night-operator-mono-theme-0.0.6` extension. For some reason when this extension is installed, and I hit Ctrl + Shift + P, searching works okay, but if I press the down arrow, the editor immediately crashes, no freeze, just straight up crashes and disappears. I'll keep looking for the original culprit, just wanted to let you know that issue as well :P

**Comment by CrossR** [comment]
That issue is known and is because that theme is implemented using XML rather than JSON. So if you attempted to select that theme, I think it will fail and crash. The error handling around that could be better though. And of course, eventually it would be nice if we could load both JSON and XML based themes/syntax etc.
