### ISSUE TITLE
Oni2 INSERT MODE accents

### ISSUE THREAD

**Issue by EduardoRFS** [onivim/oni2#1498]
## Description
When in INSERT mode you write the portuguese / spanish letter "é", the cursor jumps to the start of the line, but you keep writing on the same position, until the letter is deleted

## Version
commit: d61477c4

## Example
![example](https://user-images.githubusercontent.com/3393115/77465752-e54b1f00-6de7-11ea-9dd2-85a505c9bbeb.gif)

**Comment by bryphe** [comment]
Thanks for the issue and gif, @EduardoRFS ! That's a bad one.

Just curious - which platform are you using? And which keyboard layout?

**Comment by glennsl** [comment]
Related: #1475 where I describe this issue in the second point of [this comment](https://github.com/onivim/oni2/issues/1475#issuecomment-599682114)

**Comment by EduardoRFS** [comment]
@bryphe it's arch linux, keyboard layout is br-abnt2. On most operating systems is called just "portuguese / brazil", If you setup it and is using an ISO or ANSI keyboard it is probably going to be the key on the right side of P + e.

Will give it a try on Windows to see what happens.
