### ISSUE TITLE
Workspace not persisted.

### ISSUE THREAD

**Issue by dmikov** [onivim/oni2#1536]
**Oni 2:**
**Neovim Version (Linux only):**
**Operating System: windows*

Even though I am exiting from opened Onivim with folder opened with .git it is still openning Onivim2 folder on next start. I don't understand why it has to have certain files to re-open last directory. But it had .git which is listed.

**Expected behavior:**
Reopen the same folder/workspace.

**Actual behavior:**
Always goes to Onivim2 folder

**Steps to reproduce:**
Open Onivim2 do `:cd <folder>` 
Close Onivim2
Open it again.

**Comment by CrossR** [comment]
I can apparently transfer issues....cool!

I'll close this out as a duplicate anyways, but would be worth clicking the thumbs up on the other issues.
