### ISSUE TITLE
Terminal detects down arrow as right arrow

### ISSUE THREAD

**Issue by DanielPower** [onivim/oni2#1546]
Onivim Version: 0.4.0
Operating System: OSX 10.15.4
Steps to reproduce:
1. Open a terminal
2. In that terminal, press up a few times to go back through command history
3. Now press down to try and go forward through history. Note that nothing happens
4. Press left a few times, then down. Note that the cursor moves to the right

For further testing, open Vim in the terminal (vimception, right?). Notice that the down arrow will instead move the cursor to the right.

**Comment by bryphe** [comment]
Ouch, thanks for catching this and logging the issue, @DanielPower !
