### ISSUE TITLE
Crash when moving cursor in Ex Command Menu

### ISSUE THREAD

**Issue by SirFurness** [onivim/oni2#1554]
How to reproduce:
Type `:e `  (note the space after the "e")
Press the left arrow key

This leads to oni2 crashing immediately.
By looking at the debug output, it appears it is crashing on this line
https://github.com/onivim/oni2/blob/13da9959e397f32466e1f3c71a0a47957cf0a3b7/src/Store/VimStoreConnector.re#L423

**Comment by bryphe** [comment]
I haven't been able to reproduce this in the latest builds - feel free to re-open if there is still a crash here, though .

I suspect this was fixed either in https://github.com/onivim/libvim/commit/ce177a63fa746412d256215359cce4889485b4c8 , or possibly https://github.com/onivim/libvim/issues/226
