### ISSUE TITLE
keybinding for manipulate ui.zoom

### ISSUE THREAD

**Issue by JorgeDLG** [onivim/oni2#1556]
Like VsCode it would be great to include <kbd>Ctrl</kbd><kbd>+</kbd> and <kbd>Ctrl</kbd><kbd>-</kbd> keybindings to increase / decrease ui.zoom (maybe same for editor.fontSize)
The main use is when switching between different monitors sizes. 
Keep these parameters differents on differents windows would be great too.

**Comment by glennsl** [comment]
Thanks! I've added this to #1423.
