### ISSUE TITLE
[Normal Mode] viw key combination differs to vim

### ISSUE THREAD

**Issue by dlagg** [onivim/oni2#1561]
In normal mode typing VIW selects from the current char to end of the word. In classic vim the whole word. I don't know if is a deliberate behavior or it can be configured.

**Comment by bryphe** [comment]
Indeed, this looks like a bug. What's strange is the `iw` motion works with operators, but not doing the correct thing in visual mode.

**Comment by robinfehr** [comment]
having
`const prepareApps = `
it sometimes selects `prepareApps and the `=`
and sometimes it selects nothing but the actual character where the cursor is on.

**Comment by CrossR** [comment]
I believe this was fixed in #2429.
