### ISSUE TITLE
Get Exception in Building from source

### ISSUE THREAD

**Issue by caihedongorder** [onivim/oni2#1572]
hi,when i clone source,follow the building steps, i get an exeption when 'esy install'.
info install 0.6.2 (using package.json)
```
.... fetching shelljs@0.8.3esy: internal error, uncaught exception:
     Unix.Unix_error(Unix.EACCES, "rename", "C:\\Users\\caihedong\\source\\oni2\\_esy\\default\\tmp\\esy-f8ad30")
     Raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 263, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39
```
   how to resolve it ? thanks for your help!

**Comment by glennsl** [comment]
Try removing `_esy` before running the build again. I think this can happen a previous build has been aborted because of running out of disk space for example.

**Comment by glennsl** [comment]
I'm assuming this has been fixed since 19 days have passed without any further feedback.
