### ISSUE TITLE
fontWeight missing

### ISSUE THREAD

**Issue by mxs** [onivim/oni2#1573]
`fontSize` and `fontFamily` are the but I can't seem to configure the `fontWeight`.

On retina screens dropping weight really makes the editor feel less cramped.

**Comment by glennsl** [comment]
There is no such setting yet. I'm not aware of anything that would be blocking this though, it's just a bit of wiring that's needed I think. Maybe even a good-first-issue @bryphe?

**Comment by lucis** [comment]
@glennsl can you refer to a PR that did something like that? I would like to try contributing

**Comment by glennsl** [comment]
Sorry for the late reply @lucis. I'm not aware of anything all that similar, but I can think of a few PRs that are relevant:

- #1511, which changed how we store and pass the editor font around.
- #1436, which refactored the entire configuration system

**Comment by opeik** [comment]
This would be super nice, at the moment I have to point onivim to use actual font file in order to use semi-bold.

**Comment by marcagba** [comment]
I started working on this one, here what I got so far:

![add-font-weight-preview](https://user-images.githubusercontent.com/14045559/99918541-e8503380-2d17-11eb-9843-7a83970fd163.gif)
