### ISSUE TITLE
Fuzzy-finder window is too small 

### ISSUE THREAD

**Issue by baransu** [onivim/oni2#1574]
I have pretty long paths and looking for the right file when they are prefixed the same is super hard with the current window fuzzy-finder width.

![Screenshot 2020-04-07 at 11 50 48](https://user-images.githubusercontent.com/9558691/78655466-57cafd00-78c6-11ea-8faa-1b6e6e2bd71b.png)

**Comment by CrossR** [comment]
I'll close this out as its a duplicate/related to https://github.com/onivim/oni2/issues/1482, but if you have any further input on how it should look, that would be appreicated!

Also make sure to +1 the issue!

**Comment by baransu** [comment]
Thanks! Sorry for duplicate
