### ISSUE TITLE
Ctrl + tab keeps restoring configuration file

### ISSUE THREAD

**Issue by souzaramon** [onivim/oni2#1575]
Hi there.

After open the configuration file and close the buffer the tab go away (as expected), but if after it I press Ctrl + tab the configuration file opens again, I think this is kinda weird, cause I expect the ctrl+tab just **circle over** the current buffers.

Is this right?

[ **to reproduce** ]
- Open the configuration file
- close it (:q)
- cicle over tabs with ctrl+tab

[ **my config** ]
- Arch Linux x86_64
- 5.5.13-arch2-1
- Onivim 2 - v0.4.0

**Comment by glennsl** [comment]
Yeah, it's a bug. It does cycle over the current buffers, but closing a tab doesn't actually close the buffer. Neither does `:q` or anything else.

This has been reported earlier as #1192, so I'll close this in favor of that. But thanks for reporting and for the detailed information!
