### ISSUE TITLE
Is it possible to customize the default shell for builtin terminal?

### ISSUE THREAD

**Issue by zeux** [onivim/oni2#1578]
The behavior that I observe right now (on Windows) is as follows:

- `:term` opens cmd.exe shell
- so does `:terminal`
- "Open terminal" commands in command palette open PowerShell

I'd like all of these to open `wsl.exe` shell instead, Looking at #1403 I discovered that $SHELL environment variable affects the choice. After setting this globally, `:term` and `:terminal` open wsl.exe but "Open terminal" continues to open PowerShell.

It would be nice to be able to specify a consistent default across these different options via editor settings since I'm not sure what the implications of overriding SHELL globally are on Windows.

**Comment by glennsl** [comment]
That shouldn't require anything special from Onivim. As long as it runs zsh, and your `.zshrc` is set up for oh-my-zsh, it should just work. At least it does for me.
