### ISSUE TITLE
Quick Open is hard to use on large projects

### ISSUE THREAD

**Issue by zeux** [onivim/oni2#1579]
It looks like because of the asynchronous file scanning (?), quick open is very hard to use on large projects - it takes time to populate the list, and as the list is being populated the selection jumps around unpredictably. It also seems that scanning either never finishes, or is restarted on key presses.

Attaching a video capture using Unreal Engine 4.

[Welcome - unrealengine - Onivim 2 2020-04-07 23-02-56.zip](https://github.com/onivim/oni2/files/4448507/Welcome.-.unrealengine.-.Onivim.2.2020-04-07.23-02-56.zip)

```
/mnt/c/work/unrealengine $ time find . | wc -l
183378

real    0m2.805s
user    0m0.328s
sys     0m2.484s
```

Worth noting is that Sublime Text (which is what I normally use) handles this very smoothly.

**Comment by CrossR** [comment]
I'm currently in the process of swapping the filtering logic out (#1566) and am doing testing/benchmarking against different repos. I'll try and grab a copy of the Unreal Engine 4 source and test how my changes are affecting that repo as well as the other repos I was looking at.

The internal benchmark we have, and the filtering logic itself is much faster, so hopefully it helps! Though both of those don't have elements of streaming the data in from ripgrep.
