### ISSUE TITLE
Syntax highlighting has visible latency for basic operations

### ISSUE THREAD

**Issue by zeux** [onivim/oni2#1581]
When editing files of moderate size - the example below is https://github.com/zeux/meshoptimizer/blob/master/src/simplifier.cpp which is ~1500 lines - syntax highlighting tends to have a visible delay. For some operations, like deleting lines, the delay manifests as flashing highlights for the rest of the file, which is visually distracting. Unsure if this is limited to C++ (which is what I mostly edit) or a more general problem.

[_simplifier.cpp - meshoptimizer - Onivim 2 2020-04-08 09-27-37.zip](https://github.com/onivim/oni2/files/4451636/_simplifier.cpp.-.meshoptimizer.-.Onivim.2.2020-04-08.09-27-37.zip)

As a comparison, Sublime on the same file has rock-solid syntax highlighting, any editing operations seem to immediately highlight the newly inserted text and don't disturb the highlighting for the rest of the file.

(by the way, I love the work you guys are doing - I've been using Vim exclusively since 2010, and I increasingly gravitate towards Sublime or Visual Studio with Vim emulation plugins to get more IDE functionality, so I'm excited about the future of onivim - just filing issues that come up as I start to explore the editor)

**Comment by pikachunakapika** [comment]
Hi, I have this with files that are only like 100 lines long when deleteting lines or adding lines.

**Comment by Raikiri** [comment]
I'd really like to see OP contributing to this project's performance optimization because he's pretty good at it.
