### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TicTak21** [onivim/oni2#1582]
### Error
```
fetching shelljs@0.8.3esy: internal error, uncaught exception:   
     Unix.Unix_error(Unix.ENOTEMPTY, "rename", "/usr/oni2/_esy/default/tmp/esy-8dc797")
     Raised at file "esy-lib/RunAsync.re", line 13, characters 2-51
     Re-raised at file "esy-lib/RunAsync.re", line 13, characters 2-51
     Re-raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 263, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39

```
OS verison: macOS Catalina 10.15.4(19E266)
Node version: 12.14.0
NPM version: 6.14.4
esy version: 0.6.2

### Steps to reproduce:
1) git clone https://github.com/onivim/oni2
2) cd oni2
3) esy install

**Comment by meshchaninov** [comment]
Same

**Comment by glennsl** [comment]
Remove `_esy`, then try again. This happens sometimes if a previous build has been aborted due to lack of disk space or similar issues.

**Comment by TicTak21** [comment]
Tried twice, but I still get this error.

**Comment by glennsl** [comment]
Oh, on macOS it can also be caused by the maxfiles limit being too low. Try this:

```
sudo launchctl limit maxfiles 65536 200000
```

then remove `_esy`, or go even further by running `git clean -dxf`, before trying again.

**Comment by glennsl** [comment]
But if that is the case, you should have gotten `error: Too many open files` a bit above the error you've pasted here.

**Comment by TicTak21** [comment]
So, I tried `sudo launchctl limit maxfiles 65536 200000`(+ remove `_esy`) and got new error: 
```
error: Too many open files                        
  unpacking @esy-ocaml/libffi@github:onivim/libffi#590b041
  installing @esy-ocaml/libffi@github:onivim/libffi#590b041
esy: exiting due to errors above
```

**Comment by glennsl** [comment]
Yeah, that's the problem it's supposed to fix. Try `ulimit -Sn 4096`. I ahve no diea what the difference is, but this fix is actually documented even: https://onivim.github.io/docs/for-developers/building#build-the-front-end

**Comment by TicTak21** [comment]
Although I didn't get the `error: Too many open files`, `ulimit -Sn 4096` helped me.
Thank you, @glennsl.
