### ISSUE TITLE
File Explorer - filesExclude not recognized

### ISSUE THREAD

**Issue by pikachunakapika** [onivim/oni2#1583]
Hi!
I have a bug that filesExlude is not recognized until I refresh a node in  file explorer by collapsing and expanding. It might be a race condition:

![Peek 2020-04-08 23-59](https://user-images.githubusercontent.com/13935418/78837885-50564180-79f5-11ea-970a-9f08afad43f0.gif)

Thanks for work.
Marcel

```
"files.exclude": [
    "_esy", "node_modules", ".ci", ".git", ".ccls-cache", ".vscode", "bench"
  ],

"filesExclude": [
    "_esy", "node_modules", ".ci", ".git", ".ccls-cache", ".vscode", "bench"
  ],
```

**Comment by pikachunakapika** [comment]
Sorry I think this is a duplicate of #1104

**Comment by RastaDollo** [comment]
@pikachunakapika Hi, I don’t know how to contact you, I'm search a version of bitcrack with -r function, could you share somewhere
