### ISSUE TITLE
UI: Software Rendering Support

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1588]
On requirement of Onivim 2, today, is OpenGL support. This can be problematic for some older versions of Windows, and some Linux versions. It also may be desirable to run Onivim 2 without the GPU (perhaps less animations / effects).

This is tracking enabling software rendering support - let me know if this is something that would be of interest to you and what hardware / OS it would be useful for -

This would be implemented in Revery - we could add a flag to window creation to specify a preference (software/hardware accelerated).

**Comment by bryphe** [comment]
One case where software rendering is helpful is to prevent the extra battery usage of the GPU on a laptop.

**Comment by bryphe** [comment]
An option for software rendering is to use the software Mesa3D drivers - but the perf is probably untenable for most use cases. We'd likely need to customize our rendering / compositing in Revery to minimize overdraw.

**Comment by pa3k-lu** [comment]
I have two use cases: 

- virtualized Windows Virtual machines without OpenGL support
- Surface Pro X (windows on arm64) that has only OpenGL 1.1 support, but fully hw  accelerated DirectX 12.

Did you consider library like https://github.com/floooh/sokol to make cross platform rendering native?

**Comment by badgeek** [comment]
hi @bryphe im on osx, and wondering if sublime also using software renderer with skia ? also check out alacritty, its gpu accelerated terminal its really fast and does not switch my mac to extenal vga card

**Comment by gblock0** [comment]
I remote into my Windows 10 box using the official Microsoft Remote Desktop OS X application. I just downloaded and installed Onivim, and the app just shows a white screen (same as #1809).

**Comment by CrossR** [comment]
Progress on this was made a few months ago, looks like the wrong issue was linked: https://github.com/onivim/oni2/pull/2318
