### ISSUE TITLE
Mouse Support: Minimap scrollbar

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#159]
This is tracking adding mouse support for the minimap scrollbar:
- Click to move thumb immediately
- Drag to scroll

We might be able to re-use some of the implementation in the slider: https://github.com/revery-ui/revery/blob/99d3a7a9ebed3ef7813b5646cbaabd1b5d4a82fa/src/UI_Components/Slider.re#L121

**Comment by KingEdwardI** [comment]
I'd like to take a swing at this. I have a solid background in React however no ReasonML experience. I'm extremely excited about Oni2 and would like to contribute as much as possible.

**Comment by Akin909** [comment]
I'll close this off since #240 was merged
