### ISSUE TITLE
Cursor Falling Behind with force-device-scale-factor

### ISSUE THREAD

**Issue by sghill** [onivim/oni2#1592]
On Ubuntu 18.04 after launching oni2 (0.4.0) with `--force-device-scale-factor=2.0` the cursor is falling behind the actual position of the text.

![cursor-at-scale](https://user-images.githubusercontent.com/230004/79047957-a9c59880-7bce-11ea-9e5e-5c693ab451aa.gif)

**Comment by CrossR** [comment]
From a quick test, I wasn't able to repro this, though I did see that the cursor was getting into a weird position when I was moving across a line, where it was off by a small amount. It looked normal enough without forcing the scaling factor.

Setting font smoothing to subpixel antialiased did help there (https://onivim.github.io/docs/configuration/settings#editor) but I can't confirm if it will help with this yet unfortunately.

**Comment by sghill** [comment]
Setting `"editor.fontSmoothing":"subpixel-antialiased"` worked!

Thanks for the suggestion and trying this out so quickly @CrossR.
