### ISSUE TITLE
Bug: Onivim becomes unresponsive if built-in terminal runs a command with a lot of long lines

### ISSUE THREAD

**Issue by cmrd-senya** [onivim/oni2#1599]
I hit this bug when I was trying to run Ruby on Rails + Sidekiq inside Onivim.

The synthetic way of reproducing this is to run a command which generates a lot of long lines.

Steps to reproduce
1. Open terminal using `:term` command (
2. Enter the following command (in bash): `for i in $(seq 1 10000); do printf %1000s |tr " " "-"; done`

Expected result:
Command is being executed in terminal while other parts of editor keep working and respond to user interaction

Actual result:
Editor freezes (almost) instantly and has to be killed.

OS: Arch Linux, Onivim revision 18b0475a24d9cc34a7d9d8e9f55b2a8c1bc33478, built from AUR (`onivim2-git` package)

**Comment by bryphe** [comment]
Thanks for logging the issue and the great repro, @cmrd-senya !

Indeed, I profiled, and see a few culprits:
![image](https://user-images.githubusercontent.com/13532591/79174781-8eb27e80-7db0-11ea-8516-ac3b0647be25.png)
