### ISSUE TITLE
ReasonML port - vscode-snippet-parser

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#160]
It'd be ideal to have an 'in-proc' version of [`vscode-snipper-parser`](https://github.com/onivim/vscode-snippet-parser) that we can call within our front-end.

Alternatively, we could implement this 'wrapper' API: https://github.com/onivim/oni/blob/master/browser/src/Services/Snippets/OniSnippet.ts

But it'd be preferable for performance / user experience to handle this in our 'front-end' process vs having to handle it asynchronously in one of the node helper processes.

**Comment by despairblue** [comment]
I made some progress with the parser, but currently hit my head on parsing not delimited strings.

In all the examples they parse a structured language containing unstructured text (e.g. JSON). That means all unstructured text is delimited:

"foo"


So the lexer can when it finds a " create a buffer and consume everything until it finds another " and then return a STRING (Buffer.contents buf) token. The point is that it can simply ignore the double quotes. 

Now, the snippets are unstructured text containing structured data (the marker). So for let ${1:f} = (${2:pattern});$0 the lexer needs to consume all text until it hits the $. So I have two rules. One that matches everything and puts it into a buffer and then reads the next token and another one that matches $. Now the second rule would need to convert the buffer into a string and then return the tokens: STRING (Buffer.contents buf); DOLLAR.

Well but ocamllex does not allow you to return 2 tokens. It does not allow you to lookahead or rollback/rewind. All suggestions go into the direction of hacking the lexer and creating a cache that the parser calls into to get the tokens.

I think I'll check out sedlex. Probably a good idea as well considering that ocamllex doesn't support UTF8.

**Comment by tcoopman** [comment]
@despairblue Just skimmed over the issue, so I can be wrong, but I would guess that [angstrom](https://github.com/inhabitedtype/angstrom) could also be an option. A getting started tutorial can be found here: https://ocamlverse.github.io/content/monadic-parsers-angstrom.html

**Comment by despairblue** [comment]
@tcoopman thanks. I'll check that out as well. And thanks for the ocamlverse website, so many documentation gems on there :heart_eyes:

**Comment by despairblue** [comment]
@bryphe I have something in [this repo](https://github.com/despairblue/reason-vscode-snippet-parser). It's by far not ready and probably in a bad shape API-wise, but I'd like to hook it up to oni for testing it out.

What would be a good spot to do something like this? I suppose I need to restrict it to insert mode and I need to capture each keypress (preventing it from going to libvim) and mutate the buffer manually instead.

I wonder if that would be a good approach and where to do that. Thanks in advance :)

**Comment by bryphe** [comment]
@despairblue - very cool! Looks promising.

There's a few things that I think we should add:
- A `snippet` state - we should figure out how we are going to model the 'snippet session' that is active. We could create a `Snippet.re` module in src/Model and add it to the `State.t`.
- Commands for next placeholder (`jumpToNextSnippetPlaceholder`) and previous placeholder (`jumpToPrevSnippetPlaceholder`). We probably want to also add a `when` condition for `inSnippetMode`, where these bindings would be active.
- When `jumpToNextSnippetPlaceholder` or `jumpToPrevSnippetPlaceholder` run - we'll want to synchronize the state. My thinking is we could use 'replace' mode to highlight the current snippet (this happens here in Onivim 1: Thttps://github.com/onivim/oni/blob/b5e57ce614259b7b769c0da8dd38810afe945b5a/browser/src/Services/Snippets/SnippetSession.ts#L375) Then, when the buffer changes while in 'snippet' mode, we mirror the change in the other placeholders (happens here: https://github.com/onivim/oni/blob/b5e57ce614259b7b769c0da8dd38810afe945b5a/browser/src/Services/Snippets/SnippetSession.ts#L362)

>  I suppose I need to restrict it to insert mode and I need to capture each keypress (preventing it from going to libvim) and mutate the buffer manually instead.

I think the above proposal is pretty similar to what you're suggesting! However, we'd actually still be leveraging insert mode in this case (which will be important if we want compatibility with VimL insert mode keybindings). Just, when we have an active snippet, we'll listen to the buffer update, and then mirror the changes across the other placeholders with the manual buffer mutation. The other main consideration is 'undo' - we want to make sure that undo works as expected.

Here's a few other references that might give ideas:
- The snippet-management code from Onivim 1: https://github.com/onivim/oni/blob/c66787474ca09ebe6f3445fbef66f465ce12f08c/browser/src/Services/Snippets/SnippetSession.ts 
... I was also just playing around with multiple-cursors in insert mode in 'user space' - https://github.com/onivim/oni2/tree/experiment/multiple-cursor - somewhat relevant to this.

Hope that helps give some ideas at least. Let me know if you have any questions on any of the particulars. Thanks for your work on this @despairblue ,  this would be an incredible addition!

**Comment by bryphe** [comment]
I've built an initial implementation for this in #2817
