### ISSUE TITLE
Closing the last open buffer quits the entire application

### ISSUE THREAD

**Issue by barbu110** [onivim/oni2#1603]
When having a single active buffer, closing a buffer with `:q` quits the entire application.

Personally, I would only prefer this to happen while in Zen mode, since we open that just to edit a single file. However, when having a project open and hitting `:wq` out of habit, having the application disappear from your sight is a huge bottleneck in productivity.

I would love to have a config option for this behavior. What do you guys think?

**Comment by glennsl** [comment]
Closing as duplicate of #759. You should give that an upvote though, to increase its priority.
