### ISSUE TITLE
Linking error during building on MacOS

### ISSUE THREAD

**Issue by ArtemDrozdov** [onivim/oni2#1604]
Hello.
I'm getting linking error during `esy build` process:

```
Undefined symbols for architecture x86_64:
  "__nl_msg_cat_cntr", referenced from:
      _ex_language in libvim.a(ex_cmds2.o)
  "_libintl_bind_textdomain_codeset", referenced from:
      _mb_init in libvim.a(mbyte.o)
  "_libintl_bindtextdomain", referenced from:
      _common_init in libvim.a(main.o)
      _vim_setenv in libvim.a(misc1.o)
  "_libintl_gettext", referenced from:
      _alloc_does_fail in libvim.a(misc2.o)
      _do_outofmem_msg in libvim.a(misc2.o)
      _lalloc in libvim.a(misc2.o)
      _alloc_id in libvim.a(misc2.o)
      _alloc_clear_id in libvim.a(misc2.o)
      _lalloc_id in libvim.a(misc2.o)
      _find_special_key in libvim.a(misc2.o)
      ...
  "_libintl_ngettext", referenced from:
      _u_add_time in libvim.a(undo.o)
      _msg_add_lines in libvim.a(fileio.o)
      _do_bufdel in libvim.a(buffer.o)
      _msgmore in libvim.a(misc1.o)
      _ex_exit in libvim.a(ex_docmd.o)
      _op_shift in libvim.a(ops.o)
      _op_yank in libvim.a(ops.o)
      ...
  "_libintl_setlocale", referenced from:
      _common_init in libvim.a(main.o)
      _enc_locale in libvim.a(mbyte.o)
      _get_mess_lang in libvim.a(ex_cmds2.o)
      _set_lang_var in libvim.a(ex_cmds2.o)
      _ex_language in libvim.a(ex_cmds2.o)
      _mac_lang_init in libvim.a(os_mac_conv.o)
  "_libintl_textdomain", referenced from:
      _common_init in libvim.a(main.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
error: command failed: 'refmterr' 'dune' 'build' '-p' 'Oni2' '-j4' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1
```

I'm using MacOS 10.15.4. Tried to reinstall project and dependencies but no luck.
Found the same issue with linking #1568 but it's already closed and no solutions were found.

**Comment by CrossR** [comment]
One of the things @bryphe mentioned on Discord was trying `brew install gettext` (or equivalent in other package managers).

You can check if you have that already with `find /usr -name libintl* -print 2>/dev/null`.

**Comment by ArtemDrozdov** [comment]
@CrossR Thanks for reply!

Googled some similar issues and tried a lot of things: reinstalling gettext, relinking it, putting export variables into mine .zshrc:
```
export PATH="/usr/local/opt/gettext/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/gettext/lib"
export CPPFLAGS="-I/usr/local/opt/gettext/include"
```

`find /usr -name 'libintl*' -print 2>/dev/null` command (with quoted libintl*) returns this:
```
/usr/local/include/libintl.h
/usr/local/lib/libintl.dylib
/usr/local/lib/libintl.8.dylib
/usr/local/lib/libintl.a
/usr/local/Cellar/gettext/0.20.1/include/libintl.h
/usr/local/Cellar/gettext/0.20.1/lib/libintl.dylib
/usr/local/Cellar/gettext/0.20.1/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.20.1/lib/libintl.a
```

Not sure if it matters but `find /usr -name libintl* -print 2>/dev/null` (without quotes around libintl*) gives me `zsh: no matches found: libintl*`.

**Comment by ArtemDrozdov** [comment]
I was able to fix that problem after few days of investigating and trying different options. :relieved: :tada:

So I would leave some options to try if someone faced the same problem during building:
1. Try `brew install gettext`;
2. You can try force link gettext with `brew link gettext --force` command;
3. (Helped option) Full reinstall of brew. After that step I didn't have to even link gettext to make the build.

Also maybe uninstalling and installing or upgrading gettext can work out but this didn't work for me.
