### ISSUE TITLE
Double clicking macOS title bar doesn't resize the window

### ISSUE THREAD

**Issue by opeik** [onivim/oni2#1631]
Very minor, but would be a nice quality of life feature.

Expected behaviour:

- When you double click the title bar, the window resizes to use all available space 

Actual behaviour:

- Nothing

**Comment by glennsl** [comment]
I'm pretty sure you mean title bar, soI corrected that for you. Otherwise I do not know what you mean.

**Comment by ArtemDrozdov** [comment]
Created issue in Revery repository to add double click event on Node so this feature can be implemented.
