### ISSUE TITLE
Cannot insert at the start of lines with visual block

### ISSUE THREAD

**Issue by opeik** [onivim/oni2#1633]
![out](https://user-images.githubusercontent.com/11566773/79685518-09294580-826c-11ea-98c5-6f1c126bc5f1.gif)

After creating a visual block, pressing `I` doesn't seem to do anything. Pressing `c` on the other hand does work, but consumes the first character as you'd expect.

Steps to reproduce:

- Create a visual block selection (`Control-Q`) containing only the first character of every line
- Press `I` to enter insert mode

Expected behaviour:
- You enter insert mode at the start of every line

Actual behaviour:
- Nothing happens

**Comment by Apostolique** [comment]
The same issue happens with regular visual mode. `I` and `A`.

**Comment by mtippett** [comment]
Hey looking into this as part of an online debugging experiment (see twitch.tv/bastiondebugging).

Looking at the actual behavior suggested, vim doesn't actually operate in the same way, when you go highlight a block ```^V```, and then run ```I``` to insert the block selection is cleared and you fall back to single character.  This violates the expected behavior as described above.  I'll see if libvim does this behavior elsewhere.

**Comment by mtippett** [comment]
I've looked into it a bit under LiveDebug (https://www.twitch.tv/bastiondebugging).  

It looks like libvim isn't handling the block mode correctly.  I'll be updating the visual_mode tests to demonstrate for comparison.  Observations are (using unit test hacks)...

Starting file is
```
line1
line2
line3
line4
line5
```
The `test_insert_block_mode` is modified to comment out the viminput("<c-v>") and ("j") (ie: just doing a straight insert).  Output is

```
LINE: abcline1
LINE: line2
LINE: line3
```

When the visual mode is used, with "I", it will produce

```
LINE: line1
LINE: line2
LINE: line3
```
expected
```
LINE: abcline1
LINE: abcline2
LINE: abcline3
```

When visual mode is used with "c", it will product
```
LINE: abcine1
LINE: ine2
LINE: ine3
```
Expected 
```
LINE: abcine1
LINE: abcine2
LINE: abcine3
```

I'll construct a pull request for these tests in the next debug run.

**Comment by 77abe77** [comment]
Any update on this issue? I am still experiencing this on latest build https://github.com/onivim/oni2/commit/c7711292500331dc4c4ccd676c7df94717557626

**Comment by Shirk** [comment]
Also still in 4aa0458a but since it's probably a libvim issue it might be better situated in that repo.
