### ISSUE TITLE
Unable to clear terminal with ^L

### ISSUE THREAD

**Issue by opeik** [onivim/oni2#1636]
Expected behaviour:

- Terminal is cleared when <kbd>Control</kbd>+<kbd>L</kbd> is pressed 

Actual behaviour:

- Nothing happens

Steps to reproduce:

- Open a terminal
- Press <kbd>Control</kbd>+<kbd>L</kbd>

**Comment by avimmer** [comment]
A lot of other combinations like `<C-J>` for enter, `<C-[>` for ESC, `<C-H>` for backspace and possibly others don't reach the shell running through the terminal. Should they be separate issues or they're all related?

**Comment by alincota** [comment]
I just downloaded it today and when I was trying it out I had a similar experience to the one described here. Also, calling clear in ther terminal resulted in the following error (see attached).
![onivim_clear_issue](https://user-images.githubusercontent.com/16885897/82152667-ce123600-985a-11ea-8598-a61558a2850e.png)
