### ISSUE TITLE
Starting a new "find in files" search doesn't interrupt the existing search

### ISSUE THREAD

**Issue by opeik** [onivim/oni2#1637]
Expected behaviour:
- Starting a new "find in files" search interrupts the existing search

Actual behaviour:
- The existing search continues, and our new search doesn't occur

Steps to reproduce:
- Start a search with "find in files"
- Start a new search with "find in files" before the existing one has completed

**Comment by glennsl** [comment]
I can't reproduce this. For me it always aborts the current search and immediately starts showing results for the new search. It could perhaps be a platform-specific bug though. Which platform are you using?

**Comment by opeik** [comment]
macOS, I start the search in my home directory which has a million dotfiles.

**Comment by glennsl** [comment]
I can reproduce this very rarely on my MacBook. Does it happen for you every time you interrupt a previous search, or just occasionally?

**Comment by opeik** [comment]
It happens every time.

**Comment by bryphe** [comment]
This should be fixed now with the changes in https://github.com/onivim/oni2/pull/3488
