### ISSUE TITLE
syntax highlighting dissapears - possibly due to broken config file

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1638]
Syntax highlighting has dissapearred for me on oni, possibly related to a broken config (preferences) file as discussed last week on discord. I can't see an obvious mistake but here is my config below:

```
{
  "workbench.colorTheme": "One Dark Pro",
  "editor.detectIndentation": true,
  "editor.largeFileOptimizations": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.indentSize": 4,
  "editor.insertSpaces": false,
  "editor.lineNumbers": "on",
  "editor.matchBrackets": true,
  "editor.minimap.enabled": true,
  "editor.minimap.maxColumn": 120,
  "editor.minimap.showSlider": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "all",
  "editor.rulers": [],
  "editor.tabSize": 4,
  "editor.zenMode.hideTabs": true,
  "files.exclude": [ "_esy", "node_modules" ],
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.iconTheme": "vs-seti",
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true, 
  "vim.useSystemClipboard": true:
}
```

**Comment by glennsl** [comment]
```
  "vim.useSystemClipboard": true: <--- there
```

**Comment by glennsl** [comment]
This is being addressed by #1590 btw

**Comment by yunti** [comment]
Thanks, wow I'm blind sometimes. ☺️  Thanks @glennsl.

**Comment by bryphe** [comment]
Good test case for #1590 - with it, we'll show an error highlight:
![image](https://user-images.githubusercontent.com/13532591/79759230-4674ee00-82d3-11ea-99ad-63a8acf2f484.png)

and a message:
![image](https://user-images.githubusercontent.com/13532591/79759274-5391dd00-82d3-11ea-8389-a9552bb1e336.png)

Hopefully will make config errors easier to catch!
