### ISSUE TITLE
move out of terminal into other splits

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1640]
I do not find an easy way to use keys to move out of terminal into other splits, when a terminal is one of the splits:

![Screenshot from 2020-04-20 13-26-02](https://user-images.githubusercontent.com/8382834/79746573-7f7c8500-830a-11ea-9d06-9877326036b0.png)

Would it be possible to make sure that Ctrl-W + {hjkl arrows} allows to move in / out of the terminal window as if it were a normal split?

**Comment by avimmer** [comment]
It works by first going into normal mode using `<C-\><C-N>`, then using a window command like `<C-W>{hjkl}`. It's the same way it's implemented in neovim and possibly vim 8+ as well. I'm seeing it as preferred way of working with the terminal window, because:
* it's compatible with vim/neovim defaults;
* it doesn't mask `<C-W>` from the terminal itself.

It it's not possible to remap this binding atm. then it's another story.

**Comment by mabuchner** [comment]
On my german Mac keyboard I have to press three keys (Shift-Alt-7) for a backslash. This makes it impossible to use the default keybinding `<C-\><C-N>` on this kind of keyboards.

Of course software can't consider all kinds of language specific oddities, but I really wish, I could just use the regular window commands instead.

This is my first day using Oni2, so I still need to figure out, how and if this can be solved with a custom key binding.

**Comment by CrossR** [comment]
In case anybody is interested, this is what I'm using at the moment in my `configuration.json` (Ctrl/Cmd-Shift-P -> Open Configuration File).

```json
  "experimental.viml": [                                                                                                                                            
    "nnoremap <C-H> <C-W><C-H>",                                                                                                                                    
    "nnoremap <C-J> <C-W><C-J>",                                                                                                                                    
    "nnoremap <C-K> <C-W><C-K>",                                                                                                                                    
    "nnoremap <C-L> <C-W><C-L>"                                                                                                                                     
  ]
```

Which does allow you to leave the terminal etc, but is also does conflict with built in commands (`Ctrl-l` in most Unix terminals clears the screen). For some people, the conflicts won't matter (as it doesn't really matter to me on Windows), so the binds might be useful.

That should allow you to move around as you'd expect.
