### ISSUE TITLE
Terminal opening up blank 

### ISSUE THREAD

**Issue by quuu** [onivim/oni2#1648]
![image](https://user-images.githubusercontent.com/32676955/79794739-ca08fc00-8320-11ea-8615-e1635532385f.png)

Opening up the terminal with :term, command pallete :terminal, and any method opens a blank panel that can't be interacted with.

Recloned and built from source, still running into the same issue.

MacOS Catalina 10.15.3

**Comment by glennsl** [comment]
Possibly related: #1461, #1494, #1531

**Comment by quuu** [comment]
> Possibly related: #1461, #1494, #1531

@glennsl  saw #1461, reported this because in #1461 the terminal at least detected to use the fish shell. In this bug, no shell gets detected at all.

**Comment by glennsl** [comment]
Yeah I'm not suggesting it's a duplicate. Those issues should be fixed as well, so this seems like something different.

**Comment by quuu** [comment]
Added debug output to running it, seems like it can't find my shell?
![image](https://user-images.githubusercontent.com/32676955/79807442-def18980-8338-11ea-8938-b5e8f2d95536.png)

**Comment by bryphe** [comment]
Hi @quuu - it sounds like you built from source.

Did you [install the node dependencies](https://onivim.github.io/docs/for-developers/building#install-node-dependencies) - via the `node install-node-deps.js` command? That's needed to bring in all of our node dependencies (required for the extension host / terminal). If those aren't present - the terminal won't load.

Once that has run - we should see a `vscode-exthost` folder in `oni2/node/node_modules`

**Comment by quuu** [comment]
@bryphe  Thanks! It worked, I missed that step in building thinking it was to be ran if npm install failed or something
