### ISSUE TITLE
Command window popup hides big part of the file

### ISSUE THREAD

**Issue by janvanveldhuizen** [onivim/oni2#1650]
![onivim2](https://user-images.githubusercontent.com/43573150/79883206-eb86e800-83f3-11ea-8f3f-971bbca6cc5a.gif)
This is sometimes annoying. See the attached example, where I want to replace the string win2016sql16 by another string, using the :s/ command.
With a vim-like command line at the bottom you can still see the source lines, but now the string I want to replace is hidden.
Maybe this can be made optional? Or maybe the popup can be made resizable or movable/

**Comment by bryphe** [comment]
Looks like @zbaylin 's fix #1979 addressed this:

![image](https://user-images.githubusercontent.com/13532591/85346602-cd4c6f80-b4aa-11ea-8c44-beb30afff594.png)

**Comment by janvanveldhuizen** [comment]
I hope so. Waiting for his PR to be merged.

**Comment by bryphe** [comment]
This should be fixed now with #1979 - but let us know if you have additional feedback 👍
