### ISSUE TITLE
Add window size to configuration

### ISSUE THREAD

**Issue by janvanveldhuizen** [onivim/oni2#1659]
As you cannot easily change the window size (In Windows the Alt+Space shortcut doesn't work) I would suggest to add a "workbench.windowSize" option in config file, in order to be able to always launch at your prefered size.

**Comment by glennsl** [comment]
Don't you think it would be better to have workspace persistence, as proposed in #640? That's how most apps solve this.

**Comment by janvanveldhuizen** [comment]
Yes, that makes more sense.
Basically, what I miss is the standard Windows alt+space menu, where I can quickly maximize the windows with Alt-Space-X.

**Comment by glennsl** [comment]
Right, yeah you might want to make an issue in https://github.com/revery-ui/revery for that. Doesn't sound like it'd be too hard to add, but it does require some native integration.

**Comment by glennsl** [comment]
Should this be considered fixed by #1703? Enabling <kbd>Alt</kbd>+<kbd>Space</kbd> is a Revery-issue entirely I think.

**Comment by janvanveldhuizen** [comment]
I agree
