### ISSUE TITLE
_release/run.sh doesn't work for MacOS

### ISSUE THREAD

**Issue by ddmendes** [onivim/oni2#1667]
I just gone through [How to build and run from source](https://onivim.github.io/docs/for-developers/building) today and when I executed the `./scripts/osx/create-symlink.sh` then command oni2 was not working.

In order to fix it I edited the _release/run.sh, on the last line. It was
```sh
"$DIR"/../MacOS/Oni2 --working-directory "$CWD" "$@"
```
and I changed it to
```sh
"$DIR"/Onivim2.app/Contents/MacOS/Oni2 --working-directory "$CWD" "$@"
```
and now the command oni2 works.

I would open a PR but I'm without time to understand how all of this works.
If someone could mentor me on this fix I can do it myself.

Really thank you for this project! I'm really loving it!

**Comment by CrossR** [comment]
I think this is the instructions and the code becoming a bit out of sync (I didn't realise there was a "Make symlink" script when updating the code, as I just use `esy run` to debug locally).

The current `run.sh` script is made to be used with the release build of Oni2. That is, `esy create-release`, install the application as normal by dragging to your applications, start Oni2, and from inside Oni2 `Add to system PATH` (Cmd-Shift-P). That should then add the `oni2` executable to your path to use in the shell.

As such, that path is setup for the way the in application symlink works. I think changing it would break that workflow. We might just want to add a new duplicated script with your fix, or improve the logic of working out which environment we are in

**Comment by ddmendes** [comment]
Hi @CrossR ! Great, so it's just doc out of sync.

I'll try to install as you said and then I'll update the doc for you. Is it ok?

**Comment by CrossR** [comment]
Sounds good!

I'm not sure if anyone uses the symlink script in development, so if its not used we could just drop mentioning it at all.

**Comment by ddmendes** [comment]
PR #1669
