### ISSUE TITLE
Opening new buffer loses changes in previous buffer

### ISSUE THREAD

**Issue by ijzerbroot** [onivim/oni2#1671]
Hello,

I had not seen this one reported yet (or my search-fu is broken).
When opening a new buffer I seem to lose my unsaved changes in the buffer I was previously working in. ~~But this only happens at the first switch and to the first buffer.~~
I don't have a screenrecorder but to reproduce:
1. open a new buffer with :e filename and type a few words
2. open another buffer with :e otherfilename and type some words

When switching to the first buffer it will be empty.
Switching back to the second buffer shows that that one still looks good
This is on Windows 10.

Is this a known issue ?

EDIT: it looks that the loss of unsaved changes happens for the buffer that was active at the time when ":e newfile" is given. For me it seems to happen everytime I open a new buffer.

**Comment by bryphe** [comment]
Thanks for logging this issue, @ijzerbroot ! Indeed, there's something going wrong here - seems specific to the `:e` command. It's interesting that opening from the quickopen (which takes a different code path) doesn't seem to clear out the buffer contents.
