### ISSUE TITLE
Change: Minimap max width

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#168]
The minimap is currently pretty wide:

![image](https://user-images.githubusercontent.com/10038688/54566019-9e9e3a00-49c7-11e9-856a-eac7ed65977e.png)

This is on a 4K monitor with 150% scaling, Windows 10.

I think it probably makes most sense to default to 80 cols, and have a configuration option for more (`"editor.minimap.maxColumn"` in VSCode.) I can't quite tell from the code if this is what is already attempted to be done, so maybe this is only a small change.

**Comment by bryphe** [comment]
Sounds good! Seems like if we implement `editor.minimap.maxColumn`, we should be good-to-go.

The current code doesn't handle this today - it auto-sizes to scale up with the buffer width (so the same number of columns should be visible in the minimap as in the buffer). This is where we the 'auto-sizing' is implemented:
https://github.com/onivim/oni2/blob/1b9124ef67d65e8bd7ddf50825ca722b66714bee/src/editor/Model/EditorLayout.re#L45
