### ISSUE TITLE
Sneak isn't usable on 29/4/2020-5:43:44 Build

### ISSUE THREAD

**Issue by JorgeDLG** [onivim/oni2#1686]
As you can see in the image, the letters are unreadable.
![Oni-SneakBroken](https://user-images.githubusercontent.com/44321931/80619389-f15c7900-8a44-11ea-9160-bae4b8035ca2.png)

My system:
Linux dlag-pc 5.6.7-arch1-1 #1 SMP PREEMPT Thu, 23 Apr 2020 09:13:56 +0000 x86_64 GNU/Linux

**Comment by bryphe** [comment]
Thanks for logging the issue, @JorgeDLG - I'm able to repro with the `Monokai` theme, too.
