### ISSUE TITLE
Navigation `gg` needs another (any) keypress to register

### ISSUE THREAD

**Issue by Samonitari** [onivim/oni2#1691]
Tested with commit (at least 2e704922), or nighlty build at 2020.03.30
If I type `gg` in normal mode, it won't go to the first line, until I press another key - it does not matter what I press.

Seems like it waits for the key sequence to complete, but it already is.

Platform: Windows 10

**Comment by glennsl** [comment]
I can't reproduce this. Do you have any custom keybindings?

**Comment by Samonitari** [comment]
hmm, I don't think so
keybinding.json:
```
{
    "bindings": [
        { "key": "<C-P>", "command": "quickOpen.open", "when": [["editorTextFocus"]] },
        { "key": "<S-C-P>", "command": "commandPalette.open", "when": [["editorTextFocus"]] },
        { "key": "gt", "command": "commandPalette.open", "when": [["editorTextFocus"]] },
        { "key": "<ESC>", "command": "menu.close", "when": [["menuFocus"]] },
        { "key": "<C-N>", "command": "menu.next", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<down>", "command": "menu.next", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<up>", "command": "menu.previous", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<CR>", "command": "menu.select", "when": [["menuFocus"], ["textInputFocus"]] }
    ]
}
```

But there is definitely some funky think going on with keybindings:
If I use `G` with CapsLock, it produces the same behaviour, even though `H` `M` `L` does not - the latter ones react just fine, with CapsLock or with Shift

**Comment by glennsl** [comment]
What happens if you disable the `gt` keybinding?

I doubt this is platform-specific, but still definitely nice to know just in case. There are a few known issues with keybinding sequences though, so I'm thinking it's probably that.

**Comment by glennsl** [comment]
Great. Thanks for confirming! I don't expect this bug to live for very long as it's causing several other problems and blocking feature implementation as well.

> is it default, or did I make this?

It's definitely not a default, and it's not an old default either as this kind of keybinding is relatively new.

> The thing is though, gt and gT are tab switching for me a la vim, so I cannot get rid of it.

I'm not sure I see how having `gt` open the command palette relates to that, as that's not even a vim feature... I can see how you'd want `gt` and `gT` to bind to `next`/`previousEditor`. Hopefully we'll have that sorted soon.

**Comment by Samonitari** [comment]
> I'm not sure I see how having `gt` open the command palette relates to that, as that's not even a vim feature... I can see how you'd want `gt` and `gT` to bind to `next`/`previousEditor` though, if that's what you mean. Hopefully we'll have that sorted soon.

I meant that `gt` is must, but in the vim way for me, so not as in my config - maybe I way going for that, but just with commanPalette, and then forgot it after I did not find the correct command for it.

Could you tell it for it and/or the way to discover the other keybinding options?

**Comment by glennsl** [comment]
The commands you ca bind to? That's really any command in the system, built-in or contributed via extensions. Which is a lot. Unfortunately there isn't a way for end-users to discover those easily, but I imagine one day we'll add some way of getting the command id of anything in the command palette. In the meantime you can look at either the current default keybindings:

https://github.com/onivim/oni2/blob/2e704922b440a9a6a4a44022ca702aca4610131b/src/Store/KeyBindingsStoreConnector.re#L16-L341

or the globally defined commands, but even that doesn't list all the built-in commands:

https://github.com/onivim/oni2/blob/2e704922b440a9a6a4a44022ca702aca4610131b/src/Model/GlobalCommands.re#L16-L380
