### ISSUE TITLE
closing the search pane doesn't "defocus it"

### ISSUE THREAD

**Issue by tcoopman** [onivim/oni2#1693]
Steps to reproduce:

1. Open the search pane
2. Close it
3. type anything
4. open the search again

All the input you typed is now in the `Find in Files` box.

Expected: if you close the search pane, the focus is given back to the window

**Comment by glennsl** [comment]
There seems to be two similar but separate issues here. One is that he search input field doesn't unfocus when the pane is closed with the close button, which might be old but is an easy fix. The other is that it doesn't unfocus the search input field if you click on the editor while the pane is still open. This is a relatively new issue, and I haven't been able to track down the cause yet.
