### ISSUE TITLE
Some characters only show up after 3 times.

### ISSUE THREAD

**Issue by Apostolique** [onivim/oni2#170]
https://gfycat.com/HarmfulHatefulBeauceron

In the video above, I press 'é' 3 times for a single one to show up. Each one has the width of 2 characters. (I think it does that on accented characters.)

**Comment by Muream** [comment]
The same thing happens on my side but I'm using WinCompose to create the accented character so it's probably not an issue with ethe input but rather the special character itself.
I also got a crash when trying to enter the € sign:
`Fatal error: exception Invalid_argument("U+20AC is not a latin1 character")`

**Comment by bryphe** [comment]
Some additional information from Discord - keyboard layout:
![image](https://user-images.githubusercontent.com/13532591/54651927-1aed5780-4a72-11e9-95b6-ebb7fcfffce3.png)

(Canadian French layout - Windows)

More details from chat:

ç is above enter with c
So I press 2 keys
è is left of enter with e -> 2 keys
^^ doesn't glitch it
`` doesn't glitch
} glitches

1 issue is on specific keys
And 1 issue is on keyboard layouts
I can't write [ and ] at all
~ gets entered as ;~
semicolon and tilde
I enter it with alt + ;  which normally gives ~
