### ISSUE TITLE
The language client requires VS Code version ^1.41.0 but received version 1.33.5

### ISSUE THREAD

**Issue by andrewrynhard** [onivim/oni2#1707]
I'm seeing this in the debug logs when attempting to use the `vscode-go` extension

```
[DEBUG]    +0ms Oni2.Extensions.NodeProcess : [2671|bootstrap-fork.js] [WARN] [ 'stack trace: Error: The language client requires VS Code version ^1.41.0 but received version 1.33.5\n\tat LanguageClient.checkVersion (/home/andrewrynhard/.config/oni2/extensions/go/node_modules/vscode-languageclient/lib/main.js:123:19)\n\tat new LanguageClient (/home/andrewrynhard/.config/oni2/extensions/go/node_modules/vscode-languageclient/lib/main.js:104:18)\n\tat buildLanguageClient (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:102:22)\n\tat /home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:90:13\n\tat Generator.next (<anonymous>)\n\tat /home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:12:71\n\tat new Promise (<anonymous>)\n\tat __awaiter (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:8:12)\n\tat startLanguageServer (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:69:12)\n\tat Object.<anonymous> (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:64:16)\n\tat Generator.next (<anonymous>)\n\tat fulfilled (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:9:58)\n\tat process._tickCallback (internal/process/next_tick.js:68:7)' ]
[DEBUG]    +1ms Oni2.Extensions.NodeProcess : [2671|bootstrap-fork.js] UNEXPECTED ERROR: Error: The language client requires VS Code version ^1.41.0 but received version 1.33.5

```

**Comment by glennsl** [comment]
@bryphe  in the process of updating the extension host component, which should fix this (and make it easier to keep up to date in the future)

**Comment by andrewrynhard** [comment]
Would that happen to be #1706?

**Comment by glennsl** [comment]
That and many other PRs. It's been a work in progress for a couple of weeks now. I don't want to put my foot in my mouth by saying anything about when I think it'll be done, but I'm pretty sure it's closer to the end than it is to the beginning at least.

**Comment by andrewrynhard** [comment]
:+1: Awesome, looking forward to it.

**Comment by bryphe** [comment]
Ah ya, this is the main thing I've been working on the past couple of weeks - upgrading our extension host to the latest. 

I'm tracking the final 'integration' here: https://github.com/onivim/oni2/pull/1708 - still a few pieces that need to come in, and some testing (it's a pretty big switch). But will be much easier for us to keep up-to-date in the future, since we require very little modification to the Code extension host now.

**Comment by bryphe** [comment]
This is actually fixed now - I tested with this extension: https://github.com/microsoft/vscode-go/releases/tag/latest


And am now able to get diagnostics, completion, and signature help from the go extension:
![image](https://user-images.githubusercontent.com/13532591/85188581-b6184280-b25c-11ea-867b-89e2c4a5a40d.png)

There's a few tools that need to be set up manually - so I need to document the full set of instructions, still. But this particular issue is fixed, since our extension host is newer and now can support the `vscode-go` extension 👍 

I'll keep this open to track adding a language section for `go`, though, in our documentation.

**Comment by andrewrynhard** [comment]
@bryphe Are there any plans to get the go tools installation command working?

**Comment by bryphe** [comment]
> Are there any plans to get the go tools installation command working?

Yes! I believe we have the APIs wired up for it (for it downloading the binaries / prompting for suggestion). I've also added some documentation: https://onivim.github.io/docs/languages/go - with the recommendation to use `"go.languageServer": true` and `gopls`

**Comment by bryphe** [comment]
This error is fixed in the latest build:
```
[DEBUG]    +0ms Oni2.Extensions.NodeProcess : [2671|bootstrap-fork.js] [WARN] [ 'stack trace: Error: The language client requires VS Code version ^1.41.0 but received version 1.33.5\n\tat LanguageClient.checkVersion (/home/andrewrynhard/.config/oni2/extensions/go/node_modules/vscode-languageclient/lib/main.js:123:19)\n\tat new LanguageClient (/home/andrewrynhard/.config/oni2/extensions/go/node_modules/vscode-languageclient/lib/main.js:104:18)\n\tat buildLanguageClient (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:102:22)\n\tat /home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:90:13\n\tat Generator.next (<anonymous>)\n\tat /home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:12:71\n\tat new Promise (<anonymous>)\n\tat __awaiter (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:8:12)\n\tat startLanguageServer (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:69:12)\n\tat Object.<anonymous> (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:64:16)\n\tat Generator.next (<anonymous>)\n\tat fulfilled (/home/andrewrynhard/.config/oni2/extensions/go/out/src/goLanguageServer.js:9:58)\n\tat process._tickCallback (internal/process/next_tick.js:68:7)' ]
[DEBUG]    +1ms Oni2.Extensions.NodeProcess : [2671|bootstrap-fork.js] UNEXPECTED ERROR: Error: The language client requires VS Code version ^1.41.0 but received version 1.33.5
```

We're now at version 1.52.1 (and plan on staying closer in sync!)
