### ISSUE TITLE
Terminal displays warnings about missing libraries before bash prompt

### ISSUE THREAD

**Issue by avimmer** [onivim/oni2#1722]
Onivim 2 0.4.0 `ea560d1d` run as an AppImage.

When opening a terminal window seeing the following list of warnings before the bash prompt:
```
flatpak: /tmp/.mount_onigmzEhN/usr/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/libarchive.so.13)
flatpak: /tmp/.mount_onigmzEhN/usr/lib/libmount.so.1: version `MOUNT_2.24' not found (required by /lib64/libostree-1.so.1)
flatpak: /tmp/.mount_onigmzEhN/usr/lib/liblzma.so.5: version `XZ_5.2' not found (required by /lib64/librpmio.so.8)
```

neovim installed via an AppImage doesn't behave the same way when opening a terminal window.

**Comment by bryphe** [comment]
This should be fixed now with: https://github.com/onivim/oni2/pull/2608
