### ISSUE TITLE
Cannot create configuration dir path on Windows - wrong path is used

### ISSUE THREAD

**Issue by Samonitari** [onivim/oni2#175]
Oni2 tries to create the directory for storing configuration file, on opening it first-time from command palette. So far, so good.
Unfortunetly, on Windows it fails to do so, with error
`can't create directory 'C:\Users\***\AppData\Local\.config\oni2' because 'No such file or directory`

Causes
1. Creating the oni2 directory doesn't create the parent directories, only the last level. This is reflected in the error msg, so it is the direct cause.
2. The underlying issue is in `src/editor/Core/Filesystem.re :: getOniDirectory` implementation.
It should be also platform specific, as `unsafeFindHome` - using .config is smelly on Windows, Oni used `AppData/Roaming/Oni`, instead of `Appdata/Local/.config/oni2` by the way.

**Comment by Akin909** [comment]
@Samonitari thanks for raising the issue, I added that recently but I don't have a windows machine or understand it's filesystem very well thanks for raising this. I definitely didn't know that it doesn't use `.config` I'll look at changing that to use `/Roaming/Oni`

**Comment by Samonitari** [comment]
I'll continue to "test" Oni2 on Windows with pleasure!

Also, the Local vs. Roaming is a usecase question:
If you want to domain sync the settings (i.e.: workplace login on multiple computers) use Roaming, otherwise use Local.
see this [SuperUser Question](https://superuser.com/questions/21458/why-are-there-directories-called-local-locallow-and-roaming-under-users-user)
I'd like Roaming if possible though!
