### ISSUE TITLE
Bug: Selecting root folder in explorer locks up navigation keys

### ISSUE THREAD

**Issue by Phaen** [onivim/oni2#1779]
When the root folder in the explorer is selected, either directly by clicking, through sneak or by navigating to it using the arrows, it locks up the navigation keys. When this happens, the arrow keys no longer allow you to navigate away and the enter key no longer toggles the folder's display either. The sneak feature can still be used to navigate away, but using it to navigate repeatedly to the root folder will not toggle its display.

**Comment by bryphe** [comment]
This should be fixed now with #2502 - focus and navigation has been completely revamped (with that and some other PRs, #2476 #2492 #2519 #2540 #2560 #2600 )
