### ISSUE TITLE
oni2 --extensions-dir not working / improperly documented

### ISSUE THREAD

**Issue by clehene** [onivim/oni2#1783]
The [documentation](https://onivim.github.io/docs/configuration/extensions) states that

> This can be overridden with the --extensions-dir command line flag however.

I tried both

    oni2 --extensions-dir ~/.vscode/extensions

and 

    oni2 --extensions-dir=~/.vscode/extensions

None seem to work

**Comment by CrossR** [comment]
Whoops! Looks like this wasn't being passed over in some part of the code...I'll stick a PR up.

Thanks for raising!

**Comment by clehene** [comment]
@CrossR thank you for patching this. 

Unfortunately it still doesn't work / not documented properly.
How is it supposed to be used? Please consider updating the documentation too.

```
(⎈ |dev-1:default)➜  ~ oni2 --extensions-dir ~/.vscode/extensions
(⎈ |dev-1:default)➜  ~ oni2 --list-extensions
(nothing)
```
