### ISSUE TITLE
On Windows, window edges extend outside of the screen when maximised

### ISSUE THREAD

**Issue by Phaen** [onivim/oni2#1817]
When maximising the Oni2 window on Windows, all four edges of the window extend outside of the screen and are not rendered. The following images demonstrate the issue:

This is the top-left of a regular floating window. This is expected behaviour, nothing out of the usual.
![Top-left of regular floating window](https://user-images.githubusercontent.com/5429189/82751317-9c4b2300-9db6-11ea-9065-04873275a8ff.png)

When maximising the window, you can see that both edges are slightly cut off. Besides the lack of spacing, this is apparent from the cut logo and the disappearing indicators for the file explorer and search.
![Maximised window (both edges are cut off)](https://user-images.githubusercontent.com/5429189/82751340-c866a400-9db6-11ea-90fe-2a4070f8158e.png)

While lazy resizing to a regular window, it becomes more apparent that the edges were not rendered. (Window isn't re-rendered during a lazy resize, filling the unrendered edges with content of the old render.)
![While resizing to regular window](https://user-images.githubusercontent.com/5429189/82751390-17acd480-9db7-11ea-8442-73f081c6f438.png)

**Comment by CrossR** [comment]
I've stuck a comment on #1801 with some issues I've seen, I think that is related.

**Comment by zbaylin** [comment]
Thanks @Phaen for bringing this to our attention! I think this happens because we render _over_ the default frame, and when the window is maximized, the frameshape changes, which we (well, more accurately SDL2) doesn't adjust for. I'll mess around with this either today or early this week to come up with a fix!

**Comment by bryphe** [comment]
This is fixed now with #1823 - thanks @zbaylin !
