### ISSUE TITLE
Text goes underneath minimap incorrectly

### ISSUE THREAD

**Issue by alincota** [onivim/oni2#1819]
On a Linux Ubuntu 18.04, Oni2 version 0.4.0 I'm getting an unexpected behaviour when text reaches the end of the screen:
text dissapears (because it goes underneath the minimap) and only after you type some more and it finally reaches the actual end of the screen, it then starts scrolling horizontally.

The way I see it, the left side of the minimap column (if I can call it this way) is the end of the edit area and it should trigger scrolling/ wrapping (if enabled) the moment text gets close to it.

**Comment by glennsl** [comment]
Closing as duplicate fo #1544
