### ISSUE TITLE
Search the yanked string crashes the app.

### ISSUE THREAD

**Issue by dlagg** [onivim/oni2#1820]
If you try to yank a selection, `/` for search, and `Ctrl` + `R` + `"` for paste the yanked string. The app crashes. I don't know if `Ctrl` + `R` keybind is implemented yet.

**Comment by mabuchner** [comment]
Just entering insert mode and pressing `<C-R>` will also freeze Oni2.

1. `oni2 foo.txt`
2. `i`
3. `<C-R>`

In Vim I'm using this feature a lot, because it allows to paste a register without having to leave insert mode.

**Comment by bryphe** [comment]
Fixed with #2101
