### ISSUE TITLE
Nim VsCode extension crashing oni2

### ISSUE THREAD

**Issue by nepeckman** [onivim/oni2#1825]
I installed the [Nim language extension](https://github.com/pragmagic/vscode-nim) by navigating to the oni2 extensions directory and git cloning the repo. Oni starts fine, but if I try to open a .nim file, it crashes immediately. 

The crash log is very short: `Yojson.Safe.Util.Type_error("Can't get member 'name' of non-object type string", _):`

Please let me know if more details are needed. Thanks!

**Comment by bryphe** [comment]
Thanks for logging the issue, @nepeckman !

Looks like there is a bug in our textmate syntax parser - it's crashing parsing these capture groups: https://github.com/pragmagic/vscode-nim/blob/989d9b52d86e5291e6804aa2de4db5407f5b1e74/syntaxes/nim.json#L316

(We're always expecting that to be a `name` field, but... seems out that is a wrong expectation).
