### ISSUE TITLE
Wrong default value for editor.insertSpaces

### ISSUE THREAD

**Issue by mabuchner** [onivim/oni2#1826]
According to the [documentation](https://github.com/onivim/oni2/blob/1f1ceb227d26c5656cb0ce8b375d17d6d116a847/docs/docs/configuration/settings.md#L55) the default value for `editor.insertSpaces` is `true`. However calling `Preferences: Open Configuration File` for the first time will show a configuration file with `editor.insertSpaces` set to `false`.

**Comment by glennsl** [comment]
Thanks for the report! This was sort of addressed in #1580 as well, but that just fixed the default, not the initial value in the configuration file. Which ought to always be the same, of course, but that's a more involved issue we'll ned to address separately.
