### ISSUE TITLE
Syntax highlighting for CMakeLists.txt

### ISSUE THREAD

**Issue by mabuchner** [onivim/oni2#1829]
I installing the [CMake For VisualStudio Code](https://marketplace.visualstudio.com/items?itemName=twxs.cmake) extensions. Now I get syntax highlighting for `*.cmake` files, but `CMakeLists.txt` files are not highlighted.

My guess is, that it doesn't work due to the `*.txt` file extension. I tried to call `:set syntax=cmake` and `:set filetype=cmake`, but nothing obvious changed.

It would be nice, if the `CMakeLists.txt` files also could enjoy the [CMake For VisualStudio Code](https://marketplace.visualstudio.com/items?itemName=twxs.cmake) extension.

**Comment by CrossR** [comment]
We aren't using two extra bits of information that the extension host gives us right now for syntax highlighting:

 - First line matching (i.e. shebangs, so we can tell that something with `#!/usr/bin/env bash` should be highlighted as a shell script regardless of extension)
 - Filenames (which gives hard-coded file names that should be highlighted, for example [this](https://github.com/twxs/vs.language.cmake/blob/8602a1399af2144d72fd25dd6ebb884a6cb62aa6/package.json#L46-L48)).

I know we have an issue for the first, but less sure about the second, so we can use this to track the addition of parsing out and actioning on the filename attribute.

I think everything for this one should be in place, so someone just needs to hook up reading it, storing a map of `filename -> syntax` and then finally check that before/after the extension check.

**Comment by bryphe** [comment]
Looks like this is fixed now with @CrossR 's PR to use more information (filenames and first-line matching): https://github.com/onivim/oni2/pull/2119 🎉 

At least - I see some highlighting now, with that plugin:
![image](https://user-images.githubusercontent.com/13532591/89352503-1a566080-d669-11ea-90c7-602f8d3895c1.png)

**Comment by bryphe** [comment]
I'll close this out as resolved by #2119 , but let us know if you still see issues 👍
