### ISSUE TITLE
Windows 10 on bare metal - just a white screen

### ISSUE THREAD

**Issue by kevintynfron** [onivim/oni2#1842]
This is an update from #850 - I have upgraded from windows 7 to Windows 10 Pro.  I am getting the same result as #1809. The underlying UI seems to be there, but I can't see it. 

I did the debug start and attached the result:
[onivim_Debug_log.txt](https://github.com/onivim/oni2/files/4697921/onivim_Debug_log.txt)
It is basically looping around 

```
[INFO]    +27ms Revery.CanvasContext : Creating Skia context...
[ERROR]    +0ms Revery.CanvasContext : Unable to create skia context
```

You mention in #1809 that Onivim is using OpenGL 4+ .  I am using the latest Intel HD3000 driver but it doesn't have any Windows 10 drivers.

I used OpenGL Extension Viewer 6.1.0.0 and it says that 4.0 is supported (21% - 3/4) and no later version. I have added the report generated to this ticket in 
[GLExtensionViewer.zip](https://github.com/onivim/oni2/files/4697985/GLExtensionViewer.zip)

Here's the highlights of what the report on v4.0 supported features.
![gl4_4_support](https://user-images.githubusercontent.com/11351294/83188286-5d56fd80-a127-11ea-8dca-5671604b0b86.png)

**Comment by bryphe** [comment]
Thanks for logging the issue and your detailed investigation, @kevintynfron ! Sorry that it's just one problem (Windows 7 not working) to another...

The log you shared is very helpful - this section here gives some info:
```
[INFO]    +49ms Revery.Core.Window : Window created successfully.
[INFO]     +2ms Revery.Core.Window : OpenGL hardware info:
[INFO]     +0ms Revery.Core.Window :   renderer: GDI Generic
[INFO]     +1ms Revery.Core.Window :   version: 1.1.0
[INFO]     +1ms Revery.Core.Window :   vendor: Microsoft Corporation
[INFO]     +1ms Revery.Core.Window :   shadingLanguageVersion: (null)
```

The OpenGL version is coming across as `1.1.0` for us when we initialize Skia. 

It's unfortunate but the OpenGL support just doesn't seem as great on Windows. I think the best for us to better support broader Windows hardware is to switch to DirectX. Will require us to build ANGLE and change the way we initialize SDL 2 on Windows.

In the meantime - there is a set of steps that some users have tried to get Intel HD 3000 on Windows 10 working with applications that require newer OpenGL - it's pretty rough though: https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

**Comment by mabuchner** [comment]
I have no idea about your technology stack, but OpenGL actually works quite fine on Windows. You just need something like [GLEW](http://glew.sourceforge.net) to load newer OpenGL functions and you might have to request a specific OpenGL version during context creation:

```c++
// Use OpenGL 3.2 core
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK,
    SDL_GL_CONTEXT_PROFILE_CORE);
```

**Comment by mabuchner** [comment]
I think, you can forget my comment. You weren't talking about OpenGL support on Windows in general, but about the Intel HD 3000 GPU on Windows in particular.

**Comment by bryphe** [comment]
#2283 is now in nightly, and we use D3D for rendering - which is better supported with the Intel HD 3000, so this should be fixed now. Please let me know if you still have issues opening Onivim 👍
