### ISSUE TITLE
Using the tab key is unreliable

### ISSUE THREAD

**Issue by dannyharding10** [onivim/oni2#185]
When using the tab key, the cursor moves where it seems it should, but the text entered is far less indented than it should be. You can see the behavior in the attached gif

![bad tabbing](https://user-images.githubusercontent.com/11875246/55049534-a2ab0700-501a-11e9-843c-642b1409b091.gif)

**Comment by bryphe** [comment]
Thanks for logging the issue, @dannyharding10 and for supplying the gif . 

Indeed, we're not handling the 'tab' character correctly here.
