### ISSUE TITLE
[Idea] Any word completion

### ISSUE THREAD

**Issue by Miziak** [onivim/oni2#1862]
At first thanks guys for amazing work, I looking forward for vim tabs and workspace feature.

But it is another nice feature of vim that you may implement it is:
[https://vim.fandom.com/wiki/Any_word_completion](https://vim.fandom.com/wiki/Any_word_completion)
In my setup of neovim i get at first completion from LSP(in oni case from vsc plugin ecosystem) then in same hint i get vim completion of words its super handy and speed up typing so much ;)

I think it wolulb be great to see this in oni, since editing is powered by vim i think you can get completion for words fairly easy ;) And once more thanks for great work ;)

**Comment by bryphe** [comment]
Thanks @Miziak !

> then in same hint i get vim completion of words its super handy and speed up typing so much ;)

Ah ya, definitely something I want to have available. I started a PR for it: https://github.com/onivim/oni2/pull/1227 - need to revive it and get it going again.

**Comment by bryphe** [comment]
We now have keyword completion in latest nightly - implemented in #2575 and #2581 - let me know if you have any feedback on it :+1:
