### ISSUE TITLE
HTML syntax highlighting is not displayed

### ISSUE THREAD

**Issue by thecodejedi** [onivim/oni2#1879]
I'm opening a partial .html file and there is no syntax highlighting. Full html files with <html> tag do work, correctly.

Highlighting for .ts files work, also highlighting of CSS or JS in an html work correctly.

Here is a screenshot of my problem:
![Screenshot from 2020-06-06 11-45-27](https://user-images.githubusercontent.com/1226172/83941544-85f88a80-a7ec-11ea-9035-e15fad2b59df.png)

here is a [log](https://github.com/onivim/oni2/files/4739795/log.txt) of just opening the file with `-f --debug`

this is the [source](https://gist.github.com/thecodejedi/dfebb12915de718e7314e62313bf5c51) of the file I tried to open.

I'm on Fedora 32 with GDM on Wayland. (5.6.15-300.fc32.x86_64)

**Comment by bryphe** [comment]
This looks like a similar issue to https://github.com/onivim/oni2/issues/1899 - a problem with our default `OneDark-Pro` theme. I'm able to reproduce with that theme:
![image](https://user-images.githubusercontent.com/13532591/84720741-bd291300-af33-11ea-865b-ef0b3b1484f9.png)

But other themes, like `Monokai`, seem to work correctly:
![image](https://user-images.githubusercontent.com/13532591/84720776-cc0fc580-af33-11ea-9036-da5aba13a658.png)

**Comment by yunti** [comment]
Just came across this issue today, seems I get it with full html files.  
I'm on the onedark-pro theme as that was the earlier default theme.
What's the default/most tested theme now, so I can switch to that?

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1826271/87945811-29e67e80-ca99-11ea-9793-1d5c0c034755.png">

**Comment by yunti** [comment]
Note syntax highlighting support varies per theme quite a bit eg for jsx in js files. (possibly related)

Dark + theme.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/1826271/87946540-0ff96b80-ca9a-11ea-861a-8bb914d08e8c.png">

one dark pro
<img width="764" alt="image" src="https://user-images.githubusercontent.com/1826271/87946626-2e5f6700-ca9a-11ea-9dd9-15a6a6423a0c.png">

**Comment by bryphe** [comment]
This looks better now with #2301 👍 

![image](https://user-images.githubusercontent.com/13532591/90459564-88157a00-e0b6-11ea-929d-9d4c62262f8c.png)
