### ISSUE TITLE
autocomplete should also complete path delimiters like '/'

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1886]
I want to do a ```:vsp``` from a folder, with 1 file (Readme.md), and a couple of folders, 1 of them called Guide (the other folders have different first letters).

However, when I try to autocomplete starting ```:vps G```, the autocompletion goes only to ```:vsp Guide```, and no matter how many times I press tab, the ```/``` is not autocompleted. I would prefer if it was autocompleted to ```:vsp Guide/``` so that I do not need to type ```/``` myself.

**Comment by glennsl** [comment]
Duplicate of #754
