### ISSUE TITLE
failing commands from the oni2 terminal

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1888]
If I am in a system terminal on my Ubuntu 18.04, I can do a:

```okular guide.pdf```

But from the terminal of onivim2 when I use the same command I get a segmentation fault.

Any idea why? The terminal is much more useful if system commands can be run... :)

**Comment by bryphe** [comment]
I believe this is likely the same issue as #2040 & #2370 - fixed by #2608 

The `LD_LIBRARY_PATH` environment variable was being passed, so it could result in incorrect versions of libraries being used (which could cause a segfault). Let me know if you're still seeing this, though :+1:

**Comment by jerabaul29** [comment]
Yipee, I can confirm that this works now :) .

**Comment by bryphe** [comment]
Awesome, thanks for confirming @jerabaul29 ! :tada:
