### ISSUE TITLE
language 'support' / plugin for Fortran?

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1894]
If I want to have syntax coloring etc for Fortran for example, how can I enable it?

**Comment by glennsl** [comment]
If there's a vscode extension for it, you could try loading that. See https://onivim.github.io/docs/configuration/extensions#installing-extensions The goal is to provide full support for language extensions, but there is some way until we're there.

**Comment by glennsl** [comment]
I'll close this out as answered. If any features of such an extension doesn't work, it should be more or less covered by the umbrella issue for extensions https://github.com/onivim/oni2/issues/1058
