### ISSUE TITLE
giving more help to find extensions / plugins

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#1897]
The manual page there:

https://onivim.github.io/docs/configuration/extensions#installing-extensions

does not help to find where the extensions should be found. Could you add on this page where the recommended location for finding extensions is?

**Comment by jerabaul29** [comment]
Would this page be the best choice for example?

https://marketplace.visualstudio.com/

**Comment by glennsl** [comment]
That definitely has the largest collection of vscode extensions, but I don't think we can recommend as they only allow downloaded extension to be used with vscode-family products. See more about that in #1018 

Another alternative is http://open-vsx.org/

**Comment by bryphe** [comment]
Related to #1932 - definitely need a better experience for installing extensions!

**Comment by bryphe** [comment]
I believe this should be fixed now (since we have a built-in UI for installing extensions) :+1:
