### ISSUE TITLE
Shallow cloning skia deps

### ISSUE THREAD

**Issue by amiralies** [onivim/oni2#1920]
I'm not sure but it seems `esy-skia` is deep cloning its git dependencies.
I think it's possible to improve its behvaiour by cloning specific needed commit. (init, remote add, fetch --depth 1, checkout)

**Comment by CrossR** [comment]
https://github.com/esy/esy/pull/1089 seems to imply that we'd need to swap the commit hash we use to a long one to use the shallow clone.

For some repos (like `esy-skia`) we should probably test/make that change.

**Comment by amiralies** [comment]
I think this can be done about [skia's deps](https://github.com/revery-ui/esy-skia/blob/master/DEPS) (being fetched by a python script) too

**Comment by bryphe** [comment]
Sounds reasonable! Would be open to a PR on esy-skia to do the shallow-cloning: https://github.com/revery-ui/esy-skia

I'll close this here since it's not an issue with Onivim 2, per se, but a dependency-
