### ISSUE TITLE
Text rendering on Winows 10 is completly broken

### ISSUE THREAD

**Issue by Miziak** [onivim/oni2#1937]
Most of text no t rendering at all, but in some files we can see some single lines of text.
Image show bug:
![image](https://user-images.githubusercontent.com/4346598/84599079-a7521a00-ae6f-11ea-91e3-f8126f2800ed.png)

Todays (14.06) build from https://github.com/onivim/oni2/commit/0bf0a9a9b91a0427b5414d27d348d9fac88a4d63

Log:
[oni.log](https://github.com/onivim/oni2/files/4776873/oni.log)

**Comment by tmshv** [comment]
The same on macOS

<img width="1498" alt="Screenshot 2020-06-14 20 07 18" src="https://user-images.githubusercontent.com/290948/84599437-bab6b280-ae7a-11ea-84dd-0cc502007c19.png">

**Comment by zbaylin** [comment]
Hey @tmshv and @Miziak, sorry that you're having this issue. I think I know what the problem is but would you guys mind posting your configs, specifically the `editor.fontFamily` flags?

**Comment by Miziak** [comment]
@zbaylin 
```json

{
  "editor.detectIndentation": true,
  "editor.fontFamily": "FiraCode-Regular.ttf",
  "editor.fontSize": 14,
  "editor.largeFileOptimizations": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.indentSize": 4,
  "editor.insertSpaces": false,
  "editor.lineNumbers": "on",
  "editor.matchBrackets": true,
  "editor.minimap.enabled": true,
  "editor.minimap.maxColumn": 120,
  "editor.minimap.showSlider": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "all",
  "editor.rulers": [],
  "editor.tabSize": 4,
  "editor.zenMode.hideTabs": true,
  "editor.zenMode.singleFile": true,
  "files.exclude": ["_esy", "node_modules", ".git"],
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.iconTheme": "vs-seti",
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true,
  "workbench.tree.indent": 2,
  "vim.useSystemClipboard": ["yank"]
}
```

**Comment by zbaylin** [comment]
@Miziak if you delete the fontFamily line does the problem still occur?

**Comment by Miziak** [comment]
@zbaylin  it rendering ok now but defaults to andnother font I belive

**Comment by zbaylin** [comment]
@Miziak and @tmshv, this should be fixed now in the latest build. Feel free to reopen this if you see the same thing today/tomorrow. One change that was made was that we moved the default to JetBrains Mono, so if you want to use Fira now you'll have to download and install it yourself. Sorry for the inconvenience!
