### ISSUE TITLE
No Reason/OCaml autocompletes or hovers

### ISSUE THREAD

**Issue by jplew** [onivim/oni2#1946]
Hello, 
it seems my Reason language support is not working. I am getting useful autocomplete suggestions and mouse hovers when editing `js` and `ts` files, but have no such support for `ml` or `re` files. For example, when I type `Console.l`, nothing happens. 

The `reason-vscode` plugin appears to be loading fine:
![image](https://user-images.githubusercontent.com/462836/84733496-01f88c80-afbc-11ea-928c-7f21b1b6dfac.png)

In contrast,  autocompletion works fine in VS Code (with the reason-vscode plugin installed), when I open the same Reason project there.

I tried using my own `reason-language-server` and linking it manually in the `configuration.json` (following these instructions: https://github.com/jaredly/reason-language-server#onivim), but no dice: 

`  "language.reason.languageServer.command": "/usr/local/bin/reason-language-server",`

I'm using the the latest build (#86aa3de7) on Mac OS 10.15.5.

**Comment by bryphe** [comment]
Hi @jplew ,

Thanks for logging the issue!

What kind of project is this - is it a bucklescript project (ie, using `bsb`) or a reason native project (ie, using `esy`)? Is it an open source project that I can try and reproduce on?

One common issue is not having the sources built - but the fact that it is working in VSCode but not in Onivim rules this out.

**Comment by jplew** [comment]
I experience this problem in both types of projects.

It fails for `git clone https://github.com/esy-ocaml/hello-reason.git` and `bsb -init my-new-project -theme basic-reason`.

**Comment by bryphe** [comment]
Thanks for the update @jplew !

> Now that I think about it, the problem is probably not in Onivim. I suspect the problem lies in the reason-vscode extension, related to this issue: jaredly/reason-language-server#248

Interesting... I've had good luck with [`ocaml-lsp`](https://github.com/ocaml/ocaml-lsp) in both types of projects. It's a bit pain to set up for bucklescript (but [doable with these steps](https://github.com/ocamllabs/vscode-ocaml-platform#bucklescript))

> If you agree I'll close this and file the bug there.

Sure! I started drafting up some documentation on setting up ReasonML/OCaml/BuckleScript integration here: 
https://github.com/onivim/oni2/blob/master/docs/docs/languages/reason-ocaml.md 

Will close this, but let me know if you have any feedback on the docs 👍
