### ISSUE TITLE
Scrolling Up: Dropped frames + flicker + rendering artifacts

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#197]
@jordwalke noticed that there is some weirdness when scrolling up:
![flicker-scroll-up-1](https://user-images.githubusercontent.com/13532591/55202592-444e6780-5185-11e9-8116-96be295c9caf.gif)

This isn't just with fast scrolling - it reproduces deterministically if you just scroll up at the boundary:
![flicker-scroll-up-2](https://user-images.githubusercontent.com/13532591/55202604-4dd7cf80-5185-11e9-873b-c7b06438d3df.gif)

If you scroll down when the line number doesn't update - there are some rendering artifacts and the cursor position is off by a bit.

**Comment by Samonitari** [comment]
This seems resolved (master at: f5241034796) for me

**Comment by somebody1234** [comment]
@bryphe yeah seems fixed, could you verify

**Comment by jordwalke** [comment]
It seems pretty good to me!

**Comment by bryphe** [comment]
Sure, I'll close this out! I believe this was addressed. We do have some more perf issues to fix relate to scrolling - namely #139 and #174 . Interested to see how things perform / what bottlenecks are present once we switch to [Skia](https://github.com/revery-ui/revery/projects/1)

**Comment by bryphe** [comment]
Will close this out, but we can continue to track specific perf issues in separate bugs 👍
