### ISSUE TITLE
Hover: Hover shows on all visible editors

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1973]
If you open a `hover` via `gh` - it will show on all visible editors, ie:

![image](https://user-images.githubusercontent.com/13532591/85211469-5f634500-b2fe-11ea-8e6a-cd56724e9561.png)

__REPRO__:
- Open Onivim2 in the `oni2` directory
- Open a reason file
- Run `:vsp README.md`
- Show a hover in the reason file via `gh`

Expected: The hover should only be shown in the active editor window
Actual: The hover is shown in all windows

**Comment by zbaylin** [comment]
Oh interesting, I'll fix this now. Sorry about that!

**Comment by bryphe** [comment]
Fixed now with #1978 - thanks @zbaylin !
