### ISSUE TITLE
Hover: Syntax highlighting not correct for Reason with ocaml-lsp

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1974]
Might be related to issues discussed in #1947 - but created a separate issue because this might be specific to `ocamllsp`.

The syntax highlighting we're getting with `ocamllsp` isn't quite correct - ie:
![image](https://user-images.githubusercontent.com/13532591/85211518-fe883c80-b2fe-11ea-9f6f-3d279329b6ca.png)

![image](https://user-images.githubusercontent.com/13532591/85211541-211a5580-b2ff-11ea-8c0d-451449c34d26.png)

(Note how the `module` keyword is highlighting differently in the editor vs in the hover)

It seems like `ocamllsp` is _always_ sending us a language identifier of `ocaml` for the hover.

Some ideas:
- Maybe we should just ignore the language identifier in the markdown, and always use the editor surface?
- Alternatively,  if this is a bug in `ocamllsp` - we could log a bug there, and in the meantime, special case this (if a buffer is reason, and we get a hover that says ocaml, assumes it is reason..)

**Comment by zbaylin** [comment]
@bryphe is it possible for you to run Oni with `--trace --log-filter Revery.Components.Markdown`? That will output an s-expression of the parsed markdown. Should be helpful to see what is getting sent from the extension host and what it's getting parsed as.

**Comment by bryphe** [comment]
Here's the log for it:
```
[TRACE]    +0ms Revery.Components.Markdown : Code block has label : ocaml
[DEBUG]   +23ms Revery.Components.Markdown : Parsed Markdown as: ((fenced-code
  "[> BackgroundColor(Revery_Core__Color.t)\n | Color(Revery_Core__Color.t)\n | FlexGrow(int) ]"))
```

And a hover pre-parse:
![image](https://user-images.githubusercontent.com/13532591/85296872-df042780-b456-11ea-948c-07f475f30889.png)

**Comment by zbaylin** [comment]
Thanks! It looks like you're right about it always sending OCaml then, which would explain why the `module` color is different from Reason to OCaml.

> Maybe we should just ignore the language identifier in the markdown, and always use the editor surface?

This would work I'm sure, but I think there are times where the Hover info sent back is of a different language than what the buffer is. I will look after I post this, but I'm pretty sure I've seen JS hovers that have sample HTML DOMs to show what the effect of certain operations are.

I think the second option makes more sense, although we can use the first as a temporary fix until the second has been resolved. Let me know what you think!

**Comment by bryphe** [comment]
>  I will look after I post this, but I'm pretty sure I've seen JS hovers that have sample HTML DOMs to show what the effect of certain operations are.

Good point! Ignoring the language identifier would be too hacky and break that case 👍 

> I think the second option makes more sense, although we can use the first as a temporary fix until the second has been resolved. Let me know what you think!

The second option sounds good given that case - but I think our special case could be that, if we are in a `reason` file, and we get an `ocaml` markdown... assume that it is actually a `reason` markdown.
