### ISSUE TITLE
Signature Help: Remains open after backspacing

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1980]
![2020-06-22 07 35 25](https://user-images.githubusercontent.com/13532591/85300168-11b01f00-b45b-11ea-9ab0-188cafd2dacc.gif)

It looks like there is a bug on the closing condition of signature help - if I backspace past where the signature help was first opened, it remains opened.

We'll need to figure out the right condition to close in this case - an option would be to save the cursor position when we first trigger it, and if the cursor ends up before that position, we'd cancel the gesture.

Another option would be to save the cursor position of the last successful request, and if the cursor ends up prior to that position, we'd request again (and possibly cancel if null/none is returned for the signature help provider).

**Comment by zbaylin** [comment]
Either of those would work, but I think it might be better if we could somehow find a way to get the deleted character on backspace/delete. This way we could detect if it's a trigger character and request new info from the extension host. Not sure if that's possible, though.

**Comment by Apostolique** [comment]
I have this same bug (or similar) in vscode and it's soooo annoying. In vscode the only way I found to close the menu is to click with the mouse.
