### ISSUE TITLE
The interface will be distorted when resizing the window 

### ISSUE THREAD

**Issue by AlawnCN** [onivim/oni2#1986]
The interface will be distorted when resizing the window.
look this screenshot
<img width="1652" alt="20200623102809" src="https://user-images.githubusercontent.com/49110973/85354463-341a6900-b53d-11ea-8629-4967429fa881.png">

**Comment by AlawnCN** [comment]
I'm  macOS

**Comment by mabuchner** [comment]
Duplicate of #1318.

**Comment by bryphe** [comment]
Thanks for logging the issue @AlawnCN and for catching the dup @mabuchner - I'll resolve this as a dup of #1318
