### ISSUE TITLE
Quick open not working on Windows

### ISSUE THREAD

**Issue by Sloff** [onivim/oni2#1993]
The quick open window does not display any results on Windows.

**Comment by bryphe** [comment]
Hi @Sloff ,

Thanks for reporting! Just curious - are you building from source, or did you download and install the build from the portal? I believe there may be an issue in the build-from-source case with the environment growing too large.

**Comment by Sloff** [comment]
Hi @bryphe,

Downloaded from the portal.

**Comment by Sloff** [comment]
Just tried the latest release from the portal and it looks like it's working now 🎉

**Comment by bryphe** [comment]
Excellent! Thanks @Sloff for the update
