### ISSUE TITLE
Signature help in offset location and unscrollable. 

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#1999]
(Following on from discord discussion).

When comparing signature help to type info on hover, currently signature help/ parameter info is offset away from the cursor location.

Additionally if the parameter info is long, then the popup isn't scrollable.  (Compared with hover info which is scrollable).  

Pics below to clarify.
Paramater info / Signature help:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/1826271/85619434-345c5680-b65a-11ea-88fc-f97ac694415c.png">

Type info on hover:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/1826271/85619534-59e96000-b65a-11ea-81e8-582cb2537c57.png">

**Comment by zbaylin** [comment]
Hi @yunti, thanks again for making this issue! What extension are you getting the parameter hints from? I can't seem to replicate this with the JS/TS extension, so maybe I can get closer if I use the extension you're working with.

Thanks!

**Comment by yunti** [comment]
@zbaylin it's a reason (bucklescript) project, so just the default reason plugin in oni. Sorry the screenshot wasn't wide enough to make that more obvious.
