### ISSUE TITLE
Oni disables compositor effects on KDE

### ISSUE THREAD

**Issue by pikachunakapika** [onivim/oni2#2003]
Hi all,

everytime I run Oni my kde plasma disables all compositor effects globally (like transparency or blurring).
Maybe it is just a skia setting so it does not take control over all GPU?

Thx!

**Comment by bryphe** [comment]
Interesting, thank you for reporting @pikachunakapika !

I saw an issue here too - it seems like SDL2 disables the compositing by default: https://github.com/buggins/dlangide/issues/215

We'll have to see if there is a way to turn that off on our end.

**Comment by pikachunakapika** [comment]
Oh thx. You are very quick :D. 

I don't think it's very urgent but I noticed it while testing.

**Comment by bryphe** [comment]
It looks like this may be the culprit:
https://github.com/spurious/SDL-mirror/blob/c8b01e282dfd49ea8bbf1faec7fd65d869ea547f/src/video/x11/SDL_x11window.c#L601

Perhaps we can turn this off via the `SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR` hint. (Software rendering could also address this: https://github.com/onivim/oni2/issues/1588)

**Comment by MoritzS** [comment]
I use KDE as well and for me it freezes the taskbar when I start Oni. This may be related to this issue?

Fortunately closing Oni just unfreezes it again but this is still very annoying.

**Comment by bryphe** [comment]
FYI - we set this flag in Revery now: https://github.com/revery-ui/revery/pull/921, and we've picked up that change in https://github.com/onivim/oni2/pull/2113 - it may be fixed in latest builds

**Comment by MoritzS** [comment]
The latest build indeed fixes my problem. Thank you!

**Comment by bryphe** [comment]
That's great! Thanks for confirming @MoritzS . I'll close this out.
