### ISSUE TITLE
crashes randomly on linux ubuntu 20.04

### ISSUE THREAD

**Issue by MichaelBelousov** [onivim/oni2#2007]
I'm unaware of where any logs or dumps would be, if I could be pointed in the right direction I'll upload them, but I was getting in frequent random crashes, the last I remember occurred while I was moving the window around. I'm sorry for such a vague issue, once I can get logs it should be better.

**Comment by mabuchner** [comment]
Take a look at

https://onivim.github.io/docs/using-onivim/command-line#logging

> The '-f' argument can be used to keep Onivim 2 attached to the terminal, and provide logging output.

**Comment by MichaelBelousov** [comment]
[oni2.log](https://github.com/onivim/oni2/files/4831579/oni2.log)
Here is the log, it crashed as I dragged the window against the top of the display to resize it to fit that display in my 2 monitor setup.

**Comment by MichaelBelousov** [comment]
I realize debugging wasn't enabled, I'll try to get it to crash again.

**Comment by bryphe** [comment]
Thanks for reporting and grabbing logs, @MichaelBelousov !

Does there happen to be an `onivim2-crash.log` in the directory you ran Onivim from? That might have some helpful output, as well, if present

**Comment by bryphe** [comment]
Ah, it looks like our nightly build missed this fix: https://github.com/onivim/oni2/commit/544a21f398d0028b34ec44dc08ae240751c9f850 ... that could be a possible culprit.

I'm kicking off the nightly run to get that in and rule that out as a culprit.

**Comment by MichaelBelousov** [comment]
I do not see an onivim2-crash.log in the directory I ran it, and I haven't been able unfortunately to crash it again. All I know is I opened a file, opened a terminal, ran some commands, changed the font and font size, and then it crashed when I tried to dock the window to my display as full screen.

**Comment by bryphe** [comment]
Interesting, thanks for the additional details and the help debugging! 

I would expect an `onivim2-crash.log` to be dropped if it was https://github.com/onivim/oni2/commit/544a21f398d0028b34ec44dc08ae240751c9f850 - if there is no `onivim2-crash.log` that suggests a segfault or another native crash. I'll see if we can get some better tracing in that case.

**Comment by MichaelBelousov** [comment]
want me to run the log with trace? I'm afraid of dumping megabytes of log since I can't seem to reproduce it and I'd expect to be running it for a while before finding it again.

**Comment by bryphe** [comment]
Hmm, if the crash is on the native side - which it sounds like, given no `onivim2-crash.log` is present - the logs might not be as helpful (they'd give some context), but a core dump would be helpful for debugging that.

It'd be interesting to see if there are any dumps relating to Onivim 2 - you can find the location with this command: `cat /proc/sys/kernel/core_pattern`. Would be curious if any dumps are showing up there.

 And just to check - are you running via the AppImage, the tar.gz, or building from source?

**Comment by MichaelBelousov** [comment]
built from source but running `_release/Onivim2-x86_64.AppImage`, I didn't see anything in the "building from source docs" about where the executable is besides in `_release`, and I guess I haven't thoroughly explored `_release/linux/`.

```
mike@mike-HP-ZBook-15-G5 ~/personal/oni2 (master) 10:36:53.934
$ cat /proc/sys/kernel/core_pattern
|/usr/share/apport/apport %p %s %c %d %P %E
```

**Comment by bryphe** [comment]
> built from source but running _release/Onivim2-x86_64.AppImage, I didn't see anything in the "building from source docs"

Cool, thanks for the details!  You can run the executable directly as well via `./_release/linux/bin/Oni2` - might be interesting to see if it reproduces there.

Which commit are you on (`git log --oneline -n1`)? Wondering if you already have https://github.com/onivim/oni2/commit/544a21f398d0028b34ec44dc08ae240751c9f850 (which would certainly rule that out as being the culprit)

**Comment by MichaelBelousov** [comment]
I'm on `0e476a6f`, and I tried running that executable first but it doesn't seem to do anything (no window launched). I can get a log from that too.

I also just got a log running the AppImage doing something that I just now forgot :frowning:
[oni2.log](https://github.com/onivim/oni2/files/4832109/oni2.log)

**Comment by MichaelBelousov** [comment]
It just seems to be failing to load libjpeg, I'll double check that I have it installed.
```
./_release/linux/bin/Oni2_editor: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
```

**Comment by MichaelBelousov** [comment]
I do not have libjpeg-dev installed, but I do have libjpeg-turbo8, and libjpeg8, should I get libjpeg-dev and rebuild?

**Comment by MichaelBelousov** [comment]
I found a crash log, looks like it was in the editor's loaded directory, not the cwd of the shell where I ran the executable. Probably from the latest crash, not the current one, I didn't see it until now.
[onivim2-crash.log](https://github.com/onivim/oni2/files/4832194/onivim2-crash.log)

**Comment by MichaelBelousov** [comment]
and just got another crash on a pipe.onStreamRead uncaught exception of connection reset:
[oni2-pipe-reset-debug.log](https://github.com/onivim/oni2/files/4832223/oni2-pipe-reset-debug.log)
[onivim2-crash.log](https://github.com/onivim/oni2/files/4832232/onivim2-crash.log)

**Comment by bryphe** [comment]
Wow, thanks! These are very helpful @MichaelBelousov

**Comment by bryphe** [comment]
I split these each out to separate issues - based on the callstack, looks like they'll require different fixes:
- https://github.com/onivim/oni2/issues/2011
- https://github.com/onivim/oni2/issues/2012

**Comment by MichaelBelousov** [comment]
if you @ mention me in any of those issues or here, I'll provide as much info as I can :smile:

**Comment by MichaelBelousov** [comment]
@bryphe would you know how I can get the native executable running? (I'm still getting that libjpeg not found error even after installing libjpeg-dev on ubuntu and re-bootstrapping (although maybe I need to invalidate or clear some more stuff?))

**Comment by bryphe** [comment]
@MichaelBelousov - I think it's linking against a locally-built version, which must not be compatible with the system installed one (we are probably bundling it up into the AppIamge).

You could try this:
`esy build-env | grep libjpeg_turbo`

And then, there should be an entry with `LD_LIBRARY_PATH`, you could try running with that, like:
`/Users/bryphe/.esy/3__________________________________________________________________/i/esy_libjpeg_turbo-dc3b4679/lib:$LD_LIBRARY_PATH ./Oni2`

That would help the linker get to our locally built library

**Comment by MichaelBelousov** [comment]
That worked, thanks!

**Comment by MichaelBelousov** [comment]
closing since we recategorized into specific issues
