### ISSUE TITLE
ctrl-tab resurrects dead terminals

### ISSUE THREAD

**Issue by MichaelBelousov** [onivim/oni2#2009]
- create a terminal (i.e. `:term ++curwin`)
- type the exit command, it will disappear from the tab tray/list
- use ctrl-tab (hold it or continuously press it over and over again), the dead terminal can be accessed and will be readded to the tab tray even though it is already exited

**Comment by woeps** [comment]
I can confirm this behavior still exists in the latest nightly build for linux (build from 8/25/2020, 6:39:07 AM, commit: https://github.com/onivim/oni2/commit/d2a59799cc38410e10992851c5c61a4fa4905312).
I'm not sure if keeping already closed windows in the list of `<C+TAB>` is the desired behavior. For me personally, this can get pretty annoying, when I try to use Oni2 as my daily editor.
