### ISSUE TITLE
Crash: Feature/Layout/Model.re - assert failure

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#2011]
From

Log file: https://github.com/onivim/oni2/files/4832194/onivim2-crash.log

```
"Assert_failure src/Feature/Layout/Model.re:45:4":
Raised at file "src/Feature/Layout/Model.re", line 45, characters 4-72
Called from file "list.ml", line 92, characters 20-23
Called from file "src/Feature/Layout/Model.re", line 170, characters 4-117
Called from file "src/Feature/Layout/Feature_Layout.re", line 87, characters 6-48
Called from file "src/Store/Features.re", line 270, characters 26-59
Called from file "src/Updater.re", line 10, characters 33-56
Called from file "list.ml", line 121, characters 24-34
Called from file "src/Updater.re", line 7, characters 4-253
Called from file "src/Store.re", line 111, characters 29-61
Called from file "src/Feature/Sneak/Feature_Sneak.re", line 183, characters 8-18
Called from file "list.ml", line 110, characters 12-15
Called from file "src/Store.re", line 172, characters 9-32
Called from file "list.ml", line 110, characters 12-15
Called from file "list.ml", line 110, characters 12-15
Called from file "src/Store.re", line 172, characters 9-32
Called from file "list.ml", line 110, characters 12-15
Called from file "src/Core/Tick.re", line 112, characters 9-15
Called from file "src/Core/Tick.re", line 90, characters 15-32
Called from file "list.ml", line 92, characters 20-23
Called from file "list.ml", line 92, characters 32-39
Called from file "src/Core/Tick.re", line 99, characters 22-52
Called from file "src/Core/App.re", line 261, characters 4-23
Called from file "src/reason-sdl2/sdl2.re", line 803, characters 10-20
Called from file "src/bin_editor/Oni2_editor.re", line 372, characters 11-26
```

**Comment by bryphe** [comment]
Looks like the root action that is triggering this is:
```
  | GroupTabClicked(id) => (
      updateActiveGroup(Group.select(id), model),
      Nothing,
    )
```

**Comment by glennsl** [comment]
Looks like the editor whose tab was clicked doesn't exist, which is curious. A repro would be very useful here.

**Comment by glennsl** [comment]
It might be that the editor is in a different editor group, since `GroupTabClicked` assumes it is the active group. Which normally it should be, since `GroupSelected` should trigger first, but it would still be a good idea to pass the group id in the message just to remove that assumption.

Would still be nice to have a repro to test if that fixes the issue.

**Comment by bryphe** [comment]
Thanks for looking at this, @glennsl !

Is there a case where, possibly, we could be dispatching `GroupTabClicked(id)` for an editor in another tab (ie, the non-active tab?). The only case I could think of was if we were dispatching `GroupTabClicked(editor)` for an editor that was valid, but not in the active group, for whatever reason.. I was trying to reproduce by clicking a tab in an inactive editor group - but couldn't reproduce. 

@MichaelBelousov - do you happen to recall what you were doing to reproduce this particular error? Might give us a clue 😄

**Comment by bryphe** [comment]
Oops, you beat me to it, looks like we had the same thought re: editor in a different editor group (somehow).

> Which normally it should be, since GroupSelected should trigger first, but it would still be a good idea to pass the group id in the message just to remove that assumption.

This sounds like a robust fix 👍

**Comment by glennsl** [comment]
> Is there a case where, possibly, we could be dispatching GroupTabClicked(id) for an editor in another tab (ie, the non-active tab?).

Good thinking! :D I can't see any case where it does, but think this is a bad and unnecessary assumption anyway.
