### ISSUE TITLE
<C-w> window splitting not working for me

### ISSUE THREAD

**Issue by davidwilde** [onivim/oni2#2019]
Hi, I purchased the pre-order $35 version and I'm on 0.4.0 OSX, for some reason I am not able to use Ctrl-w to instigate any window splitting commands. Other Ctrl commands such as Ctrl-v seem to work fine for me

**Comment by bryphe** [comment]
Hi @davidwilde - thanks for logging the issue (and for supporting the project!)

Indeed, this looks like a bug - both the of those shortcuts to open a vertical and horizontal split are not hooked up. I think these is something in our transition of the window-management logic. Should be a straightforward fix.
