### ISSUE TITLE
unable to load font

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#2039]
I am getting a new error using the latest nightly build available for download (no problem before). See screenshot.

![Screenshot from 2020-06-30 11-33-51](https://user-images.githubusercontent.com/8382834/86110272-a81cba00-bac5-11ea-8b09-9ea78bfc22c6.png)

**Comment by jerabaul29** [comment]
PS: this is on Ubuntu 18.04

**Comment by kakamorsch** [comment]
It happened to me too, but on windows, the solution was to put the absolute path for the font on the settings file.

**Comment by jerabaul29** [comment]
Ok, thanks!

It is just strange that this error suddently appears following an update, guess there is something that got broken?

**Comment by CrossR** [comment]
The default font changed a few weeks ago and Fira Code was removed (well, stopped being bundled).
It should gracefully fall back to the new default, but perhaps the error message still occurs.

If you still want Fira Code, you'll have to install it manually. If you don't care, you can delete that line from your config and it'll stop the error message and just use the default font.

**Comment by jerabaul29** [comment]
Thanks. I don't care, so will just remove it. Is it something you should also remove somewhere in the code / default config to avoid the error in the future? :)

**Comment by CrossR** [comment]
I'll close this out now at least.

The new config will have the new font so new users shouldn't hit this. If its an issue for current users, and the default loading isn't behaving as expected, we should look into that.
