### ISSUE TITLE
Launch and open folder from command line

### ISSUE THREAD

**Issue by fuzzthink** [onivim/oni2#2069]
Is there a way to start the app and open folder from command line?

Vscode is via `code .`
Sublime is via `sublime .`
(where `.` can be the path to open)

Version: latest via downloaded dmg on osx 10.15.4

**Comment by AceroM** [comment]
I believe if you just type "oni2" in the terminal, it should pop open the editor in the same editor?

**Comment by fuzzthink** [comment]
"command not found: oni2"

What's the path of it? I can check if it's there..

**Comment by CrossR** [comment]
The `oni2` executable isn't added to your path by default, it has to be added via the command palette: https://onivim.github.io/docs/using-onivim/command-line#macos

We could look at adding it all the time, but I was under the impression that wasn't simple/possible with the current way we distribute Oni2 on Mac.

**Comment by fuzzthink** [comment]
Ok, didn't see that. Works now. May I suggest moving/adding that as a section under "Getting Started"?

That's the way many people open their project folders with vscode or sublime.
