### ISSUE TITLE
Should not open the sidebar by default if no specific folder is open

### ISSUE THREAD

**Issue by danielo515** [onivim/oni2#2084]
Hello,
The other day I installed onivim2 on my backup computer and when I opened it the sidebar where all the files are listed was open on my home directory, which is hughe. This was an instant froze for the sidebar. Luckily I managed to open the command bar and cd to a smaller directory.
I don't want to be forced to open onivim2 from the command line if I don't want an instant freeze, I think doing what VSCode does, asking you to open a folder, is much more  usable, after all I never edit my entire home folder.

Regards

**Comment by bryphe** [comment]
Hi @danielo515 ! Thanks for the feedback. This is similar to https://github.com/onivim/oni2/issues/1983  - we definitely need to handle this case better.

**Comment by danielo515** [comment]
Yeah, the issue is similar, but I think this one is more concrete and more actionable because it highlights a very specific problem and contains a proposed fix.

Regards
