### ISSUE TITLE
Running Oni2 automatically switches to dedicated graphics

### ISSUE THREAD

**Issue by taylorthurlow** [onivim/oni2#2090]
I have a Macbook Pro 2019 16" with a dedicated AMD GPU. Running oni2 causes the GPU to switch to dedicated graphics automatically. This is pretty bad for battery life and heat output, especially when the integrated cuts it just fine.

Any way to prevent this from happening?

**Comment by bryphe** [comment]
Good catch @taylorthurlow  - SDL2 always defaults to the dedicated GPU.

It looks like there's a way to force it to default to the integrated GPU (which would make more sense for an editor): https://discourse.libsdl.org/t/question-is-it-possible-to-set-sdl2-to-use-integrated-graphics-only/23929

**Comment by bryphe** [comment]
Looks like we need to set this flag in the `plist`: https://developer.apple.com/documentation/bundleresources/information_property_list/nssupportsautomaticgraphicsswitching

Working on getting a dual-GPU mac device to verify on. Possibly related to #2225
