### ISSUE TITLE
Title bar rendering problem on windows

### ISSUE THREAD

**Issue by metehan** [onivim/oni2#2091]
![image](https://user-images.githubusercontent.com/747125/87243401-0f2b5e80-c436-11ea-85c2-6d77908c1a04.png)

There is a blackbar on top of rendered area and when you need to click stuff you always need to click little bit above.

**Comment by bryphe** [comment]
Thanks for logging the issue, @metehan ! Which version of Windows are you on?

@zbaylin - this looks like it might be related to our custom titlebar

**Comment by metehan** [comment]
It's Windows 10  Home Edition

**Comment by metehan** [comment]
The problem disappeared on latest built.

**Comment by bryphe** [comment]
That's great news! Thanks for the update @metehan 

I suspect it may have been improved by the switch to ANGLE (using Direct3D instead of OpenGL) - https://github.com/onivim/oni2/pull/2283
