### ISSUE TITLE
Feature: Symbols Explorer (was: TagBar plugin from https://github.com/majutsushi/tagbar)

### ISSUE THREAD

**Issue by gordonrust** [onivim/oni2#2123]
Hi

This  Ctags plugins is a lifesaver when wading through a bewildering mass of code. I know you guys are going to be mimicking vscode and probably the symbols explorer for the code is going to reside  on the left pane, where the fileexplorer is. Would it be possible to treat that view as navigable. Basically I am hoping the symbols panel to also have the functionality that  Issue #528  grants to the fileexplorer.

Note: The vscode breadcrumbs feature also assists in the code exploration and I find it better suited. Except that I wish it would be a split window in its own right.

**Comment by bryphe** [comment]
Thanks for logging the issue, @gordonrust !

Yes, we'd like to have the symbols explorer in the same place - and have it navigable in a Vim style (like #528). Will keep it in mind as we work on getting the full keyboard-navigation in place there 👍

**Comment by bryphe** [comment]
We actually have this now in the nightly builds- indeed, the symbol explorer is in the same pane. You can to it by using `Control+W`, `Control+H` to the sidebar, and then `Control+W`, `Control+J` down to the symbol pane. Alternatively - you can use `gO` (goto-outline as the mnemonic) :+1: 

![symbol-explorer](https://user-images.githubusercontent.com/13532591/99137439-b9331700-25df-11eb-9d7a-aa230fa734f7.gif)
