### ISSUE TITLE
Thread killed on uncaught exception Sys_Error

### ISSUE THREAD

**Issue by Akin909** [onivim/oni2#213]
![image](https://user-images.githubusercontent.com/22454918/55456896-24cd9980-55e0-11e9-9a83-2f5fc6650a37.png)

Haven't had a chance to investigate properly, but opening and closing the menus repeatedly eventually leads to a crash with the error above.

**Comment by Akin909** [comment]
This actually seems to come from the quick open attempts to open files work but print a Thread killed exception, and eventually the app crashes.
Might relate to #211

**Comment by bryphe** [comment]
Thanks for logging the issue @Akin909 ! Ya, indeed, it looks like what happens is the `Unix.kill` call will throw that exception if the process is _already closed_. Just added a fix in rench here: https://github.com/bryphe/rench/pull/25
