### ISSUE TITLE
Feature: :tabp, :tabn, ... based navigation with default config

### ISSUE THREAD

**Issue by jisensee** [onivim/oni2#2153]
Currently `:tabp`, `:tabn` and related commands do nothing in the default configuration (`singleTabMode=false`) even though they are suggested when typing.
It would be nice to have those work there as well as alternative to `CTRL+PAGE UP` and `CTRL+TAB` based navigation.

**Comment by glennsl** [comment]
`:tabp` and `:tabn` work exactly the same regardless of `singleTabMode`. Editor tabs and (vim-style) layout tabs are different things, and you can use both simultaneously. Try opening a second layout tab with `:tabe`, then you can use `"tab*` to work with them.

**Comment by jisensee** [comment]
@glennsl Thanks for the response, I didnt know layout tabs were a thing here!
I tried out `:bnext:` and `:bprevious` but both just open a new untitled file instead of navigating between my open buffers/tabs. Thats not right, isnt it?

**Comment by glennsl** [comment]
No, there's even an existing issue for it: https://github.com/onivim/oni2/issues/1098. Make sure to give it an upvote for increased priority.

**Comment by jisensee** [comment]
Alright, will do! Closing this issue here then.
