### ISSUE TITLE
Code suggestion persist open even if we change line

### ISSUE THREAD

**Issue by Miziak** [onivim/oni2#2167]
![test](https://user-images.githubusercontent.com/4346598/88260535-dc4e5980-ccc4-11ea-8cf5-ae2122fb5be1.gif)

Type phrase triggering completion then(don't leave insert) move up and down using arrows.

**Comment by bryphe** [comment]
Thanks for reporting this, @Miziak! Gif was very helpful!

Fixed in #2202 - we dismiss the completion UI automatically now if the line changes. I'll close this but please lmk if you see any further issues 👍
