### ISSUE TITLE
Vim general usage

### ISSUE THREAD

**Issue by jirmonder** [onivim/oni2#2169]
Hi guys, love all the hard work on making onivim2 a reality

At the moment i'm using onivim2 v0.4.0

Can't seem to select text inside quotes with vim commands like v+i+' or v+a+' also no support for this same movement with tags.

**Comment by mabuchner** [comment]
Duplicate of #1880.

**Comment by bryphe** [comment]
Thanks for logging the issue @jirmonder (and thanks @mabuchner for finding the duplicate issue!)

Will use #1880 to track - I'll be taking a pass over these in the next milestone (focusing on Vim improvements)
