### ISSUE TITLE
Sneak: Shows hints even when file explorer is turned off

### ISSUE THREAD

**Issue by ultrox** [onivim/oni2#2179]
I'm running macOS Catalina Version 10.15.5 with the latest nightly build of oni.

How to recreate: Open Oni, close file explorer click `Gtrl + G`

![image](https://user-images.githubusercontent.com/3077558/88457168-8fb17c80-ce84-11ea-9851-6a7bb66bd03f.png)

**Comment by mjdi** [comment]
To add to this, when you are navigating the file explorer by arrow keys, and then minimize it back to the side bar (Sneak or mouse click), the keyboard focus still remains on the now hidden file explorer (i.e. I can still use arrows to highlight different items in the file hierarchy). I assume this isn't default VSCode behaviour and that returning focus to the last vim buffer is more ideal?
