### ISSUE TITLE
QuickOpen / Menu: Add handling for <c-h> and <c-w>

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#218]
__Repro:__
- Open QuickOpen (`<c-p>`)
- Type some characters (`abc`)
- Press `<c-w>`

__Expected:__ Text should be cleared
__Actual:__ Text is not cleared

(Same issue with `<c-h>`, except I'd expect it to behave like `<backspace>`).

**Comment by romgrk** [comment]
I wonder if it wouldn't be possible to implement QuickOpen in terms of viml's `input()` function. This would allow neovim to handle keybindings as it does for all commandline types, which may vary for everyone (e.g. I map readline-like keybindings for commandline mode: `<a-f>`, `<a-b>`, ...).
