### ISSUE TITLE
QuickOpen: Add scrollbar to menu

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#219]
In Oni1, we had a scrollbar for our Menu / quickopen:
![oni1-scroll-bar](https://user-images.githubusercontent.com/13532591/55523213-ef0ace00-563c-11e9-83bf-0a48f7f0776e.gif)

Our current QuickOpen experience doesn't have this in Oni2 - would be nice to bring this back!

**Comment by Akin909** [comment]
for context to anyone looking into this the menu is a `<Flatlist/>` component which means it only renders the items in view. `Revery` does have a `ScrollView` which does come with a scrollbar but that would not work in this case as if list the menu renders is not virtualised (i.e. renders all visible and nonvisible components) this list becomes v. v. slow.

A solution here would be adding the option to render a scrollbar in the menu ?adding it to the virtualised list as a toggleable option?

**Comment by somebody1234** [comment]
Weird... supposedly `FlatList` should have `showsVerticalScrollIndicator` prop as `true` by default? Do we just have to render the scrollbar (well, that and handle dragging the scrollbar) in the `render` function then 🤔

**Comment by CrossR** [comment]
We actually have our own FlagList: https://github.com/onivim/oni2/blob/master/src/editor/UI/FlatList.re

So we'd need to add a similar property to that as well as a bar for it.

**Comment by somebody1234** [comment]
:/ why do we have our own anyway

**Comment by bryphe** [comment]
It's been kind of an organic process! I'm opening to moving the `<FlatList />` over to Revery though 👍

**Comment by glennsl** [comment]
FYI: I'm working on this as part of the menu renovation project.
