### ISSUE TITLE
Key-repeat doesn't work under Wayland/Sway

### ISSUE THREAD

**Issue by synaptiko** [onivim/oni2#2191]
It seems that OniVim2 under Wayland (Sway v1.5 in my case) doesn't support key-repeat, meaning that if you press and hold a key, it's typed only once.

**Comment by thotypous** [comment]
Very annoying bug. It should have the tag `I-daily-editor-blocker`.

**Comment by yiding** [comment]
This is unimplemented in SDL's wayland handling code: https://bugzilla.libsdl.org/show_bug.cgi?id=4445

I attached a patch there that implements it.

**Comment by PedroHLC** [comment]
Since that patch was merged, what is missing here?

**Comment by yiding** [comment]
[esy-sdl2](https://github.com/revery-ui/esy-sdl2) needs to be updated to have the sdl changes. cc @bryphe

**Comment by goetzc** [comment]
There is already a esy-sdl2 PR https://github.com/revery-ui/esy-sdl2/pull/19 to upgrade SDL to 2.0.14
