### ISSUE TITLE
Formatting(in my case via Prettier extension) start duplicate text after approx 4 uses

### ISSUE THREAD

**Issue by pmizio** [onivim/oni2#2196]
Like in topic - gif demonstrating problem:
![test](https://user-images.githubusercontent.com/4346598/88725463-6d418c80-d12c-11ea-84ff-c924e6c67404.gif)

Oni2 lastest build from early access https://github.com/onivim/oni2/commit/3ceb0a167ed9ed5c965eab7b993f71774a4595f1
Prettier extension fresh installed via gui version: 5.1.3

**Comment by necabo** [comment]
Had the same issue using rust-analyzer so this is probably a general issue. I sadly couldn't figure out how to reproduce it consistently. It seemed to work fine for a long time after a restart before breaking again.

**Comment by marcagba** [comment]
I encounter a similar issue. Up until a certain amount of use prettier start to mangle my file: some lines are duplicated and others are removed.
