### ISSUE TITLE
Xcape remapping ignored

### ISSUE THREAD

**Issue by kuator** [onivim/oni2#2200]
I use [xcape](https://github.com/alols/xcape) to make my space bar act as a space when tapped alone, and as a ctrl modifier when pressed with other keys. This keybinding is ignored in oni2 though.

**Comment by bryphe** [comment]
Thanks for logging the issue @kuator ! Just for some more info - what distro of Linux are you running?

Might be related to #557

**Comment by kuator** [comment]
I'm using linux mint 20. The is she is definitely related to #557. Should I close it then?

**Comment by bryphe** [comment]
Thanks @kuator ! Yes, that sounds good - we'll track in #557 👍
