### ISSUE TITLE
Ctrl+R in :terminal

### ISSUE THREAD

**Issue by ftlc** [onivim/oni2#2205]
I wasn't able to find this mentioned before, so I'm opening an issue here. Please link me if there are previous discussions around it.

My current pre-Oni2 setup is nvim in a tmux pane with terminals on the bottom, and I heavily heavily rely on Ctrl-r to run previous commands. I use fzf in my terminal to get fuzzy searching through the command history, and it's really nice for running old tests or ssh commands and the like.  With the Oni2 term I've run into a problem. <C-r> in the terminal doesn't work since it's a vim binding and it waits for me to paste something from a register instead of searching history.

Is there a way to "passthrough" C-r so that vim doesn't handle it and it goes to the terminal when it's focused? Here's my current, unsuccessful attempt

    { "key": "<C-r>", "command": "", "when": "terminalFocus" }

With this mapping <C-r> will no longer check the register, but it also doesn't open the history, just does nothing. 

Is there a way to "substract" the mapping and let the terminal handle it? Or, conversely, to "add" a mapping that will go to the shell fzf command when it's pressed? 

Note, <Ctrl+t> does work fine in the :term, so I'm guessing it's not a problem with terminal or fzf itself.

**Comment by bryphe** [comment]
Hi @ftlc,

Thanks for logging the issue! Indeed - this looks like a regression from https://github.com/onivim/oni2/pull/2101 - we shouldn't be taking over the terminal functionality with it.

> Is there a way to "passthrough" C-r so that vim doesn't handle it and it goes to the terminal when it's focused? Here's my current, unsuccessful attempt

> Is there a way to "substract" the mapping and let the terminal handle it? Or, conversely, to "add" a mapping that will go to the shell fzf command when it's pressed?

Unfortunately we don't have this functionality in place, yet (we need it, for sure!). Thinking about in the context of planning the work for the next milestone - there's a cluster of input-customization-related improvements that are needed (along with supporting vim-style remaps).

In the meantime - I'll remove this default `Control+R` binding when in the terminal. It could always be brought back with this keybinding:
```
  { "key": "<C-R>", "command": "vim.register.insert", when: "terminalFocus" },
```

**Comment by ftlc** [comment]
Thanks for the quick turnaround!
