### ISSUE TITLE
Difficulty compiling and running oni2

### ISSUE THREAD

**Issue by koutselakismanos** [onivim/oni2#222]
So i have tried numerous times installing and running oni2 with no success. This time i got closer
everything run successfully even the esy test 0 fails but when doing esy run, I get this error 
Oni2: /home/manos/.esy/3____________________________________________________________________/b/esy_glfw-3.2.1009-65d18ba9/_build/glfw/src/window.c:1049: glfwSetFramebufferSizeCallback: Assertion `window != NULL' failed

**Comment by alexmironof** [comment]
It could be an issue with your grapichs driver
here is the same issue https://github.com/revery-ui/revery/issues/358
