### ISSUE TITLE
Command window shows list of submodules after write command

### ISSUE THREAD

**Issue by mabuchner** [onivim/oni2#2226]
If I open a file inside a git repository with submodules and then type `:w<CR>` or `:write<CR>`, then the command window closes for a split second and then shows a list of all submodules

![ezgif-4-8936df12c3e2](https://user-images.githubusercontent.com/6006874/89366765-19294000-d70a-11ea-949e-f0a4a259b0cc.gif)

For some reason it works fine with other commands like `:wall`.

**Comment by bryphe** [comment]
Thanks for logging the issue @mabuchner ! That would be... very annoying.

It looks like it might be coming from the extension host. Just curious - is this an open source project I can try to repro on? And what extensions are you using?

**Comment by mabuchner** [comment]
boost is a bit infamous for it's use of submodules:

```sh
git clone git@github.com:boostorg/boost.git
cd boost
git submodule update --recursive --depth=1 --init
oni2 .
```

Here it takes a few seconds before the problem starts to occur. As soon as the status bar shows some git hashes it happens.

![Screenshot 2020-08-07 at 9 51 54 AM](https://user-images.githubusercontent.com/6006874/89600088-c67b8f80-d893-11ea-81a3-b86fefbe228a.png)

Just open any file (e.g. `index.htm`) and type `:w<cr>`.

![Screenshot 2020-08-07 at 9 54 09 AM](https://user-images.githubusercontent.com/6006874/89600172-f460d400-d893-11ea-9e01-5f9f1fad243a.png)

**Comment by mabuchner** [comment]
I currently only have the following plugin for CMake support installed:

https://marketplace.visualstudio.com/items?itemName=twxs.cmake
