### ISSUE TITLE
Error on onivim start: unable to load font: firacode-regular.ttf: Error loading typeface

### ISSUE THREAD

**Issue by ArthurZ** [onivim/oni2#2227]
On Win 10 Pro with all the Fira code variations installed I get on Onivim start an error:
unable to load font: firacode-regular.ttf: Error loading typeface

**Comment by bryphe** [comment]
Thanks for logging the issue, @ArthurZ !

Just curious - what does your `configuration.json` look like? You can open it with `Cmd/Ctrl+Shift+P` -> `Preferences: Open configuration file`

It sounds like there might be an outdated `editor.fontFamily` setting - the defaults changed from FiraCode to JetBrains Mono.

**Comment by ArthurZ** [comment]
Hi Bryan,

You are welcome, thank you.

I had it indeed set to Fira, changed to JetBrains
