### ISSUE TITLE
Show tab index in layout tab title

### ISSUE THREAD

**Issue by mabuchner** [onivim/oni2#2228]
The layout tabs always show a tab index of 1 for all tabs

![Screenshot 2020-08-05 at 11 02 36 AM](https://user-images.githubusercontent.com/6006874/89367307-40ccd800-d70b-11ea-91dd-9b26442364ae.png)

This seems to be only a visual problem as switching to a tab with a certain index via e.g. `3gt` still works as expected.

**Comment by glennsl** [comment]
It's not the tab index but the number of windows/splits in the tab. Vim behaves the same way, except it doesn't show the count if it's 1.

**Comment by mabuchner** [comment]
That's strange. My vim show the tab indices:

![Screenshot 2020-08-05 at 1 36 49 PM](https://user-images.githubusercontent.com/6006874/89375700-c27b3080-d720-11ea-9e05-b8e02e70f67b.png)

**Comment by mabuchner** [comment]
Ok, it's probably from the lightline plugin.

Starting vim without any plugins (`vim -u NONE`) and opening new tabs will behave as you described.

I will adjust the description, because I still think, that showing the tab index is more useful, than showing the number of splits inside a tab.

**Comment by mabuchner** [comment]
Closing this in favour of #2233.
