### ISSUE TITLE
When Onivim unmaximized it can't render itself upon next start

### ISSUE THREAD

**Issue by ArthurZ** [onivim/oni2#2229]
On Win 10 Pro, the latest builds of OniVim do not remember any window position and size other than maximized. If accidentally un-maximized Onivim can't render on screen next time it starts (varies from no window to a tiny hard to find blip).

**Comment by bryphe** [comment]
This is a bad one - thanks for catching it and logging it, @ArthurZ 

I can reproduce, and I see that we get invalid parameters for the persisted `x` and `y` in this case:

```
x: -32000 y: -32000
```

A temporary work-around is to delete the `store` directory in `C:\Users\<your-user-name>\AppData\Local\Oni2` to reset the persisted settings.

I'll also work on a fix to check the values we get from persistence prior to creating the window.
