### ISSUE TITLE
Allow to disable automatic file explorer scrolling

### ISSUE THREAD

**Issue by mabuchner** [onivim/oni2#2231]
When switching between multiple files from different directory structures, then the automatic scrolling inside the file explorer gets really distracting.

![ezgif-6-82c52e708c04](https://user-images.githubusercontent.com/6006874/89368960-5d6b0f00-d70f-11ea-9f7e-ad01d965b945.gif)

Sublime Text also highlights the current file in the side bar, but it will not automatically scroll to the highlighted file. This results in a much more unobtrusive experience.

It would be nice, if Oni2 could at least provide an option to disable the automatic scrolling.

**Comment by bryphe** [comment]
> It would be nice, if Oni2 could at least provide an option to disable the automatic scrolling.

Definitely reasonable 👍  There's an equivalent VSCode setting for it - `explorer.autoReveal`. We should implement that.

**Comment by marcagba** [comment]
Do you think this one is a good first issue for someone eager to contribute? 🤔

**Comment by bryphe** [comment]
Hi @marcagba ,

Thanks for offering to help! I do think this would be a pretty good first issue, actually 👍 

There's a couple things we have to do for it:

1) __Add a configuration setting:__ - the VSCode-equivalent setting is `explorer.autoReveal`. When set to `true`, we'd use the existing behavior (automatically select and focus the file), and when set to `false`, we wouldn't scroll / focus a file.

We'd need to add the setting here: https://github.com/onivim/oni2/blob/master/src/Core/ConfigurationValues.re and then add a parser for it here: https://github.com/onivim/oni2/blob/68ca4d93947b5a74c93453776a9a281fd526c2a6/src/Core/ConfigurationParser.re#L232

2) __Turn off the auto-focus when the configuraiton setting is `false`:__ - This behavior is controlled by a subscription, here: https://github.com/onivim/oni2/blob/68ca4d93947b5a74c93453776a9a281fd526c2a6/src/Store/StoreThread.re#L313

We could gate this by doing something like: `let fileExplorerSub = autoReveal ? Model.Sub.activeFile(...) : Isolinear.Sub.none` (this would turn the subscription to a no-op when the configuration is off). And then the configuration value is pretty straightforward to query here once 1) is implemented: https://github.com/onivim/oni2/blob/68ca4d93947b5a74c93453776a9a281fd526c2a6/src/Store/StoreThread.re#L239

Would be awesome to have help! Let me know if you have any questions.

**Comment by marcagba** [comment]
I think since @caleywoods PR this issue can be closed :)
