### ISSUE TITLE
Autocomplete fuzzy matches prioritised over substring matches

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#2235]
Currently autocomplete appears to prioritise fuzzy matches over substring matches, which seems to be prioritising less likely over more likely. 

(I'm assuming currently there isn't anything that stores recent accepted matches prioritising based on that, etc...)

onivim:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/1826271/89417458-9d89bc00-d726-11ea-95a7-f412efbea98f.png">

vscode comparison:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/1826271/89417427-95318100-d726-11ea-9435-3d1d80301087.png">

**Comment by mabuchner** [comment]
[I also had the same problem](https://github.com/onivim/oni2/issues/1831#issuecomment-635082328) inside a project, which initially wasn’t using git. After I created a git repository, the substring matches were prioritized higher, than the fuzzy matches, as one might expect.

That’s of course not a solution, but just some observation.

**Comment by yunti** [comment]
The screenshots are from a project with a git repo

**Comment by bryphe** [comment]
Thanks for logging the issue! 

I wonder if @CrossR 's improvements to fuzzy-filtering (which both the quick-open and completion use) will help this scenario: https://github.com/onivim/oni2/pull/1566

**Comment by yunti** [comment]
Tested again with the updated completion sorting.  This helps for certain completions:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/1826271/93588713-b29f6f00-f9a3-11ea-847a-23f959440fbc.png">

but no change for the original test, so will need fzf as mentioned in the pr.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1826271/93588904-f7c3a100-f9a3-11ea-8d10-2511dc60474c.png">
