### ISSUE TITLE
Feature Request: Native multiple cursors

### ISSUE THREAD

**Issue by SalmonLoom** [onivim/oni2#225]
I really love the multiple cursor feature of any modern editor (sublime, vscode, intellij). 
You do not need this feature that often, but when you need it, it feels very productive to have it.
  
There are (n)vim plugins that bring this feature but I would love to have this native and well thought through for oni2.

Thank you for all your work. It already looks very promising what you have right now.

**Comment by CrossR** [comment]
I'm going to close this issue out since there is a more complete issue now over in #288.

We are thinking about it, and know they can be very useful!
