### ISSUE TITLE
can't close terminal buffer when tabs are hidden

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#2251]
I'm using onivim in vim buffer mode which was added recently.  However I can't seem to close the terminal, presumably because `:` doesn't open up the command mode popup like an editor does. 
I can workaround this by making the terminal active and then clicking on a file in the file explorer and then doing `:q`.
Ideally it would be good to have a command to bind a key to open/close the terminal. 

<img width="345" alt="image" src="https://user-images.githubusercontent.com/1826271/89529589-e6a04580-d7e4-11ea-80ae-a21c2a6bca3e.png">

**Comment by bryphe** [comment]
Control+W, Q might work for this to close the window - I don't think we have that hooked up, yet.

One alternative would be to run the `exit` command - that should close the terminal (but is a bit more verbose!)

**Comment by yunti** [comment]
Thanks, just tested Cmd +W and it does work (onMacos). Would be good to have a keybind to toggle open/close terminal like vscode. ?But thats probably a seperate issue.   Shall I close this one out or do you want it left open to test other OS's? @bryphe

**Comment by bryphe** [comment]
This should be better now with #3498
