### ISSUE TITLE
Add Oni2 to System PATH, dialog missing application name

### ISSUE THREAD

**Issue by fson** [onivim/oni2#2261]
The password dialog that opens after selecting "Add Oni2 to System PATH" (on macOS 10.15.5) only shows "wants to make changes." – it seems to be missing the name of the program in the beginning.

<img width="454" alt="Screen Shot 2020-08-07 at 11 35 25" src="https://user-images.githubusercontent.com/497214/89626690-6e985500-d8a2-11ea-88ee-3c3d021e4dec.png">

**Comment by bryphe** [comment]
Should be fixed now with #2822
