### ISSUE TITLE
Portal build out of date

### ISSUE THREAD

**Issue by izik1** [onivim/oni2#2262]
Hi! The most recent build on the portal is 8d38f687, which is from two days ago, it seems like whatever is doing the automated releases broke

Although, it might be due to CI failures: Since 8d38f687 there has only been _one_ commit (as of 2020-08-07T07:00:55-08:00) (ad136eef1867e14e67a2a0e0c31a3945d02d83f1) that passed CI

**Comment by bryphe** [comment]
Hi @izik1 , thanks for the heads up!

I was putting in some changes in the back-end to support showing both the `nightly` and `0.5.0` build - unfortunately it wasn't pushing back to the 'old' strategy. The portal has both builds available now:
![image](https://user-images.githubusercontent.com/13532591/89822975-84f21b00-db05-11ea-9088-a0c30474eb95.png)

(nightly it still the default).

Should be fixed now! But let me know if you see any other issues with it.
