### ISSUE TITLE
Preview lines breaking from container

### ISSUE THREAD

**Issue by ultrox** [onivim/oni2#2264]
Version 0.4.0 on Mac 10.15.5

![image](https://user-images.githubusercontent.com/3077558/89664591-ad94cd80-d8d7-11ea-9b47-8329188ff5f9.png)

**Comment by bryphe** [comment]
Thanks for the logging the bug and the screenshot, @ultrox !

Will need to fix this as part of integrating completion documentation

**Comment by chinwobble** [comment]
Another issue is when you change font sizes, the popup menu doesn't resize appropriately.

**Comment by bryphe** [comment]
Oof, ya, good catch @chinwobble : 

![image](https://user-images.githubusercontent.com/13532591/90706361-d14a0300-e249-11ea-937e-bfabbe987ada.png)
