### ISSUE TITLE
:wa (write all) only saves current buffer

### ISSUE THREAD

**Issue by Grinshpon** [onivim/oni2#2276]
The `:wa` command will only save the buffer you are currently viewing/editing, but not any others.

![example gif](https://i.imgur.com/A8PNgxQ.mp4)

I can reproduce this 100% of the time by just having two buffers open with unsaved changes, typing `:wa` and only the one I'm on is saved.

**Comment by bryphe** [comment]
This should be fixed now as part of the work for https://github.com/onivim/oni2/pull/3419/
