### ISSUE TITLE
"Cntrl + Backspace" doesn't work.

### ISSUE THREAD

**Issue by dlagg** [onivim/oni2#2281]
The keyboard shortcut "Cntrl + Backspace" on Quick open, Command Palette and Vim Command doesn't work.

**Comment by fiddler** [comment]
Hi, I would love to help out with this. Did some digging and I believe got the fix done. I'll try and set up some tests and follow the contribution guidelines to get a proper PR up later this week.

**Comment by fiddler** [comment]
Would it make sense to add also the correct behavior for OS X for CMD + Backspace in the same PR? Or would you prefer a separate PR for that?

**Comment by bryphe** [comment]
> Would it make sense to add also the correct behavior for OS X for CMD + Backspace in the same PR? Or would you prefer a separate PR for that?

Oops, sorry I missed this @fiddler - I just merged your PR to fix this 😄  Thanks for the great contribution!

I have #2404 tracking some missing MacOS shortcuts - added a note there to include CMD + Backspace.

**Comment by bryphe** [comment]
Resolved with #2443
