### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#2291]
If possible, we should try and fix the issues we've got in our bindings, since the warnings it throws up are a bit worrying for new users.

Most of it looks like just standard issues or dodgy comparisons/casts.

The files I think are just our `bindings.c`, so we should go through and update them.

[Example](https://gist.github.com/CrossR/3953242e971c18f40f64ffdf50b738d1)

**Comment by bryphe** [comment]
Thanks @mrillusi0n for fixing this!
