### ISSUE TITLE
"editor.FontSize" acts on "ui.zoom" ?

### ISSUE THREAD

**Issue by dlagg** [onivim/oni2#2294]
I get unexpected behavior when I try to modify the **editor.FontSize** variable. Sometimes changes the **ui.zoom** others don't do anything.

**Comment by bryphe** [comment]
Interesting - is this on Windows, @dlagg ? It sounds a little like https://github.com/onivim/oni2/issues/2206 - where the config file changes weren't getting picked up after saving.

**Comment by dlagg** [comment]
> Interesting - is this on Windows, @dlagg ? It sounds a little like https://github.com/onivim/oni2/issues/2206 - where the config file changes weren't getting picked up after saving.

I'm on  Archlinux 5.7.12-arch1-1
