### ISSUE TITLE
Editor: tool tips text goes off screen

### ISSUE THREAD

**Issue by chinwobble** [onivim/oni2#2324]
The tooltip text often goes outside the text area, especially on long function signatures.

OS: windows 10

![image](https://user-images.githubusercontent.com/18226001/90582892-3d107980-e212-11ea-8056-f34f55c087c6.png)

**Comment by bryphe** [comment]
Thanks for logging the issue, @chinwobble (and for the screenshot!)

Looks like this may be a dup of #2264 - I'll resolve this as a dup of that

Also, nice Revery project 😎
