### ISSUE TITLE
Running the command `:set filetype` closes editor [fix(buffer/#782)]

### ISSUE THREAD

**Issue by synaptiqlabs** [onivim/oni2#2331]
On WIndows 10, build 18362, attempting to run the command `:set filetype=` immediately and unexpectedly closes the editor, regardless of the filetype specified. 

However, if the application is initiated with the  `--nofork` and `--debug` flags, the command functions as expected.

Clicking on the filetype in the status bar works without issue.

--- #782

**Comment by CrossR** [comment]
Whoops, can confirm and I think I see what the issue is. I'll submit a PR in a mo.
