### ISSUE TITLE
Issuing :bd closes the entire application.

### ISSUE THREAD

**Issue by synaptiqlabs** [onivim/oni2#2340]
Issuing `:bd` in a buffer with other buffers and tabs open causes the application to immediately exit.  

<details>
<summary>Extracted debug log entry</summary>

[DEBUG]  +257ms Revery.App : Upshifting into active state.
[INFO]   +149ms Oni2.Store.dispatch : dispatch: (KeyDown (<opaque>, <opaque>))
[DEBUG]    +1ms Oni2.Store.dispatch : After: (KeyDown (<opaque>, <opaque>))
[DEBUG]    +0ms Oni2.Store.StoreThread : Running effect: Batch:
 input.immediateDispatch

[INFO]     +0ms Oni2.Store.dispatch : dispatch: KeybindingInvoked {command = "list.select"}
[DEBUG]    +1ms Oni2.Store.dispatch : After: KeybindingInvoked {command = "list.select"}
[DEBUG]    +0ms Oni2.Store.StoreThread : Running effect: Batch:
 keybindings.executeCommand

[INFO]     +0ms Oni2.Store.dispatch : dispatch: ListSelect
[DEBUG]    +1ms Oni2.Store.dispatch : After: ListSelect
[DEBUG]    +0ms Oni2.Store.StoreThread : Effect complete: Batch:
 keybindings.executeCommand

[DEBUG]    +0ms Oni2.Store.StoreThread : Effect complete: Batch:
 input.immediateDispatch

[DEBUG]    +1ms Revery.App : Upshifting into active state.
[DEBUG]    +7ms Oni2.Store.StoreThread : Running effect: Batch:
 quickmenu.executeVimCommand

[INFO]     +0ms Oni2.Store.dispatch : dispatch: KeyboardInput {isText = false; input = "<CR>"}
[DEBUG]    +2ms Oni2.Store.dispatch : After: KeyboardInput {isText = false; input = "<CR>"}
[DEBUG]    +0ms Oni2.Store.StoreThread : Effect complete: Batch:
 quickmenu.executeVimCommand

[DEBUG]    +6ms Oni2.Store.StoreThread : Running effect: Batch:
 vim.input

[INFO]     +0ms Oni2.Store.dispatch : dispatch: BufferEnter {id = 1; fileType = Buffer.FileType.NotSet;
  lineEndings = <opaque>; filePath = None; isModified = false; version = 0;
  font =
  { fontFamily = <opaque>; fontSize = 11.; spaceWidth = 6.62255859375;
    underscoreWidth = 6.62255859375; avgCharWidth = 0.;
    maxCharWidth = 14.029296875; measuredHeight = 13.0034179688;
    descenderHeight = 3.00244140625; smoothing = <opaque>;
    features = <opaque> };
  buffer = <opaque>}
[INFO]     +2ms Oni2.Service_Syntax : Starting buffer subscription for: 1
[INFO]     +1ms Service_Exthost : Starting buffer subscription for: 1
[INFO]     +0ms Service_Exthost : Setting active editor id: onivim.editor:5
[INFO]     +0ms Service_Exthost : Stopping editor subscription for: onivim.editor:3
[INFO]     +0ms Oni2.Service_Syntax : Stopping buffer subscription for: 4
[INFO]     +0ms Oni2.Store.dispatch : dispatch: (FileExplorer (ActiveFilePathChanged None))
[DEBUG]    +1ms Oni2.Store.dispatch : After: (FileExplorer (ActiveFilePathChanged None))
[DEBUG]    +1ms Oni2.Store.dispatch : After: BufferEnter {id = 1; fileType = Buffer.FileType.NotSet;
  lineEndings = <opaque>; filePath = None; isModified = false; version = 0;
  font =
  { fontFamily = <opaque>; fontSize = 11.; spaceWidth = 6.62255859375;
    underscoreWidth = 6.62255859375; avgCharWidth = 0.;
    maxCharWidth = 14.029296875; measuredHeight = 13.0034179688;
    descenderHeight = 3.00244140625; smoothing = <opaque>;
    features = <opaque> };
  buffer = <opaque>}
[DEBUG]    +0ms Oni2.Store.Vim : Buffer update: 1
</details>

**Comment by mabuchner** [comment]
Same as #2247.

**Comment by synaptiqlabs** [comment]
Yeah. Didn't look well enough. I'll close this, then.
