### ISSUE TITLE
Compatibility with Godot, gdscript, and godot-tools?

### ISSUE THREAD

**Issue by do-kevin** [onivim/oni2#2347]
Hi there,

I was wondering if Onivim 2 will be compatible with godot-tools extension and has anyone tried working on Godot alongside Onivim 2? I would like to know if there is any additional setup that must be done to get Onivim 2 working with Godot, especially since godot-tools doesn't show up in extension search.

I also have an additional question, will Onivim 2 have interactive tutorials like the first version did?

Thanks!

**Comment by bryphe** [comment]
Hi @do-kevin ,

Good question, I haven't tried godot-tools (...might be a fun excuse to play with Godot though 😄 )

I noticed the godot-tools extension isn't on open-vsx, so I opened a PR to make it available there: https://github.com/open-vsx/publish-extensions/pull/135 as a first step. Some features - like the debugger - aren't supported yet.

> I also have an additional question, will Onivim 2 have interactive tutorials like the first version did?

I would like to have them, just been bogged down with other functionality at the moment. Were those useful for you? Is there anything you'd be looking for in terms of tutorials?

**Comment by do-kevin** [comment]
Thanks @bryphe, that's good to know.

Yeah, I found them very useful. I didn't know how to use vim and often found it intimidating. The interactive tutorials in the previous version of onivim helped me exercise and practice using vim; it was engaging and fun to do too.

Well, I don't know much about vim but if the tutorials do return in onivim2, it would be nice if there was an additional vim tutorial that shows how to do VSCode's CTRL+D where you can select text that are matched and you can replace or delete them.

**Comment by do-kevin** [comment]
Hey @bryphe,

Is Oni2's Discord still active? I want to ask some questions and learn more about using the software. The current Discord link is expired on the website and subreddit.

**Comment by Apostolique** [comment]
The Discord server is quite active: https://discord.gg/rjuN6rN

Just made a new link for you.
