### ISSUE TITLE
Unclosable Notification after saving a file

### ISSUE THREAD

**Issue by jisensee** [onivim/oni2#2358]
Since this weeks build, I get the following notification as soon as I save a file.[](url)
![Capture](https://user-images.githubusercontent.com/17804319/91182411-6f2a4b80-e6ea-11ea-8822-9fdd64a8bed0.PNG)
The buttons on it don't do anything, there seems to be no way to get rid of it except restarting oni.

The directory I am working in is not a git repo, maybe thats the issue? I am on Windows 10 here.

**Comment by bryphe** [comment]
Thanks for logging the issue, @jisensee . I can also reproduce this on OSX (in a folder that is not a git repository, when saving).

It looks like on buffer save, we're sending a `git.refresh` action... which is then sending us this dialog back. Looking at a better way to handle this.
