### ISSUE TITLE
Completions: Auto-import in typescript not working as expected

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#2360]
The TypeScript provider supports auto-import, like:
![image](https://user-images.githubusercontent.com/13532591/91229863-63855780-e6df-11ea-8b24-c1f825e647dd.png)

When accepting this completion, there should also be an import added at the file.

The issue is that the suggest item for this case:
```
{ SuggestItem.chainedCacheId = (Some (9, 816)); label = "Comparator";
  kind = CompletionKind.Class;
  detail = (Some "Auto import from 'semver-umd'\nclass Comparator");
  documentation = None; sortText = (Some "\239\191\1915"); filterText = None;
  insertText = None; insertTextRules = [];
  suggestRange =
  (Some SuggestItem.SuggestRange.Combo {
          insert =
          { startLineNumber = 52; endLineNumber = 52; startColumn = 3;
            endColumn = 3 };
          replace =
          { startLineNumber = 52; endLineNumber = 52; startColumn = 3;
            endColumn = 6 }});
  commitCharacters = ["."; ","; ";"; "("];
  additionalTextEdits =
  [{ Edit.SingleEditOperation.range =
     { startLineNumber = 20; endLineNumber = 20; startColumn = 1;
       endColumn = 1 };
     text = (Some "import { Comparator } from 'semver-umd';\n");
     forceMoveMarkers = false }
    ];
  command =
  (Some { Command.id = "_vscode_delegate_cmd_keagvkiq"; label = (Some []) })
  }

```

Provides an `additionalTextEdit` to insert the `Comparator` block. We need to hook up handling for that.

**Comment by Jorgee97** [comment]
Any updates on this issue?

**Comment by Jorgee97** [comment]
@bryphe This can be expanded not only to typescript but other languages as well, this is also happening with Dart.
Autocompletion suggestion is shown but the import is not aggregated to the top of the file:

![image](https://user-images.githubusercontent.com/8935477/99006433-6f2f3000-2510-11eb-8bc2-59690f1d14b2.png)
