### ISSUE TITLE
Fish shell does not work properly in oni2 build 0.5.1-nightly

### ISSUE THREAD

**Issue by duncte123** [onivim/oni2#2370]
As seen in the following screenshot the fish shell acts up when being opened in onivim.
I'm running Ubuntu 18.04.

![image](https://user-images.githubusercontent.com/8843386/91559137-cbce7600-e937-11ea-841e-9793c1d5bb9f.png)

**Comment by bryphe** [comment]
This may be the same underlying issue as https://github.com/onivim/oni2/issues/2040 (it looks like there is an error loading `libtinfo`, which is likely due to the `LD_LIBRARY_PATH` environment variable being overridden)

**Comment by pikachunakapika** [comment]
Maybe the terminfo is just missing.
Try  sudo apt-get install ncurses-term

**Comment by duncte123** [comment]
> Maybe the terminfo is just missing.
> Try `sudo apt-get install ncurses-term` .
> Maybe there is a better onivim2 terminal identifier that is available on many systems by default under /usr/share/terminfo/.

same issue after installing

> This may be the same underlying issue as #2040 (it looks like there is an error loading libtinfo, which is likely due to the LD_LIBRARY_PATH environment variable being overridden)

That's probably it
