### ISSUE TITLE
Weird cursor jump in terminal on second keystroke

### ISSUE THREAD

**Issue by dsincl12** [onivim/oni2#2374]
Open a terminal in Onivim and enter any command. On the second keystroke the cursor will jump to the beginning of the line and rewrites(?) all characters before going to the current position.

![weird_cursor_jump](https://user-images.githubusercontent.com/28440/91642890-47f7b500-ea2f-11ea-89f3-2dfde36edeb4.gif)

**Comment by bryphe** [comment]
Thanks for logging the issue, @dsincl12 and for the animated gif. Looks like a timing issue with setting the cursor position and redrawing - need to find where we're getting a stale cursor state.
