### ISSUE TITLE
Control Panel: some keys disabled if in visual mode

### ISSUE THREAD

**Issue by nepeckman** [onivim/oni2#2379]
If the editor is in visual mode while the control panel is popped, the keys 'a', 'i', 'o', will not register while typing a command.

Steps to reproduce:
* In editor, go into visual mode
* Pop control panel with Ctrl + Shift + P (or search panel with Ctrl + P)
* Try to use keys 'a', 'i', 'o' to input text in the control/search panel

Seems like the keys to move from normal mode to insert mode are being disabled when in visual mode, but maybe at too high a level?

**Comment by bryphe** [comment]
Thanks for reporting the issue! Looks like this was fixed in https://github.com/onivim/oni2/pull/2429
