### ISSUE TITLE
Can't build the frontend

### ISSUE THREAD

**Issue by kirillt** [onivim/oni2#2391]
Following the instructions from https://onivim.github.io/docs/for-developers/building
```bash
git clone https://github.com/onivim/oni2
cd oni2
esy install
```
Last step fails with some problem about `@esy-ocaml/substs`:
```
error unable to fetch @esy-ocaml/substs@0.0.1:                                                         
                                                source: archive:https://registry.npmjs.org/@esy-ocaml/substs/-/substs-0.0.1.tgz#sha1:59ebdbbaedcda123fc7ed8fb2b302b7d819e9a46
                                                error: error: run ['shasum' '--algorithm' '1'
                                                            '/tmp/oni2/_esy/default/tmp/esy-f92046/archive']: exited with 127
                                                         fetching dist: archive:https://registry.npmjs.org/@esy-ocaml/substs/-/substs-0.0.1.tgz#sha1:59ebdbbaedcda123fc7ed8fb2b302b7d819e9a46
error: installation error              
  fetching @esy-ocaml/substs@0.0.1
esy: exiting due to errors above
```

I checked and I can install `@esy-ocaml/substs@0.0.1` with npm successfully.
If I try to install it with `esy`, it fails as well (with the same error as above).

The OS is Fedora 32.

**Comment by bryphe** [comment]
Hmm, what version of `esy` are you using, @kirillt (`esy -version`?)

It looks like from the exit code you might be missing the `shasum` utility, which `esy` requires - might be worth checking if that is available and installing it if not.

**Comment by kirillt** [comment]
Thank you @bryphe, indeed it was caused by lack of `shasum` on my machine.
Package `perl-Digest-SHA-6.02-442.fc32.x86_64` helps with it in Fedora.
So this issue is also a duplicate of https://github.com/esy/esy/issues/854

**Comment by kirillt** [comment]
Here are more dependencies though, I installed `nasm` and `libXext`, but still there are some missing, apparently:
```
    /usr/bin/ld: cannot find -lGLU
    /usr/bin/ld: cannot find -lXxf86vm
    /usr/bin/ld: cannot find -lXrandr
    /usr/bin/ld: cannot find -lXinerama
    /usr/bin/ld: cannot find -lXcursor
    /usr/bin/ld: cannot find -lXi
```

**Comment by CrossR** [comment]
The revery dependencies should be listed here : https://github.com/revery-ui/revery/wiki/Building-&-Installing

If there is stuff missing under the Fedora subheading though, could be worth adding them. The Ubuntu ones I've used recently but the Fedora ones its been a while since I checked them.
