### ISSUE TITLE
Add yank highlights duration and colour customisation

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#2396]
Adding on to my comments from the pull request that added yank highlights #2377. Currently the yank highlights are too quick to be usable for me.

Comparing to vscode the default in vscode is a lot more obvious.

It would be good, like vscode vim, to add the options `vim.highlighted.yank.color` and `vim.highlightedyank.duration` so that the length and the color of the highlight can be customised. 

(these are outlined in vscode vim readme https://github.com/VSCodeVim/Vim)

**Comment by bryphe** [comment]
Thanks for logging this, @yunti ! Was actually just thinking about this - I was trying to record a video of these for presentation on Sunday and they were really faint. I like the idea of the config settings from VsCodeVim, I'll stick with that precedent 👍

**Comment by yunti** [comment]
The fix for this in #2402 works perfectly. Thanks. 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/1826271/93591131-b208d780-f9a7-11ea-9621-6525fafb67fa.png">
