### ISSUE TITLE
UI - Input Control: Shortcuts are not correct on macOS

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#2404]
On macOS, our selection shortcuts are using the control key (ie, `Control+a` to select all) - they should be using the MacOS paradigm of the command key (ie, `command+a` to select all). Likewise for the selection movement commands - `command+shift+left arrow`. We should take a pass over these and ensure they are correct for MacOS (the hard work - having the selection model - is already done!)

**Comment by bryphe** [comment]
In addition - we should support CMD + Backspace, as called out in #2281

**Comment by fiddler** [comment]
I'll grab this one! I have most of the fixes done - but need to clean up and setup proper tests for a PR.

**Comment by bryphe** [comment]
Awesome, thanks for the help @fiddler !

**Comment by bryphe** [comment]
Looks like this is all fixed thanks to #2537 :+1:
