### ISSUE TITLE
Toggle Problems command does not toggle problems panel

### ISSUE THREAD

**Issue by dcalhoun** [onivim/oni2#2408]
Executing the "View: Toggle Problems (Errors, Warnings)" command in the command palette results in nothing happening.

![Screen Recording 2020-09-04 at 10 46 21](https://user-images.githubusercontent.com/438664/92284845-917d4f80-eec8-11ea-9ab2-7a7183ee9060.gif)

## Steps to Reproduce

1. Launch an Oni2 window.
1. Open the command pallet: <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
1. Type "View: Toggle Problems (Errors, Warnings)"
1. Press return key

## Expected Result

The "Problems" panel opens or closes, depending on its current state.

## Actual Result

Nothing appears to happen. The "Problems" panel does not open or close.

## Environment

**OS:** macOS 10.15.6
**Oni2 Version:** 0.5.1-nightly

**Comment by bryphe** [comment]
Thanks for the bug report & the gif, @dcalhoun ! I can confirm I was able to repro - opened #2412 to address it.
