### ISSUE TITLE
Commenting a line causes get_op_type() error

### ISSUE THREAD

**Issue by dcalhoun** [onivim/oni2#2409]
Commenting a line via <kbd>G</kbd><kbd>C</kbd><kbd>C</kbd> causes a `get_op_type()` error to be shown.

![Screen Recording 2020-09-04 at 16 09 08](https://user-images.githubusercontent.com/438664/92285230-6a734d80-eec9-11ea-9f55-bc2fbae86cea.gif)

## Steps to Reproduce

1. Launch an Oni2 window.
1. Open a new buffer via `:enew`.
1. Set the language type to "JavaScript."
1. Comment a line in the file via <kbd>G</kbd><kbd>C</kbd><kbd>C</kbd>

## Expected Result

The line is commented out and no error is displayed.

## Actual Result

The line is commented out, but an error is also displayed.

## Environment

**OS:** macOS 10.15.6
**Oni2 Version:** 0.5.1-nightly

**Comment by bryphe** [comment]
Thanks for the bug report and gif, really appreciate it!

I've seen this intermittently but didn't have a consistent repro - this is the best repro I've found for it
