### ISSUE TITLE
`vi` motion working unexpectedly

### ISSUE THREAD

**Issue by lucis** [onivim/oni2#2413]
Ok, I've done some screenshots to show what's happening.

I was here on normal mode:
<img width="507" alt="Screen Shot 2020-09-05 at 9 16 37 PM" src="https://user-images.githubusercontent.com/18706156/92315768-2794a100-efc1-11ea-8c78-234beecd1446.png">

Then, I've pressed `vi(` to select the text inside the parenthesis, but ended up with this: 
<img width="532" alt="Screen Shot 2020-09-05 at 9 16 46 PM" src="https://user-images.githubusercontent.com/18706156/92315794-6dea0000-efc1-11ea-8b72-b9a3092a65ee.png">

Just adding that `ci(` works fine. I

Running on a **Macbook Pro 2019** and the editor's version is `0.5.1-nightly`.

**Comment by mabuchner** [comment]
Similar to #1880.

I really wish this would get fixed.
