### ISSUE TITLE
Unable to load on Windows 10 1809, Intel HD Graphics 520

### ISSUE THREAD

**Issue by appelgriebsch** [onivim/oni2#2424]
Hey,

I just tried the latest release on my Windows 10 box featuring a Intel i5 with Intel integrated graphics, but the Oni2 main window doesn't show up. I checked the task manager and verified that the instance was started properly.

So I started it with debug log level and noticed some errors during start:
```
[INFO] Revery.CanvasContext: Creating Skia context...
[ERROR] Revery.CanvasContext: Unable to create skia context
[DEBUG] Revery.CanvasContext: Unable to create native interface. Falling back to SDL2...
```
Those lines got repeated multiple times. 

[onivim.log](https://github.com/onivim/oni2/files/5193371/onivim.log)

Any idea?

**Comment by bryphe** [comment]
Thanks for logging the issue, @appelgriebsch - would it be possible to get the full logs? If you run with `Oni2.exe -f`, we get some logs at the beginning that would be helpful - on my Windows machine:
```
[INFO]   +102ms Oni2_editor : Starting Onivim 2.0.5.1-nightly (eef5c15c)
[INFO]   +569ms Oni2_editor : Startup: Changing folder to: D:\oni2
[INFO]   +277ms Oni2_editor : Unsanitized x value: -8
[INFO]     +1ms Oni2_editor : Unsanitized x value: -8
[INFO]     +0ms Oni2_editor : Sanitized values from persistence - x: Absolute(-8) y: Absolute(-8) width: 1936 height: 1176
[INFO]    +35ms Revery.Core.Window : Display count: 1
[INFO]   +139ms Revery.Core.Window : Display 0:Dell U2412M(Digital) - pixelFormat: SDL_PIXELFORMAT_RGB888 width: 960 height: 600 refreshRate: 29 Bounds: x: 0 y: 0 width: 1920 height: 1200
[INFO]     +0ms Revery.Core.Window : Creating window Oni2 width: 1936 height: 1176
[INFO]  +7122ms Revery.Core.Window : Window created successfully.
[INFO]   +169ms Revery.Core.Window : OpenGL hardware info:
[INFO]     +1ms Revery.Core.Window :   renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
[INFO]     +0ms Revery.Core.Window :   version: OpenGL ES 3.0.0 (ANGLE 2.1.0.a4b21cf26074)
[INFO]     +0ms Revery.Core.Window :   vendor: Google Inc.
[INFO]     +0ms Revery.Core.Window :   shadingLanguageVersion: OpenGL ES GLSL ES 3.00 (ANGLE 2.1.0.a4b21cf26074)
[INFO]   +210ms Revery.Core.Window : Using vsync: Immediate
```

In particular - I'm interested in what we're showing as your OpenGL hardware info, and if it is picking up ANGLE. 

We fairly recently switched to using ANGLE - https://github.com/onivim/oni2/pull/2283 - which uses Direct3D, and tends to be better supported across Windows hardware. It's only in nightly and not stable - the logs would show us which commit you've picked up as well, so we can see if you should be using ANGLE.

**Comment by appelgriebsch** [comment]
Hey @bryphe I’ve had attached this log already to the issue reported yesterday. Please have a look. Seems it can’t create an OpenGL context...

```
[ERROR]    +0ms Revery.SDL2 : SDL_GL_Setup failed: Invalid window
[DEBUG]    +0ms Revery.Core.Window : GL setup. Checking GL version...
[DEBUG]    +1ms Revery.Core.Window : Checking GL vendor...
[DEBUG]    +0ms Revery.Core.Window : Checking GL shading language version...
[INFO]     +1ms Revery.Core.Window : OpenGL hardware info:
[INFO]     +0ms Revery.Core.Window :   renderer: Unable to get OpenGL proc address for glGetString
[INFO]     +0ms Revery.Core.Window :   version: Unable to get OpenGL proc address for glGetString
[INFO]     +1ms Revery.Core.Window :   vendor: Unable to get OpenGL proc address for glGetString
[INFO]     +1ms Revery.Core.Window :   shadingLanguageVersion: Unable to get OpenGL proc address for glGetString
```

**Comment by appelgriebsch** [comment]
Just checked the latest release from master, which works fine on my Windows 10 installation. So I guess with moving to the new ANGLE framework for the rendering this issue is solved.

**Comment by bryphe** [comment]
Ah, sorry I missed the log the first time around.

Glad the nightly works better - it turns out Direct3D is much better supported on Windows than OpenGL (we have a pretty high OpenGL requirement - 4+ - many Windows configurations don't have support for that, and some Intel GPUs don't even have drivers for it...)
