### ISSUE TITLE
Bug: Cursor jumping to start of file in singleTabMode

### ISSUE THREAD

**Issue by jisensee** [onivim/oni2#2426]
**Preconditions**:
- Have `singleTabMode` enabled
- Created a vertical split with 2 files

When moving between those two splits with `ctrl + W` and `hjkl` the very first keystroke after the movement will reset the cursor to the start of the buffer, ignoring the previous cursor position within it. This will even scroll up if the previous position was further down the line.

**Comment by keeslinp** [comment]
This also happens in a single pane when jumping to a definition in a new file that hasn't been opened yet. It jumps to the right spot and then as soon as you navigate it goes to the top of the file. Also when you jump back <C-O> it jumps to the top of the old file instead of where you jumped from.

**Comment by jisensee** [comment]
I guess some other work fixed this bug, it doesn't happen to me anymore on the latest build. Closing this for now.
