### ISSUE TITLE
ContextKeys are missing and not properly defined

### ISSUE THREAD

**Issue by fanantoxa** [onivim/oni2#2428]
Current implementation of `src\Model\ContextKeys.re` not fully correct

It missing both `textInputFocus` and `menuFocus`
The were removed here https://github.com/onivim/oni2/pull/786 but wasn't added back anywhere.

Also after looking in `ContextKeys.re` I've noticed that other key also not propely defined.
For example `editorTextFocus`
```
| TerminalInsert
| TerminalNormal
| TerminalVisual(_) => false
| _ => true
```

Basically it say that it on focus all the time but not terminal.
And there kinda wrong because you might be in `Menu`, `Search`, `WildMenu`, and other places at this moment.

That why `paste into text input` currently work in `insertMode` and also work when I add `editorTextFocus`

Same goes for `terminalFocus`
is active when
```
| TerminalInsert
| TerminalNormal
| TerminalVisual(_) => true
| _ => false
```
But still can open menu or smth.

Can we refine and refactor this to be more persistent and clear about different `ContextKeys`?
It already blocking me from further improving `textInputs` and few other things.
In addition we have [Keybinding Suggestions and Contribution Opportunities](https://github.com/onivim/oni2/issues/1423)
as `good-first-issue` and people going to be confused while working on it.

**Comment by fanantoxa** [comment]
@bryphe I see 2 PR that fix this issue. Nice work!

**Comment by bryphe** [comment]
Awesome! Thanks @fanantoxa for confirming, appreciate the help

I added a (ugly) debug UI to help troubleshoot these sorts of issues as well:

![Uploading 2020-09-22 15.44.59.gif…]()

Let me know if you see any other context keys that are incorrect 👍
