### ISSUE TITLE
Documentation out of date for adding Onvim2.app to macOS Applications folder

### ISSUE THREAD

**Issue by JasonMFry** [onivim/oni2#2454]
https://onivim.github.io/docs/for-developers/building#osx indicates `cp -R _release/Onivim2.app $USER/Applications` but there is now `_release` directory that I can find

**Comment by CrossR** [comment]
Is that after running the full set of command above it? The `esy create-release` command should make that folder.

**Comment by bryphe** [comment]
Right! There won't be a `_release` folder until `esy create-release` is run. And you'll need to make sure the editor is run prior to that, ie via `esy run`.

**Comment by bryphe** [comment]
This should be addressed now with #2762 & #2771
