### ISSUE TITLE
Windows 10: esy bootstrap "hangs" on esy-autoconf

### ISSUE THREAD

**Issue by parkerault** [onivim/oni2#2461]
When building from source, running esy bootstrap appears to hang after building esy-autoconf. I waited about 10 minutes and then, assuming that it had failed, hit `ctrl+c` to kill the bootstrap process. This didn't kill bootstrap, but it did resume the build process. My hunch is that there was some kind of warning or dialog that isn't being displayed in the build output, but that's just a guess.

As an aside, the build process is slooooooow on windows 10. I've been trying to get it to build for almost an hour now, which is mostly due to the very long build times for each package (is this normal?). It's difficult to tell if a package build has hanged when some of them can take over five minutes to finish (at the moment I've been waiting for esy-skia to build for about 10 minutes and I have no idea if it failed or if I should go make lunch instead).

**Comment by CrossR** [comment]
Thats interesting, between that and your other issue, its possible there is something missing which is causing the hanging, as it doesn't reproduce in the CI or locally. Have you got all the build dependencies installed, including the revery ones?

The build on Windows is pretty long (well, its long on platforms, but Windows is especially long). I would estimate its close to 40-50 mins on my 6700k. On the CI machines its over an hour I believe. Downside of having lots of dependencies is that the initial build is very slow, but we gain a lot from having Skia/SDL2 etcetc around from the performance side of course. You can also tell `esy` to run in verbose mode to a get a slightly better idea of if/what is happening.

**Comment by parkerault** [comment]
Sorry for the long delay. I have all of the prereqs installed, so no idea what would cause it. Maybe an error that is silenced in the build output? I'm not sure if I'll have time to come back around to this, so unless someone else reports this issue you can probably just chalk it up to my weird little machine.

**Comment by bryphe** [comment]
The problematic dependency on `esy-autoconf` was removed here: https://github.com/revery-ui/esy-libvterm/pull/5 - so this should no longer be an issue 👍
