### ISSUE TITLE
Clicking end of line moves cursor to penultimate character

### ISSUE THREAD

**Issue by earksiinni** [onivim/oni2#2463]
When I click at the end of a line, I expect the cursor to move to the end of the line. However, it seems to move to the penultimate character (i.e., one character before the end).

![2020-09-17 11 58 55](https://user-images.githubusercontent.com/5427394/93515488-86b9b600-f8dd-11ea-8b57-5d67233f407a.gif)

**Comment by bryphe** [comment]
Thanks for the great gif, @earksiinni ! Working on a fix in #2482

**Comment by earksiinni** [comment]
Awesome! Closing this.
