### ISSUE TITLE
Prettier formatOnSave doesn't work

### ISSUE THREAD

**Issue by earksiinni** [onivim/oni2#2464]
I've set up Prettier with the following configuration:

```json
{
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
}
```

But format on save doesn't work, I have to use the palette command.

I'm using `0.5.1-nightly`.

**Comment by bryphe** [comment]
Thanks for logging the issue, @earksiinni !

Ah, yes, we haven't hooked up format-on-save yet. The main issue is that we leverage Vim for saving, and the logic happens synchronously - we need to tie in more deeply to save pipeline to allow for format on save (and other save hooks) from the VSCode extension side.

**Comment by earksiinni** [comment]
Understood. Thanks for the explanation @bryphe. Do you have an idea of how difficult this would be for a beginner to implement?

**Comment by Amokstakov** [comment]
Any updates on this feature?

**Comment by aaronamm** [comment]
I opened the similar issue but specific to .editorconfig
https://github.com/onivim/oni2/issues/2814#issuecomment-742618055

**Comment by ludvigsen** [comment]
Are there any workarounds to this? Is it possible to use vimscript? All I need is for prettier to run when I save..

**Comment by ronangaillard** [comment]
Only feature preventing me from using OniVim daily :/

**Comment by ronangaillard** [comment]
Any idea of a release date for this fix or any hints of how we could implement it ?

**Comment by bryphe** [comment]
I'm thinking about if there are maybe simpler approaches to implement this - the original approach I had in mind:

> The main issue is that we leverage Vim for saving, and the logic happens synchronously - we need to tie in more deeply to save pipeline to allow for format on save (and other save hooks) from the VSCode extension side.

I'm considering a simpler way to tie into the save pipeline, that could at least unblock this - I know it's a feature that is important to a lot of people's workflow 👍  

Need to do some prototyping to see if it is viable though as an alternative - no ETA yet, but wanted you to know I'm thinking about it (fixing this will also be necessary: https://github.com/onivim/oni2/issues/2196)

**Comment by ronangaillard** [comment]
Thanks :) 

Good luck :)

**Comment by pgzm29** [comment]
Loving OniVim 2 so far! But yeah, this feature is a must in my daily workflow. I hope we can get this soon :) 

I know that formatting from the command palette gets the job done, but it would be awesome if it could be executed on save

Thanks :)
