### ISSUE TITLE
[Mac] Command-A doesn't select all inside of UI text boxes

### ISSUE THREAD

**Issue by earksiinni** [onivim/oni2#2465]
I expect that Command-A selects all text inside of any given UI text box (e.g., the command palette). However, it currently does nothing.

**EDIT**: I just saw this comment: https://github.com/onivim/oni2/issues/1423#issuecomment-681011358

I can confirm that Ctrl+A works on my Mac, but Cmd+A doesn't. Can I rebind to use Cmd?

**Comment by bryphe** [comment]
Looks like a dup of #2404 - there's a whole set of keybindings we're missing on macOS/OSX for the text input control (including `cmd+a`, but several others too). I'll resolve this as a duplicate of that one.

**Comment by earksiinni** [comment]
Works for me!
