### ISSUE TITLE
Add documentation to git

### ISSUE THREAD

**Issue by eleijonmarck** [onivim/oni2#2473]
Hey,

I find most of the documentation that is on par is updated through their users by being able to submit a PR to a repo where the documentation for the site relies.

much like this site:
https://www.graphile.org/postgraphile/introduction/

suggest improvements on the page:
https://github.com/graphile/graphile.github.io/edit/develop/src/pages/postgraphile/introduction.md

**Comment by glennsl** [comment]
The docs are already in the repository and accepting contributions: https://github.com/onivim/oni2/tree/master/docs/docs

I'm sure they could be easier to find though, and that would be a good contribution opportunity in itself, I'd say!

**Comment by glennsl** [comment]
This was resolved by #2483, no?

**Comment by eleijonmarck** [comment]
@glennsl yes
