### ISSUE TITLE
Autocomplete with tab inserts weird special character, have to click instead (macOS)

### ISSUE THREAD

**Issue by nathanKramer** [onivim/oni2#2493]
I've tried to find a duplicate issue but can't, I hope this is a unique ticket, apologies if not.

I've tried oni2 on two macbooks and they both had this issue. Not sure if it's mac specific though.

OS: Catalina, 10.15.6
Oni2: 0.5.1-nightly

As per the below gif, hitting tab when auto-completing renders a weird special character.

![oni](https://user-images.githubusercontent.com/4732403/93830335-45e1e880-fcb3-11ea-8837-96f98cc2d4f8.gif)

From reading other issues, this is not the intended behaviour.

**Comment by CrossR** [comment]
This looks like the same as #2477. Would be useful to get some of the same logging for you, and posted in that issue (`oni2 -f --debug`, with the CLI instructions over here :  https://onivim.github.io/docs/using-onivim/command-line).

It looked like a font fall back issue, but its odd that its happened a bunch recently, and not a few weeks ago when none of that code has changed (that I remember).
