### ISSUE TITLE
Windows 10: Explorer pane is not responding at all

### ISSUE THREAD

**Issue by kkutsner** [onivim/oni2#2501]
A this point of time, on my Windows 10 machine stable build of the app is not starting up at all, though, the latest nightly build starts succesfully, but the explorer pane does not allow to open subfolders or select files to open or edit. Are the any logs that can be used to investigate?

**Comment by CrossR** [comment]
Is this still occurring? There was a few changes and fixes around this recently.

You should be able to run `oni2` from the command line with `-f --debug` to get some useful logging out otherwise.

**Comment by kkutsner** [comment]
Tried nightly build - it is slightly better. I could click on file items and it works as expected. But clicking on nested folder items within parent folder does not expand the folder content. Note that when I enable logging, I can see that items are fetching but it just the UI does not render them for some reason

**Comment by bryphe** [comment]
Thanks for trying the latest, @kkutsner !

> Note that when I enable logging, I can see that items are fetching but it just the UI does not render them for some reason

Strange - would it be possible to see the logs, @kkutsner ? 

I just tried to repro:

![expand-folder](https://user-images.githubusercontent.com/13532591/94748501-51c64e00-0336-11eb-8203-c6694b4c4480.gif)

There were two possibilities I was thinking:
- Path with spaces (previous bugs around this)
- Path length issues (some Windows APIs don't work correctly with paths over 260 characters).

I experimented with both these and wasn't able to reproduce, but I'd be interested to look through the logs and see if we can narrow the delta.

**Comment by kkutsner** [comment]
Not sure what I did... but while trying to figure out how to push logs to some output file I ran the app from command line:

 'C:\Program Files\Onivim2\Oni2.exe' .\Documents\Development\

And now I can't repro the issue anymore, no matter which way I try to run the app - from command line or from start menu - the explorer just works as expected. So may be passing some explicit startup path to the app triggered some cleanup that did not happen before.

**Comment by bryphe** [comment]
I'm not able to reproduce this anymore either - will continue to track in #2213 , though
