### ISSUE TITLE
Filetype specific configuration

### ISSUE THREAD

**Issue by abemilk** [onivim/oni2#2506]
I was making a new Makefile for a project and noticed that it was using spaces instead of tabs therefore resulting in invalid makefile syntax.

First the filetype was being detected as Plain text so I installed the Makefile extension and relaunched and now it marks the filetype as makefile however it defaults to spaces.

I then tried to make filetype specific settings changes like in vscode and unfortunately that didnt work.

![Screen Shot 2020-09-24 at 9 21 46 AM](https://user-images.githubusercontent.com/47203201/94174955-d6066600-fe4a-11ea-9c97-617172d85639.png)

![Screen Shot 2020-09-24 at 9 22 01 AM](https://user-images.githubusercontent.com/47203201/94174873-b707d400-fe4a-11ea-859d-0c9505462b5e.png)

![Screen Shot 2020-09-24 at 9 23 19 AM](https://user-images.githubusercontent.com/47203201/94174842-aa837b80-fe4a-11ea-9e68-1ae40d25e7ec.png)

**Comment by CrossR** [comment]
So, we do actually allow for per filetype config, using the exact syntax you use.
However, I believe that we don't require the filetype to be passed over when asking for things from the config:

```reason
let getValue =
    (~fileType=?, selector: ConfigurationValues.t => 'a, configuration: t) => {
```

And looking at the indentation store, it looks like the filetype is never given.
@bryphe, I think this is probably a more widespread issue than just the indentation (though this is probably the area most people will bump into it). Is there a sensible fix here?

I don't know if requiring the filetype for everything is smart/needed, but it looks like making it completely optional means that its going to be forgotten about in some places. Perhaps it shouldn't have a default value, and you explicitly need to send `None` when you don't care about the per file config.
