### ISSUE TITLE
Installing extensions from the CLI fails on macOS

### ISSUE THREAD

**Issue by raw-bin** [onivim/oni2#2507]
```
> oni2 -f --debug --trace --install-extension clangd
[DEBUG]   +72ms Oni2.Exception : Recording backtraces
[DEBUG]    +0ms Oni2.Exception : Recording backtraces
[DEBUG]    +0ms Oni2.Core.Setup : Looking for setup configuration at: /Applications/Onivim2.app/Contents/Resources/../MacOS/setup.json
[ERROR]    +0ms Service.Extensions.Management : Unable to install extension: clangd
[DEBUG]    +0ms Oni2.Core.ThreadHelper : Starting thread: 1 (Utility.waitForCondition)
[DEBUG]    +0ms Oni2.Core.ThreadHelper : Closing thread: 1 (Utility.waitForCondition)
Failed to install extension: clangd

> oni2 -f --debug --trace --install-extension exuberant-ctags
[DEBUG]   +45ms Oni2.Exception : Recording backtraces
[DEBUG]    +0ms Oni2.Exception : Recording backtraces
[DEBUG]    +0ms Oni2.Core.Setup : Looking for setup configuration at: /Applications/Onivim2.app/Contents/Resources/../MacOS/setup.json
[ERROR]    +0ms Service.Extensions.Management : Unable to install extension: exuberant-ctags
[DEBUG]    +0ms Oni2.Core.ThreadHelper : Starting thread: 1 (Utility.waitForCondition)
[DEBUG]    +0ms Oni2.Core.ThreadHelper : Closing thread: 1 (Utility.waitForCondition)
Failed to install extension: exuberant-ctags
```

Note that installing these extensions using the in-editor extensions UI works just fine.

**Comment by bryphe** [comment]
Thanks for logging the issue, @raw-bin !

The problem is the CLI is very picky about the format, at the moment - it expects the form `publisher.name`, so:

- `oni2 --install-extension llvm-vs-code-extensions.vscode-clangd`
and
- `oni2 --install-extension chrisweeldon.exuberant-ctags`

We should improve the output in this case - we could search and provide a list of candidates, ie 'Did you mean `chrisweeldon.exuberant-ctags`', or, if there is only a single match (both of the examples you gave would only have a single match!) - just install the one we find.

**Comment by raw-bin** [comment]
Hi @bryphe !

Thanks for the response.

So I was basically trying to follow the guidance [here](https://onivim.github.io/docs/languages/c).

Turns out I wasn't following the advice very well! :)

All the same, I think the page needs to be modded a bit.

I mean: At present the page suggests using:

`oni2 --install-extension vscode-clangd`

.. but that doesn't work either for clangd. What works is your suggestion above:

`
oni2 --install-extension llvm-vs-code-extensions.vscode-clangd
`

Oddly, your suggestion for exuberant-ctags doesn't work though!

**Comment by raw-bin** [comment]
Oh and agree that a helpful prompt in the failure case would be the way to go! Thanks.

**Comment by bryphe** [comment]
Ah, just realized I had a typo for exuberant-ctags - should be:
```
oni2 --install-extension chriswheeldon.exuberant-ctags
```
(I missed the `h` previously)
