### ISSUE TITLE
Git checkout does nothing

### ISSUE THREAD

**Issue by danielo515** [onivim/oni2#2525]
OX: macosx
Onivim version: downloaded yesterday

When I open the command palette and I select git checkout from the list of options nothing happes. I was expecting it to ask me a branch to checkout to, but that didn't happened.
Not sure what else can I report, but just let me know.

**Comment by edwinclement08** [comment]
Same here, git checkout does nothing

**Comment by edwinclement08** [comment]
This is a BUG, not an enhancement
