### ISSUE TITLE
Windows 10: Incorrect output from the Clipboard

### ISSUE THREAD

**Issue by richyk1** [onivim/oni2#2526]
- OS: Windows 10
- Oni Version: Latest nightly build

The issue arises when pasting something inside Oni. It can be replicated by copying some form of code or just text with multiple lines and then CTRL+V'ing or pasting by using the Clipboard. Upon pasting, after every line there will be an empty line inserted by the editor. 

For example by copying this code:
```
:e ++ff=dos
:e ++ff=mac
:e ++ff=unix

```
The editor would paste it like this:
```
:e ++ff=dos

:e ++ff=mac

:e ++ff=unix
```

**Comment by CrossR** [comment]
I've tagged as Windows as I was not able to reproduce on Mac at least.
Another interesting point is that this is seemingly restricted to just the Ctrl-v path, not the Vim based path (`"+p`).

![image](https://user-images.githubusercontent.com/10038688/94677921-98578080-0315-11eb-822b-e56c0131f3af.png)

The first is with insert mode and Ctrl-v, the second is in normal mode with `"+p`.

**Comment by ShazzAmin** [comment]
Going to take a crack at fixing this issue.
