### ISSUE TITLE
Single Tab Mode: Cursor moves to top of file when switching between splits

### ISSUE THREAD

**Issue by baldwindavid** [onivim/oni2#2534]
When I am in single tab mode, switching between splits moves the cursor to the top of the file.

I'm on a Mac (10.15.6) with the nightly build (0.5.1546).

Added this configuration:

```
"oni.layout.singleTabMode": true,
"oni.layout.layoutTabPosition": "top"
```

Open two splits with different files. Move the cursor a few lines down in both files. Switch to one of the panes and then hit "j" (really any movement key). You should end up at the top of the file. This happens every single time I switch panes.

If I set "oni.layout.singleTabMode" to `false` the issue goes away.

**Comment by jisensee** [comment]
I logged the same issue a while ago already in #2426

**Comment by baldwindavid** [comment]
Closing this since, as mentioned by @jisensee , this issue has already been logged.
