### ISSUE TITLE
Filenames with invalid UTF-8 cause the editor to crash

### ISSUE THREAD

**Issue by fratajczak** [onivim/oni2#2539]
When using Ctrl-P to search for files, if a filename contains an invalid UTF-8 sequence, the editor crashes.

`onivim2-crash.log` says:

```
Zed_utf8.Invalid("at position 9: invalid end of UTF-8 sequence", "projects/\224"):
```
or
```
Zed_utf8.Invalid("at position 8: invalid middle of UTF-8 sequence", "projects/\128"):
```
depending on the character.

To reproduce:

* in bash, do `touch $'\200'` in a directory that will be searched by onivim
* in onivim, press Ctrl-P then any character, the editor crashes.

**Comment by bryphe** [comment]
Unfortunately I haven't been able to reproduce this - would it be possible to attach a file here that reproduces this issue?

**Comment by bryphe** [comment]
I haven't been able to reproduce this - but please feel free to open a new issue if a repro is available! :+1:
