### ISSUE TITLE
window/splits navigation rebinds not working in editor

### ISSUE THREAD

**Issue by Miziak** [onivim/oni2#2544]
Hi like in issue title rebinds not working only in editor, but they are working like a charm in file explorer and bottom pane.
To my keybindings config I added:
```json
  { "key": "<C-H>", "command": "vim.window.moveLeft", "when": "!insertMode || terminalFocus" },
  { "key": "<C-J>", "command": "vim.window.moveDown", "when": "!insertMode || terminalFocus" },
  { "key": "<C-K>", "command": "vim.window.moveUp", "when": "!insertMode || terminalFocus"  },
  { "key": "<C-L>", "command": "vim.window.moveRight", "when": "!insertMode || terminalFocus"  }
```

Tested on latest nightly build

**Comment by CrossR** [comment]
Is the behaviour any different when using `window.moveLeft/Down/Up/Right`, i.e. no `vim`? I can't quite remember the difference between the two bindings, but that seems to work for me everywhere.

**Comment by Miziak** [comment]
I found `vim.` pefixed command somewhere in repo but without it working just fine thanks @CrossR
