### ISSUE TITLE
Latest Build: Download has cursor issues, building dies on macOS.

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#2550]
I’m trying to get the latest build of oni2 after I had to wipe my full system and start over. So, I download the pre-built binaries for macOS. For it, the cursor isn’t in the right location after a line hits around the 20th character mark. It looks like a variable font is being used as the blinking box shrinks and grows as you move around. Look awful.

So, I’m trying to build from the repository like I used to. It is constantly failing as well with the following errors:

```bash
    error: include location '/usr/local/include' is unsafe for cross-compilation [-Werror,-Wpoison-system-directories]
    1 error generated.
    ninja: build stopped: subcommand failed.
```

You get this message for every file compiled. I never had that happen on my system before the wipe, but since then I’ve turned on SIP. Not sure if that is related or not. I’m not to good at the Revary build system and language yet. So, I’m not sure where to debug this one.

**Comment by raguay** [comment]
My building issue seems to be the same as `onivim2 build failure on macOS Catalina with macports #2508`. I’m on Catalina latest but I use homebrew and not macports. Therefore, I doubt it’s an issue with the installers being used. I would of posted under that one, but I just noticed it after posting (I must of overlooked it).

**Comment by bryphe** [comment]
> I’m trying to get the latest build of oni2 after I had to wipe my full system and start over

Ouch, sorry to hear you had to wipe your system! Always a pain.

I assume that you don't have any custom configuration, then? My first thought is maybe it's not finding a font, and falling back to a non-monospace font.

And I'm assuming it's Catalina?

> . So, I download the pre-built binaries for macOS. For it, the cursor isn’t in the right location after a line hits around the 20th character mark.

This is very strange! Would it be possible to see a screenshot? What sort of file is it?

I tried to repro on a retina display device (Catalina) w/ latest master - but I'm not seeing it. Might help to see a screenshot.

Another thing that might help is to see the logs - can tell us what font is being loaded and if it is falling back to a non-monospace font.

**Comment by raguay** [comment]
Your right. I forgot to install my fonts! 🤦 Looks and works much better with the right font. 

Therefore, Oni2 doesn't work well for non-monospaced fonts. It also doesn't compile on my system right now. Yes, I'm using the latest Catalina, but I don't have a retina display. I have a 2017 Macbook Air.

**Comment by raguay** [comment]
Also, where are logs kept? I've looked using Console and in the `~/.config/oni2` directories and can't find logs.

**Comment by raguay** [comment]
It might be good to tell the user that they are using a non-monospaced font and it will not work well.

**Comment by CrossR** [comment]
Logs aren't made by default, if you launch from the CLI with `oni2 -f --debug` it will log out info to the terminal. There is a bit in the user manual about installing that CLI binary, since it isn't included by default on Mac.

**Comment by bryphe** [comment]
Sounds like this is resolved! Tracking the bad-font-defaults issue here: #884
