### ISSUE TITLE
Add h, l to expand and close file tree in file explorer

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#2556]
As discussed in discord, it would be really natural to have h, and l keys to collapse and expand the file tree. Currently this is done via enter with the command `"vim.list.enter"`, but using h and l would likely be quicker and more natural for users.

Testing out the keybind suggested by ryan work fairly well actually, so perhaps this isn't needed.
This also has the benefit of being able to open the file with `l` ie when you have fully expanded the tree, which seems fairly intuitive.
Perhaps they keybinds should be added by default?
```
{ "key": "h", "command": "vim.list.enter", "when": "!textInputFocus && vimListNavigation" },
  { "key": "l", "command": "vim.list.enter", "when": "!textInputFocus && vimListNavigation" }
```

**Comment by bryphe** [comment]
Thanks @yunti @CrossR for the keybinding suggestion - I think this is a pretty reasonable default for our tree views. I'll bring it in to the default vimlist keybindings 👍
