### ISSUE TITLE
sneaking into buffer doesn't focus the buffer

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#2569]
when I focus the file explorer with sneak mode or vim window movement and then want to sneak back into a specific buffer the file explorer focuses the buffer but the focus remains on the file explorer.
I would expect the sneak mode always setting the focus to the target area.

**Comment by izik1** [comment]
Note: This seems to still be around, along with applying to say... Terminal movement to a different buffer (if they're in a split)

**Comment by kinglouie** [comment]
@bryphe this is still present, when the file explorer has keyboard focus, sneaking into an open buffer by using the sneakmark of the tab bar, it makes the buffer visible if it wasn't visible but the keyboard focus remains on the file explorer.

another inconsistency I noticed is that I can shift keyboard focus from file explorer to the active buffer by clicking into the buffer but I can not shift the keyboard focus to the file explorer by clicking on the title or other clear areas. the only way I could focus it with the mouse is by toggling it invisible and visible again.
