### ISSUE TITLE
Using "Go to definition" on a symbol of another module causes the editor to slide left

### ISSUE THREAD

**Issue by lainor** [onivim/oni2#2590]
As in the gif:
![Peek 2020-10-16 08-11](https://user-images.githubusercontent.com/828651/96219677-a3521800-0f87-11eb-96ad-bdbb60b9ef88.gif)

- Pop OS 20.04
- ElixirLS extension
- Gnome 3.36.0

**Comment by CrossR** [comment]
I think this may be more widespread than just Go to definition.

I'm able to reproduce this with the search as well, at least on opening a new buffer. Subsequent search results in the same buffer are all fine, so its possible its a calculation issue on buffer opening.

**Comment by bryphe** [comment]
Looks like I can reproduce this as well:

![2020-10-16 17 53 36](https://user-images.githubusercontent.com/13532591/96324846-9f9ab180-0fd8-11eb-8c1d-0d0618266c47.gif)

With this repro:
- Run onivim in the Onivim repro
- Open `src\Core\NodeTask.re`
- Navigate to the `withNamespace` function
- Use `gd`

**Comment by bartduisters** [comment]
The same behavior can be seen if you do `ctrl + shift + f`, search for a term. Click on any of the files in the result list.

At first I thought it was a bug, then I noticed it jumped to the definition within that file, and decided not to log.
