### ISSUE TITLE
command tab-complete in non-first path argument deletes all text past first path argument and 'tab-completes' the first argument

### ISSUE THREAD

**Issue by MichaelBelousov** [onivim/oni2#2624]
command tab-complete in non-first path argument deletes all text past first path argument and 'tab-completes' the first argument.

Try for instance the command: `:!cp /some/path /another/incomplete/pat`
then without entering the command, press tab to tab complete the second path.
the tab completion for the second path will be applied to the first path, and all text after the first path obliterated.
this means tab completion can mess up multi-path argument commands and make you have to retype them and remember
to not accidentally try completing.

**Comment by MichaelBelousov** [comment]
Put up a PR fixing it with a one character change :smile: + a test

**Comment by bryphe** [comment]
Looks like this is fixed now in #2630 - thanks @MichaelBelousov !
