### ISSUE TITLE
Bug - Keybinding: Command Palette on OSX 

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#263]
`<Cmd+Shift+P`> should open command palette on Mac. However, you need `<Control+Shift+P>`, right now. 

This will be jarring and unintuitive for users coming from other editors (ie, VSCode and Onivim 1!), so we should fix this binding to use `Cmd` on Mac instead of `Control`. We'll want to check out keybindings and make sure we're handling this correctly - I believe VSCode, for example, has faculty for saying something like `CmdOrControl` in the key bindings.

**Comment by maxdietrich** [comment]
Hey, I'd like to look into this if no one is working on this right now.

**Comment by bryphe** [comment]
That would be great @maxdietrich - thank you for the help!

**Comment by maxdietrich** [comment]
Okay, I had a look into this. And with my limited context, this looks like it needs to be addressed upstream in `reason-glfw` first. The callback defined [here](https://github.com/onivim/oni2/blob/master/src/editor/bin/Oni2.re#L160) has a `mods` argument of the type defined [here](https://github.com/bryphe/reason-glfw/blob/793be75dc868bf3834c03811501f4e1b0c4f8943/src/glfw.re#L71). There is a handling for Shift, Ctrl, Alt and Super, but not for Cmd yet. Without receiving the info whether the `Cmd` modifier is pressed, I don't see a way of fixing this Issue inside `oni2`.

**Comment by CrossR** [comment]
I think (not 100%) that super is `Cmd` on Mac. It seems to change name a bunch, but going off this old GLFW reference (https://www.glfw.org/GLFWReference278.pdf) it seems to be.

```
GLFW_KEY_LSUPER                         Left super key, WinKey, or command key
GLFW_KEY_RSUPER                         Right super key, WinKey, or command key
```

Since it can be the Win key on Windows, you'd need to make sure to gate the command to being Mac only.

**Comment by maxdietrich** [comment]
@CrossR you're right! I've got a version of this running, but there is one issue left. For now, I used `Sys.unix` to decide which Command Modifier Key to use. This would change it so that Linux users would also have to press their super key instead of Ctrl, which I personally would expect as a Linux user. I guess you have more experience in Reason and can maybe point me to a way to explicitly check for MacOS and not just unix generally? I have a hard time finding something that does that. Is there maybe a way integrating JS can solve that issue?

**Comment by CrossR** [comment]
There is this over in Revery which you should be able to use: https://github.com/revery-ui/revery/blob/3f42eb8bdbff4d9dee70b768c85c88d5468ec6ee/src/Core/Environment.re#L30-L47

You should just be able to call `Revery_Core.Environment.os` to get the OS out.

**Comment by bryphe** [comment]
Thanks for the PR, @maxdietrich (and thank you for all the help, @CrossR !) Looks like this is in now, will close it out 🎉
