### ISSUE TITLE
Is Elm as language supported? I am getting error with it.

### ISSUE THREAD

**Issue by segmentationfaulter** [onivim/oni2#2640]
I have tried installing [this elm extension](https://marketplace.visualstudio.com/items?itemName=Elmtooling.elm-ls-vscode) and it failed to load as shown in the screenshot. Is Elm as a language not supported?

![elm-error](https://user-images.githubusercontent.com/6733537/97422512-b5d93380-192f-11eb-9af2-d35976a60764.png)

**Comment by bryphe** [comment]
Hi @segmentationfaulter ,

I just installed the elm extension to double-check - and it seems to be working for me:

![elm-language](https://user-images.githubusercontent.com/13532591/97498758-f6ce4980-1929-11eb-9bf1-b5dc98c81bc5.gif)

(At least - hover via `gh`, go-to definition via `gd`, basic completion, etc).

The error message suggests that maybe the installation wasn't successful - the `request` package referenced in the error message should be bundled with the extension.

My recommendation would be to try uninstalling and reinstalling the plugin - you could run this command:
```
oni2 --uninstall-extension elmTooling.elm-ls-vscode
```

And then:
```
oni2 --install-extension elmTooling.elm-ls-vscode
```

Once it successfully installs - try opening Onivim 2 in the directory of your project. Hopefully that error should go away on reinstall.

**Comment by segmentationfaulter** [comment]
It seemed to be working after installing and uninstalling to the extent you have mentioned above, but I cannot see diagnostic messages. Can you see diagnostic messages with you? Thanks for the help though.

**Comment by bryphe** [comment]
Troubleshooted the diagnostics today - it seems the diagnostics are run on save, but we weren't sending the appropriate `textDocument/didSave` event, so diagnostics would never run. 

With that implemented, we now get diagnostics:
![image](https://user-images.githubusercontent.com/13532591/104788805-02225b80-5748-11eb-819b-2f5dc06b2b6d.png)
