### ISSUE TITLE
oni2 creates a `node_modules` folder when I open ocaml projects

### ISSUE THREAD

**Issue by mseri** [onivim/oni2#2641]
When I open any OCaml project `oni2` shows an error `ocaml 4.11.1 not supported` and around the same time creates a `node_modules` folder in the project root.

As an aside: I have `ocaml-lsp-server` installed in the opam switch, onivim should use that instead of relying on a custom one.

**Comment by bryphe** [comment]
Hi @mseri  - thanks for logging the issue and the details!

Looks like this is a bug in our bundled `reason-vscode` extension - it tries to use `esy` to find the `ocamllsp` binary, and then falls back to a bundled reason-language-server executable.

However - it should try and find `ocamllsp` via the current environment (as would be provided by OPAM), independent of `esy`.
