### ISSUE TITLE
Position of Comment symbol

### ISSUE THREAD

**Issue by tscholiadis** [onivim/oni2#2653]
I have one request and one error when I type `gcc` in normal mode, to comment out a line of code.

Firstly, I get the following error: `E685: Internal error: get_op_type()`.

Secondly, I would like to know about the positioning of the comment symbol. Currently, when I type `gcc` it adds the comment symbol at the begging of the line, instead of just near the text I'm commenting. Same thing happens for blocks, and it doesn't keep indentation.

What I'm currently getting is this:
```ruby
class MyClass
  def my_method
    (0..1).each do |item|
#       item += 1
#       item.to_s
    end
  end
end
```

What I expected it to do (and what I know [tcomment](https://github.com/tomtom/tcomment_vim) does is:
```ruby
class MyClass
  def my_method
    (0..1).each do |item|
       # item += 1
       # item.to_s
    end
  end
end
```

Any way I can achieve this now?

**Comment by bryphe** [comment]
Looks like this got logged twice! I'll use #2652 to track the leading-whitespace issue
