### ISSUE TITLE
Dart extension doesn't work at all

### ISSUE THREAD

**Issue by daaniiieel** [onivim/oni2#2677]
Autocomplete or hover doesn't work at all. On editor open, this shows up in the notifications:
![20201105173006](https://user-images.githubusercontent.com/41679054/98268210-89a35f80-1f8c-11eb-95b6-bb4f25ef112a.png)

**Comment by bryphe** [comment]
Thanks for logging the issue, @daaniiieel !

Will take a look and see what's blocking - one issue is that our version of the extension-host is a bit behind (Onivim is on 1.47.0, Dart requires 1.50.0) - been meaning to get it up-to-date - thats likely the source of the proposed-api warning.

Related issue: https://github.com/onivim/oni2/issues/2411

**Comment by bryphe** [comment]
I've updated the extension host here, and then tracking the remaining issues here: #2411 

I recommend in that issue setting `dart.previewLsp` to `true` for best results - it seems like the LSP behaves much better with Onivim than the previous diagnostics service.

I'll close this to track the remaining issues in #2411
