### ISSUE TITLE
Install as default app and running under working directory?

### ISSUE THREAD

**Issue by EternalWinter** [onivim/oni2#2721]
Any way to install it as default app? And any way to run it under working directory like as onivim v1? Without copying appimage to each working directory... Cause now when i open it every time i see my whole home directory...

**Comment by CrossR** [comment]
Installing it as a default app depends on the OS, and right now for Linux we haven't got a consistent way of doing that (I'm not 100% if/how that works with an appimage, though we should also have a flatpak/snap at some point). You can add it to your PATH though, which should let you access it from the terminal more easily: https://onivim.github.io/docs/using-onivim/command-line#linux

There is also some steps in there of how to open different folders from the command line (by using `oni2 my_folder/` or `oni2 .`. You can also swap folders inside Oni2 with `:cd`.

**Comment by EternalWinter** [comment]
Oh, thank u so much. I'll try it.

**Comment by EternalWinter** [comment]
So ur answer is helpful. If anyone else wondered this then u can use appimagelauncher, but it can not let u run oni2 from command line.
