### ISSUE TITLE
Extension search fails

### ISSUE THREAD

**Issue by iwikal** [onivim/oni2#2723]
When I search for extensions with a very common keyword (such as "theme"), results initially show up and fill the screen, but then they are quickly replaced with a message saying "There was an error searching for extensions. Please check your network connection and try again."

This was a problem in a nightly version downloaded on 2020-09-22, and still is.

**Comment by bryphe** [comment]
Thanks for logging the issue, @iwikal ! I can reproduce - there's a parsing error with one of the extensions that comes in the `"theme"` query, and causes that misleading error.
