### ISSUE TITLE
ocaml support broken

### ISSUE THREAD

**Issue by ghennequin** [onivim/oni2#2741]
Support for OCaml projects seems completely broken now. It used to work either out of the box, or with the Ocaml Platform openVSX extension from Ocaml Labs (preferred, as I have found syntax highlighting to be more accurate). Now (master branch as of yesterday) type information, jump to definition, switch to mli, etc no longer work using either. Attempting to format a file returns "Invalid range specified". With Ocaml Platform, trying to "Select a sandbox" no longer triggers a menu with the various sandbox choices.

(I am aware of https://github.com/open-vsx/publish-extensions/pull/222 but this didn't fix anything for me)

**Comment by bryphe** [comment]
> It used to work either out of the box, or with the Ocaml Platform openVSX extension from Ocaml Labs (preferred, as I have found syntax highlighting to be more accurate). Now (master branch as of yesterday) type information, jump to definition, switch to mli, etc no longer work using either. 

Hmm, indeed - it should work out of the box - Onivim 2 just needs to be able to find `ocamllsp` in the PATH, and should be good to go. 

I just tested with OPAM + https://github.com/aantron/luv repo to see - and it looks like `master` was working locally for me (I installed the language server via `opam install ocaml-lsp-server` previously, though):

![image](https://user-images.githubusercontent.com/13532591/99693768-9326d000-2a40-11eb-94c2-06aeb84e1ae3.png)

It sounds like from your description the language server isn't getting initialized at all.

Some information that might help narrow this down:
- What platform are you using (Windows / OSX / Linux)?
- Is the project open-source? In other words - is it one I can try out?
- How are you launching Onivim? From the shell, or another way?
- Are you using `OPAM`, `esy`, or another tool for managing the project?
- Is the project built locally?

The logs could also be helpful, if you're able to provide them - `oni2 --trace --log-file trace.log .` from the project folder

My guess is that Onivim is not able to find the `ocamllsp` server (provided by the `ocaml-lsp-server` OPAM package) - a quick check would be, if you're on Linux/Mac - to run `which ocamllsp` and see if it is found for your project, after setting the OPAM env.

Also need better output in Onivim to help give more details here, for sure...

> (preferred, as I have found syntax highlighting to be more accurate).

Ah, this is good to know - our bundled syntax highlighting is out-of-date. I'd like to update it, so there is a great OCaml experience out of the box.

**Comment by ghennequin** [comment]
Thanks @bryphe for the detailed answer!

- I'm using Linux (Debian)
- I've tried several of my projects but none work (e.g. https://github.com/hennequin-lab/gp)
- I'm launching onivim via an alias (oni2) pointing to the AppImage; I call `oni2 .` from the project root.
- I am using `opam`
- the project builds
- ocamllsp is in my path (`which ocamllsp` points to my opam switch)

The log file is huge :) Is there a specific part of it that you'd like to see?
Searching for `ocamllsp` in the log file doesn't return anything.

**Comment by bryphe** [comment]
Thanks for the details @ghennequin !

> The log file is huge :) Is there a specific part of it that you'd like to see?

A few things I'd look for:
- Checking if the extension host started up
- Checking if the `vscode-reason` (our bundled OCaml/Reason extension) activated
- Checking the resolution log for the binary (did it bail on finding `ocamllsp`, etc).

One other thought that comes to mind - did you build from source to create the AppImage, or download it?

**Comment by ghennequin** [comment]
The latter did the trick (updating the dependencies) -- thank you so much @bryphe , I am now back in heaven :smile:

**Comment by bryphe** [comment]
Awesome, glad it's working now! :tada:
