### ISSUE TITLE
Cmd P crashes the app

### ISSUE THREAD

**Issue by Mat-R** [onivim/oni2#2742]
The issue seems to be the same as #540 but as it is closed and it was asked to reopen it in case it is still happening, here it is.

# How to reproduce
Just after opening Onivim, if I press cmd P, Onivim crashes.
It looks like it happens when opening Onivim from Launchpad but not if I open it from the command line with the full path (/Applications/Onivim2.app/Contents/MacOS/Oni2).

# Versions
System: macOS Catalina 10.15.7.
Onivim version: 0.5.1-nightly (0.5.1672)

**Comment by bryphe** [comment]
Thanks for re-opening the issue @Mat-R ! Bummer that it is not fixed, but appreciate it being on the radar.

> It looks like it happens when opening Onivim from Launchpad but not if I open it from the command with the full path (/Applications/Onivim2.app/Contents/MacOS/Oni2).

Oh, interesting observation - that's very helpful. I can reproduce now. Looking into it-

**Comment by bryphe** [comment]
Investigating further - we're getting a an ocaml exception `Sys.error` here:
https://github.com/onivim/oni2/blob/d81680d3f96965768ae6d29da7c27b5d8aa406a2/src/Store/QuickmenuStoreConnector.re#L526
when trying to query the current working directory. 

In some cases, in MacOS, we may not have permissions for the current directory - need to handle that more gracefully (along the vein of #2711 )
