### ISSUE TITLE
Bug when cycling through suggestions of auto complete

### ISSUE THREAD

**Issue by bartduisters** [onivim/oni2#2746]
In this specific case, when having a suggestion menu and cycling through (either with `<C-n>` or down arrow), it does not cycle through all items.

Also, when one of the items has an 'auto import' suggestion, it adds one rule 'auto import' every time it gets cycled over.

With just a suggestion menu without lines that include 'auto import', it selects the first item. Then pressing down, it goes to the second item, it selects the second item and then swaps the first and the second item. It is not possible to go to suggestions after those second two, because it keeps swapping them.

![bug](https://user-images.githubusercontent.com/43420049/99886324-e2852000-2c3b-11eb-8cea-49979185b257.gif)

**Comment by Jorgee97** [comment]
@bartduisters I would suggest downloading the last nightly build and transitioning between suggestions using ctrl-n (down) and ctrl-p (up) for navigating the suggestions.

I hope this helps.

**Comment by bartduisters** [comment]
@Jorgee97 It didn't render my `<C-n>`, it occurs in both scenarios. It is the latest build.

**Comment by bryphe** [comment]
@bartduisters - just to clarify, is it the latest `nightly` or `stable` build? Would it be possible to see the output on the `:version` screen? ie:

![nightly](https://user-images.githubusercontent.com/13532591/100015126-4d457100-2d8c-11eb-906e-1eed596bc0bc.gif)

The reason I ask is it looks a lot like https://github.com/onivim/oni2/pull/2649 - which is fixed in the latest nightly, but isn't in the latest stable. Wondering if this a case not covered by https://github.com/onivim/oni2/pull/2649 , or if it is already fixed.

Also, is the repo you're using open-source? Would like to try and repro too if possible

**Comment by bartduisters** [comment]
Hey @bryphe, here a screenshot of the version screen.
![2020-11-23-1606166651_screenshot_555x467](https://user-images.githubusercontent.com/43420049/100017202-d388a400-2dda-11eb-9866-8047a783f784.jpg)

**Comment by bryphe** [comment]
Thanks @bartduisters for providing the version screen, that helps!

This build - from [`f18a1e90`](https://github.com/onivim/oni2/commit/f18a1e90) is actually a pretty old build (from October 15th - over a month old) - and is indeed before the fix https://github.com/onivim/oni2/pull/2649 was included, which came in end of October.

Just wondering - how are you getting and running the build? It looks like somehow you're stuck on an outdated nightly

>  The code itself is not my code, so I don't feel comfortable sharing that. That said, I feel this is the case for any .js/.ts file with autocompletion.

Totally understand! Might not be necessary, I believe this is likely the same issue as https://github.com/onivim/oni2/pull/2649 .  If we can get you on the latest nightly we can confirm

**Comment by bartduisters** [comment]
I think I did something wrong when moving the .AppImage then, I thought I downloaded the latest nightly (which I did), but then I did something wrong, probably.

I'll make sure to test the latest nightly asap (probably this weekend) and I'll leave feedback on this ticket. If it's solved. I'll leave feedback and close the ticket.

Thanks.

**Comment by bartduisters** [comment]
Indeed seems to be fixed with latest nightly.

**Comment by bryphe** [comment]
Excellent, thanks for confirming, @bartduisters !

And good call @Jorgee97 , you knew what the issue was right away -
