### ISSUE TITLE
Ctrl+V pastes from clipboard instead of escaping a control character

### ISSUE THREAD

**Issue by iwikal** [onivim/oni2#2747]
In vim, Ctrl+V escapes a control character to let you, for instance, insert a literal tab character into the buffer instead of indenting with spaces, or insert a literal carriage return character into the command line instead of executing the command. I use this feature semi-regularly. Is there a way to do that in oni2? Or an option to disable the Ctrl+V clipboard behavior?

**Comment by bryphe** [comment]
Thanks for logging the issue, @iwikal !

Was looking at this - our `Ctrl+V` binding for paste overrides the default `Ctrl+V` behavior. Vim actually provides an alternate keybinding - `Ctrl+Q` - which does work in insert mode (and fixing it in command-line mode here: https://github.com/onivim/libvim/pull/250)

So a few things I'm looking at:
- On Mac, we shouldn't bind `Ctrl+V` by default anyway 
- To get this functionality back, with the libvim fix, it should be enough to add this to the `configuration.json` file:
```
"experimental.viml": [
  "noremap! <C-v> <C-q>",  
]
```

However - there's one more blocking bug I'm looking at. In the insert-literal state, some other keybindings are interfering, so I need to fix a bug where insert-literal isn't taking precedence over keybindings. 

Working on some fixes in:
- https://github.com/onivim/libvim/pull/250
- https://github.com/onivim/oni2/pull/2758
