### ISSUE TITLE
Smartcase

### ISSUE THREAD

**Issue by iwikal** [onivim/oni2#2749]
I can't find any way to turn on smartcase for searching. Is this just missing as of yet? `:set smartcase` doesn't work.

**Comment by iwikal** [comment]
I'm a fool. Forgot to enable ignorecase.

**Comment by CrossR** [comment]
Make sure to stick both in your `experimental.viml` config if you want them auto applied! I have both and haven't noticed any issues. https://onivim.github.io/docs/configuration/settings#experimental
