### ISSUE TITLE
:tabnew does not open empty tab

### ISSUE THREAD

**Issue by mabuchner** [onivim/oni2#2753]
When using the `:tabnew` command in Vim, a new tab with an empty (unnamed) buffer will get opened.

Trying the same in Oni2 (with layout tabs) will open a new tab with the previously active buffer instead of an empty buffer.

**Comment by bryphe** [comment]
Thanks for logging the issue @mabuchner !

Looks like we're not handling any variant of the `:new` command correctly - similar issue in #1455 (for `:vnew` and `:new`). Fix should address both this and #1455
