### ISSUE TITLE
Building from source: fatal error: choices.h: No such file or directory

### ISSUE THREAD

**Issue by carsonbaker** [onivim/oni2#2782]
This is current master branch, building on Fedora 33.

```
carson ~/oni2 (master)> esy install
info install 0.6.7 (using package.json)
info fetching: done
info installing: done

carson ~/oni2 (master)> esy bootstrap
info building reason-fzy@github:CrossR/reason-fzy#7339d4e@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: reason-fzy@github:CrossR/reason-fzy#7339d4e
    # esy-build-package: pwd: /home/carson/.esy/3/b/reason_fzy-ef926d27
    # esy-build-package: running: 'refmterr' 'dune' 'build' '-p' 'Fzy'
        discover src/c_flags.sexp,src/cxx_flags.sexp,src/flags.sexp
    /home/carson/.esy/3/b/esy_fzy-bc4c509a/src
    /home/carson/.esy/3/b/esy_fzy-bc4c509a
          ocamlc src/bindings.o (exit 2)
    (cd _build/default/src && /home/carson/.esy/3/i/ocaml-4.10.0-e4568572/bin/ocamlc.opt -g -ccopt -I -ccopt '/home/carson/.esy/3/b/esy_fzy-bc4c509a/src' -ccopt -I -ccopt '/home/carson/.esy/3/b/esy_fzy-bc4c509a' -ccopt -g -o bindings.o bindings.c)
    bindings.c:21:10: fatal error: choices.h: No such file or directory
       21 | #include <choices.h>
          |          ^~~~~~~~~~~
    compilation terminated.
    error: command failed: 'refmterr' 'dune' 'build' '-p' 'Fzy' (exited with 1)
    esy-build-package: exiting with errors above...

  building reason-fzy@github:CrossR/reason-fzy#7339d4e
esy: exiting due to errors above
```

**Comment by bilal3ilogic** [comment]
have same issue building from source. 

`./../include/core/../private/SkWeakRefCnt.h:63:5: note: overridden virtual function is here
        ~SkWeakRefCnt() override {
        ^
    2 errors generated.
    [11/1206] compile ../../src/gpu/GrPath.cpp
    FAILED: obj/src/gpu/gpu.GrPath.o
    clang++ -MMD -MF obj/src/gpu/gpu.GrPath.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ENABLE_DISCRETE_GPU -DGR_TEST_UTILS=1 -DSKIA_IMPLEMENTATION=1 -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -g -Werror -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-extra-semi-stmt -Weverything -Wno-unknown-warning-option -Wno-anon-enum-enum-conversion -Wno-sizeof-array-div -Wno-nonportable-include-path -Wno-nonportable-system-include-path -Wno-cast-align -Wno-cast-qual -Wno-conversion -Wno-disabled-macro-expansion -Wno-documentation -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-format-nonliteral -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-pedantic -Wno-reserved-id-macro -Wno-shadow -Wno-shift-sign-overflow -Wno-signed-enum-bitfield -Wno-switch-enum -Wno-undef -Wno-unreachable-code -Wno-unreachable-code-break -Wno-unreachable-code-return -Wno-unused-macros -Wno-unused-member-function -Wno-unused-template -Wno-zero-as-null-pointer-constant -Wno-bad-function-cast -Wno-covered-switch-default -Wno-deprecated -Wno-missing-noreturn -Wno-old-style-cast -Wno-padded -Wno-newline-eof -Wno-implicit-fallthrough -Wno-unused-parameter -I/home/bilal/.esy/3____________________________________________________________________/i/esy_libjpeg_turbo-e4385a3b/include -Wno-poison-system-directories -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wno-noexcept-type -Wno-abstract-vbase-init -Wno-weak-vtables -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-undefined-func-template -c ../../src/gpu/GrPath.cpp -o obj/src/gpu/gpu.GrPath.o
    In file included from ../../src/gpu/GrPath.cpp:8:
    In file included from ../../src/gpu/GrPath.h:12:
    In file included from ../../src/gpu/GrPathRendering.h:12:
    In file included from ../../src/gpu/GrPipeline.h:12:
    In file included from ../../src/gpu/GrFragmentProcessor.h:11:
    In file included from ../../src/gpu/GrProcessor.h:15:
    In file included from ../../src/gpu/GrProcessorUnitTest.h:15:
    In file included from ../../include/android/../private/GrTextureProxy.h:12:
    ../../include/private/GrSurfaceProxy.h:399:13: error: '~GrSurfaceProxy' overrides a destructor but is not marked 'override' [-Werror,-Wsuggest-destructor-override]
        virtual ~GrSurfaceProxy();
                ^
    ../../include/private/GrSurfaceProxy.h:149:13: note: overridden virtual function is here
        virtual ~GrIORefProxy() {
                ^
    In file included from ../../src/gpu/GrPath.cpp:8:
    In file included from ../../src/gpu/GrPath.h:12:
    In file included from ../../src/gpu/GrPathRendering.h:12:
    In file included from ../../src/gpu/GrPipeline.h:12:
    In file included from ../../src/gpu/GrFragmentProcessor.h:11:
    In file included from ../../src/gpu/GrProcessor.h:19:
    In file included from ../../src/gpu/GrSurfaceProxyPriv.h:13:
    In file included from ../../src/gpu/GrResourceProvider.h:15:
    In file included from ../../src/core/SkScalerContext.h:19:
    ../../include/core/SkTypeface.h:304:13: error: '~SkTypeface' overrides a destructor but is not marked 'override' [-Werror,-Wsuggest-destructor-override]
        virtual ~SkTypeface();
                ^
    ../../include/core/../private/SkWeakRefCnt.h:63:5: note: overridden virtual function is here
        ~SkWeakRefCnt() override {
        ^
    In file included from ../../src/gpu/GrPath.cpp:8:
    In file included from ../../src/gpu/GrPath.h:12:
    In file included from ../../src/gpu/GrPathRendering.h:12:
    In file included from ../../src/gpu/GrPipeline.h:16:
    In file included from ../../src/gpu/GrProgramDesc.h:15:
    ../../src/gpu/glsl/GrGLSLFragmentShaderBuilder.h:25:13: error: '~GrGLSLFragmentBuilder' overrides a destructor but is not marked 'override' [-Werror,-Wsuggest-destructor-override]
        virtual ~GrGLSLFragmentBuilder() {}
                ^
    ../../src/gpu/glsl/GrGLSLShaderBuilder.h:26:13: note: overridden virtual function is here
        virtual ~GrGLSLShaderBuilder() {}
                ^
    3 errors generated.
    [12/1206] compile ../../src/opts/SkOpts_avx.cpp
    FAILED: obj/src/opts/avx.SkOpts_avx.o
    clang++ -MMD -MF obj/src/opts/avx.SkOpts_avx.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ENABLE_DISCRETE_GPU -DGR_TEST_UTILS=1 -DSKIA_IMPLEMENTATION=1 -I../../include/android -I../../include/c -I../../include/codec -I../../include/config -I../../include/core -I../../include/effects -I../../include/encode -I../../include/gpu -I../../include/atlastext -I../../include/pathops -I../../include/ports -I../../include/svg -I../../include/utils -I../../include/utils/mac -I../../include/private -I../../src/c -I../../src/codec -I../../src/core -I../../src/effects -I../../src/fonts -I../../src/image -I../../src/images -I../../src/lazy -I../../src/opts -I../../src/pathops -I../../src/pdf -I../../src/ports -I../../src/sfnt -I../../src/shaders -I../../src/shaders/gradients -I../../src/sksl -I../../src/utils -I../../src/utils/win -I../../src/xml -I../../third_party/gif -I../../src/gpu -mavx -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -g -Werror -Wall -Wextra -Winit-self -Wpointer-arith -Wsign-compare -Wvla -Wno-deprecated-declarations -Wno-maybe-uninitialized -Wno-extra-semi-stmt -Weverything -Wno-unknown-warning-option -Wno-anon-enum-enum-conversion -Wno-sizeof-array-div -Wno-nonportable-include-path -Wno-nonportable-system-include-path -Wno-cast-align -Wno-cast-qual -Wno-conversion -Wno-disabled-macro-expansion -Wno-documentation -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-format-nonliteral -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-pedantic -Wno-reserved-id-macro -Wno-shadow -Wno-shift-sign-overflow -Wno-signed-enum-bitfield -Wno-switch-enum -Wno-undef -Wno-unreachable-code -Wno-unreachable-code-break -Wno-unreachable-code-return -Wno-unused-macros -Wno-unused-member-function -Wno-unused-template -Wno-zero-as-null-pointer-constant -Wno-bad-function-cast -Wno-covered-switch-default -Wno-deprecated -Wno-missing-noreturn -Wno-old-style-cast -Wno-padded -Wno-newline-eof -Wno-implicit-fallthrough -Wno-unused-parameter -I/home/bilal/.esy/3____________________________________________________________________/i/esy_libjpeg_turbo-e4385a3b/include -Wno-poison-system-directories -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wno-noexcept-type -Wno-abstract-vbase-init -Wno-weak-vtables -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-undefined-func-template -c ../../src/opts/SkOpts_avx.cpp -o obj/src/opts/avx.SkOpts_avx.o
    In file included from ../../src/opts/SkOpts_avx.cpp:11:
    ../../src/opts/SkRasterPipeline_opts.h:1688:15: error: AVX vector return of type 'V<unsigned long>' (vector of 8 'unsigned long' values) without 'avx512f' enabled changes the ABI [-Werror,-Wpsabi]
        auto px = gather(ptr, ix);
                  ^
    1 error generated.
    ninja: build stopped: subcommand failed.
    error: command failed: 'bash' './esy/build.sh' 'linux' '/home/bilal/.esy/3____________________________________________________________________/i/esy_libjpeg_turbo-e4385a3b' (exited with 1)
    esy-build-package: exiting with errors above...

  building esy-skia@github:revery-ui/esy-skia#60e0260
esy: exiting due to errors above`

**Comment by CrossR** [comment]
Looks like a separate issue, as the first is having trouble compiling `esy-fzy`, not `esy-skia`.

I've built Oni2 recently in Fedora 32, but not tried 33. I'm surprised its failing to find the header file for `fzy` though... I'll try it out on 33 tonight and see.

**Comment by CrossR** [comment]
I was able to build fine on Fedora 33, so not 100% what the error is with `choices` being missing.

The simplest thing to try is removing the `_esy` folder in the Oni2 folder (the local cache, should be quick to build still) or `~/.esy` (top level cache, slow rebuild). Otherwise, there must be I'm missing here, since it looks like some files haven't been copied over as expected.
