### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by dcalhoun** [onivim/oni2#2795]
I am setting up a new MacBook and while attempting to install Oni2 extensions, they all fail no matter which approach. I've tried installing `sdras.night-owl`, `esbenp.prettier-vscode`, and a vsx file for `rescript-vscode`.

## Steps to Reproduce

1. Open Extensions sidebar.
1. Search for "night."
1. Click "Install" for Night Owl theme.

\- OR -

1. Launch Terminal.
1. `oni2 --install-extension sdras.night-owl`

## Expected Result

Extension installs successfully.

## Actual Result

Extension fails to install.

<details>

<summary>Screenshots</summary>

<img width="912" alt="Failed UI extension install 1" src="https://user-images.githubusercontent.com/438664/101026704-d6069e80-353c-11eb-9dc2-fd20c7d7677a.png">
<img width="912" alt="Failed UI extension install 2" src="https://user-images.githubusercontent.com/438664/101026706-d7d06200-353c-11eb-85c5-df07f7897ab7.png">
<img width="917" alt="Failed CLI extension install" src="https://user-images.githubusercontent.com/438664/101026710-dacb5280-353c-11eb-9646-dc023216bb53.png">

</details>

## Environment

- macOS 11.0.1
- Onivim2 0.5.1698

**Comment by bryphe** [comment]
Thanks for the issue and logs, @dcalhoun !

Just fixed this in https://github.com/onivim/oni2/pull/2786 - it's available in the latest nightly build now.
