### ISSUE TITLE
Ctrl+Shift+v Not Working In Terminal

### ISSUE THREAD

**Issue by RilDev** [onivim/oni2#2805]
Good day,

I would like to `copy/paste` code in my Onivim2 terminal. I copy the test to my clipboard and then I try to paste it in terminal. But, so far:

- `Ctrl+v` doesn't work.
- `Ctrl+Shift+v` doesn't work.
- Going to normal mode with `Ctrl+\,n` and then pasting it from the registry `",+,p` and `",*,p` doesn't work.

Is there an other way I am not aware of to do this thing?

Thank you!

**Comment by bryphe** [comment]
Thanks for all the great issues @RilDev , and the details here!

Indeed, we're missing the plumbing for paste here. Starting to investigate in #2807

**Comment by RilDev** [comment]
You are welcome! I really like Onivim2, it's like an elegant mix between what Visual Studio Code will never become and what Vim can never be.

Thank you for doing this project and for your reactivity!

**Comment by RilDev** [comment]
That was quick, thank you!

![oni2-fix-no-pasting-in-terminal](https://user-images.githubusercontent.com/13135150/101613129-ab6c8800-3a0b-11eb-8067-9eeaaf1a3eb1.gif)
