### ISSUE TITLE
Relative line numbers does not appear to work from config

### ISSUE THREAD

**Issue by benwainwright** [onivim/oni2#2815]
Hi there!

So it would appear that in the config

```json
{
   "editor.lineNumbers": "relative"
}
```
 doesn't work. I can *get* relative numbers, but only by using the `set relativenumber` ex command. This is not a big deal because it turns out I can do this:

```json
{
  "experimental.viml": ["set relativenumber"],
}
```

... but the setting itself is definitely broken.

**Comment by bryphe** [comment]
Hi @benwainwright ,

Thanks for the issue!

I'm having trouble reproducing - at least with my simple config, the `"relative"` setting seems to work:

![2020-12-11 12 05 29](https://user-images.githubusercontent.com/13532591/101949974-4ea6d400-3ba9-11eb-96da-e9f1dd63a748.gif)

Would it be possible to see the full configuration so I can reproduce?

One possibility off the top of my head if is if there is a combination like:
```
{
   "editor.lineNumbers": "relative",
  ...
  "experimental.viml": [
    "set number"
  ]
}
```

In a case like that - we defer to Vim's setting (number, but no relative number), so it would override the `editor.lineNumbers` configuration. I wonder if something like that is occurring, or perhaps another bug / interaction between settings.

**Comment by benwainwright** [comment]
@bryphe My bad.

I just looked again; I had `editor.lineNumbers` specified *twice* in my config.

**Comment by bryphe** [comment]
Ah, nice catch @benwainwright, thanks for the update!

We should probably show an error in that case, to make it more obvious (I've made that mistake several times too..)

**Comment by benwainwright** [comment]
> We should probably show an error in that case, to make it more obvious

A general error if a config key is specified twice would be really useful, yes!
