### ISSUE TITLE
Oni2 not usable when built from source.

### ISSUE THREAD

**Issue by benwainwright** [onivim/oni2#2816]
Hey there!

So I wanted to have a go at contributing, except there is a bit of a snag...

You may remember that I opened https://github.com/onivim/oni2/issues/1185 a while back, and the issue was resolved. Well, it seems to be back, but oddly enough _only when I build from source_.

I've downloaded the latest nightly dmg from the website and that works fine. I've also confirmed it appears to be the same issue by unplugging my external monitor and trying the build from source version, and sure enough, when I do that, it works fine.

🤦

**Comment by bryphe** [comment]
Hey @benwainwright ! Awesome, can always use extra help 😄 

> Well, it seems to be back, but oddly enough only when I build from source.

Interesting - part of the fix for this was to add a `plist` entry for the [NSSupportsAutomaticGraphicsSwitching](https://developer.apple.com/documentation/bundleresources/information_property_list/nssupportsautomaticgraphicsswitching) property (https://github.com/onivim/oni2/pull/2278)

For development builds, we're not creating a plist at all (we're only generating one on release here: https://github.com/onivim/oni2/blob/9f3c85e5ee6b28ae59c46d9813fc913011c65dd3/scripts/release.js#L146) - so it wouldn't have that setting. I think we may need an `Info.plist` in development builds too

**Comment by benwainwright** [comment]
> I think we may need an Info.plist in development builds too

Ok, well maybe that can be my first contribution. I'm a web/react developer by day and completely new to the reason/ocaml/dune/esy domain, so I'll be slow moving. But I've done some digging and read some docs and some of your code and I think I understand the following:

* When you run `esy build` the output is the raw binaries without any packaging
* Esy run simply runs the binary (from inside the `esy` sandbox) itself
* `esy "@release" create` essentially packages together the actual MacOS app bundle

So if I understand this correctly, the only way to include an `Info.plist` in development builds would be to create an app bundle for development builds. This would either be done by adding an execution of another node script similar to `release.js` onto the end of the `build` invocation here: 

https://github.com/onivim/oni2/blob/da63813b905d81a49d57e85a16863b4a14aaf2d7/package.json#L7

or a separate script that people need to execute themselves, similar to the `create` script in `release.json`.

**Comment by bryphe** [comment]
> I'm a web/react developer by day and completely new to the reason/ocaml/dune/esy domain, so I'll be slow moving. But

Most of the contributors have a web background - that's a perfect skillset. Revery / Reason is like React taken to the extreme :sunglasses:  But the build / tool chain is quite different for sure!

>  So if I understand this correctly, the only way to include an Info.plist in development builds would be to create an app bundle for development builds

Actually, @zbaylin discovered we could just put an `Info.plist` alongside the executable to have some properties picked up (as part of exploring notifications on OSX): https://github.com/revery-ui/revery/pull/672 Could potentially easier than having to add an app bundle.

I'll put together a prototype branch for that - we can give it a shot and see if that addresses the issue

**Comment by benwainwright** [comment]
Great thanks!

**Comment by bryphe** [comment]
Giving it a shot here: https://github.com/onivim/oni2/pull/2822

If you'd be up for trying it out, that would be a huge help:

- `git fetch origin`
- `git checkout experiment/build/2816/development-plist`

...we'll see if it fixes the issue :crossed_fingers:

**Comment by bryphe** [comment]
I think it's good to have it in either case - it means the development builds are closer to what we ship, anyway

**Comment by benwainwright** [comment]
@bryphe Yup, that did the trick!

**Comment by bryphe** [comment]
Awesome! Thanks @benwainwright
