### ISSUE TITLE
Formatting ReScript file fails with error

### ISSUE THREAD

**Issue by dcalhoun** [onivim/oni2#2820]
When attempting to format a ReScript file, Onivim fails to format the file and throws an error.

## Steps to Reproduce

1. Download and install [`rescript-vscode` extension](https://github.com/rescript-lang/rescript-vscode/releases) vsix file.
1. Launch Onivim 2.
1. `:enew`
1. `:w test.res`
1. <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
1. Type "format" and select "Formatting: Format Document."
1. `:enew`
1. Switch tab back to first file.
1. <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>
1. Type "format" and select "Formatting: Format Document."

## Expected Result

The ReScript file (`res`) is formatted. No errors are displayed.

## Actual Result

The ReScript file (`res`) is not formatted. Errors are displayed.

The first format call produces: `Invalid range specified`.

The second format call produces: `ParseFailedException("Expected null or:\n while decoding a list:\n element 0:\n in field \"range\":\n in field \"endColumn\":\n Expected an int, but got 1.7976931248623157e+308\n"`.

<img width="1904" alt="Screen Shot 2020-12-11 at 15 58 15" src="https://user-images.githubusercontent.com/438664/101958814-b53bea00-3bc9-11eb-9841-460578a3f915.png">

## Environment

- macOS 11.0.1
- Onivim 2 0.5.1-nightly 0.5.1718

**Comment by bryphe** [comment]
Thanks @dcalhoun for all the details and the screenshot. Very helpful!

I pushed up a fix for the parse exception - #2825 - we weren't handling some types of numerical values correctly in our JSON parsing for ranges.

I'm still seeing some quirks though with the ReScript formatter, even after that - possibly related to / similar issue as: https://github.com/onivim/oni2/issues/2196

**Comment by dcalhoun** [comment]
@bryphe I didn't necessarily test this again, but figured I'd close this based upon your comments/work within #3233. Feel free to reopen if I am mistaken.

**Comment by bryphe** [comment]
Thanks @dcalhoun for closing! Indeed, I did a quick test w/ #3233 - and I wasn't able to reproduce the issue anymore. 

Of course, keep me posted if you hit any other issues with formatting :+1:
