### ISSUE TITLE
Search box is a regex by default

### ISSUE THREAD

**Issue by benwainwright** [onivim/oni2#2821]
I tried to search for `(public_names` just now and it got zero results until I removed the open paren. This was really confusing for me until I realised its probably a regex.

Having the search feature use a regex by default is going to be confusing to newcomers to the editor; I'd expect it to be a simple string search, with regex search something you are able to enable in your preferences.

**Comment by bryphe** [comment]
Thanks for logging the issue @benwainwright !

> Having the search feature use a regex by default is going to be confusing to newcomers to the editor

I agree, there's no indication that the search would be a regex. It'd be great to have a regex option down the road (which would be more explicit - surfaced via a button or UI element - and need to be opted-in / turned on like in VSCode). Until we have that - should just be a simple string search.

**Comment by bryphe** [comment]
I'll use this to track changing the default to simple string search, and #2599 to track adding the regex option.
