### ISSUE TITLE
Feature request - ex command history

### ISSUE THREAD

**Issue by benwainwright** [onivim/oni2#2829]
From https://github.com/onivim/oni2/issues/1914#issue-636635397

Users of vim will be expecting `:<up>` to cycle through a history of previously executed `ex` commands.

**Comment by bryphe** [comment]
Thanks @benwainwright , definitely agree we need this!

We have a few related issues:
- #494 (command history - potential dup)
- #969 (search history)

**Comment by benwainwright** [comment]
Ah I think you mean #464. I'm happy to close this one and subscribe to that one 👍🏻

**Comment by bryphe** [comment]
Oops, good catch! #464 is the right one :+1:
