### ISSUE TITLE
Continuous render not working on resize

### ISSUE THREAD

**Issue by benwainwright** [onivim/oni2#2830]
So in https://github.com/onivim/oni2/issues/1914#issue-636635397 I bought up the issue of resize rendering:

> The way that resizes are rendered (the image is scaled without maintaining the aspect ratio until you release the mouse, at which point the layout appears to be recalculated) is ugly.

@bryphe in reply you referenced https://github.com/revery-ui/reason-sdl2/pull/57 which appears to have been merged. Has this change been brought into the Oni2 codebase yet? Because for me the rendering behaviour appears identical to how it was.

**Comment by bryphe** [comment]
Thanks for splitting this out, @benwainwright ! Maybe a dup of #1318 ?

> in reply you referenced revery-ui/reason-sdl2#57 which appears to have been merged. 

Good question... we did attempt to fix in that PR (@zbaylin did an awesome investigation!)

Unfortunately, we had to back it out (https://github.com/revery-ui/reason-sdl2/commit/4b79da99a9905dae9d36e43f3bcf753482cb59b4) - it was causing a native crash in certain instances, like maximizing or restoring the window.

The crash is the same underlying issue @zbaylin is asking about here: https://discuss.ocaml.org/t/determining-if-the-runtime-system-is-currently-acquired-from-c/6934

The 'resize' code can potentially be called on either the main thread, or a separate thread, and depending on how it's called, we may or may not have an handle on the OCaml runtime lock - which causes problems when we call back into ocaml code to handle the resize. It's still kind of an unsolved problem for us, and affects interop with multiple APIs in OSX.
