### ISSUE TITLE
Remapping `jj` to `vim.esc` doesn't allow you to write any `j`s while in InsertMode

### ISSUE THREAD

**Issue by kingedward35** [onivim/oni2#2850]
I just noticed recently that when I enter insertmode and then try to type a `j` character, nothing happens. If I hit space or some other key, then the `j` will show up. However if I press `j` and then wait a few seconds and press `j` again, I am then put back in normal mode. I don't remember this being an issue before. The same thing happens if instead of `jj` as a `vim.esc` mapping I use `jk`. Here is what my keybinding looks like: `  { "key": "jj", "command": "vim.esc", "when": "insertMode" },
`
Thanks.

**Comment by bryphe** [comment]
Thanks for logging the issue @kingedward35 !

Indeed, it seems we're missing the 'timeout' behavior - we're waiting indefinitely for the next character in the chord, instead of accepting the first `j` after a timeout period.

**Comment by kingedward35** [comment]
Are there any updates on when this might be fixed? I don't mean to rush you, but not being able to use my normal vim keybindings makes using this as a daily driver very difficult. Once again not trying to rush just looking to see if there might be a timeline when this might get taken care of. Thanks.

**Comment by bryphe** [comment]
Looks like it shouldn't be too hard to add this - working on it in #3102 , which adds a timeout behavior. The main thing we're still missing after that is a visual indication when there are pending keys that will timeout - but hopefully this unblocks the functionality for you @KingEdwardI
