### ISSUE TITLE
Download without paying

### ISSUE THREAD

**Issue by Makurisan** [onivim/oni2#2851]
Where can I download a version for Windows 10 without paying?
I dont like to pay for something which I havent tested.

**Comment by CrossR** [comment]
Right now there isn't a public download (its on the timeline on the Website for when we leave beta).
However, the source code is available here, and we have the build instructions here: https://onivim.github.io/docs/for-developers/building

**Comment by bryphe** [comment]
Hi @Makurisan ,

No trial build yet - see the FAQ entry [Is there a trial version](https://onivim.github.io/docs/other/faq#is-there-a-trial-version). 

Building from source as @CrossR suggested is the best way to try it out in the meantime :+1:
