### ISSUE TITLE
In macos, open file or folder dragging over icon

### ISSUE THREAD

**Issue by mdnmdn** [onivim/oni2#2855]
In macos, dropping a file or folder into the Oni2 dock doesn't open the contents

## Steps to Reproduce
* drag a file (or folder) from an finder window
* drop the file over the oni2 dock icon

## Expected result
* oni2 opens the file or the folder for edit

## Actual result
* Can't drop the file

## Environment
* macos 10.15.1
* oni2   0.5.2-nightly (0.5.1733)

**Comment by bryphe** [comment]
Thanks @mdnmdn for logging the issue! Can reproduce - looking at a fix in #2865
