### ISSUE TITLE
Git diff doesn't show in the sign column

### ISSUE THREAD

**Issue by amahmod** [onivim/oni2#2857]
File preview in VSCode
![2020-12-18_09-38](https://user-images.githubusercontent.com/22317231/102572007-2f61f680-4115-11eb-896c-120f4d92aa53.png)

File preview in oni2
![2020-12-18_09-41](https://user-images.githubusercontent.com/22317231/102572051-499bd480-4115-11eb-8a52-ae118a8716d4.png)

OS - Arch Linux (64)
WM: BSPWM
Oni Version: 0.5.9-nightly | 34bc87b6

**Comment by amahmod** [comment]
My configuration 

```json
{
  "workbench.colorTheme": "One Dark Pro Bold",
  "editor.detectIndentation": true,
  "editor.fontFamily": "Fira Code",
  "editor.fontSize": 16,
  "editor.fontSmoothing": "antialiased",
  "editor.largeFileOptimizations": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.lineNumbers": "relative",
  "editor.indentSize": 2,
  "editor.insertSpaces": true,
  "editor.matchBrackets": true,
  "editor.minimap.enabled": true,
  "editor.minimap.maxColumn": 120,
  "editor.minimap.showSlider": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "none",
  "editor.rulers": [],
  "editor.tabSize": 2,
  "editor.zenMode.hideTabs": true,
  "editor.zenMode.singleFile": true,
  "files.exclude": [ "_esy", "node_modules", ".git" ],
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.iconTheme": "vs-seti",
  "workbench.sideBar.location": "left",
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true,
  "workbench.tree.indent": 2,
  "vim.leader": "<space>",
  "vim.useSystemClipboard": [ "yank" ],
  "vim.highlightedyank.enable": true,
  "vim.highlightedyank.color": "#FF00FFFF",
  "go.useLanguageServer": true,
  "git.suggestSmartCommit": false
}
```

**Comment by bryphe** [comment]
Thanks for logging the issue, @amahmod !

Can reproduce this as well editing a file in the Onivim repo.

Looks like this is a regression from upgrading the git extension - it used to be that the git extension would give us a file path to query the original file content for us to diff, but now it is implementing a virtual file system. Need to update our extension host integration to handle talking to an extension-provided virtual file s ystem.
