### ISSUE TITLE
Copying to clipboard not working

### ISSUE THREAD

**Issue by Murtrag** [onivim/oni2#2861]
I have tried `control + c` `windows + c` `fn + c` `ctrl + shift + c` `windows + shift + c` and nothing works.
The only way I can copy something out of editor is `"+y` but this is not my favorite way to do that.
I tried to bind it manually
 ```
[
{ "key": "<C-S-C>", "command": "editor.action.clipboardCopyAction", "when": "visualMode" }
]
```
But not working or I do it incorrectly.

```
$ uname -r
5.6.13-100.fc30.x86_64
```
My keyboard settings:
![image](https://user-images.githubusercontent.com/19934843/102684125-356bdc00-41d6-11eb-8185-59127145e66b.png)

**Comment by kinglouie** [comment]
After all this is a vim based editor so have you checked out or modified the vim setting for the system clipboard `vim.useSystemClipboard `?

**Comment by Murtrag** [comment]
No I didn't but I have just set this property to true and it works.
Thank you!
