### ISSUE TITLE
Bracket pair colorizer 2 not working

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#2863]
I love to use the following extension in VSC: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

However it seems to not work in onivim 2; any idea why / some missing APIs or other?

**Comment by jisensee** [comment]
Would also like to have that working. Maybe even built into onvim itself.

**Comment by bryphe** [comment]
Ah, might be a dup of https://github.com/onivim/oni2/issues/2491

> any idea why / some missing APIs or other?

Yep, indeed a couple missing APIs - the bracket-pair-colorizer extension tries to find `vscode-textmate` via vscode internals, and past that, it uses the text-decoration API which is not yet wired up to Onivim

**Comment by jerabaul29** [comment]
Yes it is a dupe - closing in favour of the initial post.
