### ISSUE TITLE
cannot install exuberant-ctag following the instructions

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#2872]
I am on Ubuntu 18.04

I try to follow: https://onivim.github.io/docs/languages/c

But I get:

```
~$ oni2 --install-extension exuberant-ctags
Failed to install extension: exuberant-ctags

Did you mean one of these extensions?
- chriswheeldon.exuberant-ctags
- henriiik.vscode-perl
~$ oni2 --version
Onivim 2 (0.5.9-nightly)
```

**Comment by jerabaul29** [comment]
Seems to be a quite general problem, as:

```
~$ oni2 --install-extension vscode-clangd
Failed to install extension: vscode-clangd

Did you mean one of these extensions?
- llvm-vs-code-extensions.vscode-clangd
- notskm.clang-tidy
- mitaki28.vscode-clang
- a5huynh.vscode-ron
- jamestiotio.compstruct-vscode
- samplavigne.p5-vscode
- paiqo.databricks-vscode
- jcanero.hoogle-vscode
- macabeus.vscode-fluent
- deerawan.vscode-faker
- vscode-icons-team.vscode-icons
- evilz.vscode-reveal
- bajdzis.vscode-database
- trixnz.vscode-lua
- bung87.vscode-gemfile
- zxh404.vscode-proto3
- wingrunr21.vscode-ruby
- GitLab.gitlab-workflow
```

**Comment by CrossR** [comment]
I believe this is the same issue that was previously fixed in https://github.com/onivim/oni2/pull/2786 ?

I'm able to reproduce on a few day old nightly though, so perhaps they've update their API again?

**Comment by bryphe** [comment]
Ah, the documentation is out-of-date - we require the `publisher.extension` - so it should be corrected to:

- `chriswheeldon.exuberant-ctags`
- `llvm-vs-code-extensions.vscode-clangd`

**Comment by bryphe** [comment]
I had also thought about improving the CLI, such that `--install-extension vscode-clangd` would install the best matching plugin - but given that some namespaces are public, I wanted the user to explicitly specify the namespace/publisher, too. 

Perhaps the CLI, though, could be improved with a better message?

**Comment by jerabaul29** [comment]
You are the best placed for deciding what the best fix is, as long as the doc works I am happy :)

**Comment by jerabaul29** [comment]
(may be worth double checking if recommended plugins for other languages should be updated similarly? :) ).

**Comment by bryphe** [comment]
Updated docs in #2874 !

> (may be worth double checking if recommended plugins for other languages should be updated similarly? :) ).

For sure 😄 Took a pass - the other languages with explicit install ids have a publisher/namespace 👍
