### ISSUE TITLE
QuickOpen: Show a loading / spinner experierence while rg is running

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#289]
__Issue:__ I'm trying to get use Onivim 2 as my daily editor - it's getting closer and closer! But I'm having some issues with the fuzzy find experience. 

In some cases, I'll type a filter that should match - but there end up being no matches. See the 'Actual' gif below.

I wonder if it is the case that `rg.exe` is still running, and collecting files, and it just hasn't reached the folder I'm looking for, yet? If I wait - eventually it will become available.

__Repro:__
- Open Onivim 2 in the oni2 repo
- Open QuickOpen via `<C-p>`
- Type `srceditorCoreTypes`

__Actual Result:__
![quick-open-file-find](https://user-images.githubusercontent.com/13532591/56903809-e5189700-6a51-11e9-859c-20d1dcc326ab.gif)

Note that, in this case, it seems several matching entries are shown that shouldn't necessarily be there (like the files at the root).

__Expected Result:__
![image](https://user-images.githubusercontent.com/13532591/56903798-d7631180-6a51-11e9-85ec-4cedd17d1886.png)

**Comment by somebody1234** [comment]
Is there a reliable way to test this? Seems like it's instant for me, so maybe it'd be good to have a slow testcase/maybe there's a cache somewhere I have to clear?

**Comment by CrossR** [comment]
I have certainly noticed in my usage of the editor that the first search seems to be entirely different to the second search.

That is, I can do `indentLinRen` and get nothing related at first launch of Oni2, and then repeat it a second time after opening a file and get the exact file I want.

**Comment by bryphe** [comment]
@CrossR - ya, I think I'm seeing the same behavior you are!

@somebody1234 - I imagine it depends on the size of the directory. It does feel instant for smaller directories, but for the `Oni2` folder w/ all the vendored stuff, it is slower for me (and reproduces pretty consistently the first time I search)

**Comment by CrossR** [comment]
This was covered in #695.

From my testing, I've stopped noticing the issue where the first and second runs are different, but if people are still seeing that, we should open a separate issue.
