### ISSUE TITLE
<c-w>w and <c-w><s-w> don't cycle through splits like they do in vim

### ISSUE THREAD

**Issue by omginbd** [onivim/oni2#2897]
| command | output |
|-|-|
|`lsb_release -rd`| `Description:	Pop!_OS 20.10`<br />`Release:	20.10`|
|`oni --version` | `Onivim 2 (0.5.9-nightly)`|

### What I do
Press `ctrl+w w` or `ctrl+w W` (or run `:wincmd w` or `:wincmd W`)

### What happens
Nothing that I can tell. The same split is highlighted.

### What I expected to happen
> move cursor to window below/right of the current one.  If there is no window below or right, go to top-left window.

Behaviour described [here](http://vimdoc.sourceforge.net/htmldoc/windows.html#:wincmd) in the vim manual.

**Comment by bryphe** [comment]
Fixed with #3376
