### ISSUE TITLE
Multiple lines changes

### ISSUE THREAD

**Issue by Murtrag** [onivim/oni2#2921]
I just wanted to perform changes in multiple lines the same way I do in vim
![edit](https://user-images.githubusercontent.com/19934843/103479211-6fd79a80-4dcc-11eb-9a03-dae954975ac3.gif)
But it doesn't work in Onivim2 :(

**Comment by Doerge** [comment]
I think this issue is already tracked over here: https://github.com/onivim/oni2/issues/471 (scroll to the bottom).
Upvote that issue to help the devs prioritize🙂

**Comment by CrossR** [comment]
I'll close this out as the linked issue should cover this (and links to some of the work in the area).
