### ISSUE TITLE
Modifier keys not working

### ISSUE THREAD

**Issue by travv0** [onivim/oni2#2924]
```sh
$ oni2 --version
Onivim 2 (0.5.9-nightly)
```

I ran onivim with the following command and tried to open the command pallet with cmd+p which didn't work, then opened a file and tried to use ctrl+d to scroll down, which also didn't work.
```sh
$ oni2 --disable-extensions --disable-configuration -f --debug --log-file oni.log
```
Here's the log: [oni.log](https://github.com/onivim/oni2/files/5762061/oni.log)

I'm on macOS Catalina, and I don't have this problem with the stable release.

**Comment by glatteis** [comment]
This is probably not an inherent problem with this nightly build as it works for me^TM on linux. So maybe it has something to do with Mac specifically.

**Comment by travv0** [comment]
Yeah, it works fine for me on Windows as well and I don't have another Mac to test on to see if it's just My Machine or a general problem on macOS.

**Comment by bryphe** [comment]
Thanks for reporting @travv0 !

I'm trying to reproduce - but not having success.  Just curious - what keyboard layout are you using?

I do see some strange behavior in the log:
```
[INFO]  [ 9.174s] Feature.Input.ReveryKeyConverter : No keymap for key.
[INFO]  [ 9.175s] Feature.Input.ReveryKeyConverter : No keymap for key
```

We query OSX to ask about the keymap for the current scancode pressed, but in your case, we're not getting any info. I'll look also to see about adding some additional logging to narrow this down.

**Comment by bryphe** [comment]
Thanks @travv0 ! I'm able to reproduce this now with Romanji too - looking at a fix

**Comment by travv0** [comment]
Great, thanks!
