### ISSUE TITLE
`:split file_name` displays both file_name and current file

### ISSUE THREAD

**Issue by sandersac** [onivim/oni2#2952]
Windows Version: 1903 (OS Build 18362.1256)
Oni2 Version: 0.5.9-nightly | 40b0ffc7
Extensions: Arc+ Theme
Configurations: All default besides activating Arc+ theme.

Issue: Opening a split with `:vsplit file_name` or `split file_name` opens a split with two tabs: one with `file_name` in addition to the file open in the current window. I would expect only `file_name` to be opened. Note that `:vsplit` and `:split` both work as intended when called without any arguments.

Thank you :)

**Comment by bryphe** [comment]
Thanks for logging the issue! Looks like this may be a similar root cause to #2900
