### ISSUE TITLE
Extensions: codeblocks use incorrect font in extension descriptions

### ISSUE THREAD

**Issue by zbaylin** [onivim/oni2#2953]
I noticed when looking at extensions recently that (on macOS, at least), code blocks in extension descriptions are rendered with the wrong font at the wrong size. Take the Ruby extension:
![image](https://user-images.githubusercontent.com/4527949/103947919-e0512500-5106-11eb-8265-1c746096a54b.png)
The inline code is rendered fine (as in "`ruby.useLanguageServer`") but the code block seems to use the default system font which is not monospace and is also the wrong size.

I'm not sure if this is a bug in the Markdown component or if there is something we're not passing to the component that we should be.

Also @bryphe are the Uninstall/Update button colors inherited from the theme at all? It seems a little strange to have Uninstall be red in the sidebar but green on the extension page -- should be an easy fix though!

**Comment by zbaylin** [comment]
Strangely I've found that if I explicitly set `codeBlockFontSize` in `RemoteMarkdown.re` that seems to fix it. I don't know why this would be the case though -- I'll look into it more.

**Comment by bryphe** [comment]
> Also @bryphe are the Uninstall/Update button colors inherited from the theme at all? It seems a little strange to have Uninstall be red in the sidebar but green on the extension page -- should be an easy fix though!

Good question... I think with the initial implementation, they were hardcoded, but I can't remember now if I ever updated them... will check it out. It does look busted for sure with that mismatch between the list/details
