### ISSUE TITLE
Small cursor flicker when entering command.

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni2#2968]
When entering a command with the buffer scrolled to the top, but with the current cursor placed somewhere not on the top line of the file, hitting enter in the `:` command window makes a small caret flash on the first line.

Feel free to close if this is a dupe of another issue.

Thanks!

**Comment by bryphe** [comment]
Thanks @jordwalke !

Might be a similar underlying issue to https://github.com/onivim/oni2/issues/1405 - when the command line is open, we lose track of the cursor.

Interestingly, I see the cursor flash on the first line when pressing `enter` but not `esc` (although, in both cases, the cursor disappears - it's just when pressing `enter`, the cursor comes back first on the first line, and then teleports to the previous position)
