### ISSUE TITLE
nnoremap kills oni

### ISSUE THREAD

**Issue by davidsteinberger** [onivim/oni2#2972]
I know that experimental.viml is still experimental ;-). Though I thought I should report it here anyways.

I'm working on Mac OS Big Sur with a german layout. Previously all attempts to remap the _ö_ character to _:_ via `"experimental.viml": ["nnoremap ö :"]` failed. However with the latest version oni2 crashes immediately and won't restart unless I revert the _configuration.json_.

**Comment by bryphe** [comment]
Hi @davidsteinberger , thanks for logging the issue!

>  Though I thought I should report it here anyways.

Definitely, appreciate it - the crash is a regression from some work being done. Luckily, though, I think the work actually makes it easier to actually support keybindings like that correctly - working on a fix in #2977

**Comment by davidsteinberger** [comment]
Thanks! Can’t wait to try it out.
