### ISSUE TITLE
Extensions: Search sorting isn't correct

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#2979]
When searching for extensions, the returned result order is unexpected and incorrect.

For example - searching for "Search Lights", I'd expect the "Search Lights" extension to be at the top - but it's halfway down the list:
![image](https://user-images.githubusercontent.com/13532591/104256272-c4fc5780-542f-11eb-822c-ebe62d5e6cc3.png)

**Comment by jakubbaron** [comment]
I don't have experience with OCaml yet, will have a try. :)

**Comment by bryphe** [comment]
Sweet, thanks @jakubbaron !

I think the issue might be around: https://github.com/onivim/oni2/blob/06493ff4aea685827a0411d0637dabef6ba431cb/src/Service/Extensions/Sub.re#L35 

I was playing around previously and added logging here: https://github.com/onivim/oni2/blob/06493ff4aea685827a0411d0637dabef6ba431cb/src/Service/Extensions/Catalog.re#L283

like this:
```
let search = (~offset, ~setup, query) => {
  let url = Url.search(~query, ~offset);
  prerr_endline (Printf.sprintf("-- search: %d %s | url: %s", offset, query, url));
  Service_Net.Request.json(~setup, ~decoder=SearchResponse.decode, url);
};
```

And I see that we're getting a bunch of results:
```
-- search: 0 Search Lights | url: https://open-vsx.org/api/-/search?query=Search Lights&offset=0
-- search: 18 Search Lights | url: https://open-vsx.org/api/-/search?query=Search Lights&offset=18
-- search: 36 Search Lights | url: https://open-vsx.org/api/-/search?query=Search Lights&offset=36
```

But I think we're appending them out of order - such that the last results are bubbling to the top of the search results, displacing the first results

**Comment by jakubbaron** [comment]
Thanks @bryphe!

Yes, looks like the order is getting destroyed when the second and third result is being returned

I've noticed that when you search, it re-renders the `SearchResults` three times:
- on the first refresh, the searched item is actually on the top
- on the second and third refresh, the searched item is on the top

![ExtensionSearch](https://user-images.githubusercontent.com/7096437/104783877-4aad3980-5787-11eb-86ca-e7f471a9da97.gif)

**Comment by bryphe** [comment]
Ya, good catch - I think there might be an issue with this logic here:
```
     Lwt.on_success(
        result,
        ({offset, totalSize, extensions}: Catalog.SearchResponse.t) => {
          let newExtensionCount = List.length(extensions);
          let newQuery =
            Query.{
              offset: offset + newExtensionCount,
              maybeRemainingCount:
                Some(totalSize - offset - newExtensionCount),
              searchText: query.searchText,
              items: extensions @ query.items,
            };
          dispatch(Ok(newQuery));
        },
      );
```

Specifically - this line: 
```
items: extensions @ query.items,
```

The `extensions` are coming from the search response, and the `query.items` is the current set of items so far... so `extensions @ query.items` is saying concatenate the _new items_ with the _existing items_ - so later search results are getting added to the front. It might mean we just have to flip that concatenation around

**Comment by jakubbaron** [comment]
Right, I was searching for the place where we actually concatenate previous results and new result. It's a bit harder while not fully knowing the syntax yet. :)
Thank you a lot for a thorough explanation!

Created a PR for it https://github.com/onivim/oni2/pull/3000

**Comment by bryphe** [comment]
> Right, I was searching for the place where we actually concatenate previous results and new result. It's a bit harder while not fully knowing the syntax yet.

Definitely! Superficially it's like javascript... but there's a lot of new / extra stuff, like the operators for [list concatenation](https://reasonml.github.io/docs/en/basic-structures#add-to-end)

Nice job with the PR - thanks for taking this on @jakubbaron ! Extension search feels much better with this change :+1:
