### ISSUE TITLE
Pressing 'w' once in normal mode does nothing

### ISSUE THREAD

**Issue by TheSamsa** [onivim/oni2#2980]
command | output
-|-
lsb_release -rd | Description:	Manjaro Linux<br>Release:	20.2.1
oni2 --version | Onivim 2 (0.5.9-nightly)

If I am in the normal mode and press 'w' oni does nothing, but as soon as i press another key it executes the word jump and then the other key.
ie:
- I press 'w' the cursor stays on the current word.
- If I then press 'i' it jumps the word and goes into insert mode.
Or if I press 'w' and then another 'w' it jumps twice.

Also if I go into the vim-ex mode it does not register a typed 'w', only as above if I press another key.

I tried to remove my configuration.json as well as keybindings.json, neither one had an effect on the behavior.

Edit:
I discovered that '>' won't be recognized in insert or normal mode, but in the vim-ex mode.
Edit2:
Nope the '>' problem has something to to with my keybindings, sorry about that.

**Comment by bryphe** [comment]
Thanks for logging the bug @TheSamsa , appreciate it! I'm able to reproduce, and upon initial investigation this looks like a regression from #2977 .

Working on a fix; in the meantime I'm reverting #2977 and pushing out a new nightly to address this, since it's a severe bug / blocker.
