### ISSUE TITLE
Extension: hashicorp terraform didn't work

### ISSUE THREAD

**Issue by ddup1** [onivim/oni2#2981]
Hi,

I just installed hashicorp terraform extension, installation is ok but when  load a tf file i get this error in notification status :
> Error: Activating 'hashicorp terraform' failed: The "listener" argument must be of type function. Received an instance of Object

I use a Onivim2 5.9 nightly on linux system.

Regards.

**Comment by bryphe** [comment]
Thanks for the logging issue @ddup1 and for copying the error message - I can reproduce, bug in our extension host - working on a fix in #2995
