### ISSUE TITLE
PHP: Syntax highlighting does not appear to work at all

### ISSUE THREAD

**Issue by nerdo** [onivim/oni2#2985]
I'm having trouble getting any syntax highlighting to work at all. I am trying to open primarily PHP and JS files, but they appear completely white/gray. I've also tried opening various other files like JSON.

Full disclosure: I have only been trying onivim out every so often to see how it has been progressing, so I may not know what I'm doing. I thought that syntax highlighting used to work for these out of the box, but I may be mistaken?

I've previously loaded vscode extensions and tinkered around, so I tried to fully reset onivim by removing `~/.config/oni2` and starting it fresh but get the same result.

I'm using Onivim 2 (0.5.9-nightly) on (Arch) Linux.

**Comment by bryphe** [comment]
Hi @nerdo ,

>  I am trying to open primarily PHP and JS files, but they appear completely white/gray.
> I thought that syntax highlighting used to work for these out of the box,

Definitely, this should work out of the box - we bundle syntax grammars for both of those languages.

I've seen a similar issue when we are unable to load a theme - curious if it is that issue, would be interesting to see if changing themes works to bring back the highlights:
1) Open a JS or PHP file in Onivm
2) Press Control+Shift+P
3) Type "Theme Picker", enter
4) Cycle through the themes with Control+N or Control+P

I can reproduce something similar to this issue by setting an invalid theme, and restarting the editor:
<img width="1221" alt="Screen Shot 2021-01-12 at 3 55 17 PM" src="https://user-images.githubusercontent.com/13532591/104388742-b2952300-54ee-11eb-9c6c-e15c8a2130e4.png">
...but not sure it's the same issue you're seeing.. Deleting the `.config/oni2` should've removed any invalid theme.

One other troubleshooting step would be to see if the logs - if you run with the `--log-file=output.log` argument, the resultant `output.log` may give some helpful info if we're having an issue loading the theme or syntax grammars.

I'll work on a fix for the invalid-theme-no-tokens issue in the meantime, just to rule that out as a possibility.

**Comment by nerdo** [comment]
So I might have misspoke about JS syntax highlighting, because when I tried it again, it was working, but PHP is not working for some odd reason.

Here is a screen recording I took just after moving my `.config/oni2` directory and starting over.

https://user-images.githubusercontent.com/1031502/104444036-3a1d7900-5565-11eb-9daa-ef579af9f2d4.mp4

And here is the output.log file:

[output.log](https://github.com/onivim/oni2/files/5808170/output.log)

**Comment by willopez** [comment]
I attempted to change the theme and the syntax still does not work for PHP files.

**Comment by bryphe** [comment]
Thanks @nerdo for the clarification and @willopez - indeed, there does seem to be a bug specific to PHP files
