### ISSUE TITLE
<C-^> always open new tabs

### ISSUE THREAD

**Issue by Schniz** [onivim/oni2#2988]
given the following VimL:
```
nnoremap <backspace> <C-^>
```
tapping `<backspace>` will toggle between the last 2 files, but will open new buffers/tabs every time:

![image](https://user-images.githubusercontent.com/2054772/104426620-da39c900-558a-11eb-965a-d91f59288ea8.png)
(check out the tabs above, lots of `.yarnrc` and `Welcome`)

**Comment by despairblue** [comment]
https://youtu.be/bbtr5sLYr-I

I have the same. Here's a video demonstrating the bug.

**Comment by bryphe** [comment]
Thanks @Schniz and @despairblue for reporting, I can reproduce - I also saw it repro with `Control+Tab` - working on a fix here: https://github.com/onivim/oni2/pull/2984

**Comment by Schniz** [comment]
Exciting! Trying to set Oni up to use it as my editor :)
