### ISSUE TITLE
Add Onivim to ECD Tools Adopters Page for Open VSX

### ISSUE THREAD

**Issue by brianking** [onivim/oni2#3005]
The Eclipse Cloud Developer Tools (ECD Tools) adopters page is now live at https://ecdtools.eclipse.org/adopters/.

As an adopter of the Open VSX Registry, we would love to see Onivim listed there. 

Instructions on how to get listed are at https://ecdtools.eclipse.org/adopters/how-to-be-listed-as-an-adopter/.

**Comment by bryphe** [comment]
Hi @brianking ,

Thanks for reaching out, would be great to have Onivim listed there! I've opened a PR and signed the necessary agreements: https://github.com/EclipseFdn/eclipsefdn-project-adopters/pull/59

Let me know if there is anything else you need from me 👍

**Comment by brianking** [comment]
Excellent, thanks.
