### ISSUE TITLE
Document formatting not working

### ISSUE THREAD

**Issue by willopez** [onivim/oni2#3014]
I have a react component open and eslint has been configured. When I execute `Formatting: Format Document` command, I get an `Invalid ranged specified` error. I would assume that the command would format the whole document by default? further, don't see where I could specify a range.

**Comment by bryphe** [comment]
The error message there is very poor, for sure - in actuality there isn't a document formatter out of box for JavaScript / TypeScript.

I'd recommend installing the [`prettier`](https://open-vsx.org/extension/esbenp/prettier-vscode) extension in the meantime - that has an included document formatter

**Comment by bryphe** [comment]
Should be fixed now with #3240
