### ISSUE TITLE
Ability to select correct import suggestion when there is multiple with the same name/symbol

### ISSUE THREAD

**Issue by chris-armstrong** [onivim/oni2#3032]
At the moment, it's not possible to select the right import symbol when there is multiple with the same name. For example, I have two `createContext` symbols in my workspace, but I can only select the last one that was found (I can even see the suggestion box flickering while it loads all the suggestions from the extension host):

![image](https://user-images.githubusercontent.com/11450231/105450142-fac1fb80-5ccd-11eb-9337-5c78b463c1f6.png)

A similar issue occurs when a function is overloaded and the 'hover' is activated - there is currently no way to switch between the overloaded function variants (although I do see the 1/x indicator in the description)

**Comment by bryphe** [comment]
Thanks for catching this, @chris-armstrong !

It looks like there is a bug in our duplicate detection for completions - Onivim removes all duplicate completion entries, but in cases like this, that's not the correct behavior.
