### ISSUE TITLE
zen mode messes up splits layout

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3035]
I use the "classical vim" configuration for tabs and splits (i.e., in my config):

```
  "oni.layout.singleTabMode": true,
  "oni.layout.layoutTabPosition": "top",
```

Let's say I have a few splits opened:

![Screenshot from 2021-01-23 11-11-43](https://user-images.githubusercontent.com/8382834/105575418-d3ba0700-5d6b-11eb-9e22-05cbcc58295d.png)

Then using zen mode makes me loose the splitting displaying (immediately after enabling zen mode see below), though the splits are still here actually (they come back when I de-activate zen mode, and I can still navigate between them with Ctrl-w + hjkl in zen mode):

![Screenshot from 2021-01-23 11-12-00](https://user-images.githubusercontent.com/8382834/105575429-e46a7d00-5d6b-11eb-827e-63ff75757781.png)

- is this really the behavior wanted? I would like to keep my splits configuration, but to have less clutter in the zen mode, not to loose the splits layout. I.e., I would like to keep the same splitting configuration, but without clutter.

- so it looks like now zen mode both removes clutter, and maximizes the current active split. Would it be possible to split those behaviors? I.e., one command (possibly shortcut too? Ctrl-w + z or something like that?) to maximize the current split, and one command to remove clutter without changing splitting.

Maybe I am just confused, but could not really find help about that (may have missed something).

**Comment by bryphe** [comment]
Thanks for the thoughts here @jerabaul29 !

> is this really the behavior wanted? I would like to keep my splits configuration, but to have less clutter in the zen mode, not to loose the splits layout. I.e., I would like to keep the same splitting configuration, but without clutter.

I agree, this actually isn't desirable - it causes a lot of confusion. Both in this case - and in cases where you are in zen mode, create a split via `:vsp`... and the editor doesn't show a new split. Extra confusing when we start with zen mode by default when opening a single file.

I'll change this default, and then, if users want the previous zen-mode-plus-maximize behavior, we can explore an additional setting.
