### ISSUE TITLE
Question: Are the commands editor.action.moveLinesDownAction (and up)  implemented?

### ISSUE THREAD

**Issue by DanMacDonald** [onivim/oni2#3039]
Are the VSCode command's  `editor.action.moveLinesDownAction` and `editor.action.moveLinesUpAction` supposed to be bindable and supported in Onivim2? When I try to bind them it seems the binding (it overwrites the alt+down default behavior and instead does nothing) works but the action is not performed.

**Comment by CrossR** [comment]
I believe not yet : https://github.com/onivim/oni2/issues/2735

It has been something that has been asked for a few times, so we are aware it would help!
