### ISSUE TITLE
Idle Rendering Issue

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#304]
It looks like there is a bug that stops the Idle rendering loop kicking in, in some fashion.

Opening Oni2 and not using QuickOpen means that when you unfocus the editor or don't make any changes to the buffer, the CPU and GPU usage drop to 0%.

However, once you open the QuickOpen menu (not even selecting an item), the idle usage jumps up to match the focused/changed usage.

For example, here I've opened 4 files and then unfocused Oni2:
![image](https://user-images.githubusercontent.com/10038688/57251272-569fa900-7041-11e9-95a0-766be3e1615c.png)

I then left it for a few mins (just to check it wasn't a random issue), then opened the QuickOpen menu. The usage jumps up instantly as the Menu is opened, and doesn't drop back down even after closing or selecting an item.
![image](https://user-images.githubusercontent.com/10038688/57251529-f5c4a080-7041-11e9-9e90-7602151ef62a.png)

The actual usage seems to vary: I've seen between 1-10% GPU usage, and it seems to be somewhat related to the buffer contents. It is higher when the editor is open, but no changes are being made, whereas before opening the QuickOpen the usage will stay at 0% until a change is made.

Ie this is the unfocused usage of the editor being visible, but not focused: 
![image](https://user-images.githubusercontent.com/10038688/57251685-58b63780-7042-11e9-909f-0504cb30de3e.png)

Where it should be 0% and 0%.

It feels like this is probably something to do with the ripgrep process. When the quick open is actually open I do see a `rg.exe` process, so I think that is being closed properly since it goes away, but its possible the process used to open the process isn't closed?

**Comment by bryphe** [comment]
One contributing factor for this, as well as the lack of idling, is this bug in the reconciler we are using:
https://github.com/briskml/brisk-reconciler/pull/40

Our QuickOpen is leaking this effect: https://github.com/onivim/oni2/blob/f012628fdc09ad8888777aa4297db9086f980ffa/src/editor/UI/OniInput.re#L189

(In essence - the `Tick` being set never clears). This means for any menu - or any UI that uses the Input - it's bumping up the CPU usage.

We need to either fix that brisk-reconciler bug, or have a more reliable way to start/stop animations in Revery.
