### ISSUE TITLE
Powershell inside :term freezes on start

### ISSUE THREAD

**Issue by iilonmasc** [onivim/oni2#3041]
This might not a deal-breaker for me, since I use WSL inside a separate terminal, but calling `:term` on windows causes onivim to open powershell by default (apparently) but the shell seems frozen, it doesn't recognize any input, so you can't even exit it without closing the term window completely.

**Comment by mabasic** [comment]
I have tried `:term wsl.exe`, it opens the correct shell, but it seems frozen. Can't do anything inside.

**Comment by bryphe** [comment]
Thanks for opening this! I was thinking this might be related to #3040 - at least, when I tested with Avast, the first time I opened the terminal, it required scanning the `winpty-agent.exe`. Are there still issues after re-launching Onivim after the scan, @iilonmasc ?

For other users running into this - would it be possible to provide a log file? (`Control+Shift+P` -> Debug: Log to trace file) and then opening the terminal. Might give some clues...

One instance I've seen this occur is building from source - if the node dependencies aren't installed (`node install-node-deps.js`), the terminal won't open.

**Comment by iilonmasc** [comment]
@bryphe it did require a scan yes, but as mentioned in #3040 after the first scan and relaunch the AV seems to be fine with onivim.
I tried again to be on the safe side, but the terminal still freezes.

**Comment by iilonmasc** [comment]
I created a debug log right after opening onivim, pastebin didn't want me to upload it there because it was too large so I created a gist. https://gist.github.com/iilonmasc/fe9df44b187b161a27ee3caa570699f1

Steps I took during the debug trace:

1. Start the terminal via `:term`
2. Switch to the terminal
3. try to type `asd` inside the terminal
4. Closing onivim

**Comment by bryphe** [comment]
Thanks for the logging the issue and all the details, @iilonmasc - this should be fixed now in latest nightlies w/ #3117
