### ISSUE TITLE
Vim command line key-binding eats subsequent key presses

### ISSUE THREAD

**Issue by mfish38** [onivim/oni2#3048]
I use the space bar instead of `:` for ergonomics. Since the key binding .json file does not appear to support opening the vim command line, I have added the following to my config:

```json
"experimental.viml": [
    "nnoremap <Space> :",
    "vnoremap <Space> :"
]
```

The issue is that after pressing space there is a very short period where any key-presses that follow it are lost. This means that a quick `:w` (by typing `<Space>w`), which is well ingrained in my muscle memory, will almost always fail unless I consciously type it slowly.

**Comment by bryphe** [comment]
Thanks for the details @mfish38  - can reproduce as well. Working on a fix in #3053
