### ISSUE TITLE
Onivim2 seems to use three different fonts etc

### ISSUE THREAD

**Issue by snoblenet** [onivim/oni2#3062]
Onivim2 seems to use three different fonts etc.

And only the fonts in the editor seem to be user-configurable.

![image](https://user-images.githubusercontent.com/62277/106219789-3e68b800-622e-11eb-8336-83c23280e6d3.png)

**Comment by baldwindavid** [comment]
There is a [configuration](https://onivim.github.io/docs/using-onivim/integrated-terminal#appearance) for the terminal. One of the Oni devs on Discord mentioned that it might be better if the terminal font defaulted to the same as `editor`.

For the "third" font I assume you mean the theme? If so, I'm not sure how to update a theme font.

**Comment by bryphe** [comment]
> One of the Oni devs on Discord mentioned that it might be better if the terminal font defaulted to the same as editor.

Indeed, we should fall back to the editor font if the terminal font isn't specified! 

Right now - we default to our embedded font ([JetBrains-Mono](https://www.jetbrains.com/lp/mono/)) if the editor font isn't specified.... which is confusing if `"editor.fontFamily"` has been set to something else.

> If so, I'm not sure how to update a theme font.

Right, we use a non-monospace font for several UI elements (like the explorer, tab titles, etc), Currently we don't have a way to customize this font (it's bundled, a font called [Inter UI](https://rsms.me/inter/))

**Comment by snoblenet** [comment]
Thanks I have now applied my editor fontSize and fontFamily settings to terminal.

However, the line spacing still seems different between the two?

**Comment by bryphe** [comment]
> However, the line spacing still seems different between the two?

Ah, it's something similar - there is an `editor.lineHeight` setting which defaults to `1.2`. Onivim is missing the equivalent setting for the terminal, and like the fontFamily, it should fallback to `editor.lineHeight`.

**Comment by snoblenet** [comment]
Related: changing the theme changes the appearance of the chrome and the editor but not the terminal.

**Comment by bryphe** [comment]
> Related: changing the theme changes the appearance of the chrome and the editor but not the terminal.

Interesting - which theme did you change from / to? I'm not reproducing the theme issue:

![Uploading 2021-02-01 17.21.20.gif…]()

Working on a fix for the font-family and size fallbacks in #3077

**Comment by snoblenet** [comment]
I think it might be related to me coding colours for my normal terminal emulator in my `~/.zshrc`.

My other issue about publishing a variable that allows us to detect and account for Onivim2 will be the fix for this.
