### ISSUE TITLE
Does Onivim2 set an environment variable or anything I call listen for to tailor shell behaviour?

### ISSUE THREAD

**Issue by snoblenet** [onivim/oni2#3068]
Does Onivim2 set an environment variable or anything else that I call listen for to tailor shell behaviour?

Background: When I create a shell in my terminal emulator, `~/.zshrc` tells it to automatically join the existing TMUX session or otherwise create one.

I'd like to skip this behaviour when typing `:term` in Onivim2.

**Comment by bryphe** [comment]
Good question @snoblenet - we should have an environment variable for this.

There isn't a robust environment variable to use currently... there is a `TERM_PROGRAM=vscode` set by virtue of the extension, but it's not reliable (and I'll change the hardcoded 'vscode' string eventually).

We should have one, though - I'll add an `ONIVIM_TERMINAL` variable such that the Onivim  terminal could be detected like:
```
if [[ -z $ONIVIM_TERMINAL ]]; then
    echo "Not in Onivim Terminal"
else
    echo "In Onivim Terminal"
fi
```

and you could use it to make sure your `~/.zshrc` does the right thing in Onivim 2
