### ISSUE TITLE
Error: `Common.gypi not found` while building on Windows

### ISSUE THREAD

**Issue by hundredeir** [onivim/oni2#3069]
When installing node dependency via
`node install-node-deps.js`

I am getting the error

```gyp: ...\AppData\Local\node-gyp\Cache\14.15.4\common.gypi not found (cwd: ...\Documents\software\oni2\node\node_modules\native-watchdog) while reading includes of binding.gyp while trying to load binding.gyp```

Common.gypi indeed doesn't exist in that folder. I tried searching for it and it isn't anywhere. 
Though there was a reference to the file in
```...\AppData\Local\node-gyp\Cache\14.15.4\include\node```

But, it was named like 
`common.gypi.DELETE.c21d825`

System is Windows x64
```
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
```

**Comment by bryphe** [comment]
Hi @hundredeir ,

You might need to install the matching headers for `node-gyp`:

`npm install -g node-gyp`
`node-gyp install 14.15.4`

(matching the node version)

You can also use `node-gyp list` to see what node headers are available.

**Comment by hundredeir** [comment]
Thanks!
The install command worked.
