### ISSUE TITLE
Check for updates doesn't work (macOS)

### ISSUE THREAD

**Issue by dahmc** [onivim/oni2#3070]
Checking for updates from the help menu fails with the following:

![Screenshot 2021-01-31 at 06 59 35](https://user-images.githubusercontent.com/75008413/106376099-2a3dcb80-6392-11eb-9787-58537fad2ab1.png)

Tested in versions 
- 0.5.9-nightly (0.5.1845)
- 0.5.9-nightly (0.5.1856)

Seems not to be a temporary downtime, since this has happened all week long.

macOS 11.1

**Comment by bryphe** [comment]
Hi @dahmc ,

Thanks for logging the issue! 

Auto-update right now requires a license key - just curious, have you entered it in the UI?

There's a spot in the titlebar where we show:

<img width="727" alt="Screen Shot 2021-02-01 at 4 16 16 PM" src="https://user-images.githubusercontent.com/13532591/106534533-2cdf1480-64a9-11eb-94a2-5b70d30f6ae4.png">

On top of that - if you don't enter a license key, there's no useful error message - it provides that same 'Update Error!' dialog. 

I'm wondering if it is hitting this no-license-key case, or if perhaps there is another issue blocking it from receiving the update.

**Comment by dahmc** [comment]
Hi @bryphe,

Thanks a lot for the info. I have to admit I never realized the unregistered notice at the top. :)

Once I entered my key, the update worked:
![Screenshot 2021-02-02 at 06 55 31](https://user-images.githubusercontent.com/75008413/106558355-e24eae00-6523-11eb-98f7-316757ce42a6.png)

However, the banner to show the successful purchase never goes away.

![Screenshot 2021-02-02 at 06 55 52](https://user-images.githubusercontent.com/75008413/106558409-f4c8e780-6523-11eb-9e90-9a2ae998a841.png)

I can't click it, or even when changing files or doing other stuff it just keeps staying. Restarting oni will make it go away.

**Comment by bryphe** [comment]
Hi @dahmc ,

Excellent, glad the update worked after entering the key!

We definitely need to smooth out that flow - working on a couple fixes in #3078  :
1) If a license key isn't entered, and 'Check for Updates' is run, let the user know a license key is needed
2) Fix the bug where the dialog isn't closeable - add a close button, and accept `enter` from the keyboard as well.

**Comment by snoblenet** [comment]
Could be related: I have a license key but Onivim seems to be downloading the same updates over and again. I say 'seems to' because I haven't actually written down and compared the commit SHAs. I've just read the release notes and the last four or five releases have all had the same changes.

**Comment by bryphe** [comment]
Interesting - it sounds like it might be picking up the `nightly` builds, @snoblenet - we have a configuration setting to choose which build it should use:
```
      "oni.app.updateReleaseChannel": "stable"
 ```
(where `"stable"` gets the point releases, approximately monthly, and `"master"` gets the nightly release). Might be worth switching that to `"stable"` so you get less noisy updates.

The changelog gets pulled from here: https://github.com/onivim/oni2/blob/master/CHANGES_CURRENT.md - and isn't smart enough to diff between nightlies, so at least the top changes would be the same for each nightly build.
