### ISSUE TITLE
Onivim nightly AppImage crashes with "NULL data at keyboard-layout-linux" error seen the crash log

### ISSUE THREAD

**Issue by mkazlouski** [onivim/oni2#3073]
Fedora 31 (xorg) in Virtualbox 6.1.16 on Windows 10
```
$ oni --debug --nofork
[DEBUG] [ 0.000s] Oni2.Exception : Recording backtraces
[INFO]  [ 0.000s] Oni2_editor : Starting Onivim 2 (0.5.9-nightly / c54a9e90 / master / 1.53.0)
[DEBUG] [ 0.000s] Oni2_editor : Calling App.start
No protocol specified
error: XDG_RUNTIME_DIR not set in the environment.
[ERROR] [ 0.008s] Revery.SDL2 : SDL_Init failed: No available video device
[DEBUG] [ 0.008s] Oni2_editor : Init
No protocol specified
[ERROR] [ 0.031s] Oni2.Exception : Exception (Failure "NULL data at keyboard-layout-linux.c:55"):
Raised by primitive operation at file "src/bin_editor/Oni2_editor.re", line 235, characters 4-30
Called from file "src/Core/App.re", line 199, characters 17-34
Called from file "packages/reason-sdl2/src/sdl2.re", line 269, characters 17-59
Called from file "packages/reason-sdl2/src/sdl2.re", line 269, characters 17-59
Called from file "src/bin_editor/Oni2_editor.re", line 524, characters 11-26
```
No _clear_ steps to reproduce. Doesn't happen frequently, but when it does I cannot start the editor until reboot. Could be related to #2922

_What's known so far_:
* Onivim is running on behalf of a separate user
The user is being created with `useradd -mG wheel USER`, given access to the default display with `xhost +local:USER@`, logged in with `sudo su -l USER` and the `DISPLAY=:0` variable is being exported. The issue **does not** reproduce when running on behalf of the graphical session user even when the OS transfers to broken state. Please see 
[the log](https://github.com/onivim/oni2/files/6048703/onivim.log) of oni running on behalf of the graphical session user.
* The issue starts reproducing when the OS is transferring to a broken state
When my laptop goes to sleep instead of locking the (guest) session it forcefully logs out. At least that's what I think it does as I have to log back in and observe that all user processes were terminated. The nature of the broken state is unknown, yet. According to https://github.com/onivim/oni2/issues/3073#issuecomment-776296546 there's no significant difference in the environment block. It's possible that there's a combination of issues with VirtualBox guest tools and Fedora 31 that make it perform that way.

**Comment by mkazlouski** [comment]
More recent build:
```
$ oni --debug --nofork
[DEBUG] [ 0.000s] Oni2.Exception : Recording backtraces
[INFO]  [ 0.000s] Oni2_editor : Starting Onivim 2.0.5.9-nightly (678dbea1)
[DEBUG] [ 0.000s] Oni2_editor : Calling App.start
No protocol specified
error: XDG_RUNTIME_DIR not set in the environment.
[ERROR] [ 0.007s] Revery.SDL2 : SDL_Init failed: No available video device
[DEBUG] [ 0.007s] Oni2_editor : Init
No protocol specified
[ERROR] [ 0.028s] Oni2.Exception : Exception (Failure "NULL data at keyboard-layout-linux.c:55"):
Raised by primitive operation at file "src/bin_editor/Oni2_editor.re", line 232, characters 4-30
Called from file "src/Core/App.re", line 199, characters 17-34
Called from file "packages/reason-sdl2/src/sdl2.re", line 269, characters 17-59
Called from file "packages/reason-sdl2/src/sdl2.re", line 269, characters 17-59
Called from file "src/bin_editor/Oni2_editor.re", line 511, characters 11-26
```

**Comment by bryphe** [comment]
Thanks for reporting the issue, @mkazlouski and for providing the log!

It looks like several things that we expect to have on initialization are not available:
- `XDG_RUNTIME_DIR` defined
-  No x11 display information
- No keyboard layout information

Would it be possible to run the `env` command in the case it isn't working (ie, `env > broken-env.log`) and then compare with the `env` output when it is working (ie, `env > working-env.log`). I'm wondering if there is a clue in the environment that could narrow this down.

One other useful bit of info would be to compare the `whoami` command output in both cases, as well. 

The only time I've seen this happen is when a different user that might not have the full environment is running (via some terminal / shell command that switches user, `sudo`s, etc) - would be interesting to see if that is what is happening here or if there is something else going on..

**Comment by mkazlouski** [comment]
Hi Bryan,

Unfortunately I cannot reproduce this at the moment, but I can tell you that you are right with the guess. I'm starting the editor on behalf of another user. The user is being created with `useradd -mG wheel USER`, given access to the default display with `xhost +local:USER@`, logged in with `sudo su -l USER` and the `DISPLAY=:0` variable is being exported. I didn't find it to be connected with the issue at first since the crash starts happening after some event which I couldn't figure out.

I'll try reproducing it and will post the difference in env output here. Thanks!

**Comment by mkazlouski** [comment]
Cleaned up the description, updated crash log with one from the latest nightly version.

I was finally able to reproduce this, gather copy of the environment and can say there's not much of a difference unfortunately. Please find copies of before ([env.0.log](https://github.com/onivim/oni2/files/5954677/env.0.log)) and after ([env.1.log](https://github.com/onivim/oni2/files/5954678/env.1.log)) attached.

Steps to reproduce look obscure. I'm running Fedora in Virtualbox 6.1.16 on Windows 10. When my laptop goes to sleep instead of locking the (guest) session it forcefully logs out. At least that's what I think it does as I have to log back in and observe that all user processes were terminated. After that Onivim starts performing the way described above. The only difference in the environment I could find is the PID of the ssh-agent which seems fair since I had to log back in and create another instance of it.

**Comment by mkazlouski** [comment]
Updated the description with logs of the nightly build running on behalf the graphical session user. The issue **does not** reproduce when running on behalf of the graphical session user even when the OS is in broken state. Let's call it a workaround.

**Comment by mkazlouski** [comment]
After reproducing it again I found that `xclip` utility stops working on behalf of the separate user as well. I no longer believe this issue is onivim's fault or could be fixed. Ideally I would like Oni to behave a little bit better than just not start silently, but it's tough to show any kind of warnings when graphical server cannot be accessed.

@bryphe I'm ready to close this. This could be left for the reference if you'd find it necessary. I'll leave it for your discretion.
Thanks!

**Comment by bryphe** [comment]
Thanks for the update @mkazlouski !

I'll close this, but I'll continue to track a potentially related issue in #3438
