### ISSUE TITLE
Problem with font resolution

### ISSUE THREAD

**Issue by dahmc** [onivim/oni2#3080]
I'm having trouble resolving the fonts.

I use this line on VSCode, which works just fine:

```
  "editor.fontFamily": "Dejavu Sans Mono, Arial",
```
Arial in the back to make sure that I see when the resolution of the first font doesn't work.

The same line in Oni just makes it jump to Arial instead. I can't seem to get any Font working at all, other than Arial. I've also tried Menlo, which works fine in VSCode, but not oni.

I've seen some examples of using a .ttf file, but from what I gathered from https://github.com/onivim/oni2/pull/715 and https://github.com/revery-ui/revery/pull/549 the font resolution should just work normally.

The docs also just states

> editor.fontFamily (string) - The font family used by the editor surface. This must be a monospace font.

What am I doing wrong here?

macOS 11.1, 0.5.9-nightly (0.5.1860)

**Comment by bryphe** [comment]
Hi @dahmc ,

We don't support font-fallback currently - so the `,` in the font-family might produce unexpected results.

Does either of the following work?
- `"editor.fontFamily": "Dejavu Sans Mono"`
- `"editor.fontFamily": "Menlo"`

I tested and it seems to be working on 10.15.7:
![2021-02-03 11 36 47](https://user-images.githubusercontent.com/13532591/106799521-35079300-6614-11eb-84e1-ecd74f54609c.gif)

It's possible that there is a difference in font-resolution behavior though on 11.1 - I need to check

**Comment by dahmc** [comment]
Hi @bryphe , 

Thanks for the explanation! Damn, I tested so many combinations, never thought about trying without the fallback :)

It works now, appreciate it! Happy to be reunited with my trusted font, haha
