### ISSUE TITLE
Add "Deep Purple" as a Theme Option

### ISSUE THREAD

**Issue by markteekman** [onivim/oni2#3082]
I feel like this one goes perfectly with Onivim 2's retro look and feel theme LaserWave! There's a nice theme for Atom and one for VS Code (different authors but very similar styles).

**Atom version**: https://github.com/nickvanderwildt/deep-purple-syntax
**VS Code version**: https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple

Screenshot example:
![afbeelding](https://user-images.githubusercontent.com/3909046/106745617-a863d180-6621-11eb-94ad-6c6d91f91309.png)

**Comment by bryphe** [comment]
Hi @markteekman ,

This is an awesome theme - thanks for sharing! I hadn't seen it before - unlike the City Lights (#3081 ) theme, it looks like this one hasn't been published to open-vsx before.

I opened https://github.com/ahmadawais/shades-of-purple-vscode/issues/106 to see if the creator would be open to publishing to open-vsx.

In the meantime, seems like the same workaround to manually install in #3081 works here too:

![image](https://user-images.githubusercontent.com/13532591/106802606-08557a80-6618-11eb-9a2d-26d03d35c456.png)

You can manually install this from the command prompt by running:
```sh
git clone https://github.com/ahmadawais/shades-of-purple-vscode $HOME/.config/oni2/extensions/shades-of-purple
```

🤞 Hopefully it will make it on open-vsx soon so it'll be easier to install. I'll resolve this as external too

**Comment by markteekman** [comment]
Thanks @bryphe for your reply and great to see the City Light workaround works for this one too! It looks great 😃 I'll be sure to give this a try right away, would be nice to see it on open-vsx eventually :)
