### ISSUE TITLE
More visual feedback when using VIM operators like "d", "c" and "t"

### ISSUE THREAD

**Issue by markteekman** [onivim/oni2#3083]
It could be I'm missing something, or that this goes beyond the scope of what VIM is all about, but before I started using Onivim 2 I used Atom with the [vim-mode-plus](https://atom.io/packages/vim-mode-plus) package. Now what I liked about this is that when I would type an operator like "d" or "c" the block cursor would change to a blinking fat underline cursor, giving me the feedback where I'm at (I now Onivim 2 also shows this at the bottom right corner, but I would like to keep my eyes on the code). Even when after "d" or "c" I would chain the operator "t" to it, it changes the fat underline to a thin underline. I found this really helpful to stay focused on the code. Some screenshots to help visualize this:

Normal mode:
![Schermafbeelding 2021-02-03 om 12 16 14](https://user-images.githubusercontent.com/3909046/106739594-9e3dd500-6619-11eb-98d1-ed8db80a4b76.png)

Pressed "d":
![Schermafbeelding 2021-02-03 om 12 17 24](https://user-images.githubusercontent.com/3909046/106739755-c75e6580-6619-11eb-92e7-b93e40716427.png)

Pressed "t":
![Schermafbeelding 2021-02-03 om 12 17 59](https://user-images.githubusercontent.com/3909046/106739804-dba26280-6619-11eb-81a1-ccb99f713b22.png)

Operation complete with pressing the quote:
![Schermafbeelding 2021-02-03 om 12 19 25](https://user-images.githubusercontent.com/3909046/106739933-0ee4f180-661a-11eb-9ead-5df5660bb1bd.png)

**Comment by bryphe** [comment]
Hi @markteekman ,

Not missing anything! I agree, we need to improve the operator-pending visualization.

We should have enough context right now to adjust the cursor when operator-pending is active. We might need a bit more info from libvim for the `f`/`t` visualization (but this would be really nice to have!)

Related to #2357

**Comment by markteekman** [comment]
Thanks @bryphe! Didn't notice the other issues before when searching on the topic, but great to see it's taken into account 😃
