### ISSUE TITLE
Is there a way to hide the menu bar?

### ISSUE THREAD

**Issue by mabasic** [onivim/oni2#3089]
In VSCode I can hide the menu bar and then call ti back by pressing the alt key.

Can we have a way to hide the menu bar and have a vim command to bring it back like eg. `:tmenu` for toggle menu?

**Comment by glennsl** [comment]
It can be hidden with a configuration setting:
```
  "window.menuBarVisibility": "hidden"
```

**Comment by mabasic** [comment]
@glennsl Thank you. Do you know is there a documentation page with all options that can be set? I haven't found one...

**Comment by glennsl** [comment]
Indeed there is! https://onivim.github.io/docs/configuration/settings

**Comment by mabasic** [comment]
Thank you. I must have missed it every time xD
