### ISSUE TITLE
File explorer folders not showing content when clicking on them

### ISSUE THREAD

**Issue by Jorgee97** [onivim/oni2#3092]
This has been happening for quite a while, and I think is a pretty important feature and hasn't been addressed yet and as I couldn't find a similar Issue created yet I will leave it here with a gif that shows the behavior.

![error_files](https://user-images.githubusercontent.com/8935477/106949557-1c25dd00-66fb-11eb-9eab-aa33a554fa9c.gif)

If you guys need any more info I would be happy to help sorting this issue

**Comment by bryphe** [comment]
Hi @Jorgee97 ,

Thanks for reporting! 

> I think is a pretty important feature and hasn't been addressed yet and as I couldn't find a similar Issue created yet I will leave it here with a gif that shows the behavior.

Definitely. I've seen this come up a few times, but haven't been able to reproduce locally - trying to figure out what is different between the environments.

I just opened #3096 to add some additional logging around the expand-node-path - maybe can give us some clues. In particular, we weren't logging if there was an error while executing the `readdir` to get data.

Some other info that might be helpful:
1) Would it be possible to share the full path? I'm wondering if there is a special character, a space, a size limit, or something that could breaking our path resolution.
2) How did you open the folder?  Was it through the menubar, command line argument (`oni2 C:\some\path`), or via an x command (`:cd`)?

Might be related to https://github.com/onivim/oni2/issues/2213 - there was a similar issue expanding the folder on Windows there, but went away after updating

**Comment by Jorgee97** [comment]
1. C:\Users\ingjo\Documents\andrea\api-money-back (this is where the project lives).
2. My results for every method:
    2.1. I just tested with **_oni2 ._** and this way it works nicelly.
    2.2. Opening the project from **_file context menu_** does not work.
    2.3. Opening the project with **_:cd source_to_project_** works aswell

**Comment by bryphe** [comment]
Interesting! Thanks for testing and sharing the results @Jorgee97 . Indeed, there is nothing suspicious about the path itself - no special characters, under the 260 character limit imposed by some older path APIs.

Glad one of those options works.

For the attempt that failed, 2.2:

> Opening the project from file context menu does not work.

Just to confirm, the folders  didn't expand in that case? Or did something else go wrong?

I suspect that the path must be coming through in a different form in that case where it isn't working 🤔

**Comment by Jorgee97** [comment]
The folders didn't expand when opening from the file context menu

**Comment by wmaurer** [comment]
I had been struggling with the same problem, but now thanks to @Jorgee97 at least I have a workaround ;-) (i.e. opening the project via methods 2.1 or 2.3)

**Comment by BorisVSchmid** [comment]
Not sure if it is related, but right-clicking on the sub-folders gives a weird-looking path, with the last slash being a backslash.  (Parent folder was selected through File>Open Folder, and I don't get opening sub-folders either. Win10).

![notexpanding](https://user-images.githubusercontent.com/25182535/107762425-4d229500-6d2d-11eb-9b68-5f61c45f2c63.png)

**Comment by bryphe** [comment]
Thanks @Jorgee97 and @BorisVSchmid for the all the information! With your help, I've been able to reproduce this locally consistently - and working on a fix in #3142
