### ISSUE TITLE
Performance: Elements 'snap-in' on load

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#311]
It looks like layout is being blocked while the File Explorer loads:

![elements-snap-in-on-load](https://user-images.githubusercontent.com/13532591/57390749-e5134800-7171-11e9-803b-7f7c8bbe2ff2.gif)

This adds some 'jank' to the loading experience. 

I wonder if there are any blocking portions of loading the explorer?

**Comment by Akin909** [comment]
@bryphe just tried opening it repeatedly on my machine and I can't replicate this on my machine unless I up the recurse depth, but in that case it does do something similar.

Could be that I've missed a trick in the `docs`(https://ocsigen.org/lwt/4.1.0/manual/manual). Two things of note is that when `Lwt_main.run` is called it waits for the promise to be fufilled, I don't quite know how `Isolinear` works but the `run` is called in an effect there so maybe waiting for that promise stops things temporarily. I also just realised that although it talks about a separate thread a lot I think you have to use `Lwt_preemptive.detach` to actually run the promise in a seperate thread

**Comment by Akin909** [comment]
Scratch that `lwt_preemptive.detach` is intended for long running *non*-lwt functions

**Comment by Akin909** [comment]
I might have jumped in too heavily on the `Lwt` aspect of things I guess something to also consider is rendering/processing the tree

**Comment by Akin909** [comment]
Ok I'll stop spamming this thread I'll look into it (unless someone else has already), it could be that I'm misusing `Lwt` in parts :thinking:

**Comment by Akin909** [comment]
Dropping the `maxDepth` to `5` or so completely resolves the issue in large directories on my machine, although before implementing that I'm going to look into if/how I can get `Lwt` to handle this differently.

**Comment by bryphe** [comment]
Cool, thank you for investigating this @Akin909 ! 💯 

> Dropping the maxDepth to 5 or so completely resolves the issue in large directories on my machine, 

This seems reasonable - we don't expand directories by default, I don't think, so would it be OK to just use a `maxDepth` of `1` for the initial load - and then go deeper when the user expands a folder? 🤔

**Comment by Akin909** [comment]
@bryphe tbh that's definitely doable its probably what I'd have done from the outset if I'd implemented it with the depth concept at the beginning as all the folders are closed on load. I actually tested with one when implementing the depth, there's no real difference to the user :man_shrugging:.

But yeah it would be nice for `Lwt` to handle all the processing of to the side and only report back when the tree is loaded

**Comment by bryphe** [comment]
Fixed by #320
