### ISSUE TITLE
Latest release, 0.5.3, does not build

### ISSUE THREAD

**Issue by glennsl** [onivim/oni2#3111]
It was broken when https://github.com/CrossR/reason-fzy/pull/1 was merged and a commit pointed to by oni2 was removed. In master this was fixed in #3101, but there's been no release since with this fix back-ported.

I understand that making sure these releases keep building is not a very high priority. But for Linux users, and Arch users in particular, as long as there's no working auto-update functionality it would be nice if the latest release would build so that we can also keep up-to-date, with relatively stable releases, using the system package manager.

To that end, avoiding dependencies that reference specific commits when punching a release would probably help a great deal.

**Comment by bryphe** [comment]
Thanks for the heads up @glennsl 

> To that end, avoiding dependencies that reference specific commits when punching a release would probably help a great deal.

I agree, this would be ideal. In the meantime - I've restored the missing commit: https://github.com/bryphe/reason-fzy/commit/ab172e16602bf20685440a282524a29c63e0d94a
