### ISSUE TITLE
```:tabedit FILENAME``` opens 2 tabs at once, both FILENAME and the file from which opening

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3150]
I noticed a small bug that is a minor daily annoyance (Ubuntu 20.04, Onivim 2 (0.5.9-nightly) ).

If I am editing a file FILE_1 and I open a new tab with ```tabedit FILE_2```, the new tab has both the FILE_1 and FILE_2 buffers open.

Before doing the tabedit:

![Screenshot from 2021-02-17 08-54-01](https://user-images.githubusercontent.com/8382834/108172970-d0613380-70fd-11eb-8e56-3476edf77407.png)

After the ```:tabedit assert_tools.h``` (note that 2 buffers are open in the last tab, both vector_and_quaternion.h from which I issued the tabedit, and assert_tools.h:

![Screenshot from 2021-02-17 08-54-11](https://user-images.githubusercontent.com/8382834/108172986-d525e780-70fd-11eb-9ba3-22c06bc2b98d.png)

**Comment by jerabaul29** [comment]
(i.e., I would like / think it would be more logical, in the second screenshot, to only have the assert_tools.h buffer opened, see the top list of buffers; the list of tabs as seen at the bottom list of tabs looks good)

**Comment by AakashMallik** [comment]
Yup. I was having fun switching to Tab->Window->Buffer mindset from the VSCode world but this was really offputting for me to have an extra file opened every time I opened a new tab. Glad it is being tracked.

**Comment by jerabaul29** [comment]
Any update on this? It is actually really painful in daily life, because it introduces "cognitive dissonance". If I ```:tabedit``` to look at some file, and then ```:q```, I expect that I am back to the "initial" state of matters, but it is not the case, since I now have one more tab... Even though I know about this bug, I get bitten by it and confused several times a day. Any way around / setting to kill the bug or similar @bryphe ? :)

**Comment by bryphe** [comment]
Should be fixed now with #3755 ; feel free to re-open if you still hit this.
