### ISSUE TITLE
Opening folder doesn't work for network share (in latest nightly)

### ISSUE THREAD

**Issue by taffit** [onivim/oni2#3151]
When trying to open a folder on a network share (`\\WSL$\Ubuntu\home\admin\myfolder\`), it doesn't do anything in the latest nightly build 0.5.9-nightly | d35adc3c on Windows. Tried it with clicking on a button, `:cd <path>` as well as File -> Open Folder. No updates in the Explorer view at all.    

It works perfectly fine on 0.5.3-stable, where it changes to the directory and immediately shows the file tree in the Explorer view.

**Comment by bryphe** [comment]
Thanks for logging the issue, @taffit  - and for discovering that it doesn't reproduce on `0.5.3`, that's really helpful.

I'm investigating, believe this could be a regression from: https://github.com/onivim/oni2/pull/3142 - that PR moved from using strings as paths to strongly-typed paths, but it seems the path parsing doesn't handle UNC paths.
