### ISSUE TITLE
Cannot type ' and " on windows

### ISSUE THREAD

**Issue by duncte123** [onivim/oni2#3157]
As the title suggests I cannot type `'` and `"` in the editor no matter how hard I try. A workaround is to type the quote in notepad and copy-paste it into oni2.

Edit: same applies to the integrated terminal

Version info:
![image](https://user-images.githubusercontent.com/8843386/108327084-467f9c00-71cb-11eb-93cf-b0d9508f44b9.png)

**Comment by bryphe** [comment]
Hi @duncte123 ,

Thanks for logging the issue.

I'm trying to reproduce this - but having trouble. A few pieces of extra info might help narrow this down:

1) What keyboard layout are you using? Is it English, English International, German, Romaji, etc?

2) Do you have any custom configuration or keybindings set?

3) We could also look at the log - with `Control+Shift+P` -> "Debug: Log to trace file" - and then press a `'` or `"` key, and then exit Onivim. The log should give us some clues about why the key isn't working.

Thanks for the help -

**Comment by duncte123** [comment]
My keyboard layout is set to US International and there's no keybinding set to any of the keys.

As for the log file, I'm having trouble locating it and windows explorer can't seem to find it either.

**Comment by duncte123** [comment]
Ok I managed to locate it, It ended up in the folder the editor was open in but I expected it to be in some appdata folder
[onivim2-trace.log](https://github.com/onivim/oni2/files/6008862/onivim2-trace.log)

**Comment by bryphe** [comment]
Thanks @duncte123 for the details! Very helpful.

At first, I thought I wasn't able to reproduce it - I found that:
- <kbd'</kbd> + <kbd>a</kbd> -> á
- <kbd>'</kbd> + <kbd>space</kbd> -> '

But, looking through your log, I saw that you pressed <kbd>'</kbd> repeatedly - on Windows, we'd expect:
- <kbd>'</kbd> + <kbd>'</kbd> -> '' 

However, nothing was being output. There was a bug in our keyboard handler where we were resetting the dead-key state.

Working on a fix in #3166
