### ISSUE TITLE
file explorer is not refreshing on new files

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#3158]
I built oni2 from master today (using arch) and noticed that if I open a folder and then create a new file by  `:e newfile.txt`
and then save that file, the file explorer doesn't show the file. Its the same if I create the file externally by terminal or os file explorer.
Also tested renaming files from outside oni and that wasn't reflected either.

It seems like the filesystem events are not working as they should.

EDIT: Also tested with the appimage nightly build and that has the issue as well.

**Comment by nikbrunner** [comment]
I have the same problem.

**Comment by AakashMallik** [comment]
@kinglouie https://github.com/onivim/oni2/issues/2056
Duplicate?

**Comment by bangursis** [comment]
Don't know if it's an OS-dependent problem, but I have the same problem with Manjaro and Ubuntu

**Comment by iilonmasc** [comment]
I encountered this as well on Linux, Macos and Windows
