### ISSUE TITLE
Quick Open does not have an ideal approach when it comes to long file paths

### ISSUE THREAD

**Issue by AakashMallik** [onivim/oni2#3175]
![Screenshot from 2021-02-21 16-59-33](https://user-images.githubusercontent.com/19551058/108623710-68487f80-7466-11eb-915d-08dcf3eb9635.png)

In my opinion, either showing the end of the path or having a marquee approach would be better from a UX point of view. 

I recently bought OniVim2 and I wish to make it my daily driver. I am super impressed by the editor but there are a few rough edges here and there. This is one of them. 

A point to note is that this behaviour majorly happens for files that are out of the CWD of Oni. Thus forcing it to show the full path.

**Comment by kinglouie** [comment]
The same issue is literally 3 below yours

**Comment by AakashMallik** [comment]
> The same issue is literally 3 below yours

Oh. Thanks, I'll close it.
