### ISSUE TITLE
MacOS: Unbound command strings are inserted in Insert Mode

### ISSUE THREAD

**Issue by maxdietrich** [onivim/oni2#318]
Actual behavior: When one presses Cmd + anything that isn't a configured key binding (e.g. Cmd + A) in Insert Mode in MacOS, the resulting command string is inserted into the current buffer. This doesn't happen when pressing a valid keyboard shortcut (e.g. Cmd + P).

![image](https://user-images.githubusercontent.com/6197482/57524663-c1463280-7328-11e9-900e-36a9e8d59438.png)

Expected behavior: Cmd + ? combinations that are not bound keyboard shortcuts should not insert anything.

**Comment by CrossR** [comment]
As far as I can see, #138 fixed this!

Closing this out, but drop a comment if that isn't the case and we can re-open this.

**Comment by alex-ketch** [comment]
Hi there, I still seem to be experiencing this on MacOS 10.14.6:
Version: 2.0.2.0
Date: 2019-08-17, 10:15:59 PM
Commit: 4a4826a

In the recording below I'm pressing `CMD + Alt` but it seems to be interpreted as `CMD + Alt + -`
![Kapture 2019-08-18 at 20 21 00](https://user-images.githubusercontent.com/1646307/63232429-f26eb280-c1f5-11e9-92ea-045ec890764b.gif)
