### ISSUE TITLE
Text with same VS Code settings for font and font size looks smaller

### ISSUE THREAD

**Issue by Siilwyn** [onivim/oni2#3198]
Using the same font settings comparing VS Code and Oni gives a smaller font by the looks of it.

**Config**
```
"editor.fontSize": 16,
"editor.fontFamily": "Fira Code",
```

**Screenshots**

Oni
![image](https://user-images.githubusercontent.com/5701149/109427007-a9a1d780-79f0-11eb-805c-8e4d485f79dd.png)

VS Code
![image](https://user-images.githubusercontent.com/5701149/109427042-d8b84900-79f0-11eb-9ea4-13a7c718cb8b.png)

Tested on Linux Fedora 33 with a 1920x1080 screen 100% scale, Oni 0.5.3.

Wondering where this difference comes from, comparing to 16px text in another native text editor it does look like the font is too small for 16px in Oni.

**Comment by bryphe** [comment]
Hi @Siilwyn ,

Good question - it does seem like the font is incorrectly sized in your screenshot.

Would it be possible to see the full `configuration.json`, just in case any other settings are set that could have an impact (ie, `"ui.zoom"`)? 

A log file might help too, if you run Onivim with logging, like: `./Onivim2-x86_64.AppImage -f --debug --log-file=debug.log`.

That would show us a few interesting bits - like if Onivim is picking up the screen scale incorrectly, and that it is loading the correct font size.

**Comment by Siilwyn** [comment]
Hi @bryphe

My whole `configuration.json` is quite minimal:
```
{
  "workbench.colorTheme": "GitHub Dark",
  "editor.fontSize": 16,
  "editor.fontFamily": "Fira Code",
  "vim.useSystemClipboard": true
}
```

[The debug.log](https://github.com/onivim/oni2/files/6074674/debug.log), I did open it on an external monitor this time but the font size looks exactly the same.
