### ISSUE TITLE
"Couldn't get esy version"

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni2#3199]
I was trying out the latest Oni with some reason native code, and got this UI error in Oni. 

Repro:

```
npm install -g pesy
mkdir deleteme
cd deleteme
pesy
```

Everything builds fine.

Then I open Oni, and `:cd deleteMe/`, open `deleteMe/library/Util.re`, and I get this error message:
<img width="717" alt="Screen Shot 2021-03-01 at 1 56 42 AM" src="https://user-images.githubusercontent.com/977348/109481676-e6da8980-7a31-11eb-9062-24fe286db8d1.png">

It's coming from this line:
https://github.com/onivim/oni2/blob/a2b024d4aaaa006f91f55a846550182028cb8db7/extensions/reason-vscode/src/index.js#L125

I manually `cd` into that directory in my terminal and run `esy --version` and it prints out

```
esy --version
0.6.7
```

I haven't tried Oni with native code in a long time, so I am not suggesting this was a problem with the latest update, but rather maybe just something with using the set of packages that pesy installs by default:

Here's the `package.json` pesy creates: I wouldn't expect this to "just work", but I just couldn't understand why it can't even run the version command successfully. Curious if you know why.

```
{
  "name": "deleteme",
  "version": "0.1.0",
  "description": "Starter Reason Project",
  "esy": {
    "build": "dune build -p #{self.name}",
    "buildDev": "pesy build",
    "release": {
      "rewritePrefix": true,
      "releasedBinaries": [
        "DeletemeApp"
      ]
    }
  },
  "pesy": {
    "azure-project": "esy-dev/esy",
    "github": "esy/pesy-reason-template"
  },
  "buildDirs": {
    "library": {},
    "bin": {
      "imports": [
        "Library = require('deleteme/library')"
      ],
     "bin": {
        "DeletemeApp": "DeletemeApp.re"
      }
    }
  },
  "scripts": {
    "start": "esy x DeletemeApp"
  },
  "dependencies": {
    "@opam/dune": "*",
    "@esy-ocaml/reason": "*",
    "@pesy/esy-pesy": "0.1.0-alpha.11",
    "ocaml": "~4.9.0"
  },
  "devDependencies": {
    "@opam/merlin": "*",
    "@opam/ocaml-lsp-server": "ocaml/ocaml-lsp:ocaml-lsp-server.opam",
    "refmterr": "*"
  }
}
```

**Comment by bryphe** [comment]
Thanks for logging the issue and the details, @jordwalke !

> Here's the package.json pesy creates: I wouldn't expect this to "just work", but I just couldn't understand why it can't even run the version command successfully. Curious if you know why.

It actually should "just work" - there's 3 things we need:
1) `esy` in the PATH
2) `@opam/ocaml-lsp-server` as a devDependency (to provide the `ocamllsp` binary)
3) Onivim opened to the folder containing the `package.json` or `esy.json`

I tried it out (note that I had to use `pesy@latest`)

Based on the error you're seeing - it seems like there is a bug in the first condition, where Onivim isn't finding `esy` in the PATH:

> Then I open Oni, and :cd deleteMe/, open deleteMe/library/Util.re, and I get this error message:

I'm wondering how you started Oni - was it from the terminal or finder? Would be interesting to see:
- The output of `echo $PATH` in Onivim
- If running `:term` and then `esy --version` works

Also, is `zsh` your default shell, or do you use another?

**Comment by bryphe** [comment]
I added some debug logging in this branch here: https://github.com/onivim/oni2/commit/2a86f0f02742efdc1758e211d646d72ce2060f86 (https://github.com/onivim/oni2/tree/investigate/3199/logging-for-path)

The tricky thing about this is that, when we last investigated, it only reproduced when launching from Finder (launching from Terminal worked). So I'm curious to see what environment the `reason-vscode` extension sees when it tries to run `esy --version`

My suspicion is that something is going wrong here: https://github.com/onivim/oni2/blob/2a86f0f02742efdc1758e211d646d72ce2060f86/src/Core/ShellUtility.re#L225 - which is the codepath we use to patch the `PATH` which doesn't come through by default when launching via Finder. But seeing the environment of the extension host will help make sure we're looking in the right direction.

**Comment by bryphe** [comment]
Able to reproduce this now setting the login shell to `bash` on Catalina:

```
Starting log file...
Checking esy version, for projectPath: /Users/bryphe/deleteme
Ambient environment: {
  ...
  "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
  ...
}
Unable to get esy version: Error: Command failed: esy --version
/bin/sh: esy: command not found

Unable to get ocaml-lsp-server binary: Error: Command failed: which ocamllsp
Esy not found, falling back to RLS: null
```
