### ISSUE TITLE
using onivim2 for C++ development: layer and setup

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3212]
I am on Ubuntu 20.04, using the latest Onivim2 build.

I am considering the C++ layer documentation and help-page here: https://onivim.github.io/docs/languages/c

A few comments:

- the link to exuberant-ctags seems to be dead
- I cannot find much hit for exuberant-ctags on the internet. The github and sourceforge pages seem to be long dead.

Would it make more sense to change to this as the ctag generation engine? https://github.com/universal-ctags/ctags At least it seems well maintained and alive :) . Not sure how this should be provided through an extension though.

**Comment by bryphe** [comment]
Ah, good catch - thanks @jerabaul29.

Ya, the extension was this one [chrisweeldon.exuberant-ctags](https://github.com/chriswheeldon/vscode-ctags) but unfortunately it is no longer on open-vsx (there is a tracking issue here - https://github.com/chriswheeldon/vscode-ctags/issues/4)

We could look at forking and publishing if it is desirable or there is a use case not covered by `clangd` - `clangd` is really nice for C/C++ though

**Comment by bryphe** [comment]
In the meantime - I'll remove the `ctags` mention for now
