### ISSUE TITLE
error trinying to install clangd

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3213]
Trying to follow the layer manpage to install clangd (from https://onivim.github.io/docs/languages/c ) , I get:

```
~$ oni2 --install-extension llvm-vs-code-extensions.vscode-clangd
Error querying catalog: Utility__LwtEx.Timeout
Failed to install extension: llvm-vs-code-extensions.vscode-clangd
```

**Comment by bryphe** [comment]
Hmm, I just ran the command and it succeeded:

```
➜  ~ oni2 --install-extension llvm-vs-code-extensions.vscode-clangd
Successfully installed extension: llvm-vs-code-extensions.vscode-clangd
```

I'm wondering if this was an intermittent connectivity issue - could you please retry and see if you have better luck?

Could be related to this: https://github.com/onivim/oni2/pull/3123 if it's an older build

**Comment by jerabaul29** [comment]
You are right, working now. Strange. Closing.
