### ISSUE TITLE
Installed Extensions not running

### ISSUE THREAD

**Issue by HakKet** [onivim/oni2#3215]
Hi,

I am using Onivim 2 version 0.5.9-nightly on Windows 10
I have installed all of the 3 extensions by using the command `oni2 --install-extension`.

The extensions installed are : 

- Live Server - Ritwick Day,
- open in browser - techer,
- jumpy - wmaurer

I can see all of them in the Extensions pane and their commands seem also available (CTRL+shift+P).

None of the extensions are working. 

PS: The result of `oni2 -f --quiet` is enclosed as text file

[oni2_20210303_1545.txt](https://github.com/onivim/oni2/files/6076023/oni2_20210303_1545.txt)

**Comment by bryphe** [comment]
Hi @HakKet ,

Thanks for logging the issue. Taking a look through some of the extensions - they expose some missing APIs:

1) Live Server

- Our `$findInFiles` implementation isn't respecting the max count - so we end up traversing further than needed (blocks the status bar from loading the `Go Live` item)
- Our `$findInFiles` implementation will return an error if a `stat` call fails, which isn't correct
- The `vscode.workspace.saveAll` API wasn't implemented

2) Open in browser

The open in browser extension wasn't being activated as expected - Onivim wasn't sending a proper activation event in this case.

3) The jumpy plugin relies on implementing the text decoration API - looking at tracking here: https://github.com/onivim/oni2/issues/3189

I'll use this issue to track fixes for 1) and 2) though - 1) is related to a PR I just opened recently: https://github.com/onivim/oni2/pull/3225

**Comment by HakKet** [comment]
Closing this issue.
Thank you.
