### ISSUE TITLE
Request: Middle clicking on an open tab to close tab

### ISSUE THREAD

**Issue by Apostolique** [onivim/oni2#322]
Add middle clicking to close an open tab.

Bonus request: Middle clicking on an empty spot on the tab bar opens a new tab with an empty buffer.

**Comment by thangngoc89** [comment]
I worked on this a little bit and found out this is blocked by Revery. I sent a PR for address this here https://github.com/revery-ui/revery/pull/517 

But it looks like revery changed a little between 0.7.0 (what oni2 is using) vs the current master 0.23.0. So I would say this issue is blocked.
