### ISSUE TITLE
FOSS or die

### ISSUE THREAD

**Issue by brennanfee** [onivim/oni2#324]
I am severely distressed to see you guys switching to a commercial license.  Sadly, I and others will need to look elsewhere for the editor we have always wanted (vim-like modal editing, but with VS Code's plug-in flexibility and a modern UI).

Disappointing.  You should seriously reconsider your choice and continue with FOSS or your project will likely fail to reach a significant user base.

**Comment by dreamwavedev** [comment]
As I understand their license, it is indeed free and open source with the sole restriction being that that license only applies for non commercial use, and they are making a concession on that point in that after a certain period of time (18 months) any code written before that time becomes fully FOSS by being dual licensed under MIT, and is already fully open _source_ in that the contents of all components may be read in full source form for all individuals.

In my opinion this is a very effective monetization model, and shows a nice balance between providing incentive to contribute by paid contributors (solely bryphe at the moment) and recognizing and supporting the open source community. To omit the fact that there is a time-bomb license that makes code older than 18 months completely free (as in freedom and as in money) seems disingenuous and unfair, considering how much thought they put into figuring out such a strategy.

**Comment by bryphe** [comment]
Great summary @dreamwavedev - couldn't have said it better myself! Thank you for jumping in!

>  To omit the fact that there is a time-bomb license that makes code older than 18 months completely free (as in freedom and as in money) seems disingenuous and unfair, considering how much thought they put into figuring out such a strategy.

Agreed - IMO, this model is very exciting in helping us strike a balance between a funding model and giving back to the OSS community. And to add: what ends up getting open sourced at the 18 months is _better_ than what would've been open-sourced without funding!

Not only that... we've also opened-sourced under MIT some critical pieces of Onivim, like [Revery](https://github.com/revery-ui/revery).

The reality is that building a quality product takes time and resources. The work on our v2 simply __wouldn't be possible without a funding model.__ I would love to build a free product - but the fact is, our v2 simply wouldn't exist at all without funding. 

@brennanfee, I read your message as you saying is you want people to work for free, to give you something for free, without you contributing anything back. That is doesn't seem very reasonable to me at all.

Your sense of entitlement - that you should get something for free, without contributing anything back - means at the end of the day, our community is better off without you.
 
I'll close and lock this for now, as I don't see any meaningful discussion past this. I'd prefer to focus my time and attention on the users that actually __want to help us on our mission of building a great editor__!
