### ISSUE TITLE
Notifications: Window opens with a jerky motion

### ISSUE THREAD

**Issue by marcagba** [onivim/oni2#3245]
Not sure since which update but notification windows can open with a jerky motion when some horizontal splits have been created.

Here a repro recording

https://user-images.githubusercontent.com/14045559/110391481-c9c43d00-8067-11eb-8094-c5822a50580a.mov

**Comment by bryphe** [comment]
Thanks for logging the issue and including the video @marcagba! 

Ya, the animation sure is glitchy... I'll remove it for now (a glitchy animation is worse than no animation...), potentially will revisit with a more robust animation strategy.
