### ISSUE TITLE
Oni 2 doesn't support libinput smooth scroll events

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#325]
This might be a little early to start asking for this, but it seems one of the goals of Oni 2 was to have smoother, more responsive, viewport movement and scrolling. On linux it doesn't currently seem to listen to or support LIBINPUT_POINTER_AXIS_SOURCE_CONTINUOUS and related discrete events to allow for smooth scrolling on devices using libinput. What work is required to get something along these lines working?

**Comment by bryphe** [comment]
> This might be a little early to start asking for this, but it seems one of the goals of Oni 2 was to have smoother, more responsive, viewport movement and scrolling.

Definitely!

> On linux it doesn't currently seem to listen to or support LIBINPUT_POINTER_AXIS_SOURCE_CONTINUOUS and related discrete events to allow for smooth scrolling on devices using libinput.

Good catch... We're using GLFW (backed by X11) for input handling on Linux - which looks like it uses X11 events for processing scroll:

https://github.com/glfw/glfw/blob/51bb76c7c3de934b2dd3affcdc297a32e4817835/src/x11_window.c#L1400

(And they are discrete events, vs something smoother...)

Using `libinput` sounds like it could help here... We'd basically need Reason hooks to those APIs, to listen to input events - and use them instead of the default scroll events. Not sure if there would be any issues or conflicts the X11 input strategy used by GLFW.

**Comment by szbergeron** [comment]
As I understand it, Wayland and X11 handle it differently but are both able to provide the same amount of information if XInput2 is used. I'd have to look into it further, but I know this is how GTK is able to provide continuous scroll events on both X11 and Wayland with Libinput and even the older Synaptics driver in a lot of cases.

**Comment by bryphe** [comment]
> EDIT: Looks like the GLFW folks already know about this: glfw/glfw#1376

Nice find @szbergeron ! Good catch - seems like a bug that GLFW doesn't use the latest smooth scrolling APIs.

> E2: Now I wonder what it does on Wayland, if I can get Oni2 running on a wayland session I'll report back on what happens.

Unfortunately there is a blocking bug for this at the moment - our build of GLFW isn't set up to build wayland (today): https://github.com/bryphe/reason-glfw/issues/69

**Comment by szbergeron** [comment]
For GLFW not having a build support both X and Wayland is definitely not awesome, I'll see if I can peek around their source code and start making some patches. I'm not super familiar with the intricacies of Xinput2 but I can try my hand at it.

**Comment by bryphe** [comment]
Ya, it's a bummer that it needs separates builds for X / Wayland.

> I'll see if I can peek around their source code and start making some patches. I'm not super familiar with the intricacies of Xinput2 but I can try my hand at it.

That would be awesome - thanks for the help!

**Comment by szbergeron** [comment]
Update from discussion on discord:

I'm looking into handling all input with Revery rather than pulling from GLFW, just because of the flexibility that would provide in how input gets handled, and should make this "just work" based on changes in Revery.

**Comment by szbergeron** [comment]
This is entirely downstream at this point (revery, sdl2, libscroll) so probably doesn't need to be tracked here anymore
