### ISSUE TITLE
How to refresh the files explorer

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3253]
I understand that the files explorer does not refresh automatically, for example when copying some files to the current folder using the command line these do not appear. If possible, it would be great if it could actually do refresh automatically (attempting once a second? each half second? or is there another way of doing that than "pulling").

In the absence of an automatic refresh, is there a way to manually force a refresh? That would be most useful.

**Comment by Apostolique** [comment]
You can do `:cd .`

**Comment by morganhein** [comment]
> You can do `:cd .`

This didn't refresh anything for me. Performing `:cd <someDir>` and then `:cd ..` did refresh though.
