### ISSUE TITLE
<C-w> waits to be executed in command palette

### ISSUE THREAD

**Issue by BenoitPingris** [onivim/oni2#3262]
Oni version: 2b0be8b1

`<C-w>` is not executed right away in the command palette, I guess it waits  `timeout`  ms for an extra command to be executed (like `h/j/k/l` to move to a split for example).

It shouldn't wait when the editor is in `Command Line` mode, I guess.

**Comment by bryphe** [comment]
Thanks @BenoitPingris for catching this!

>  I guess it waits timeout ms for an extra command to be executed (like h/j/k/l to move to a split for example).

> It shouldn't wait when the editor is in Command Line mode, I guess.

Ya, this is exactly right 👍  I need to fix the condition for the window commands
