### ISSUE TITLE
Documentation - font smoothing default is not listed

### ISSUE THREAD

**Issue by sandersac** [onivim/oni2#3266]
In the [configuration documentation](https://onivim.github.io/docs/configuration/settings) under "Configuration Settings" -> "Editor" ->"editor.fontSmoothing", the default setting is not listed like the other configuration settings.

**Comment by bryphe** [comment]
Thanks for catching this, @sandersac ! I would like to auto-generate these docs, eventually... would help eliminate this sort of issue.
