### ISSUE TITLE
Some file didn't have syntax highlight.

### ISSUE THREAD

**Issue by ahmadshiddiq** [onivim/oni2#3271]
This is one of the sample files I take, this file was detected as `javascriptreact` and the strange is, it didn't have syntax highlight even the file was detected. The problem was found on the `css` file too.
But on `package.json` the syntax highlight does not have a problem there.

![image](https://user-images.githubusercontent.com/53107961/111175065-98ed8600-85da-11eb-8be8-de34a14f7135.png)

**Comment by ahmadshiddiq** [comment]
This is after I installed the postcss plugin after I remove the syntax highlight back to normal.

**Comment by bryphe** [comment]
May be related, or the same issue (as postcss plugin brings in `embededLanguages`) as https://github.com/onivim/oni2/issues/2998
