### ISSUE TITLE
Search selected text in project

### ISSUE THREAD

**Issue by lougreenwood** [onivim/oni2#3277]
possibly related to https://github.com/onivim/oni2/issues/943

My first issue here, excellent work on onivim.... I spent weeks earlier this year learning and setting up nvim, but this project convinced me to ditch that effort and adopt onivim, so much nicer DX to use vscode plugins and not waste time configuring language servers etc... I already bought a license!

Anyways....

In vscode, it's possible to select some text, press `cmd-shift-f` and perform a project search with that text. This is a super useful workflow.

it would be really great to do this in onivim.

**Comment by bryphe** [comment]
Hi @lougreenwood ,

Thanks for logging the issue and the words of encouragement 😎 

> In vscode, it's possible to select some text, press cmd-shift-f and perform a project search with that text. This is a super useful workflow.

Totally, this would be nice to have - looking at it in #3287

**Comment by grahambates** [comment]
The more vim-like equivalent of this behaviour is provided by the [Visual Star](https://github.com/nelstrom/vim-visual-star-search) plugin. It allows you to just hit `*` with text selected, just like you normally would to search for the word under the cursor without a selection. The VS Code Vim extension has a 'Visual Star' option to emulate this.

I don't know whether you'd consider adding this key binding to OniVim2 or wait for Vim plugin support to use the existing plugin.

**Comment by lougreenwood** [comment]
@grahambates AFAIK, visual star is only for searching in the current file? This issue is concerned with searching in all files.

Although I am looking forward to being able to use the visual star plugin to search selected text in a file, it's super useful when combined with `cgn` as a replacement for multi-cursor-like editing: https://medium.com/@schtoeffel/you-don-t-need-more-than-one-cursor-in-vim-2c44117d51db

**Comment by grahambates** [comment]
Yeah you're right, I was thinking of `cmd-f` with text selected which also works in vscode but not in onivim.

**Comment by lougreenwood** [comment]
@bryphe works well in nightly, thanks for implementing this! 🙏
