### ISSUE TITLE
Can't use emmet in jsx or tsx

### ISSUE THREAD

**Issue by ahmadshiddiq** [onivim/oni2#3283]
I was coding with react lately, but I don't think that seems to support emmet on javascript react, I already change the filetype to HTML too, but it doesn't work.
Can I manually support emmet on my javascript-react?

**Comment by bryphe** [comment]
Added documentation in #3296 , and fixed a completion sort order issue in #3298 - this should now be supported via setting:

```
  "emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "typescript": "typescriptreact"
  }
```
