### ISSUE TITLE
will it run on FreeBSD?

### ISSUE THREAD

**Issue by catastrop** [onivim/oni2#329]

**Comment by bryphe** [comment]
Hi @catastrop ,

No plans at the moment for FreeBSD. I'm looking at the following initial platforms for our downloadable builds:

- Windows 10 
- Mac OS High Sierra
- Linux: Latest Arch & Ubuntu

If anyone is on FreeBSD - please 'upvote' this issue so I can get a sense of priority 👍 

(I would love to support as many platforms as we can - just a matter of time / prioritization)

**Comment by catastrop** [comment]
@bryphe, You should also expand your Linux platform to RPM based system like Fedora.

**Comment by bryphe** [comment]
Thanks for the suggestion @catastrop ! I updated my list above with a prioritization order of the package types we're working towards.
