### ISSUE TITLE
Relative line numbers are turned off when typing a command

### ISSUE THREAD

**Issue by peternoordijk** [onivim/oni2#3299]
[![Image from Gyazo](https://i.gyazo.com/ce22e83517797cd68aa2350b4e0cd6dd.gif)](https://gyazo.com/ce22e83517797cd68aa2350b4e0cd6dd)

I'm using `Version 0.5.9-nightly (0.5.1829)`

Besides this issue I would also like to say Onivim 2 is looking a lot better already since last time I gave it a try 😊 I'm really looking forward to this editor getting stable

**Comment by BenoitPingris** [comment]
With 82d7c432 I do not have this issue, I tried with your configuration `editor.lineNumers: "relative"` and also with the vim configuration `set relativenumber`. In both cases it works.
Maybe try again with the latest nightly build

**Comment by peternoordijk** [comment]
@BenoitPingris ah yes you're right! I tried it out just now. Awesome! 🎉
