### ISSUE TITLE
Bug - Find dialog stays open after losing focus

### ISSUE THREAD

**Issue by lougreenwood** [onivim/oni2#3304]
After opening the find dialog (`/` or `?`), and then clicking somewhere in the UI, the dialog remains open, but key presses do not populate the dialog - it is also not possible to close it with `esc`.

To close the dialog after it loses it's focus, you must re-trigger it (`/` or `?`) and then close it using `esc`.

**Comment by bryphe** [comment]
Hi @lougreenwood ,

Which version are you on? The version + commit will be visible on the welcome screen:

![image](https://user-images.githubusercontent.com/13532591/111838191-333d1a80-88b6-11eb-999f-0834227d02aa.png)

I believe this might be similar to #3031 , and also addressed with https://github.com/onivim/oni2/pull/3146 - but wanted to double-check - that fix is in nightly, but not yet in the stable (0.5.4) build

**Comment by lougreenwood** [comment]
Yep, fixed in nightly, thanks 👍
