### ISSUE TITLE
Bug - "workbench.tree.indent" does not seem to work?

### ISSUE THREAD

**Issue by lougreenwood** [onivim/oni2#3305]
I've tried to increase the indent of the file selector tree, but `workbench.tree.indent` doesn't seem to work.

I've tried to set this value to `12`, but nothing changes.

**Comment by bryphe** [comment]
Ouch, thanks for logging this! I missed bring this configuration back over as part of some refactoring - working on bringing it back in #3307 👍

**Comment by lougreenwood** [comment]
All good now, thanks!
