### ISSUE TITLE
Extension Code Spell Checker can't add word to user dictionary

### ISSUE THREAD

**Issue by zetashift** [onivim/oni2#3335]
Extension: https://open-vsx.org/extension/streetsidesoftware/code-spell-checker works fine for reporting spelling mistakes. However I can't seem to add words that are fine, but the dictionary does not know yet (including `onivim`), to the user dictionary? I tried adding the word through the `showCommands` menu and a keybinding, both didn't work:
```json
{
    "key": "zg",
    "command": "cSpell.addWordToUserDictionary",
    "when": "!insertMode"
}
```

On Linux x64. Pop_Os 20.10 using Onivim Onivim 2 (0.5.9-nightly) `2b0be8b1`

**Comment by bryphe** [comment]
Thanks for the issue @zetashift !

Just looked into this - there's actually two problems:

Issue 1 - the spell-checker extension checks the current text editor selection, and if there is one available, it'll pick up that word:

https://github.com/streetsidesoftware/vscode-spell-checker/blob/66e056cf829f4845d71e9f072987886e6e5855ff/packages/client/src/commands.ts#L124

There's a bug on the Onivim side - it's not properly synchronizing this selection. 

Issue 2 - If there isn't a selection, the spell-checker pops open a QuickInput - this is currently unhandled by Onivim:

https://github.com/streetsidesoftware/vscode-spell-checker/blob/66e056cf829f4845d71e9f072987886e6e5855ff/packages/client/src/commands.ts#L126

So unfortunately each possibility in that code-path isn't working correctly in Onivim.

__Workaround:__

Words can be manually added to the dictionary by adding them to the `"cSpell.userWords"` configuration, for example:
```
  "cSpell.userWords": [
    "Onivim"
  ]
```

**Comment by zetashift** [comment]
Hiya, thanks for looking into this! I'll keep the workaround in mind, and I wish I could help! 

@bryphe I'm not sure if it's okay to put it in this issue too or if it needs its own issue, but https://open-vsx.org/extension/valentjn/vscode-ltex is also bugging out a bit, mistakes get highlighted, but no real reporting is done, the "Problems" pane isn't reporting anything. 
This and the Markdown highlighting are the only things stopping me from using Oni2 as my daily note taking application. But for what it's worth, I am loving all the progress so far and thanks for all the hard work!

**Comment by bryphe** [comment]
Thanks @zetashift !

I logged a new issue for the LTeX issue: #3354  - was trying to reproduce it, if you have a simple file that reproduces that mistakes-but-no-reporting issue, that would be a huge help.

I think the markdown highlighting is likely tracked here: #3322
