### ISSUE TITLE
Paste from clipboard MacOS

### ISSUE THREAD

**Issue by polotto** [onivim/oni2#3353]
Hi,
Tried to paste some content from clipboard in a text file and I couldn't past. I tried cmd+V and p (in normal mode) but both failed. Is there a way to past content from clipboard in Oni2?

**Comment by bryphe** [comment]
Hi @polotto ,

Good question - you can paste from the clipboard in normal mode right now with <kbd>"</kbd><kbd>*</kbd><kbd>p</kbd> (where `"*` specifies to use the clipboard register for pasting).

Another option is that, if you find that you primarily use `p` to paste from the clipboard, you can customize the `vim.useSystemClipboard` setting: https://onivim.github.io/docs/configuration/settings#vim 

If you set `"vim.useSystemClipboard: true"` or `"vim.useSystemClipboard: ["yank", "paste"]`, the `p` paste would default to use the clipboard, unless some register was specified. Need to improve the documentation around that a bit.

Definitely a bug though that `Cmd+V` isn't pasting in normal mode - that should 'just work'!

**Comment by polotto** [comment]
Thanks @bryphe . I'm very glad with the Oni2 community. The people here are awesome. I'll keep posting problems since the people are very respectful.
