### ISSUE TITLE
has the tabs overview disappeared in the latest nightly version?

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3356]
Usually when I use tabs, these are displayed on a top bar of the editor, together with the name of the split file under focus, and the total number of splits. This is very convenient. For example:

With:

```
~/Downloads$ ./Onivim2-x86_64-stable.AppImage --version
Onivim 2 (0.5.4)
```

I get:

![Screenshot from 2021-04-01 16-53-09](https://user-images.githubusercontent.com/8382834/113312591-c04a8f80-930a-11eb-991c-fcf3b7cc553e.png)

-----------------

But with the latest nightly build:

```
$ oni2 --version
Onivim 2 (0.5.9-nightly)
```

I get by contrast, even with several tabs open:

![Screenshot from 2021-04-01 16-54-19](https://user-images.githubusercontent.com/8382834/113312769-ea03b680-930a-11eb-86ab-72f0c69090f9.png)

------------------

- Are you able to reproduce / is this a bug?
- If you are not able to reproduce, any idea what the problem is? I am running both on the same computer, would expect the same packages and config apply.

**Comment by bryphe** [comment]
Hi @jerabaul29 ,

Thanks for the screenshots! Very helpful.

> Are you able to reproduce / is this a bug?

At first I wasn't able to reproduce - but was able to do with this:
- `oni2 test.c`
- `:tabnew test.h`

On 0.5.4 - switches out of zen mode and shows tabs. On 0.5.9 - stays  in zen mode, tabs stay hidden.

Indeed it is a bug - possibly a regression from https://github.com/onivim/oni2/pull/3160

**Comment by bryphe** [comment]
Thanks @jerabaul29! 

It looks like this changed in https://github.com/onivim/oni2/pull/3160 - the behavior is controlled by a configuration setting, `"editor.zenMode.hideTabs": true` - looks like the default was tweaked in that PR. If you prefer the previous behavior, you can try setting this to `false` instead :+1:
