### ISSUE TITLE
No ellipsis in sidebar, selected items have cut-off background

### ISSUE THREAD

**Issue by SimonEggert** [onivim/oni2#3362]
Sidebar visuals are somewhat off right now:
- the scrollbar cuts off selection colors for items
- text is overflowing without ellipsis

![Screenshot from 2021-04-02 14-41-43](https://user-images.githubusercontent.com/33206628/113416925-99e82b00-93c2-11eb-9821-dadbc2c2fbbc.png)

For comparison, this is how it looks in VSCode, which feels more natural to me:
![Screenshot from 2021-04-02 14-43-20](https://user-images.githubusercontent.com/33206628/113416927-9a80c180-93c2-11eb-93b8-d46a51af876a.png)

I will be glad to help fix this if someone can point me in the right direction. I have already found the revery example where ellipsis are applied. Does this work in a `flexGrow` context or do we need to set an explicit width? 
Also, would these changes need to be made in this repo or are they affecting the general revery elements as well?

**Comment by z0al** [comment]
> Does this work in a `flexGrow` context or do we need to set an explicit width?

Based on my attempts, it doesn't seem to work unless I set an explicit width. Maybe it's a bug in the `flex` library or `revery`.
