### ISSUE TITLE
keybindings forced to be lower-case

### ISSUE THREAD

**Issue by keforbes** [onivim/oni2#3363]
I have this basic map in vim:
```
map H ^
map L $
```

I wanted to re-create it in oni.  The docs don't show how to map a vim key to a vim key so I made a random guess of trying:
```
  { "key": "H", "command": "^", "when": "normalMode" },  
  { "key": "L", "command": "$", "when": "normalMode" } 
```
The mapping didn't work, which isn't much of a surprise.  However, what surprised me is that it broke the `h` and `l` key bindings.  The cursor didn't move left or right when I pressed `h` or `l`.

As a test, I took this example from the docs:
```
{ "key": "jk", "command": "vim.esc", "when": "insertMode" }
```
and changed it to capital `JK`
```
{ "key": "JK", "command": "vim.esc", "when": "insertMode" }
```
Typing `JK` while in insertmode would actually type the characters `JK`, yet pressing `jk` would exit insert mode.  It seems all values of `"key"` are being set to their lower-case equivalent.

This was in the latest 0.5.9-nightly build.

**Comment by keforbes** [comment]
It seems the correct way to define a mapping with capital letters is:
```
{ "key": "<S-J><S-K>", "command": "vim.esc", "when": "insertMode" }
```
Which is indeed mentioned in the docs.  I guess I just find it weird.

**Comment by keforbes** [comment]
Sorry, I just realized this is already filed as #2925

**Comment by keforbes** [comment]
As for my `H` and `L` mapping, this kinda works:
```
  { "key": "<S-H>", "command": ":norm ^", "when": "normalMode" },
  { "key": "<S-L>", "command": ":norm $", "when": "normalMode" }
```
Except it only works for movement; I can't use it as a destination in an operation.  That is, `L` will move cursor to the end of the line but `dL` (which should be equivalent to `d$`, delete to the end of the line) will actually delete up until the default `L` location, the bottom of the displayed viewport.

**Comment by bryphe** [comment]
Hi @keforbes ,

> Typing JK while in insertmode would actually type the characters JK, yet pressing jk would exit insert mode. It seems all values of "key" are being set to their lower-case equivalent.

Yeah, this is one of the trickiest (non-technical) aspects of trying to bring Vim + VSCode together - they have different interpretations for what `J` means in the keybindings. VSCode keybindings require a `Shift+J`, whereas Vim treats `J` as having a shift.

So what we've tried to do is in the VSCode-like entry points (`keybindings.json`), we use the VSCode format, and in the Vim entry points (like `:map H ^`), we'd use the Vim-style interpretation.

Probably the best way to get what you want would be to use this configuration in `configuration.json`:
```
"experimental.viml": [
   "map H ^",
   "map L $",
]
```

**Comment by keforbes** [comment]
That's exactly what I was looking for, thanks @bryphe !
