### ISSUE TITLE
horizontal scrollbar missing

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#3372]
On todays master build with the filesystemevents I noticed that I am missing horizontal scrollbars on files with long lines. shift + scrollwheel does not work either.

**Comment by bryphe** [comment]
Hi @KingEdwardI ,

Interesting - we do have word-wrap on by default - when word-wrap is on, we don't show the horizontal scrollbar (because the lines get wrapped).

Does the scrollbar come back if you set `"editor.wordWrap": false` in your configuration? (Or - can run `:set nowrap`, just to test it out).

Wondering if this is due to the changed defaults, or if there is a bug in the wrap case (not wrapping fully), or if there is a bug in the no-wrap case (not showing scrollbar correctly). 

I wasn't able to reproduce when I tested on that build, though:

![2021-04-06 16 38 11](https://user-images.githubusercontent.com/13532591/113790646-a4722f80-96f6-11eb-99f2-2ca54337fe52.gif)

**Comment by kinglouie** [comment]
Just tested :set nowrap which activated a functioning horizontal scrollbar. After resetting by :set wrap the wordwrap now functions as expected even after a restart.

So for me it seems that due to some unfortunate configuration state the wordwrap feature was broken.

**Comment by kinglouie** [comment]
@bryphe after building from master with the latest fix for the file stat issue, this issue surfaces again. This is my config file:

```
{
  "git.ignoreLimitWarning": true,
  "ui.zoom": 1.3,
  "workbench.colorTheme": "Nord",
  "editor.detectIndentation": true,
  "editor.fontFamily": "JetBrainsMono-Regular.ttf",
  "editor.fontSize": 14,
  "editor.largeFileOptimizations": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.indentSize": 4,
  "editor.insertSpaces": true,
  "editor.lineNumbers": "relative",
  "editor.matchBrackets": true,
  "editor.minimap.enabled": true,
  "editor.minimap.maxColumn": 120,
  "editor.minimap.showSlider": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "none",
  "editor.rulers": [],
  "editor.tabSize": 4,
  "editor.zenMode.hideTabs": true,
  "editor.zenMode.singleFile": true,
  "files.exclude": [ "_esy", "node_modules", ".git" ],
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.iconTheme": "vs-seti",
  "workbench.sideBar.location": "left",
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true,
  "workbench.tree.indent": 2,
  "vim.useSystemClipboard": [ "yank" ],
  "window.menuBarVisibility": "hidden",
  "files.useExperimentalFileWatcher": true
}
```

Is there some other place where configuration is stored where I could check. I believe I can fix this again with the steps from my previous comment but I leave it as is for now so I can debug this issue.

**Comment by kinglouie** [comment]
@bryphe I found another issue with `:set nowrap`. the last few characters of the line can not be seen even if I am scrolled fully to the right and some more characters are behind the minimap bar. Ideally i could scroll to the right so far that the last character of the line is not behind the minibar.

here are to screenshots with the same line, one with `wrap` and one with `nowrap`

![2021-04-09-083654_1146x115_scrot](https://user-images.githubusercontent.com/8280409/114138983-b9291000-990e-11eb-903a-111b8f591ce4.png)
![2021-04-09-083627_1148x86_scrot](https://user-images.githubusercontent.com/8280409/114139011-c2b27800-990e-11eb-82b2-191b6f76ab94.png)

**Comment by bryphe** [comment]
Thanks for the screenshot @kinglouie !

Ya, this looks like a bug too - similar to #3405 , but maybe a different manifestation.

Just curious - is the indentation 'tab' characters or 'spaces'? I wonder if there is a bug with considering tab characters in the context of wrapping

**Comment by kinglouie** [comment]
Your assumption with the tabs may be correct because the file indeed has tab indentation

```
<?php
/*
Template name: Page - Legal Texts
*/
get_header(); 
$post_type = get_post_type();
require_once 'template-parts/page-nav.php';

?>

<?php do_action( 'flatsome_before_page' ); ?>

<div class="page-wrapper page-legaltexts">
	<div class="row">
		<div id="content" class="large-12 right col" role="main">
			<div class="page-inner">
				<?php while ( have_posts() ) : the_post(); ?>
					<?php if($post_type != 'page'): ?>
						<hr>		
						<?php echo $navigation ?>
						<hr>
						<?php
							$meta1 = get_post_meta($post->ID, 'ext_name_1');
							$meta2 = get_post_meta($post->ID, 'ext_name_2');
							$title1 = isset($meta1[0]) ? $meta1[0] : '';
							$title2 = isset($meta2[0]) ? ' <span class="title2"> - '.$meta2[0].'</span>' : '';
						?>
						<h1><?php echo $title1 . $title2 ?></h1>
						<hr>
					<?php endif; ?>
					<div class="legal-text">
						<?php the_content(); ?>
					</div>
					<hr>
					<?php echo $navigation ?>
					<?php echo do_shortcode('[gap height="50px"]') ?>
					<a href="https://www.pietsch-it.de/" target="_blank">
						<?php echo do_shortcode('[block id="74"]') ?>
					</a>
				<?php endwhile; // end of the loop. ?>
			</div>
		</div>
	</div>
</div>
<script>
	jQuery('.text-side').stickySidebar({
		containerSelector: '.legal-cols-wrapper',
		topSpacing: 110,
		bottomSpacing: 60,
		minWidth: 660,
		resizeSensor: true
	});
</script>

<?php do_action( 'flatsome_after_page' ); ?>

<?php get_footer(); ?>
```
