### ISSUE TITLE
Pressing Enter has no effect in the command palette 

### ISSUE THREAD

**Issue by haideralsh** [onivim/oni2#3375]
**Platform:** macOS Catalina 10.15.5 (19F101)
**OS keyboard language:** Canadian English

To Reproduce: 
1. Install a fresh copy of Oni2
2. Click on the "Unregistered" button in the top right of the window to open the license field
3. Enter any license key
4. Press Enter 

**Actual:** Nothing happens
**Expected:** The license field closes

The same thing happens when using `cmd + p` to select a file, pressing Enter does not open the file. Pressing enter inside a file to add a line break for instance, however, _does_ register.

**Comment by bryphe** [comment]
Hi @haideralsh ,

Thanks for logging the issue! I just tried to reproduce (using the Canadian English keyboard):

![2021-04-06 16 40 27](https://user-images.githubusercontent.com/13532591/113790765-fdda5e80-96f6-11eb-9667-ddb965ed94ed.gif)

I'm wondering, to narrow this down:
1) Do you have any custom configuration?
2) Do you have any custom keybindings?
3) In the `Cmd+P` menu, does clicking a file work?

**Comment by haideralsh** [comment]
@bryphe 

> Do you have any custom configuration?

No, I just logged in using my licence key and downloaded a new .dmg and installed it.

> Do you have any custom keybindings?

I don't think so. This is my `keybindings.json`:

```
{
    "bindings": [
        { "key": "<C-P>", "command": "quickOpen.open", "when": [["editorTextFocus"]] },
        { "key": "<D-P>", "command": "quickOpen.open", "when": [["editorTextFocus"]] },
        { "key": "<S-C-P>", "command": "commandPalette.open", "when": [["editorTextFocus"]] },
        { "key": "<D-S-P>", "command": "commandPalette.open", "when": [["editorTextFocus"]] },
        { "key": "<ESC>", "command": "menu.close", "when": [["menuFocus"]] },
        { "key": "<C-N>", "command": "menu.next", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<C-P>", "command": "menu.previous", "when": [["menuFocus"], ["textInputFocus"]]},
        { "key": "<D-N>", "command": "menu.next", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<D-P>", "command": "menu.previous", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<C-N>", "command": "wildmenu.next", "when": [["commandLineFocus"]] },
        { "key": "<C-P>", "command": "wildmenu.previous", "when": [["commandLineFocus"]] },
        { "key": "<D-N>", "command": "wildmenu.next", "when": [["commandLineFocus"]] },
        { "key": "<D-P>", "command": "wildmenu.previous", "when": [["commandLineFocus"]] },
        { "key": "<TAB>", "command": "wildmenu.next", "when": [["commandLineFocus"]] },
        { "key": "<S-TAB>", "command": "wildmenu.previous", "when": [["commandLineFocus"]] },
        { "key": "<CR>", "command": "menu.select", "when": [["menuFocus"], ["textInputFocus"]] },
        { "key": "<S-C-B>", "command": "explorer.toggle", "when": [["editorTextFocus"]]}
    ]
}
```

> In the Cmd+P menu, does clicking a file work?

Yes, clicking does open the file.

Thanks!

**Comment by bryphe** [comment]
Thanks @haideralsh !

Interesting - looks like this binding is causing the break:
```
     { "key": "<CR>", "command": "menu.select", "when": [["menuFocus"], ["textInputFocus"]] },
```

If you remove that and save - does the quick-open / license dialog work as expected?

**Comment by haideralsh** [comment]
It does! Now it works as expected.

**Comment by bryphe** [comment]
Awesome, thanks for confirming @haideralsh !

It looks like this is leftover from an older version of our keybindings schema - it seems like we must have a backward compatibility issue with that binding.

**Comment by haideralsh** [comment]
That makes sense, I installed the alpha version over a year ago. Thank you for your help.

Please feel free to close this issue.

**Comment by bryphe** [comment]
Thanks @haideralsh !

It might be worth 'upgrading' this to our newer schema - since it looks like there aren't customizations, could just replace the file with our boilerplate:

```
[
  // See the onivim documentation for details on the format:
  // https://onivim.github.io/docs/configuration/key-bindings
  // Add key bindings here, for example:
  //  { "key": "<leader>p", "command": "workbench.action.quickOpen", "when": "editorTextFocus" }
  // { "key": "jk", "command": "vim.esc", when: "insertMode" },
]
```
