### ISSUE TITLE
Sidebar no refresh

### ISSUE THREAD

**Issue by Amparose** [onivim/oni2#3399]
I understand that features like rename and move are on the way for the sidebar so I jumped into a terminal to rename a file. In Onvim the sidebar does not reflect this change without closing/reopening it. Also, I just tested touching a txt file (perhaps all new files) and it doesn't show up in the sidebar even after show/hide. `CTRL p` does show recent changes and new files so perhaps the polling is available.

The current Onivim sidebar is pretty useless at the moment. Hoping that it is on the roadmap to make it functional.

**Comment by bryphe** [comment]
Hi @Amparose ,

Thanks for logging the issue. I actually just merged a PR earlier this week to enable auto-refresh via libuv file system watchers here: https://github.com/onivim/oni2/pull/3365

It's turned off by default, just to get some more testing around it - but you can enable it on nightly builds with:
```
  "files.useExperimentalFileWatcher": true,
```

in your configuration. Would be great to see if that fixes the refresh/reload issue for you!

> The current Onivim sidebar is pretty useless at the moment. Hoping that it is on the roadmap to make it functional.

Past auto-refresh, what other features are you looking for? 

There's a few things I'm tracking:
- yank / paste
- creation of new files and folders
- renaming files/folders via the explorer
- deletion of files / folders

Are there any other things missing that we should track?

**Comment by lougreenwood** [comment]
Drag & drop moving of files / folders would also be nice 😃

**Comment by Amparose** [comment]
> Drag & drop moving of files / folders would also be nice 😃

Yeah! Along with that and coming from Nova/VSCode/Sublime, I ran into these unmet expectations/confusions:

- Drag and drop files to create new splits.
- Drag to re-order tabs.
- Drag-move tabs between splits.
- Drag tab out from group to create new split.

I would hope that these could have keyboard controls as well like the origami feature in Sublime.

> Are there any other things missing that we should track?

I'm just getting into "building my first Vim" in the last few days and only purchased/installed Onivim today, so I may not be aware of all the conventions to suggest correctly, but here are a few things that occurred to me:

- Instead of exiting the app completely, closing the last file could show the welcome screen, recent files list, or maybe something useful like what vim-startify does.
- Onivim doesn't remember my open files or anything between restarts. Given that it looks like VSCode, this was unexpected. I know it's not a Vim thing (about to look into the sessions feature set) but maybe this should be a first class feature rather than something users will have to cobble together.
- Be nice if moving from a maximised split to others carried "maximise focus". This might be a Vim config issue as the same behaviour exists in Vim.
- I know there milestones around integrating vimrc stuff so looking forward to not having to manage two separate silos of config.
