### ISSUE TITLE
masking problem on the start of the line

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3405]
I am using a recent release (downloaded a day ago or so), on Ubuntu 20.04.

I have noticed a quite annoying shadowing problem. When writing long lines for example in Markdown, I get into situations like this:

![shadowing_problem](https://user-images.githubusercontent.com/8382834/114514782-f3125300-9c3b-11eb-86a2-2643c4d8fb60.png)

Note that as soon as I start typing on the next line, the problem disappears. Still, really quite annoying in daily life:

(illustration that it disappears when the next line starts):

![newline_removes_shadowing_problem](https://user-images.githubusercontent.com/8382834/114514881-0d4c3100-9c3c-11eb-84c3-a7b2461cb5ee.png)

- Any idea what causes this and how to fix that?
- I suppose my config may have something to say potentially (?), here it is in case you need it:

```
{
  "ui.zoom": 1.0,
  "clangd.path":
    "/home/jrmet/.config/oni2/global/llvm-vs-code-extensions.vscode-clangd/install/11.0.0/clangd_11.0.0/bin/clangd",
  "editor.detectIndentation": true,
  "editor.fontFamily": "FiraCode-Regular.ttf",
  "editor.fontSize": 14,
  "editor.largeFileOptimizations": true,
  "editor.highlightActiveIndentGuide": true,
  "editor.indentSize": 4,
  "editor.insertSpaces": true,
  "editor.matchBrackets": true,
  "editor.minimap.enabled": false,
  "editor.minimap.maxColumn": 120,
  "editor.minimap.showSlider": true,
  "editor.renderIndentGuides": true,
  "editor.rulers": [],
  "editor.tabSize": 4,
  "editor.zenMode.hideTabs": true,
  "editor.zenMode.singleFile": true,
  "files.exclude": [ "_esy", "node_modules", ".git" ],
  "workbench.activityBar.visible": true,
  "workbench.editor.showTabs": true,
  "workbench.iconTheme": "vs-seti",
  "workbench.sideBar.visible": true,
  "workbench.statusBar.visible": true,
  "workbench.tree.indent": 2,
  "vim.useSystemClipboard": [ "yank" ],
  "python.pythonPath": "/usr/bin/python3",
  "editor.lineNumbers": "relative",
  "editor.renderWhitespace": "all",
  "files.useExperimentalFileWatcher": true
}
```

**Comment by kinglouie** [comment]
@jerabaul29 I think what you're referring to is the shadow indicator that the buffer is scrollable into the direction of the shadow, See my comment in a similar issue #3328. 
I think it would be nice to have the shadow intensity be configurable

**Comment by jerabaul29** [comment]
Mmmh, I may be wrong of course, but I think that this is another problem; I fully loose the overview of the start if the line in the first screenshot, more than just some shadow effect. Using "shadowing" was maybe a bad word, maybe "masking" would be better description of what happens.

**Comment by kinglouie** [comment]
then maybe you're hitting the same issue as me in #3372 where the horizontal scrollbar is not showing because the editor thinks word wrap is enabled but is not working. You can check if this is the same issue by running `:set nowrap` if you get a horizontal scrollbar it should be the same underlying issue.

**Comment by jerabaul29** [comment]
Mmmh, that may be related, but I loose the "first chars" of my lines, while you miss the bottom scrollbar if I understand right? Will be curious to see what @bryphe thinks :) .

**Comment by kinglouie** [comment]
I just confirmed your issue, it happend when line wraping is enabled. The buffer scrolls a few pixels to the right when hitting the right boundary. You can unscroll the view by using shift + mousewheel. When the view is unscrolled you are not able to scroll back to the right side until you hit the boundary again. 
This should really not happen.

**Comment by jerabaul29** [comment]
Ok, thanks for confirming :) . Then I suppose we should wait for the fix by @bryphe :) .

**Comment by bryphe** [comment]
Thanks @jerabaul29 and @kinglouie for all the troubleshooting here! Can confirm this is a bug; I'm able to reproduce - my hypothesis is that when we're typing at the very end of the line, we're hitting a code path that ensures the cursor is in view, _before_ we actually process the wrap (so, for a temporary instant - the cursor is actually 'past' the viewport). Working to see if that hypothesis is correct, or if there is something else going on.
