### ISSUE TITLE
[Feature Request] Quick Open for tabs/buffers

### ISSUE THREAD

**Issue by jesstelford** [onivim/oni2#3413]
Essentially the same functionality as `workbench.action.quickOpen`, but the list of things being fuzzy-searched is all currently open tabs. Selecting an item would switch the focus to that tab.

Maybe related: #1785

**Comment by bryphe** [comment]
One thing we have right now is the control+tab buffer switcher:

![2021-04-15 14 56 31](https://user-images.githubusercontent.com/13532591/114943426-d4a68600-9dfa-11eb-9784-b2692f296c3b.gif)

But it's not quite the same - it's not the fuzzy-search experience like `workbench.action.quickOpen`. I agree, it would be nice to have this - perhaps a command like `workbench.action.quickOpenBuffer`

**Comment by jesstelford** [comment]
I'm not sure the control+tab buffer switcher is working as I expect 🤔 so I've opened #3433 to track that.

`workbench.action.quickOpenBuffer` would be a fantastic addition! 🎉

**Comment by bryphe** [comment]
Implemented by @aubinlrx in #3430 - thanks for the contribution! :tada: 

> I'm not sure the control+tab buffer switcher is working as I expect thinking so I've opened #3433 to track that.

Thanks for splitting that out, @jesstelford !
