### ISSUE TITLE
Arrow key bindings no longer working

### ISSUE THREAD

**Issue by chris-armstrong** [onivim/oni2#3417]
I'm using the latest nightly release (   0.5.2038) and the up, down, left and right arrow keys no longer move the cursor in normal or insert or visual or list mode. I've managed to remap them with 'noremap' for normal mode using the 'experimental.viml' option, but I don't know how to fix it for insert or other modes.

The hjlk keys do work, but I don't use them as I have a non-US keyboard layout.

**Comment by CrossR** [comment]
I think this fix https://github.com/onivim/oni2/pull/3414, may also work here. It applies a stricter restriction on the newly added bindings, which includes both an up and down binding.

Locally, on Mac at least, I can see left/right working fine, its just up/down that don't work. So there may be an additional bug that is causing the left/right issue for you.

**Comment by bryphe** [comment]
> I think this fix #3414, may also work here. It applies a stricter restriction on the newly added bindings, which includes both an up and down binding.

Yep, exactly 👍 

This should be fixed now with #3414 (and in the latest nightlies). I'll close this out as fixed by #3414 , but let us know if you still see issues on the latest -

**Comment by chris-armstrong** [comment]
I'm on 0.5.2048 and this appears to be working now (once I remove my attempts at custom keybindings)
