### ISSUE TITLE
Line height in hover popup not calculated correctly

### ISSUE THREAD

**Issue by ggof** [onivim/oni2#3424]
Hi!

I've been using using Onivim for a while now. Since it's first days I've had the same issue with this popup, thought it might be a good idea to open an issue about it.

I don't know if this has to do with screen resolution or font size (or both actually), but whenever the hover popup opens the text selection is off by some amount. Here's a picture of what I'm describing:
![image](https://user-images.githubusercontent.com/58317616/114961228-9f1f8e00-9e36-11eb-8dc4-89405cb739f3.png)

As you can see, the text "selected" (id in this example) is clearly off by 4-5 pixels. In this particular example it might not seem like an issue, but consider the following case: 
![image](https://user-images.githubusercontent.com/58317616/114961381-e443c000-9e36-11eb-8c66-8ff1f2f00624.png)
When the last element is selected, it is chopped up.

I'm running Arch Linux, using a 3440x1440 ultrawide monitor with a font size of 24. It's worth noting that, the further my font size is from 16, the worse it gets.

Thanks for taking the time to create this very (VERY) nice text editor. If you need any other information, feel free to @ me.

**Comment by bryphe** [comment]
Hi @ggof ,

Thanks for the issue and the screenshots!

> I've been using using Onivim for a while now. 

Awesome 😎 

> Since it's first days I've had the same issue with this popup, thought it might be a good idea to open an issue about it.

Actually, perfect timing - I just worked on a PR to improve this here - https://github.com/onivim/oni2/pull/2329:
![2021-04-16 14 03 52](https://user-images.githubusercontent.com/13532591/115083912-fbc58c00-9ebc-11eb-8406-07503f11cf3a.gif)

There's still a few more things I need to fix (mouse interaction, cut-off at borders of editor) - but the line height issue specifically should be much improved now. 

There was a build issue with the nightlies - kicking off a new build, got my fingers crossed this one will go through - but will be great to get your feedback once it's updated.

**Comment by bryphe** [comment]
Oh, one other thought - if you're using a high-DPI display - you might want to try the `ui.zoom` setting too (something like, `"ui.zoom": 1.25`) - that would increase of the UI everywhere, including non-editor fonts.

**Comment by ggof** [comment]
Thanks for the quick reply!

I actually already tried this feature, it was the way I used to cope with the misaligned text (font size 16 with something like 1.5 in zoom). Though it was a bit too scaled for me 😅

I'll try it out as soon as I can and report back any feedback I have. Thanks again!

**Comment by ggof** [comment]
Just tested this, it's great now thanks!

I think this issue can be closed.

**Comment by bryphe** [comment]
Awesome - thanks for the confirmation @ggof !
