### ISSUE TITLE
[Bug] Ctrl-Tab buffer switcher not behaving as expected

### ISSUE THREAD

**Issue by jesstelford** [onivim/oni2#3433]
_(continuing discussion from #3413)_

I'm not sure the `<Ctrl-Tab>` buffer switcher is working as I expect 🤔 I expected it to behave like vim's ability to switch to the previously edited buffer with `<C-^>`: https://vim.fandom.com/wiki/Easier_buffer_switching#Switching_to_the_previously_edited_buffer

However, it seems to pick an unrelated order for the items in the `<Ctrl-Tab>` list:

![onivim2-control-tab](https://user-images.githubusercontent.com/612020/115188840-ddfc5f00-a128-11eb-86c0-29c91a16f797.gif)

While focused on `keybindings.json`, I was expecting that hitting `<Ctrl-Tab>` would take me to `setup.js`, but instead it took me to `index.js`, and you can see that in the list of items shown:

<img width="636" alt="Screen Shot 2021-04-19 at 4 08 09 pm" src="https://user-images.githubusercontent.com/612020/115189186-71359480-a129-11eb-9bb6-e875ce4f083b.png">

Is this a bug, or a misunderstanding of how it's meant to work?

**Comment by jesstelford** [comment]
With #3442 now merged, I've tried the latest nightly (a300a792), and I'm still seeing some unexpected behaviour.

![onivim2-ctrl-tab-bug](https://user-images.githubusercontent.com/612020/115800036-1e0b5c80-a41d-11eb-8e68-78e775b95837.gif)
The above gif shows two issues:

1. When I opened `.prettierrc`, then `.gitignore`, then `.node-version`, then `Welcome`, and pressed `<Ctrl-Tab>`, the switcher incorrectly listed `.prettierrc` as the most recent file, ignoring `.gitignore` & `.node-version`:

<img width="255" alt="Screen Shot 2021-04-23 at 10 19 22 am" src="https://user-images.githubusercontent.com/612020/115800157-61fe6180-a41d-11eb-864e-4d750cc48e23.png">

2. When I later switched over to `.prettierrc`, then `.gitignore`, and pressed `<Ctrl-Tab>`, the switcher incorrectly displayed `.gitignore` (the current file!) as the most recent file:

<img width="301" alt="Screen Shot 2021-04-23 at 10 21 45 am" src="https://user-images.githubusercontent.com/612020/115800319-b6a1dc80-a41d-11eb-9cb7-2e8cc2324edc.png">

**Comment by bryphe** [comment]
Thanks for the gif and extra details, @jesstelford !

I believe what is happening here is that there are some cases where we're missing setting a buffer as used/last-used (this code here: https://github.com/onivim/oni2/blob/00a011300a0f3ba7eca2d0990606114b4be094bf/src/Core/Buffer.re#L270)

Specifically - it looks like in the case where a tab is clicked - we're not 'stamping' the last-used time - which can cause the order to be out-of-date.

 Other cases - like the Control/Command+P menu, using the `:e` or other ex commands, are stamping the last-used time.

**Comment by jesstelford** [comment]
Ah, thank you for the explanation!

I tried searching for `stampLastUsed`, but I'm not familiar with Reason, so quickly got lost 😅

Would we also need to consider the previous/next trab commands as well as the split navigation commands?

**Comment by jesstelford** [comment]
Confirmed this is now fixed by #3475

Thank you! 🙏
