### ISSUE TITLE
Auto-fullscreen setting. 

### ISSUE THREAD

**Issue by albertwh1te** [onivim/oni2#3454]
I think there should be an auto full-screen setting in the config file.

**Comment by bryphe** [comment]
Hi @MarkWh1te - thanks for the suggestion.

Sounds reasonable - can pick up the same setting Code uses:

```
"window.newWindowDimensions": "default" | "maximized" | "fullscreen"
```

We may need to look at hooking up the [SDL_SetWindowFullscreen](https://wiki.libsdl.org/SDL_SetWindowFullscreen) in Revery to get this working.

Some other tangential items:
- On Windows and Linux, `F11` could be bound to toggle fullscreen.
- We should persist the window size (fullscreen or not).

Right now, we persist per-workspace if the window is maximized, as well: https://github.com/onivim/oni2/blob/745b7151aca66e292e88837feed6fcc61d670975/src/Store/Persistence.rei#L23
