### ISSUE TITLE
Theme picker should not grey out the UI while previewing themes

### ISSUE THREAD

**Issue by Minnozz** [onivim/oni2#3459]
While the theme picker is open, the rest of the UI is desaturated (I think because it is a modal dialog). However, this changes the colors that are being previewed, which makes it hard to see how the theme would actually look.

**Comment by lougreenwood** [comment]
This frustrates me every time I change themes! 😅

**Comment by bryphe** [comment]
Ouch, yes, this is certainly a compelling argument to remove that grey-out background! Thanks for logging this, @Minnozz :+1:
