### ISSUE TITLE
Fuzzy Search not being fuzzy enough

### ISSUE THREAD

**Issue by sean-brydon** [onivim/oni2#3473]
### Fuzzy Search
I love the idea of onivim and am willing to make it my daily editor however there a few issues i seem to be having compared to my usual neovim config.

![image](https://user-images.githubusercontent.com/55134778/116580191-09423380-a90b-11eb-849b-f8c7bb58f70a.png)

Should match a file called user.service however it doesnt. Every fuzzy finder ive used supports this - rg, fzf.

I did some digging and saw this uses ripgrep so im unsure if there was a reason you chose not to show results like this?

**Comment by CrossR** [comment]
I think my response here answers this pretty well: https://github.com/onivim/oni2/issues/3278

I've been busy with my PhD at the mo, so I've not had a chance to get space based sub-filtering added, but perhaps we should just filter out the space or something equally simple at the moment, since evidently people are bumping into issues around them.

**Comment by sean-brydon** [comment]
I'm not too familiar with the code base but could you point me in the right direction where i would give it a go to implement something like this?

**Comment by bryphe** [comment]
> I've been busy with my PhD at the mo, so I've not had a chance to get space based sub-filtering added, but perhaps we should just filter out the space or something equally simple at the moment, since evidently people are bumping into issues around them.

Sounds like a good plan, @CrossR ! I've implemented the space filtering in #3487 as an interim fix

> I'm not too familiar with the code base but could you point me in the right direction where i would give it a go to implement something like this?

Sorry I missed this @sean-brydon - didn't see your message until after I pushed up the PR. We can always use help though, appreciate the offer!

**Comment by bryphe** [comment]
I'll resolve this with #3487 - but we'll continue tracking the nicer refine behavior in #3278
