### ISSUE TITLE
Refresh File Explorer On File Create

### ISSUE THREAD

**Issue by sstubbs** [onivim/oni2#3483]
Hi,

This project is awesome. I have been using it for a while. I'm now using version 0.5.5 on pop os with the appimage and it can almost become my main text editor. One issue I am having and perhaps I'm creating files incorrectly is:
- open a folder with `:cd foldername`
- create a file with `:e filename`
- save the file `:w`
- the file does not show up in the file explorer unless I use `:cd` to a different directory and then back to the directory I am working in.

**Comment by kinglouie** [comment]
This issue was solved recently but the automatic refreshing is hidden behind an experimental config setting. 
See #3365 for more information.

**Comment by sstubbs** [comment]
Thanks I have installed the nightly and this works great. This project is awesome!

**Comment by bryphe** [comment]
Hi @sstubbs ,

> This project is awesome. I have been using it for a while. I'm now using version 0.5.5 on pop os with the appimage and it can almost become my main text editor.

That's great to hear - thanks for the encouragement :smile: 

And thank you @kinglouie for your help, appreciate it. Hopefully we can get this on-by-default soon :crossed_fingers:

I'll close this out - but I have a related issue open I'm using to track having this on by default: #3399
