### ISSUE TITLE
weird build-in terminal colors

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3495]
I wonder if this has been already discussed, but the colors in the built in terminal look weird. I am running Ubuntu 20.04, "out of the box", nothing too special regarding my setup. See picture for comparison of the colors in Oni2 vs. my system terminal.

Any idea what causes that / how this can be fixed? A bit painful to my eyes and quite a lot less visible... Wonder if there should be a way to either 1) read terminal setup from some usual config files on the machine, or 2) be able to set a terminal theme?

![Screenshot from 2021-05-04 11-04-44](https://user-images.githubusercontent.com/8382834/116982182-c399b800-acc8-11eb-885f-363d697d5389.png)

**Comment by bryphe** [comment]
Ah, the terminal colors are actually determined by the theme:

We could potentially provide a way to override the terminal colors, like: https://stackoverflow.com/questions/42307949/color-theme-for-vs-code-integrated-terminal

**Comment by jerabaul29** [comment]
Aah, that explains, thanks :) . Maybe I should just use another theme ^^ :) .

**Comment by bryphe** [comment]
I also added a way to override terminal colors in #3506 - so you can manually specify.

This is a good starting set of colors to try, and then can be tweaked: https://github.com/Tyriar/vscode-snazzy/blob/c9484f46fa3f2ec44860b87fb51dfb9d1cbe2f85/snazzy.json#L5

**Comment by bryphe** [comment]
I'll close this out with #3506 👍
