### ISSUE TITLE
Code lens obscures tab on scroll

### ISSUE THREAD

**Issue by lougreenwood** [onivim/oni2#3520]
When scrolling an editor which has code lense, the code lense descriptions will overflow the editor view and obscure the tab.

Using the latest nightly, here's a video: https://monosnap.com/file/p6TtCsOO6UMiwqdsCGvf4pveZSKsOg

---

Also, as a side note, notice that the truncation of the `power-select.ts` tab should maybe kick in a bit sooner.
<img width="406" alt="Screenshot 2021-05-09 at 11 55 06" src="https://user-images.githubusercontent.com/12051736/117569432-8a44bc00-b0bd-11eb-99a1-2cc55e7f6645.png">

**Comment by bryphe** [comment]
Thanks for reporting, @lougreenwood !

This is fixed in https://github.com/onivim/oni2/pull/3517 - which is in latest nightly now
