### ISSUE TITLE
Unable to connect to open-vsx.org

### ISSUE THREAD

**Issue by AftershockGT** [onivim/oni2#3527]
OS: Arch 
Onivim Version: 0.5.9-nightly

I have built from source and after a recent update I can no longer connect to the extension marketplace.
if I try to install an extension from cli I get this: Error querying catalog: Service_Net.ConnectionFailed

Additionally I have an intermittent issue with some builds where the app won't launch and I get this /tmp/.mount_Onivim7qXsUO/AppRun: line 7: /tmp/.mount_Onivim7qXsUO/usr/bin/Oni2: No such file or directory

My last build on 0.5.9-nightly did not have this issue but the most current one and the build before last do so I am unable to launch.

**Comment by AftershockGT** [comment]
Ok so I built again and I'm getting the same error if I run the appimage, however, I can launch with esy '@release' run and it works. It still can't connect to Open-VSX.

**Comment by bryphe** [comment]
You might need to run `node install-node-deps.js`, `esy bootstrap` and rebuild. The extension host and vendored node were recently upgraded. More details: https://onivim.github.io/docs/for-developers/building#install-node-dependencies

If it's still not working, the output of `esy run -f --checkhealth` might be helpful.

**Comment by AftershockGT** [comment]
Thanks Bryphe, I rebuilt following your advice and it solved both issues.
I added the node deps to my build script.
```bash
#!/bin/bash
node install-node-deps.js
esy install
esy bootstrap
esy build
esy '@release' install
esy '@release' create
```
