### ISSUE TITLE
Oni2 doesn't load folders when folders are mounted from a nfs mount

### ISSUE THREAD

**Issue by edwinclement08** [onivim/oni2#3534]
/etc/fstab content
``
eve.local:/mnt/user/Coding /home/edwin/coding nfs default 0 0
``
The folder contents
![image](https://user-images.githubusercontent.com/9532892/117959105-5249ad00-b339-11eb-9fe3-f1814bb9ee0d.png)

The Oni Screen
![image](https://user-images.githubusercontent.com/9532892/117959282-7a391080-b339-11eb-9ba9-d064a0a78fe2.png)

Note that the Oni terminal also shows the folder contents, but the side bar does not.

Working with code on a remote server is a critical piece of my workflow. I really want to stick with Oni, but unless this is fixed, I can't use it.
I am up for a call/chat to fix this if you need to test things on my env.

**Comment by bryphe** [comment]
Thanks for logging the issue @edwinclement08 - possibly related to #3377 

Trying to set up a repro on my end

**Comment by edwinclement08** [comment]
If you need anything to reproduce, I am happy to help

**Comment by edwinclement08** [comment]
Any progress on this end?

**Comment by bryphe** [comment]
Hi @edwinclement08 ,

Yes, actually - I have a repro environment now, and I've narrowed it down to this spot in the code:

https://github.com/onivim/oni2/blob/d5cd50280484b0ccc9dfef5908311be71262f31d/src/Components/FileExplorer/Component_FileExplorer.re#L35

Essentially, in this particular case (and likely #3377 as well), the filetype comes back as 'UNKNOWN' - requires an extra stat call to figure out if it is actually a file / folder. 

So the fix will involve doing a stat on these returned on these files to determine the actual type (...and that extra context could help fix #2657 as well).

**Comment by edwinclement08** [comment]
That was amazingly quick. Thanks.
