### ISSUE TITLE
ctrl-o behavior is inconsistent

### ISSUE THREAD

**Issue by iamcodemaker** [onivim/oni2#3544]
In experimenting with jumping around code using `gd` and `ctrl-o`, behavior is inconsistent. The `ctrl-o` command does not always jump back to the previous location. It goes somewhere, but not always to the right place.

**Comment by bryphe** [comment]
Might be same issue as #1173

**Comment by iamcodemaker** [comment]
I did a quick test with 0.5.2120 and things seem to work as expected (was previously on 0.5.0).
