### ISSUE TITLE
MacOs: Inserting control escaped characters hangs UI

### ISSUE THREAD

**Issue by vincentjorgensen** [onivim/oni2#355]
commit: 63913658814299af9a1ab6ef511e491e43e5a3c3
OS: MacOS

Gcc: ```
% gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin```

When attempting to insert ctrl-V-M (a newline character), the UI hangs.

**Comment by CrossR** [comment]
As far as I can see, #138 fixed this!

Closing this out, but drop a comment if that isn't the case and we can re-open this.
