### ISSUE TITLE
In extension store the list moves to top while (loading search and exploring down the list)

### ISSUE THREAD

**Issue by inferno-umar** [onivim/oni2#3551]

**Comment by inferno-umar** [comment]
https://user-images.githubusercontent.com/70754989/118981732-4a70b500-b998-11eb-8374-7c644bfd4dc8.mp4

**Comment by inferno-umar** [comment]
Watch the scrollbar

https://user-images.githubusercontent.com/70754989/118389011-4dd90900-b645-11eb-9a93-5a7264ce8420.mp4

In vscode

https://user-images.githubusercontent.com/70754989/118389039-84af1f00-b645-11eb-8de1-55e9ebe6ce47.mp4

**Comment by bryphe** [comment]
Thanks for the videos, @inferno-umar ! Very helpful. Working on a fix in #3583
