### ISSUE TITLE
Multiple Editor Instances

### ISSUE THREAD

**Issue by pollingj** [onivim/oni2#3561]
I've just updated to the latest nightly build and when I try and open multiple instances of the editor, even from the terminal command, instead of opening a fresh instance, it switches the context of the Explorer to the new directory.  I quite often work in multiple code bases and I like being able to have multiple editor instances.

Not certain if this is a bug or not, but the previous behaviour of multiple instances was better for me.

**Comment by CrossR** [comment]
The default behaviour was changed, so now we open up in the existing instance by default. That said, I think there is a `-n` / `--new` flag you can give, to force a new window. (It should be in the `--help` text hopefully!)

I would need to check if there is a way to opt out of that by default (though you can use an alias for now to always include `-n` if that isn't implemented).

**Comment by pollingj** [comment]
Sorry, yes, I'd completely forgotten to check the flags.  Works fine 👍
