### ISSUE TITLE
Mouse Drag on Mini Map Doesn't Work as Expected on Shorter Files

### ISSUE THREAD

**Issue by Christopher-Hayes** [onivim/oni2#3563]
It appears that on files where the mini map isn't the full height of the window, dragging on the mini map does not work as expected. The view does not move with the mouse. On longer files where the mini map is the full height of the window, dragging on the mini map works as expected.

This is not a critical bug, it's just a mildly annoying thing on shorter files.

Screencast: https://www.youtube.com/watch?v=_uasETIgP6w
File 1 - Shorter file, dragging doesn't work as expected.
File 2 - Longer file, dragging works as expected.

System: `Ubuntu 20.04`
Version: `0.5.9-nightly` | `d38fee83`

Thanks!

**Comment by bryphe** [comment]
Thanks @Christopher-Hayes for the report and video!

Nice catch - at the moment, it seems you have to physically move the mouse across the entire height of a mostly-empty minimap... which is not intuitive or expected behavior.
