### ISSUE TITLE
Add bitcoin address to README

### ISSUE THREAD

**Issue by Kudostoy0u** [onivim/oni2#3564]
I was looking at a closed issue, and it seems like [this project has a bitcoin address](https://github.com/onivim/oni2/issues/243#issuecomment-482766142), though I don't see it anywhere. 

Maybe adding the bitcoin address to the README might help with donations.

**Comment by bryphe** [comment]
Thanks for the suggestion and for thinking about ways to sustain the project @Kudostoy0u - appreciate it!

However, I won't pursue this in the near term, for two reasons:

1) There isn't an automated workflow for if someone purchases or donates via bitcoin to get them a license key - it'd be a manual process 

2) When I did have the bitcoin address up, I didn't receive any donations through it

So IMO there wouldn't be much to gain from the work to set it up and then manually handle those transactions -
