### ISSUE TITLE
GLES/gl.h not found on macOS 11.3

### ISSUE THREAD

**Issue by gaetgu** [onivim/oni2#3566]
Hello guys! Thanks so much for creating this awesome project! I have used it in the past on my old laptop, but after upgrading to an Apple Silicon chip, it seems that `oni` cannot find the OpenGL libraries. I tried to build the editor using the guide found [here](https://onivim.github.io/docs/for-developers/building) and all was going well, until the `esy bootstrap` command. I have noticed that there are a few different  issues regarding that command and I am pretty sure that this is not covered by those. All seems to be going well until it completely bombs, giving this error code:

```console
...
      CC     build/SDL_render_d3d11.lo
      CC     build/SDL_shaders_d3d11.lo
      CC     build/SDL_render_gl.lo
      CC     build/SDL_shaders_gl.lo
      CC     build/SDL_render_gles.lo
    In file included from /Users/gabriel/.esy/3/b/esy_sdl2-2.0.10008-6cd8bc35/src/render/opengles/SDL_render_gles.c:26:
    /Users/gabriel/.esy/3/b/esy_sdl2-2.0.10008-6cd8bc35/include/SDL_opengles.h:33:10: fatal error: 'GLES/gl.h' file not found
    #include <GLES/gl.h>
             ^~~~~~~~~~~
    1 error generated.
    make: *** [build/SDL_render_gles.lo] Error 1
    error: command failed: 'bash' '-c' './build-scripts/esybuild.sh --os=darwin' (exited with 2)
    esy-build-package: exiting with errors above...

  building esy-sdl2@2.0.10008
esy: exiting due to errors above
```

I did some looking and it looks like OpenGL is deprecated, but still supported for the time being. If anyone can either help me or give me a definite "no it doesn't work on silicon" that would be *great*. Thanks so much!

**Comment by zbaylin** [comment]
Unfortunately the current SDL version we're using doesn't support the M1/Apple Silicon yet. The good news is I have a PR open to upgrade our SDL to 2.0.14 (revery-ui/esy-sdl2#19) which *does* support Apple Silicon (at least, it builds on my Mac Mini). I'm going to work on fixing the Linux build issue today and hopefully we can merge that in soon.

**Comment by gaetgu** [comment]
Alright, thanks so much! I will close this since I see that you have a PR open, and I will re-open it if needed.
