### ISSUE TITLE
Unknown (FileSystemError) ms-python plugin 

### ISSUE THREAD

**Issue by sanjayjaras** [onivim/oni2#3592]
Getting "Unknown (FileSystemError) ms-python plugin " when opening python files(ipynb) from FAT32 filesystems on Linux
![Oni2Error](https://user-images.githubusercontent.com/10779622/119367713-d96f1d00-bc77-11eb-90ad-db4c1f9bcf4a.png)

**Comment by bryphe** [comment]
Thanks for reporting @sanjayjaras !

I believe this should be fixed with https://github.com/onivim/oni2/pull/3431 which is in the latest nightlies. Feel free to reopen if you're still seeing this, though.
