### ISSUE TITLE
WakaTime extension does not seem to work

### ISSUE THREAD

**Issue by PaulFlatlooker** [onivim/oni2#3619]
Not sure if I should report this here or on wakatime repo, but:

- I installed WakaTime extension from the extensions panel
- Command Palette -> select "Wakatime API Key" -> Enter
- I am not prompted for my API key
- the status bar displays: "WakaTime api key not provided"

Expected behavior : I am prompted for my API key

**Comment by bryphe** [comment]
Thanks for logging the issue @PaulFlatlooker  - looks like the bug is in Onivim - we're not handling the `showInputBox` (https://github.com/wakatime/vscode-wakatime/blob/3e1b5ff46e406c4a9a50c06893f25ae32339f7a3/src/wakatime.ts#L112) call correctly
