### ISSUE TITLE
Backgroung highlight pos. is wrong, if horizontal scroll pos. ≠ "LeftMost"

### ISSUE THREAD

**Issue by Samonitari** [onivim/oni2#363]
There is some column indexing error in highlighting in Visual Mode.

Long lines doesn't get highlighted correctly when horizontal scrollbar is is not in its leftmost position: background coloring doesn't match cursor position, and characters gets this weird inner highlighting.
The Glith width/offset is proportional to the scrollbar position -> it dissapears completly if scrollbar returns to 0 ( horizontal scrollbar can't be seen as of 54a7a66)

Screenshot shows highlight started from line ending:
![highlight glitch](https://user-images.githubusercontent.com/15932551/60340799-e5c79e00-99ac-11e9-88b6-af9262650ab3.PNG)

**Comment by bryphe** [comment]
Thanks for the bug report + screenshot, @Samonitari !

**Comment by Samonitari** [comment]
I believe it's quite unneeded info, but search highlights are affected as well.

Horizontal scrollbar pos is not taken into account (at all): search highlights stays at the same place when view is displaced horizontally. I'll modify the ticket name to make it more decriptive.
