### ISSUE TITLE
clear last search highlighting

### ISSUE THREAD

**Issue by jstaursky** [onivim/oni2#3636]
How do I clear the highlighting caused by a previous search? Looking online suggests that a new keybinding needs to be introduced (or enter `:noh`), but clearing a highlight seems so basic--that I figured there must be a default keybinding for this. Is there?

**Comment by bryphe** [comment]
Hi @jstaursky ,

Thanks for logging the issue,  good question. There wasn't a default keybinding, but added one in #3638 (<kbd>Control</kbd>+<kbd>L</kbd>).  If you'd prefer another key, can still bind a key to `:nohl`
