### ISSUE TITLE
Bug - Explorer: Explorer not sorted by files / folders

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#364]
__Issue:__ The sorting for the explorer, at the moment, sorts only alphabetically by name, and does not differentiate between files and folders.

This is a bit non-standard, as usually the folders are grouped at the top (this is the case for Oni1, and for other editors, like Sublime and VSCode). 

This is what Onivim 2 looks like right now:
![image](https://user-images.githubusercontent.com/13532591/60404028-501d4180-9b59-11e9-80ed-24115b552d1d.png)

__Expected:__ Folders like `.git`, `assets`, `bench, `bench.esy.lock`, etc should be grouped at the top of the `Oni2` folder - and then files beneath that.

A particular problem with the experience we have right now is that, when expanding a folder, it can be tough to know if a file is part of that expanded folder, or not - see `azure-pipelines.yml` in the below screenshot:
![image](https://user-images.githubusercontent.com/13532591/60404041-86f35780-9b59-11e9-93a9-6dabdfa86bb5.png)

__Where to start:__

The code to load the directory tree is here: https://github.com/onivim/oni2/blob/c2c46a9d60a1cca575e72102a25e0e5fc789f938/src/editor/Model/FileExplorer.re#L156

And the code that converts the list to tree nodes is here:
https://github.com/onivim/oni2/blob/c2c46a9d60a1cca575e72102a25e0e5fc789f938/src/editor/Model/FileExplorer.re#L128

I think we need to apply a sorting strategy to the `children` list created in the `listToTree` - based on whether the item is a file or a directory. Alternatively, we could potentially insert some sorting where we get the list of files and folders: https://github.com/onivim/oni2/blob/c2c46a9d60a1cca575e72102a25e0e5fc789f938/src/editor/Model/FileExplorer.re#L89

**Comment by r281GQ** [comment]
I'm happy to take that one.

**Comment by tatchi** [comment]
@bryphe this one can be closed right?

**Comment by r281GQ** [comment]
I think so.

**Comment by bryphe** [comment]
Indeed, thank you for the fix @r281GQ !
