### ISSUE TITLE
App hangs on resize (linux, wayland, ubuntu)

### ISSUE THREAD

**Issue by Galbar** [onivim/oni2#3646]
Hi! I just got the editor. Big fan of the original onivim!

I was trying the editor on my linux laptop with `SDL_VIDEODRIVER=wayland` and the app kept hanging. I did some testing and it looks like the problem might be when the window manager resizes the window.

I managed to get the app running fine by adding `for_window [title="Welcome - <user> - Onivim 2"] floating enable` to my sway config file. That line tells the wm to allow the window to be a floating window by default. This also avoids a resize of the window on startup. Then, if I try to resize the window, the app just stops responding.

No crash or anything just stops. Logs stop showing, it stops reacting to the "close window" key combination and even when run with `--no-fork` it will still keep "running" after I CTRL-C it on the terminal (the terminal programs closes, but the window app stays "alive" and frozen).

Edit: I just tried on Ubuntu 20.04 with wayland and I see the same behaviour.

Edit 2: I'm attaching the logfile. As you can see at the end it just stops with a `END: Render frame`. After that it stops responding and no extra logs are printed
[onivim2.2.log](https://github.com/onivim/oni2/files/6586719/onivim2.2.log)

Edit 3: Might be related to https://github.com/onivim/oni2/issues/890 but, in my case, unfocus+refocus cycle does not work.

**Comment by bryphe** [comment]
Hi @Galbar ,

> Hi! I just got the editor. Big fan of the original onivim!

Thanks for supporting the project! Sorry you're hitting this on first run. 

I wasn't able to reproduce on my Manjaro + weston setup - but I'll try on Sway+Ubuntu to see if I can hit it too.

One other idea - would you mind trying the `stable` build as well? If that works, it would indicate there is some regression between then and now in Onivim 2.

Based on the log - it may be hanging when it is actually presenting / swapping buffers, which would potentially suggest an OpenGL / GPU issue. Is there any interesting configuration for your GPU? (ie, overclocking)?

Looking through Mesa - I saw this issue that may be related: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3748

And these:
- https://gitlab.freedesktop.org/drm/intel/-/issues/562
- https://gitlab.freedesktop.org/mesa/mesa/-/issues/2899

The last mesa issue looks interesting, and has some actionable ideas for troubleshooting.

Looking through the syslog for `GPU HANG` might confirm if it is indeed the same issue (or `dmesg` for 'preemption')

If it is the case that we're hitting the same thing... there is a workaround posted in one of the threads:

> It is a timeout defined by the kernel driver. There is no need to compile any component, you can play with it by changing value in `/sys/class/drm/card0/engine/rcs0/preempt_timeout_ms` and then running the executable, default value is 640.
> 
> (`sudo su` and then `echo "5000" > /sys/class/drm/card0/engine/rcs0/preempt_timeout_ms`)

With the following caveat:

> It is sort of a double-edged sword. Problem is that a buggy (or evil) application could make your desktop very unresponsive when timeout is big enough.

(found at the end of: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2899)

But we should confirm that this is in fact the same issue before tweaking that value - one way is looking at `demsg` logs after reproducing the hang - a sample from those threads is something like this:
```
[  157.384432] i915 0000:00:02.0: Resetting rcs0 for preemption time out
[  157.384451] i915 0000:00:02.0: UE4Editor[2751] context reset due to GPU hang
[  157.407763] i915 0000:00:02.0: GPU HANG: ecode 9:1:859ffffb, in UE4Editor [2751]
[  157.407766] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[  157.407767] Please file a _new_ bug report at https://gitlab.freedesktop.org/drm/intel/issues/new.
[  157.407769] Please see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
[  157.407770] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[  157.407771] The GPU crash dump is required to analyze GPU hangs, so please always attach it.
[  157.407773] GPU crash dump saved to /sys/class/drm/card0/error
```

**Comment by Galbar** [comment]
Hi @bryphe,

I tried the stable build and it works!

I'm running it on a Dell XPS 13 9370. No overclocking or anything. It is normal Ubuntu 20.04 with an extra wm entry for sway.

I could reproduce the issue in normal Ubuntu UI with wayland too.

I could not find any `GPU HANG` (or any GPU related messages for that matter) by running any of the following while reproducing the issue:
-  `grep "GPU HANG" /var/log/`
- `journalctl -f`
- `dmesg -w`

I'm not very well versed in the world of mesa drivers or graphic drivers in general in linux. In case it is of any help, this are all the mesa-related packages I have installed and their versions:

```
libegl-mesa0/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libegl1-mesa-dev/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libgbm1/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libgl1-mesa-dev/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libgl1-mesa-dri/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libglapi-mesa/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libgles2-mesa-dev/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libglu1-mesa/focal,now 9.0.1-1build1 amd64 [installed,automatic]
libglu1-mesa-dev/focal,now 9.0.1-1build1 amd64 [installed,automatic]
libglx-mesa0/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
libwxgtk3.0-gtk3-0v5/focal,now 3.0.4+dfsg-15build1 amd64 [installed,automatic]
mesa-utils/focal,now 8.4.0-1build1 amd64 [installed,automatic]
mesa-va-drivers/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
mesa-vdpau-drivers/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
mesa-vulkan-drivers/focal-updates,now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,automatic]
xserver-xorg-video-nouveau/focal,now 1:1.0.16-1 amd64 [installed,automatic]
```

(I just realized I have nouveau installed, although I have no nvidia card in the laptop :confused: :question: )

**Comment by bryphe** [comment]
Hi @Galbar ,

> I tried the stable build and it works!

Thanks for testing this out! That's a helpful data point - based on this, I don't think it's an OpenGL / hardware issue or related to that set of bugs I suspected in Mesa. Must be a regression somewhere in Onivim or Revery.

My suspicion is potentially this PR: https://github.com/revery-ui/revery/pull/1077 , based on the description that it's hanging on resize.

Still working to see if I can reproduce this to track down the regression -

**Comment by bryphe** [comment]
Was able to reproduce on Manjaro + Sway - working on a fix here: https://github.com/revery-ui/revery/pull/1083
