### ISSUE TITLE
Feature request: toggle integrated terminal

### ISSUE THREAD

**Issue by bamboovir** [onivim/oni2#3649]
Feature request: toggle integrated terminal

I am looking for the ctrl+` toggle integrated terminal feature in oni2.
The current oni2 puts the integrated terminal in the window.
This leads to no good way to hide the horizontally split terminal window without closing the terminal.
Does oni2 provide support for this feature?
If oni2 does not support this use case,
Does the development team want to provide support for this use case in the future?

Thanks

**Comment by bryphe** [comment]
Hi @bamboovir ,

We've actually added this in https://github.com/onivim/oni2/pull/3498 - which is easier to toggle as you mention:

![2021-06-03 09 14 07](https://user-images.githubusercontent.com/13532591/120677818-52c2f880-c44c-11eb-9235-19467ff7607d.gif)

It's in the latest `nightly` builds, but hasn't made it to the `stable` builds yet - let me know if you try it and it's missing something you need.

**Comment by bamboovir** [comment]
great! Thank you for such a quick reply, I will switch to the snapshot of the nightly version to try this feature.
