### ISSUE TITLE
Configuration - Auto-reload configuration when saving

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#366]
__Issue:__ Today, when changing `configuration.json`, there is no auto-reload of the configuration. After saving, you have to manually open the command palette and run `Control+Shift+P` -> `Reload configuration`.

Here's an example repro:
![reload-configuration-manual](https://user-images.githubusercontent.com/13532591/60404248-e5b9d080-9b5b-11e9-843e-539af77d206d.gif)

We could make this smoother by auto-reloading the configuration when we know it has been saved. The most reliable way to make this work would be to implement a file-watcher to watch the configuration file, but I don't think we have a cross-platform one at the moment easily available via reason.

An alternative, to at least make this a little better today, would be to watch for BufferWritePost autocommands, and check if the buffer path matches the configuration file.

We have these pieces available today - we can listen to autocommands from `reason-libvim` via the [Autocommands](https://github.com/onivim/reason-libvim/blob/master/src/AutoCommands.re) module (we use this in our [`VimStoreConnector`](https://github.com/onivim/oni2/blob/master/src/editor/Store/VimStoreConnector.re))

In addition, we just need to dispatch an `Actions.ConfigurationReload` to pick up the configuration changes: https://github.com/onivim/oni2/blob/a765ed93fd8ac0dd9489852cf01a38c643fc364e/src/editor/Store/ConfigurationStoreConnector.re#L42

So the idea would be to wire these up - listen to the buffer write autocmd, check if matches the configuration file, and if it does, dispatch the `Actions.ConfigurationReload` action.

**Comment by tatchi** [comment]
Hey @bryphe, 

I would like to work on this one if not taken yet 😀

**Comment by tcoopman** [comment]
This one can be closed now?

**Comment by bryphe** [comment]
Indeed, thanks @tcoopman - fixed by @tatchi 's PR in #371 👍
