### ISSUE TITLE
gt and gT keybindings don't work

### ISSUE THREAD

**Issue by tristil** [onivim/oni2#3660]
Trying to enable `gt` and `gT` keybindings to move back and forth between tabs results in strange behavior.

Regardless of which command I assign to `gt` pressing it will move from the selected tab from right to left after selecting the rightmost tab in the split. `gT` doesn't do anything.

This is tested with a minimal keybindings.json:

```
[
  {
    "key": "gT",
    "command": "workbench.action.previousEditor",
    "when": "normalMode"
  },
  {
    "key": "gt",
    "command": "workbench.action.nextEditor",
    "when": "normalMode"
  }
]
```

**Comment by bryphe** [comment]
Hi @tristil ,

Ya, this is a little confusing - the `keybindings.json` follows the same format as VSCode, which means the keys are case-insensitive (`t` and `T` both mean the same thing).

You could try this as a workaround:
```
  { "key": "gt", "command": "workbench.action.previousEditor", "when": "normalMode && editorTextFocus"},
  { "key": "g Shift+T", "command": "workbench.action.nextEditor", "when": "normalMode && editorTextFocus"}
  ```

Related #2925

**Comment by tristil** [comment]
Oh, I had no idea! This is outside the scope of this issue but it would be nice if the movement wrapped around. But this has been bugging me for a long time. Thank you!

**Comment by tristil** [comment]
Also, what about making this a default keybinding? This feels like a standard Vim behavior

**Comment by tristil** [comment]
I'll close this and open a separate request to add these as default keybindings.
