### ISSUE TITLE
CodeLens lines are rendered through normal lines

### ISSUE THREAD

**Issue by Minnozz** [onivim/oni2#3663]
<img width="1392" alt="Screenshot 2021-06-04 at 21 13 37" src="https://user-images.githubusercontent.com/701386/120851913-c9a9df80-c579-11eb-8a73-0542fa05aa6c.png">

Initially they are rendered between two lines, but after scrolling, they end up behind the line.

This is with the latest nightly and the OCaml Platform extension.

**Comment by Minnozz** [comment]
https://user-images.githubusercontent.com/701386/120854314-412d3e00-c57d-11eb-9c9e-12146c8e557b.mov

**Comment by bryphe** [comment]
Thanks for logging the bug and the video, @Minnozz ! I've seen this occur also for the haskell extension: #2380

There's a bug in calculating the height that is hit when the codelenses are updated - starting to work through a fix in #3665
