### ISSUE TITLE
Files created after onivim2 is opened does not show up in File Explorer

### ISSUE THREAD

**Issue by Ayrx** [onivim/oni2#3671]
If a file is created in a workspace after onivim2 is opened, it does not show up until I `:cd` to another directory and `:cd` back.

A method to refresh the file explorer view would be a good QOL improvement. It could be as simple as an option in the command palette.

**Comment by CrossR** [comment]
What version of Oni2 are you running? We added an auto refresh option a little while back, as well as auto enabling it (https://github.com/onivim/oni2/pull/3365 / https://github.com/onivim/oni2/pull/3526), so this should be working! That first PR also added a refresh command, so its possible you are just a little behind.

I know I've had auto refresh working with `:e` and making files in the terminal, so it should work, though perhaps we are still missing some case.

**Comment by Ayrx** [comment]
Ah! I am on 0.5.5 so it does look like I'm one version behind. Updating to 0.5.6 works, sorry for the noise!
