### ISSUE TITLE
Nim extension raise an error on latest devel

### ISSUE THREAD

**Issue by Clonkk** [onivim/oni2#3685]
On opening Onivim, I get an error : 
```error activating extension nimsaem.nimvscode: Activating extension 'nimsaem.nimvscod' failed : ENOENT: no such file or directory, mkdir /home/rcaillaud/.config/oni2/workspace/28499f71/nimsaem.nimvscode```

I tried un-installing and re-installing the extension without success.

This happens with Onivim 0.5.9 nightly - dde00de0

**Comment by bryphe** [comment]
Thanks for logging the issue, @Clonkk - I'm able to reproduce, working on a fix in #3709
