### ISSUE TITLE
Reason_vscode extensions doesn't work in bucklescript mode

### ISSUE THREAD

**Issue by thangngoc89** [onivim/oni2#3686]
I have an old Bucklescript project (before the split). Oni2 doesn't show me typings when hovering or types completions. The same project works wtih VS Code without any special configuration.

Here is the log file https://gist.github.com/thangngoc89/3784ba3a6672cb4b52367a588946c9ec

Here is the project and steps to re-produce

```
git clone github.com/Sketch-sh/sketch-sh
cd client
yarn install
bsb -make-world
```

**Comment by amiralies** [comment]
reason-vscode is not bundled with onivim anymore. 
the vendored reason plugin is ocaml-lsp

**Comment by thangngoc89** [comment]
@amiralies Thanks. Do you have any info on installing reason-vscode with onivim?

**Comment by amiralies** [comment]
If it's available on open vsx you can install from extensions pane. if not you can download from vscode market place and use oni's command line interface to install `.vsix`.
some links:
https://marketplace.visualstudio.com/items?itemName=jaredly.reason-vscode
https://onivim.github.io/docs/using-onivim/command-line#install-an-extension

**Comment by thangngoc89** [comment]
Thank you. For reasons unknown, my build still has reason-vscode bundled but anyway, I figured out the way to use `ocaml-lsp` in my project
