### ISSUE TITLE
Using the > and < commands to increase / decrease indent should not unselect the current selection

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3689]
At current, in oni2, using ```<``` or ```>``` correctly decreases / increases indentation, also when several lines are selected, but it also (incorrectly I think) unselect the current selected lines while doing so. Can the behavior be changed to not unselect the selected lines?

See the screenshot in vim: selection is kept, even doing several increase / reduction of indentation in a row: very convenient when you need to play around to find how many indentation levels in more or less are needed:

![Screencast from 20  juni 2021 kl  21 15 +0200](https://user-images.githubusercontent.com/8382834/122685638-0548d880-d20d-11eb-8aef-e6965476a03a.gif)

vs. in oni2: selection is dropped (quite inconvenient when you want to perform several indentations but you do not see at once how many are needed and you want to "try around to find":

![Screencast from 20  juni 2021 kl  21 10 +0200](https://user-images.githubusercontent.com/8382834/122685570-7a67de00-d20c-11eb-957c-fc07299723ef.gif)

**Comment by amiralies** [comment]
Note that default behaviour in vim/neovim is to drop selection after shifting using `>` or `<`.
try with `vim -u NONE`

**Comment by bryphe** [comment]
Good catch @amiralies - indeed, this isn't actually default vim behavior.

You can replicate this in Onivim with these in your `keybindings.json` file:
```
  { "from": "<gt>", "to": "<gt>gv", "when": "visualMode && editorTextFocus"},
  { "from": "<lt>", "to": "<lt>gv", "when": "visualMode && editorTextFocus"} 
```

![2021-06-28 16 28 46](https://user-images.githubusercontent.com/13532591/123715850-06da5800-d82e-11eb-8657-ab02beda337f.gif)
