### ISSUE TITLE
how to "normal paste" stuff that has been "yanked in visual mode"?

### ISSUE THREAD

**Issue by jerabaul29** [onivim/oni2#3690]
There is a weird interwindling output issue when using multi-line ctrl-v copy.

To reproduce (see also the video under):

- perform a ctrl-v select of content over several lines
- yank it with y
- paste it with p some other place lower down

The output now gets interwindled with pre-existing text.

See the example video below to illustrate:

![Screencast from 20  juni 2021 kl  21 47 +0200](https://user-images.githubusercontent.com/8382834/122686497-9b7efd80-d211-11eb-9cb4-ae72ed309220.gif)

**Comment by kinglouie** [comment]
This is as expected because you yanked in visual block mode therefore you will paste a block. 
see this explanation https://vim.fandom.com/wiki/Cut/copy_and_paste_using_visual_selection

**Comment by jerabaul29** [comment]
Aaah, you are right. Do you know if there is any way to "normal paste" stuff that has been "yanked in visual mode"?

**Comment by bryphe** [comment]
Yep, this is the normal 'vim' behavior - this stackoverflow entry might help:
https://vi.stackexchange.com/questions/8878/paste-visual-block-selection-on-its-own-lines

If this is something you find yourself doing a lot, you could potentially add a keybinding for `:put`, like:
```
  { "key": "<c-a-v>", "command": ":put \"", "when": "normalMode && editorTextFocus"}
```

which would bind `Control+Alt+v` to that alternative paste behavior
