### ISSUE TITLE
AppImage crashes at startup on GNOME 40

### ISSUE THREAD

**Issue by zygous** [onivim/oni2#3697]
Looks like this _might_ be related to GNOME moving the gsettings key for antialiasing?

See the attached trace from starting on the CLI.
[oni.log](https://github.com/onivim/oni2/files/6699938/oni.log)

Oni tries to read `org.gnome.settings-daemon.plugins.xsettings.antialiasing`, but that setting is now at `org.gnome.desktop.interface.font-antialiasing`

**Comment by bryphe** [comment]
Thanks for reporting @zygous - possibly related to: https://github.com/onivim/oni2/issues/3528

**Comment by zygous** [comment]
Yep, sorry for the dupe. I’m on Fedora 34, so it’s not a Manjaro blip.

**Comment by DominoTree** [comment]
I posted a quick fix (based on GNOME GitLab thread) in #3706
