### ISSUE TITLE
Opening files from command line or `open with...` crashes in infinite loop - macOS M1 chip

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#3698]
Since the last two nightly updates, I've been unable to open file in Oni2 using the macOS `open with..` or with the command line. It just freezes with the swirling ball and I have to use kill to close it. It will not close any other way (Dock quit, `<cmd>-Q`, etc).

**Comment by bryphe** [comment]
Thanks for reporting @raguay ! I was able to reproduce by dragging a file to Onivim dock icon (reproduces both on M1 and non-M1 for me, and OSX 11.x + 10.x)
