### ISSUE TITLE
Failure to start on Gnome 40

### ISSUE THREAD

**Issue by DominoTree** [onivim/oni2#3706]
It looks like the gsettings schemas have changed in Gnome 40 and are preventing Oni from starting:

```
Oni2_editor:23757): GLib-GIO-ERROR **: 14:52:48.136: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Uncaught Exception:  Error: read ECONNRESET                                                                                                                                                       

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
    at Timeout._onTimeout (/tmp/.mount_Onivim9mkgPs/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/errors.js:16:31)
```

A quick fix is to do the following:

- edit `/usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.xsettings.gschema.xml` and remove the following two lines: 
```
19,20d18
<   </schema>
<   <schema id="org.gnome.settings-daemon.plugins.xsettings.deprecated">
```
- run `glib-compile-schemas /usr/share/glib-2.0/schemas` to rebuild the schemas without deprecating the `antialiasing` key

**Comment by vaporwavie** [comment]
Got the same error here, but I think it's more due to `xsettings`, since this option is related to the xorg environment, whereas I'm using Wayland. That's probably what's causing it.

**Comment by DominoTree** [comment]
I'm on Wayland as well; the key was deprecated in Gnome 40 and Oni (for one reason or another - incompatible internal GLib-GIO library or something trying to call it maybe?) is still looking for it - looks like this may be a dupe of #3697 or #3528 - every instance seems to be from Gnome 40 where the key no longer exists

**Comment by bryphe** [comment]
Thanks for the workaround @DominoTree !

Looks like we might need to bring in a similar strategy that Inkscape uses in bundling GTK with the appimage - they experienced the same [issue](https://gitlab.com/inkscape/inbox/-/issues/4784) and [fixed it](https://gitlab.com/inkscape/inkscape/-/merge_requests/3120/diffs) by bundling in the compiled schemas matching the GTK version in the AppImage.

**Comment by bryphe** [comment]
Tested the latest nightly - looks like this is still reproducing in spite of #3721

**Comment by bryphe** [comment]
Validated the latest nightly is running on Fedora 34 / Gnome 40 after #3726
