### ISSUE TITLE
Viml - Input: 'nnoremap j gj' breaks 'o' key binding

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#3729]
__Repro:__

- Add `"experimental.viml": [ "nnoremap j gj" ]` to the configuration, and press `j`
- Press `o`

Expected: Should open a new line in insert mode
Actual: Moves cursor to the top

It looks like this is exposing a bug in our input / mapping handler - on pressing the `j` key, the `j` and `g` key are sent in reverse order to libvim - so that the editor is left with an open `g` key. When pressing `o`, this interpreted by libvim as `go` , which moves the cursor to the first byte in the file.

**Comment by StephanRoemer** [comment]
I guess it is related: also these commands don't work:
```
  "experimental.viml": [ "nnoremap <Leader>o o<Esc>" ],
  "experimental.viml": [ "nnoremap <Leader>O O<Esc>" ],

```
Both commands should add an empty line, either in the current line or the line below.
But after executing, insert mode is kept, instead of switching to normal mode.

**Comment by bryphe** [comment]
Thanks @StephanRoemer - this looks like the same underlying issue as: https://github.com/onivim/oni2/issues/2579
