### ISSUE TITLE
Go to symbol and Go to buffer. Don't start with the first item selected.

### ISSUE THREAD

**Issue by pedrohenriquerls** [onivim/oni2#3763]
Version: v0.5.9-nightly 16e8ccbb
OS: 11.2.3 (20D91)
Current behavior: GoTo symbol quick open starts without select the first item.
Suggestion: It would be nice to have it starting with the first options selected to keep the same behavior of the GoTo file.

**Comment by bryphe** [comment]
Fixed with #3766
