### ISSUE TITLE
Opening a file via command line makes status bar, side bar and tab bar disappear

### ISSUE THREAD

**Issue by StephanRoemer** [onivim/oni2#3764]
I'm using OniVim as my main editor in Total Commander. I have implemented it via the command line:
`"C:\Program Files\Onivim2\Oni2.exe" "%1"`

Whereas "%1" represents the currently selected file in the pane.

Every time I open a file (when OniVim is still closed!), I get this window layout here:

![image](https://user-images.githubusercontent.com/34496643/125620972-e6d47c2e-f563-44ce-a0ea-8f141fdb39ba.png)

And this is how it should actually look like:
![image](https://user-images.githubusercontent.com/34496643/125621114-1a14e4f2-dcd7-42b0-b3b9-d3beb4221e68.png)

**Comment by kinglouie** [comment]
you can configure this in the config

from the docs:

> editor.zenMode.singleFile (bool default: true) - When true, the Onivim will automatically enter zen mode when started up with a single file. Zen mode hides most of the UI until disabled via the command pallette.

**Comment by StephanRoemer** [comment]
Gah! Thanks Matthias! I tweaked all kinds of settings but overlooked this one. Closing!
