### ISSUE TITLE
Is it going to be free?

### ISSUE THREAD

**Issue by Venus007e** [onivim/oni2#3771]
I really liked the old onivim, and just wanted to ask if the new onivim 2 is going to be free.

**Comment by dannyhpy** [comment]
It is already. Every commit in this repository is published in the [onivim/oni2-mit](https://github.com/onivim/oni2-mit) repository after 18 months under the **MIT** license.

**Comment by Venus007e** [comment]
How do i compile it on windows? I only know a bit how to do it on linux...

**Comment by CrossR** [comment]
There is some info on the license here in the README: https://github.com/onivim/oni2#license

And we have steps on how to compile it for personal use in the User Manual: https://onivim.github.io/docs/for-developers/building

Public builds are coming soon-ish, we just didn't have them out to start with to help keep the amount of feedback and support requests to a reasonable amount.

**Comment by Venus007e** [comment]
What exactly does soon-ish mean? Like in a few weeks, months, years? I´m kinda too dumb to build it. I only understand like half of the stuff -.-

**Comment by Venus007e** [comment]
Figured it out!
