### ISSUE TITLE
Bug: `:q` doesn't work as expected

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#379]
`:q` should close the buffer tabs that we have (and the editor group, if it is the last tab open), but instead, it behaves unpredictably depending on whether or not the current file has edits. If the file has edits, nothing happens, but if it doesn't - it exits completely.

**Comment by tatchi** [comment]
Isn't it similar to #300 ?

**Comment by bryphe** [comment]
Ah, sure is - thank you @tatchi ! I'll close this as a duplicate.
