### ISSUE TITLE
Add the no-ignore flag to the args to pass to ripgrep

### ISSUE THREAD

**Issue by sollymay** [onivim/oni2#3792]
As a user, when I want to use the quick open without ignoring files/folders that are part of the .gitignore, there is currently no way to set this up. In the following screenshot, dags_dev folder is part of the .gitignore:

![Screen Shot 2021-08-03 at 4 47 34 PM](https://user-images.githubusercontent.com/6496698/128197811-45aca03e-ba2a-4a41-b251-0bb8d924fca0.png)

My particular use case requires me to have a folder in the .gitignore and use that to test (as to avoid accidentally uploading stuff that should not be uploaded into GitHub), so currently there is no way for me to quickly open files inside that folder

**Comment by bryphe** [comment]
Thanks for logging the issue, @sollymay - I'm working on a fix for this in #3795 (A configuration setting - `search.useIgnoreFiles` to add the `--no-ignore` flag when using ripgrep for quick open / find in files)
