### ISSUE TITLE
Clarify project status

### ISSUE THREAD

**Issue by likern** [onivim/oni2#3811]
Thank you for your awesome project 👍🏻 
Unfortunately, lately, I've noticed significant slowdown of development.
**14 days** without commits and many commits in last months are just minor changes. No blog updates or new versions.
Looks like you've lost interest to project or there is financial issues.

Could you clarify what is happening with project, what's it's status and describe it's future?

- [ ] Is this project still your main project or a hobby (after work)?
- [ ] Do you work on it full time?
- [ ] What is financial status?
- [ ] Do you have enough money to continue working on it?
- [ ] What we are about to expect?

**Comment by jerabaul29** [comment]
Really hope this project continues / grows / thrives, I LOVE this editor, bought a license, became a patreon supporter, and I cannot wait to get debugger, bracket colorizers, bugfixes etc :) .

**Comment by bryphe** [comment]
Hi @likern @jerabaul29 -

Thanks for your concern for the project (and the really kind words of encouragement @jerabaul29 - means a lot to me!) Certainly overdue for a status update, and it's been a pretty hectic couple of months for me.

The TL;DR is that, unfortunately, I'm unable to sustain full-time development - I ran out of $ - but I'm trying to carve out time to work on it on the side. Just been a transition time for me.

Here's what I've been up to the last couple months:

In July, I was trying to find some other options for funding, and I spent most of the month pitching to VCs (putting together pitch decks, meeting VCs, follow-up meetings, etc). Unfortunately, none of the VCs were interested... a native, desktop code editor is a pretty tough sell!

In August, after failing to raise funds, I spent time dusting off my resume, interviewing, etc - I accepted a full-time offer with a really cool product / team that's still in the dev tools space. Been building a new routine and starting a new job, which has taken up most of my time. Once I get into the rhythm, I'd like to keep working on Onivim on the side (but, of course, free-time work will be slower than full-time).  

It's been a bit of a rough stretch... but I'm incredibly thankful for all the help and support :pray: 

The main thing on my mind at this point is, given the fact that I can't sustain full-time development - how can I maximize the value for everyone who helped us get Onivim this far?

Some things I've been thinking about:
- I'd like to re-license the source code to MIT. This will happen soon (ie, for 0.5.8). It'd be great to make it easier to contribute the project, and I know the current license is a potential blocker. I'll need development help more now than ever.
- I plan on turning off Patreon shortly - I can't justify keeping it active if I'm not able to work full-time. (I plan on doing something similar to when I transitioned from Onivim v1 -> Onivim v2 - convert all current patrons to a lifetime license).
- Eventually, I'd like to open up the official downloads in some capacity, but this will be further out.

**Comment by jerabaul29** [comment]
This is very understandable @bryphe . Best of luck with your new work. Truly hope you continue working on oni2 on the side, but yes side projects is tough.

A few thoughts:

- MIT license sounds amazing

- Are you sure that you want to turn off patreon? For my part, I would be still happy to pay Patreon to you if the money goes to the development of Oni2 - no reason for not getting something back for your work, even if it is on hobby time, and / or maybe you can pay some bounty system on specially tough issues? But of course, you decide.

**Comment by SeparateRecords** [comment]
I think converting all the current patrons to lifetime licenses is a good idea, but I'm not sold on disabling Patreon altogether. It's definitely worth making an announcement on there, but if you're still motivated to work on Onivim 2 I think your patrons will be happy to continue supporting you. I don't see how the extra cash could be *de*motivating 😉

I'm with @likern regarding open-sourcing. The code is already out, just not freely licensed - people can already compile it themselves, and MIT would certainly make any funding... more difficult in the future. There's room for commercial products in this space, for sure. Wrt maximizing value of current supporters, my vote is on opening up downloads.

Onivim 2 was definitely ambitious, so I can totally see why investors would be hesitant. This has got to be one of the largest Reason projects, and you, Zach and Ryan basically maintain the entire stack yourselves (minus the Reason toolchain and hardcore rendering stuff). Even if this can't be a full time or even part time thing for you, it's *so* worth reflecting on just how much this project accomplished.

Congratulations on the new job, hopefully you've got a little less financial pressure on you now! 😄

**Comment by jerabaul29** [comment]
One thought: would it be possible to give "co-administrative" rights to the "traditional contributors" of the repo for merging pull requests etc, *if* they are interested in it? Think for example of @zbaylin and @glennsl who have contributed regularly and a lot to this repo :) .

**Comment by zbaylin** [comment]
Hey @jerabaul29 -- @CrossR and I already have ability to merge PRs and "administrate" the repo. I think I personally have held off from doing that because I don't want to violate @bryphe's code quality standards, but that would certainly be an option in the future!

**Comment by jerabaul29** [comment]
Aaah, I did not know. Ok! :) .

**Comment by jerabaul29** [comment]
Should this be closed / pinned / else?

**Comment by stupid-genius** [comment]
This will come across as harsher than intended due to being online, written, etc., but I'm disappointed in the direction this project took.  At the beginning, it seemed like this project was intended to be more vim-like than it is now.  Now, it seems like this is just a VSCode clone, which is fine for the VSCode fanboys, but for those of us that can't stand VSCode it's a bit of a disappointment.  It is for me, at least; I can't speak for others.

Thanks for trying, thanks for the update, and congrats on the new job.  Good luck!

**Comment by james-lawrence** [comment]
@bryphe well damn. leave the patreon up imo. I'd love to see you able to continue working on the project. I've been eagerly waiting for this to become my daily driver.

**Comment by cuylerstuwe** [comment]
> Also quite strange no funding giving the fact how successful was Jetbrains (Intellij IDEA), I think they are very financially successful.

[JetBrains was not VC-funded, either](https://twitter.com/intelliyole/status/1154620416473862154?s=20).

**Comment by likern** [comment]
> > Also quite strange no funding giving the fact how successful was Jetbrains (Intellij IDEA), I think they are very financially successful.
> 
> [JetBrains was not VC-funded, either](https://twitter.com/intelliyole/status/1154620416473862154?s=20).
> 
> Their editors are also not focused exclusively on modal editing _(devs who prefer Vim are a niche)_.
> 
> Nobody with any common sense should ever have expected OniVim 2 to be a commercial success. I was excited for it, but I'm aware that my tastes are a bit more elite than the mainstream.

It's the other way around. Isn't popular not because of `Vim`, but because Vim stayed as text editor, while developers need IDE. Give them high-quality modal support and you'll see how it will be commercially successfull.

1. VS Code Vim plugin - 2,965,722 installations
2. VS Code Neovim plugin - 104,615 installtions
3. Intellij Idea IdeaVim - 10 902 178 downloads

**Comment by cuylerstuwe** [comment]
> It's the other way around. [...] Give them high-quality modal support and you'll see how it will be commercially successfull

It's a little disheartening to read that someone actually believes that.

> 1. VS Code Vim plugin - 2,965,722 installations

You're missing a **crucial** datapoint: **Of how many VS Code installations?**

**Comment by likern** [comment]
@cuylerstuwe That's more than enough to be successfull. 
Quokka.js has 1,269,898 installs and Wallaby.js has only 115,133 installs. They started with one niche product (developed by one men). Now they have several products, they definitely successfull, they always were profitable. I don't now how big the company is, but suggest it's at least a small team.

**Comment by cuylerstuwe** [comment]
> @cuylerstuwe That's more than enough to be successfull.
> Quokka.js has 1,269,898 installs and Wallaby.js has only 115,133 installs. They started with one niche product (developed by one men). Now they have several products, they definitely successfull, they always were profitable. I don't now how big the company is, but suggest it's at least a small team.

Again, two major mistaken assumptions:

1. You're assuming that extension installation count reflects users who kept it installed on the machine and who use it regularly.
2. You're assuming that these separate markets have the same propensity _(and capacity)_ to purchase a commercial solution that solves the same problem.

**Comment by james-lawrence** [comment]
@cuylerstuwe you're picking and choosing your data to match your preconceptions. the requirements to be successful here are a large enough userbase that is willing to pay a subscription fee to keep the developers going, you only need around 3400 users at $5 a month to achieve a 200k USD income. the numbers don't need to be huge and they almost certainly exist within the population.

there are plenty of reasons why any given attempt doesn't succeed, but your assertion that the population doesn't exist isn't backed up by anything being discussed here.

**Comment by likern** [comment]
@cuylerstuwe I don't make any mistaken assumptions, I give estimations. The potential userbase up to 13 millions users (+XCode users who uses vim plugins or shortcuts). The conversion to real users is unknown. And how you judge it can't be successful? The way you are reasoning every fail can be described as unavoidable and "objective". That's totally not true.

User base of potential users is huge. Far more than for many startups who get funding. Users willing to pay too (estimation). Even if 3millions installations will convert to 300 000 (1:10 ratio) develops - that's huge. Considering that they well paid in all countries.

**Comment by cuylerstuwe** [comment]
> you only need around 3400 users at $5 a month

That's a lot of users. With niche products like this, It's generally harder to acquire a user than to convince a die-hard user that it's worth paying more for a product.

> to achieve a 200k USD income

No, this is not even close to correct. You're calculating dramatically-oversimplified gross billing rather than _"income"_. You need to subtract payment transaction fees and other business expenses before you start considering individual _"income"_.

Stripe's fees alone would take the gross down from from 204k to 185k. After even minimal other expenses are considered _(e.g., hosting/bandwidth for downloads, etc.)_ you're likely to be down to 150k or lower.

And whatever is left over would need to be distributed to anyone working on the project.

Your estimates are wildly optimistic.

> User base of potential users is huge. Far more than for many startups who get funding.

And yet reality suggests that real VCs disagree. Again: I'm simply explaining reality.

**Comment by likern** [comment]
You customize reality for yourself using happened fact as basis. The only reality is that project, unfortunately, unsuccessful. And I know why, at least have my own interpretation.

All your other explanation of reality are just assumptions not backed up by anything. 

First, it's not the niche product. It's just current state of affairs. Before was the other state, when vim was highly popular and had significant market share. There's nothing inherently impossible in this project. Developers very actively use shortcuts, many, if not most, use bling typing.

They are "not interested" only because they had to choose between modal text editor and fully functional IDE. The choice is obvious. IDE didn't have modal by real and again obvious reasons - resources, they implemented far more important features. Modal adds additional layer of complexity.

Modal is so "unneeded" that XCode 13 added Vim mode https://developer.apple.com/xcode? Hmm...

Project was unsuccessful not because it didn't have users willing to pay. It just was too ambitious - not only developing full-blown IDE, but using esoteric language and it's own UI framework. Trying to support everything. Many many reasons, obviously not "no users willing to pay".

You again had choice to use full-blown IDE like VS Code or modal IDE which barely working - it's absolutely not suitable for everyday working and lacks a lot of essential features. So by that reasons not many early adopters to pay are willing to pay. Because who paid mostly knew they invest, it's not a product.

Instead of concentrating on performance it would be better to just directly fork VS code and add modal layer on top of it. So we could get direct benefits. Later update fork additing performance.

Also you do not consider how markets are created. Modal editing could easily create new market as it already did. But now on top of IDE, without sacrifices.

**Comment by cuylerstuwe** [comment]
> Modal is so "unneeded" that XCode 13 added Vim mode https://developer.apple.com/xcode? Hmm...

Those same update notes put _"Vim mode"_ on the same level of importance as _"CarPlay support"_.

If anything, the fact that it took 13 major versions of the only native Apple IDE before they considered adding support should be your sign that it's a niche request. 😉

**Comment by zbaylin** [comment]
I'm gonna lock this for now until @bryphe decides if he wants to give more context.
