### ISSUE TITLE
Feature Request: Integrated Terminal

### ISSUE THREAD

**Issue by dalisoft** [onivim/oni2#3816]
Hi @onivim team.

Thank you for amazing app, i am licensed user :)

Do you plan adding feature "Integrated terminal" like VSCode? I just use this feature very frequently so if this will be implemented would be nice

**Comment by l2ig** [comment]
It already is, `:term` is the command I think

**Comment by dalisoft** [comment]
Yes, it is, but looks like a buggy and not smooth and stable like VSCode, i'd like to see it to be fixed
