### ISSUE TITLE
Installing dependency "windows-build-tools" on Windows.

### ISSUE THREAD

**Issue by Fivro** [onivim/oni2#3820]
When I tried to install 'windows-build-tools' following the [official user manual](https://onivim.github.io/docs/for-developers/building), npm says that I don't need to install the package because it is already included into nodejs. Is "windows-build-tools" still required to build onivim2?

**Comment by Et7f3** [comment]
https://github.com/revery-ui/esy-skia require a cl 2015 or 2017 in PATH if you already have installed manually with vs studio it shouldn't be required and for the one installed by node you might need to set a WIN_VC env var that point to the node installation

**Comment by Fivro** [comment]
Ok, so maybe still I need to install the package. Thank you @Et7f3!
