### ISSUE TITLE
open onivim2 from the terminal

### ISSUE THREAD

**Issue by ghost** [onivim/oni2#3856]
when i want to edit a file from the terminal i wish if i can use onivim (the path to the file) and onivim2 will open with the file to edit just like vscode with the code command

**Comment by Fuzznimp** [comment]
Which OS are you using?
On MacOS:
```
# ~/.zshrc
alias oni="/Applications/Onivim2.App/Contents/MacOS/Oni2"
```

**Comment by veryspry** [comment]
You can actually do this pretty easily by directly running the program executable on disk when you install OniVim!

As an example, I installed as an AppImage, so I've got a `AppRun` file that serves as the executable to run OniVim2. For me, that file is:

```bash
$HOME/AppImageKit/Onivim2.AppDir/AppRun
```

I can open a directory or file like so:

```bash
$HOME/AppImageKit/Onivim2.AppDir/AppRun ./some-directory
```

I also aliased this in my shell config file for easier use:

```bash
alias oni="$HOME/AppImageKit/Onivim2.AppDir/AppRun"
```

Which means I can do this to open a file / directory with Oni:

```bash
oni ./some-directory
```

You can probably do something similar to get your desired behavior. The caveat is to make sure you find the exact path to the program executable as installed on your machine and substitute that for the example here.

Hope this helps!

**Comment by ghost** [comment]
Thank you
