### ISSUE TITLE
modifier keys+shift inserts <D-SHIFT> or <A-SHIFT> into buffer

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#415]
How to reproduce: be in normal mode, mash any combination of ctrl, alt, super, and shift and odd text gets inserted into the current buffer similar to https://github.com/onivim/oni2/issues/360

**Comment by szbergeron** [comment]
Looks like ctrl changes what is inserted, but this only happens if some combination of super and or alt is included in the action

**Comment by nilscox** [comment]
On insert mode, pressing $mod+shift inserts `<D-SHIFT>`. (It only inserts `HIFT>` on normal mode).

I am running the packaged AppImage of Oni2 on Archlinux using i3 as window manager, and the "mod" key refers to the "windows" key on my keyboard.
Let me know if you need any extra info to reproduce.

**Comment by despairblue** [comment]
I opened a PR here to fix this, if you can build from git you can check if it works :)

https://github.com/onivim/oni2/pull/637
