### ISSUE TITLE
Closing last tab with close button (by mouse, not :q) overrides unsaved change check

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#417]
:q doesn't close the last remaining tab if there are unsaved changes in a file (same as vim, but no alert given), but using the close button on a tab ignores this check and closes the tab, and sometimes the whole editor.

**Comment by leavengood** [comment]
There are still a bug related to this (#733), but I believe this was has been fixed. At least when I get into the bad state from #733, if I close the window, I get the "do you want to save" prompt.
