### ISSUE TITLE
zb doesn't move cursor with viewport all the way to bottom

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#420]
zt and zz both work to put cursor at current position in buffer at the top and approximate middle of the viewport, but zb only moves cursor with viewport to bottom third, not bottom as L does to the cursor independent of the viewport.

**Comment by szbergeron** [comment]
This one seems inconsistently reproduceable, I'm working on a better methodology as it's probably an edge case.

**Comment by szbergeron** [comment]
It seems all of the cursor-relative-to-viewport movements are somewhat inconsistent, particularly with files smaller than the viewport as a whole, including zb/zt/zz, and H/M/L

**Comment by szbergeron** [comment]
Looks like this issue could actually be further expanded: if 415 has been reproduced in the current session, the entirety of what acts as the viewport is limited to a smaller portion of the total actual (visitble) viewport (sometimes as little as the top third) and movement only happens within that.

**Comment by bryphe** [comment]
Also fixed with #2597
