### ISSUE TITLE
Scrollbar/minimap: click and drag doesn't work (Linux: X11/Xwayland)

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#441]
Platform: linux, oni running in xwayland on Sway with libinput

Action: click on minimap or scrollbar handle, move cursor up or down with long file
Expected result: viewport scrolls
Actual result: dragging with mouse held down produces no result, sometimes handle sticks to mouse on cursor release and moving cursor without clicking drags viewport around wildly and unpredictably

**Comment by bryphe** [comment]
This should be fixed now in latest `master` - feel free to open a new issue if you're still seeing issues around this 👍
