### ISSUE TITLE
Cursor escapes split bounding box on scroll

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#443]
Action: create horizontal split (:spl) in long document, scroll up or down with mouse wheel
Expected result: TBD (cursor contained inside split bounding box, or cursor stays in same place in document but hides under another split)
Actual result: cursor escapes split bounding box and covers the other split view

**Comment by szbergeron** [comment]
This is mostly fixed now, the cursor does not escape the bounding box of the split, but it does cover the tab bar for the split it's in in certain situations

**Comment by bryphe** [comment]
Looks like this is fixed in latest builds - I don't see the cursor intruding on tab bars anymore in splits
