### ISSUE TITLE
Configuration: Add 'editor.rulers' configuration option

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#460]
We should add support for the `editor.rulers` configuration option, similar to what VSCode provides.

This configuration option takes an array of numbers, like:
```
"editor.rulers": [80, 120]
```

And draws a vertical rule on the editor surface.

There'd be a few things we'd need to add:

__Part 1 - Add a Configuration Setting__

We'd need to add the configuration definition to [Core/ConfigurationValues.re](https://github.com/onivim/oni2/blob/29085a2f859f631937f182ffc3d81044c78c87d7/src/editor/Core/ConfigurationValues.re#L14) and a default value to the same file [here](https://github.com/onivim/oni2/blob/29085a2f859f631937f182ffc3d81044c78c87d7/src/editor/Core/ConfigurationValues.re#L37).

We'd also need to add a `ConfigurationParser` that knows how to handle parsing an array of numbers in [Core/ConfigurationParser.re](https://github.com/onivim/oni2/blob/master/src/editor/Core/ConfigurationParser.re) - it'd be similar to the `parseStringList` configuration parser in that file.

__Part 2 - Pick up configuration setting and render__

For the actual rendering of the editor rulers, we'd want to draw a 1-pixel wide rectangle on the editor surface, at the proper column. We'll need to take into account the line number and the font size.

We can read from the configuration and get the `editorRulers` like we do for other configuration values, like line numbers: https://github.com/onivim/oni2/blob/29085a2f859f631937f182ffc3d81044c78c87d7/src/editor/UI/EditorSurface.re#L206

This rendering could take place in [`UI/EditorSurface.re`](https://github.com/onivim/oni2/blob/29085a2f859f631937f182ffc3d81044c78c87d7/src/editor/UI/EditorSurface.re#L498) right around where we render the background for the cursor line (we'd probably want to render these rulers _after_ the cursor line, though).

For each `editor.ruler`, we could call the [`bufferPositionToPixel`](https://github.com/onivim/oni2/blob/29085a2f859f631937f182ffc3d81044c78c87d7/src/editor/UI/EditorSurface.re#L251) helper method for each value. The `line` value we could ignore and pass in something like 0 or  1 - we care about the `char` value, which would correspond to a value in the editorRulers array. This would give us the _pixel position_ of the editor ruler, taking into account line numbers, scroll, and the font width.

We could then draw a rectangle from (pixelX, 0) to (pixelX + 1, metrics. pixelHeight) using the Shapes.drawRect API, which would draw a 1-pixel wide rectangle. We can just hardcode a color for now.

__Part 3 - Add a theme color__

Lastly, we'd want the `editor.rulers` to be themable - so we should add a theme color like `editorRulerForeground`. These can be added in `Theme.re`: https://github.com/onivim/oni2/blob/29085a2f859f631937f182ffc3d81044c78c87d7/src/editor/Core/Theme.re#L10

We should use this theme color instead of our hard-coded value in Part 2.

**Comment by KevinSjoberg** [comment]
@bryphe I'm really interested becoming more involved in the project, so I'd be happy to take a stab at this. 🙂

**Comment by bryphe** [comment]
Awesome! Thanks for the help, @KevinSjoberg !

**Comment by bryphe** [comment]
Implemented, unit tested, and documented - great work @KevinSjoberg !
