### ISSUE TITLE
No way to resize splits

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#463]
Expected/proposed interface: vertical resize from command view sets absolute/relative changes to split size, hovering over edge between two splits shows a resize cursor and allows a drag to manually resize viewports

**Comment by DanielPower** [comment]
Ideally there would be both a mouse and a keyboard way to do this. I would most likely use the mouse to resize, but I know many would prefer never having to touch the mouse.

**Comment by jerabaul29** [comment]
Is there a keyboard option? I tried ctrl-w+{hjkl} but it does not seem to work. This is what #1643 was asking for, and it was closed via this issue, but it seems that this issue does not add the keyboard possibility?

**Comment by glennsl** [comment]
Hmm, yeah sorry, those keybindings have not been implemented yet so I've reopened that issue. I'm still working in this area though, so will hopefully have them soon.

**Comment by jerabaul29** [comment]
Many thanks, no worries :)
