### ISSUE TITLE
Windows - Setup: Add file association registry keys

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#468]
__Issue:__ When right-clicking on a file in Windows, after having set up Onivim 2 via the installer, there is no option for Onivim 2 to open a file.

__Defect:__ We're not setting the registry keys in the installer.

This was implemented for Onivim 1 in https://github.com/onivim/oni/pull/613 and https://github.com/onivim/oni/pull/1769 - we need to port over that logic for our Onivim 2 installer.

**Comment by CrossR** [comment]
This should be as simple as populating the `fileAssociations` array in the `package.json`, with some common extensions.

As a first pass, its probably makes sense to based on the syntax highlights we have bundled.
