### ISSUE TITLE
Suggestion list doesn't scroll when tabbing off end

### ISSUE THREAD

**Issue by szbergeron** [onivim/oni2#469]
Steps to reproduce: 

1. use ctrl-p or :e in a folder with a lot of files
2. press tab several times

when the highlighted item reaches the last visible item, and then tab is pressed one more time, the highlighted entry is no longer within the dropdown viewport and no feedback is given for what the selected item is

Expected behavior: either contents of the dropdown scroll to contain the currently highlighted/selected entry, or no entry outside the visible dropdown viewport is allowed to be selectable (personal preference for the first option)

**Comment by glennsl** [comment]
FYI: I'm working on this as part of the menu renovation project.
