### ISSUE TITLE
Forgot to write activation key

### ISSUE THREAD

**Issue by karambaq** [onivim/oni2#472]
Hey, I've just pre-ordered oni2 via paypal, and it showed me something like activation key and something else, and I didn't screenshot it, how can I find this information?

Thank you

**Comment by lourenci** [comment]
Didn't you receive any email? The activation key arrived in my inbox a few minutes after the purchase.

**Comment by CrossR** [comment]
If you received a PayPal receipt, it should be in that email as well.

**Comment by karambaq** [comment]
@CrossR @lourenci Oh thank you guys, it was in spam for some reasons. Also sorry for nub question, but is there some build available or I need to build it from source?

**Comment by CrossR** [comment]
Builds are on track to be released at the end of the month. There should be some form of portal to download a complete build then.

For now, you can build from source though.
