### ISSUE TITLE
Packaging - OSX - Codesigning: Automate notarization

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#500]
Even though our OSX distribution builds are code-signed, they still trigger GateKeeper, because they are not [notarized](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution).

We need to automate this and hook it up as part of the code-signing step for our DMG.

**Comment by mhanberg** [comment]
I think this is the relevant documentation: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow#3087734

**Comment by bryphe** [comment]
Thanks @mhanberg ! Think I'm close to getting it working... 🤞
