### ISSUE TITLE
Clipboard Integration

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#506]
We should have a sane, simple, out-of-box interaction with clipboard. Right now, there is no clipboard interaction at all, which is pretty broken.

My proposal would be the following (similar to what we had in Onivim 1):

- __Insert Mode__ + `Control+V`/`Command+V`- paste from clipboard as if typed
- ~~__Normal Mode__ + `Control+V`/`Command+V` - paste from clipboard as if entering insert mode and running `Control+V`, and return to normal mode with cursor at the end of the text~~ 
-~~ __Visual Mode__ + `Control+C`/`Command+C` copy visual selection to clipboard, and exit visual mode.~~

I think this would be a reasonable start to unblock simple cases.

We should also wire up the `"+` register to pull from the system clipboard by setting up a callback in `libvim`.

**Comment by Wehrdo** [comment]
I like the suggestions for **Insert Mode** and **Visual Mode**, but in **Normal Mode**, Ctrl+V enters visual block mode, which is a great feature of vim when editing multiple similar lines. Personally, I would prefer:
 - **Normal Mode** + `Control+V` / `Command+V` - Enter Visual block mode (as per normal vim)
 - **Normal Mode** + `Control+Shift+V` / `Command+Shift+V` - paste from clipboard as you described above. This is how VS Code's Vim plugin handles it, which I like. The Ctrl+Shift+V for paste is also similar to some terminals which treat the Ctrl+V as a different input.


And isn't the `"*` register also typically mapped to the system clipboard in addition to the `"+` register?

**Comment by Apostolique** [comment]
I'm fine with `Control+V`/`Command+V` in insert mode, but I think in normal mode, it would be `p` or `P`.
For visual mode, to copy it should be `y`.

Essentially, `Control+C`/`Command+C` should not be used out of the box. Instead, use normal Vim yanking and pasting.

**Comment by Dom-R** [comment]
Agree with @Wehrdo and @Apostolique opinions.

I specially would not like to see a default and used command like ctrl+v on normal mode to be overwritten to work as a paste option, this option(if implemented) should be up to the user to enable it.

**Comment by bryphe** [comment]
Thanks all for the feedback! I'm on my way to implement the insert-mode piece in #572 

I'm planning on adding some hooks in `libvim` for handling the `"*` and `"+` registers (an API for clients to register to decide how to handle them), that we can hook into from Onivim 2.

One additional piece I was thinking about was adding a `vim.useSystemClipboard` setting, that would add this additional behavior:
- All `yanks` or `deletes` w/ the default register would be pushed to the system clipboard

**Comment by bryphe** [comment]
Splitting this up into 3 pieces:
- [ ] Part 1: Control+V/Command+V integration in insert mode
- [ ] Part 2: yank/delete push to clipboard with `vim.useSystemClipboard` - working on the libvim API here: https://github.com/onivim/libvim/pull/153
- [ ] Part 3: integrate clipboard registers with Onivim 2  - I realized there is a bug with registers in general in libvim, so that will need fixing first
