### ISSUE TITLE
Packaging - Windows: Installer shows SmartScreen

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#509]
When installing Onivim 2 via the installer executable on Windows, we get a SmartScreen notification:

![smart-screen-1](https://user-images.githubusercontent.com/13532591/62213725-6c7aec80-b358-11e9-82f6-4ca99e509621.png)

![smart-screen-2](https://user-images.githubusercontent.com/13532591/62213733-700e7380-b358-11e9-9267-385af7cfb302.png)

This, unfortunately, is a normal course of action for Windows applications - even though we've code-signed it. Windows SmartScreen requires that applications build up 'reputation'.

Relevant StackOverflow posts [here](https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why) and [here](https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why).

An option to bypass this is to purchase an EV certificate, but unfortunately this is more expensive and also cannot be run on CI (requires hardware validation).

**Comment by bryphe** [comment]
It looks like there might be a way to use Windows App Certification Kit to speed up this reputation process:
https://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application/28359323#28359323

**Comment by Raikiri** [comment]
honestly this whole EV certification thing seem like a total rip-off for small-scale developers.

**Comment by bryphe** [comment]
Looks like this has gone away on the latest builds, at least on the Windows machines I've tested 🎉
