### ISSUE TITLE
Performing actions on long lines is laggy

### ISSUE THREAD

**Issue by Azumgi** [onivim/oni2#515]
~5000 characters line causes significant lag
~30000 line almost freezes the editor
The further you move the laggier it becomes. Toggling syntax highlighting does not affect anything.

OS: Windows 10

**Comment by bryphe** [comment]
Potentially related to our currently-slow syntax highlighting strategy - https://github.com/onivim/oni2/issues/161 - which we are looking for a native alternative for. Need to also check if this reproduces w/o syntax highlighting (like a `txt` file).

**Comment by Azumgi** [comment]
Disabling highlighting does not affect anything.

Update: Seems like the problem is not caused by the line length, but by the brackets in it. You can reproduce it by going to EULA.md#55 which ships with oni2. It stops lagging when you jump to the end of the line. But if you move left it will get laggy again once you hit the first bracket.

**Comment by CrossR** [comment]
This looks to still be occurring now with the native highlighting options, so isn't HL related. From my quick test, the start of the line was completely fine, but when I `$`ed to the end, it was very slow.

**Comment by bryphe** [comment]
I did some debugging / profiling here - I see that there are several places where we are iterating over the entire line string during the course of rendering (which is _very_ slow). In particular, the UTF8 operations we do are requiring traversal (with length requiring traversing the whole string).

Lookiing at speeding this up in #1224
