### ISSUE TITLE
Wayland: Blurry rendering under high DPI

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#516]
Reported on twitter: https://twitter.com/williamsgarth/status/1156646606894260224

Seems likely we aren't getting the proper DPI in this case - I wonder if the more robust APIs in GLFW 3.3 will help?

**Comment by garth** [comment]
It looks it might be related to going though xwayland instead of native. Other non-native apps like electron have the same issue.

**Comment by kyldvs** [comment]
Is this related to https://github.com/revery-ui/revery/issues/528 ?

**Comment by CrossR** [comment]
How is this looking now that the scaling support is better?

Also noticed my issue in Revery is still open...I should probably close that.

**Comment by janza** [comment]
This seems to be solved now, latest oni version renders just fine.

**Comment by bryphe** [comment]
Great news! Thanks @janza for checking 🎉 I'll close this out, but if there are still issues we can track in a new one

**Comment by garth** [comment]
@bryphe Just tested the latest build under swaywm (wayland), unfortunately it's still not fixed.

The problem seems to be that wayland is not supported natively by onivim2, so it's running through xwayland emulation. Gnome will do some magic to fix scaling issues with x apps running via xwayland, but wlroots based desktops won't do that and simply scale up the image, so it looks very blurry.

**Comment by szbergeron** [comment]
Hi @garth, you should be able to pass SDL_VIDEODRIVER=wayland in environment variables to run in native Wayland mode. Fair warning, the Wayland protocol doesn't actually allow for fractional scaling so on wlroots based desktops it will still be slightly blurry (unfortunately not much we can do there.) We may be able to tie into whatever interface kframeworks exposes to get sharp fractional scaling on Kde but that would be a separate push that wouldn't carry over to other desktops.

**Comment by garth** [comment]
Thanks @szbergeron, I had tried GDK_BACKEND, but not seen SDL_VIDEODRIVER before.

So, I can confirm that it's working under sway with SDL_VIDEODRIVER=wayland. 

I'm aware of the fractional scaling, so generally stick with a factor of 2 and use font sizing to fine tune.

**Comment by szbergeron** [comment]
@garth so revery itself actually supports full fractional scaling now, I forget what the flag is off the top of my head but it can draw all UI and fonts at the requested fractional scale. It's just there's no way to make it do that automatically (rather than the user manually setting it)

**Comment by garth** [comment]
@szbergeron only issue with SDL_VIDEODRIVER=wayland seems to be that the window doesn't resize, so whatever size it starts with is fixed until the app is restarted.

**Comment by szbergeron** [comment]
@garth yep, was able to repro earlier, forgot to open a bug. It's a cross-desktop wayland thing, not yet sure the cause is in SDL or in reason-sdl2
