### ISSUE TITLE
OSX - Add 'Add to Path' option

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#518]
We should have a streamlined way to 'Add to Path' so that Onivim 2 can be used from the CLI in Mac via `oni`. 

For now (while we don't have brew builds) - we should add that option to the command palette. This would create a wrapper bash script accessible in the path to open Onivim 2.

**Comment by mhanberg** [comment]
@mrvicadai This works for me, thanks! But I noticed that this will open a second instance of Oni (as in, shows up twice in the cmd+tab menu). 

![oni-command-tab-duplicate](https://user-images.githubusercontent.com/5523984/62245835-6a447c80-b3b0-11e9-8bc3-a98e598fecb3.gif)

**Comment by mrvicadai** [comment]
@mhanberg great to hear that it works!

> open a second instance of Oni

I haven't personally encountered that issue -- maybe someone else have a solution?

**Comment by CrossR** [comment]
I've written (well stolen from Oni1 mainly) a script to do this, and tested it by jamming it inside another Oni2 action.

Currently, adding a symlink to Oni2 in `/usr/local/bin` doesn't work, as launching Oni2 from a symlink fails. You can check this with a local install or dev build of Oni2 and just `ln -s` to it.

I think the code over in `Oni2.re` needs to include a call to `Unix.readlink` if `stat` says there is a symlink. A quick test of doing that seemed to work, but I assume there is some considerations I need before editing that code?

**Comment by bryphe** [comment]
Nice! Thanks for your help with this @CrossR !

> I think the code over in Oni2.re needs to include a call to Unix.readlink if stat says there is a symlink. A quick test of doing that seemed to work, but I assume there is some considerations I need before editing that code?

Ah.. ya, this is tricky. I was thinking about bundling a wrapper script, like this:
https://github.com/onivim/oni2/blob/master/scripts/osx/run.sh

- We could bundle `run.sh` in the `Resources` folder of the app bundle

- Update the path to be relative to the `Resources` folder, ie:
https://github.com/onivim/oni2/blob/7981176ddef64cd8ea94177f2fe47e8d05ba7210/scripts/osx/run.sh#L14
Could be:
```
$DIR/../MacOS/Oni2 --working-directory "$CWD" "$@"
```

That script resolves the symlink, so that `Oni2.re` wouldn't need to be updated - and passes through the working directory.

Then, we'd create the symlink from `/usr/local/bin/oni2` to `/Applications/Onivim2.App/Contents/Resources/run.sh`

**Comment by CrossR** [comment]
An add to path option has now been added (for macOS).
If there is any issues, they should be raised seperately, so I'll close this out.

**Comment by bryphe** [comment]
Awesome @CrossR ! So nice to have this now.
