### ISSUE TITLE
The default config has a comma at the end

### ISSUE THREAD

**Issue by Raikiri** [onivim/oni2#525]
configuration.json in Oni2 installation directory looks like this:
```json
{
  "editor.minimap.enabled": true,
  "editor.insertSpaces": false,
  "editor.indentSize": 4,
  "editor.tabSize": 4,
}
```
And I think that comma before closing brace makes it fail to parse it.

**Comment by CrossR** [comment]
I've stuck a longer comment over in #524, but the tl;dr of that is that this issue (and #524) should be fixed as a consequence of doing https://github.com/onivim/oni2/issues/356.
