### ISSUE TITLE
Pre-alpha builds not running in Solus OS

### ISSUE THREAD

**Issue by guilhermehto** [onivim/oni2#531]
Hey there!

I'm currently running Solus 4.0 Fortitude with Budgie.
Tried both the AppImage and the `.desktop`. The former opens and closes in a fraction of a second, and there are no logs in my terminal when this happens so I'm not sure what's going on. 
The latter gives me an error: `There was an error launching the application`.

Sorry for not being able to give more information.

**Comment by bryphe** [comment]
Hi @guilhermehto !

Would you mind trying one of the latest builds? We just pulled in a fix for #514 - I wonder if this is the same issue?

**Comment by guilhermehto** [comment]
Hi @bryphe!

Just downloaded the latest build.

It's not crashing anymore! Thanks for the fix :smiley:

**Comment by bryphe** [comment]
Great news! 🎉  Thanks for confirming @guilhermehto !
