### ISSUE TITLE
Early Access Build - Linux - Can't Edit Settings

### ISSUE THREAD

**Issue by djhi** [onivim/oni2#532]
Congratulations on the alpha release :)

I downloaded the appimage on Ubuntu 19.04 and Fedora 30, followed the instructions.

The editor seems to work great, however I can't edit the settings. I can see a oni2 directory in my `.config` but it is empty. 

Please tell me if you need any more informations to debug this :)

**Comment by albertorestifo** [comment]
The same is happening to me

**Comment by jberglinds** [comment]
Same problem for me on macOS. Solved it for the moment by manually copying the configs in `Onivim2.app/Contents/MacOS/` to `~/.config/onivim2/`

**Comment by CrossR** [comment]
I'm going to close this out as its a duplicate of #524, but thanks for raising!
