### ISSUE TITLE
Error on Linux Mint

### ISSUE THREAD

**Issue by kuator** [onivim/oni2#533]
When I run AppImage it shows the following: `/tmp/.mount_OnivimdQvSB3/AppRun: 3: export: 4.2/dist/bin: bad variable name`.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
```

**Comment by bryphe** [comment]
This might be the issue: https://stackoverflow.com/questions/26251272/bad-variable-name-in-bash-script-started-by-cron

**Comment by bryphe** [comment]
Hi @kuator ,

I believe  #539 should have fixed this - the latest build on the [early access portal](https://v2.onivim.io/early-access-portal) has this fix - would you be up for trying the latest build and see if the issue still reproduces?

**Comment by kuator** [comment]
@bryphe, it works :+1:

**Comment by bryphe** [comment]
Excellent! Thanks for verifying @kuator 👍
