### ISSUE TITLE
"Open configuration file" does not work/respond

### ISSUE THREAD

**Issue by thomas-haslwanter** [onivim/oni2#535]
I am working on Win64, with onivim2 Ver.  2.0.2.0
The problem:
While "CTRL+SHIFT+P" does bring up the Preferences option, selecting
Preferences: Open Configuration file
and then hitting either the "Right" key or the "Enter" key leads to no response (the same happens when selecting "Open keybindings file")

Possibly related:
typing
:set
or
:f 
leads to no visible response.

**Comment by eljuanchosf** [comment]
Seeing same behavior here. 
OS: Windows 10 64 bits.

**Comment by CrossR** [comment]
This is due to the issue outlined in #524, since we can't copy the config, we can't edit the config.

I'll leave this open (as a duplicate) since it is perhaps easier to find, but the real fix will be #356.
