### ISSUE TITLE
Bug - Spaces in directories cause autocomplete to break

### ISSUE THREAD

**Issue by satvikpendem** [onivim/oni2#536]
When tabbing through directories to open a file, if there is a space in the directory, the directory autocomplete changes the word after the space into the autocompleted directory.

For example, if the directory is `C:\Users\New User`, on tab, it now becomes
`C:\Users\New C:\Users\User1` 

I am on Windows 10 with the pre-alpha build as of 2019-08-01.

**Comment by bryphe** [comment]
Thanks @satvikpendem ! This is a dup of #434
