### ISSUE TITLE
Click-Drag mouse highlighting does not work

### ISSUE THREAD

**Issue by jrwrigh** [onivim/oni2#537]
Click-drag highlighting with mouse does not work currently, even when running `:set mouse=a`. 

I'd add more info, but I don't know what else to report on the issue. This also may be more of a feature request than an bug.

OS: Windows 10
Version: N/A

**Comment by bryphe** [comment]
Yep, missing feature - basic mouse interaction we need. Thank you for logging it @jrwrigh 👍

**Comment by smolin** [comment]
Is this feature on the roadmap yet? Being able to use the pointer to interact with the cut-and-paste select buffer would be a huge step toward usability. Thanks!

**Comment by CrossR** [comment]
@smolin  Everything that is tagged as `daily-editor-blocker` is on the roadmap before we consider Oni2 "beta" quality!
