### ISSUE TITLE
Syntax highlighting w/o file extension?

### ISSUE THREAD

**Issue by vincentjorgensen** [onivim/oni2#548]
Commit: 64c9982

If I have a script that ends in `.sh` syntax highlighting seems to behave correctly, but if I have a script w/o an extension, though it still has either `#!/usr/bin/env bash` or `#!/bin/bash` as the first line, syntax highlighting is turned off. (Ditto for `.py` and `#!/usr/bin/env python`). Thanks.

**Comment by bryphe** [comment]
Thanks for the issue, @vincentjorgensen !

Indeed, the VSCode language contribution has a way to handle this - they specify a `firstLine` to match the language:
https://github.com/onivim/oni2/blob/dd0eae0087676bb33ec0cf78f19e25097cec5a1f/extensions/shellscript/package.json#L18

We should be using that when we detect the language for syntax highlighting

**Comment by bryphe** [comment]
Looks like this is fixed now with @CrossR 's changes in #2119

**Comment by vincentjorgensen** [comment]
Confirmed. Thanks.

**Comment by Dark-Matter7232** [comment]
it fails to detect detect dash shell

**Comment by CrossR** [comment]
We just need to update our bundled VSCode Shellscript extension, as they only added support for dash in May it seems.

https://github.com/microsoft/vscode/tree/master/extensions/shellscript
