### ISSUE TITLE
Configuration: Set editor font family and size

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#549]
We're missing customization options for setting the editor font-family and size. 

We should integrate with https://github.com/revery-ui/reason-font-manager to be able to resolve a font from a family name, and use that instead of requiring a full font file path.

This should be specified by JSON configuration options:
- `"editor.fontFamily"`
- `"editor.fontSize"`

**Comment by pertrai1** [comment]
This is definitely a blocker for me to using this. The font is way too small on Windows.

**Comment by bryphe** [comment]
Definitely, this is a major blocker - this is next on my list after wrapping up #506 

I've started the work to integrate a cross-platform font-discovery service with ReasonML (as far as I could tell... there wasn't already a library that did this): https://github.com/revery-ui/reason-font-manager

...one of those things I take for granted!

I'll look at splitting this up into two parts, as well - the `editor.fontSize` setting could go in first without needing the font discovery work.

**Comment by bryphe** [comment]
Oops, accidentally closed this with #598 - still need to implement Part 2 (selecting the font!)
