### ISSUE TITLE
Bug: Large edits cause syntax highlighting rainbows

### ISSUE THREAD

**Issue by airjp73** [onivim/oni2#550]
I noticed a visual bug when deleting many lines at once. Something not shown in the gif here is, sometimes the syntax highlighting doesn't fully correct itself until making further edits.

**Operating System:** Windows
**File in the Gif:** [On Github here](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/LocalVariableTableParameterNameDiscoverer.java)
**Command in the Gif:** `:g/*/d`

![2019-08-01_21-53-46](https://user-images.githubusercontent.com/25882770/62338596-16688f00-b4a7-11e9-914b-df286eecb552.gif)

**Comment by bryphe** [comment]
Thanks for the issue, @airjp73 !

Indeed, syntax highlighting is one of our biggest performance bottlenecks at the moment. We're tracking moving to a native syntax highlighting here in #161 - most likely tree-sitter.

**Comment by CrossR** [comment]
If I'm remembering correctly, this was before the native `tree-sitter` and native `textmate`.

Is this still an issue now, or can this be closed out?

**Comment by airjp73** [comment]
I just downloaded the latest version on the website and it looks like the state of this issue has definitely improved. There's still _some_ wonkiness but not the crazy rainbows there were when I reported the issue originally.
![2019-12-09_13-25-56](https://user-images.githubusercontent.com/25882770/70461883-acc94480-1a87-11ea-9f60-fe7875179407.gif)

**Comment by bryphe** [comment]
Thanks for the update @airjp73 !

We just merged https://github.com/onivim/oni2/pull/922 yesterday, which should improve this even further  reduce that 'waterfall' effect you were seeing in the latest gif).

The next step for us is to switch to using more tree-sitter syntax highlighter!

**Comment by bryphe** [comment]
This should be fixed now by #771 (use native textmate highlighting) and #922 (asyncify the syntax highlighting) - so I'll close this out. Feel free to log a new issue if you are still seeing issues. 

Thank you for reporting and for the update, @airjp73 !
