### ISSUE TITLE
Native editorconfig first support

### ISSUE THREAD

**Issue by Siilwyn** [onivim/oni2#555]
What would you think of the following two things for Oni?
1. using an editorconfig file for the core editor settings
2. automatically using editorconfig files in a project when present

Having an editorconfig at the core allows for easy config sharing between machines (dotfiles) and straightforward fallback per configuration rule from project > core level. Secondly it means having support for every editorconfig rule without concessions which happen when integrating editorconfig support as a plugin. What usually happens with plugins is they get in conflict with the core editor settings, e.g. in Atom using the editorconfig plugins means having to disable the core `whitespace` package.

Finally as a bonus Oni would get a nice place in the native support list at https://editorconfig.org/ :)

**Comment by Siilwyn** [comment]
@bryphe thoughts?

**Comment by bryphe** [comment]
Hey @Siilwyn ! Thanks for pinging me on this.

As I've been testing VSCode extensions - I've been thinking about `editor-config` in the context of the VSCode extension (https://github.com/editorconfig/editorconfig-vscode) - it'd be a good test case for our configuration synchronization.

Exposing it via the VSCode extension has a few benefits, IMO:
- Keeps our implementation simpler (we get the functionality via the VSCode extension host). Our configuration story is already complicated - as we have a `configuration.json` and plan on supporting some customization via VimL as well. There's no ReasonML / OCaml core, yet, which means we'd have to implement it ourselves - whereas the [`editorconfig-core-js`](https://github.com/editorconfig/editorconfig-core-js) seems pretty well maintained.

- We get to exercise our extension host integration - the more we exercise it, and work through the issues, the better and broader our extension support becomes. The `editor-config` plugin is a great test case for the configuration APIs.

So at least for our first round of `editor-config` integration - I plan on integrating with the VSCode extension for the dual benefit of us saving us work and exercising our extension integration. 

If there's gaps beyond that, that could be solved by a native implementation, and it's something users want - I'm open to exploring it. But interested to see how far the extension can get us.

**Comment by Siilwyn** [comment]
Hey @bryphe no problem! Good points, especially for the foreseeable future going for 'integration' of the EditorConfig VSCode extension makes the most sense.

I'll close this issue until maybe someday it becomes relevant again. :)
