### ISSUE TITLE
<C-v>A" freeze

### ISSUE THREAD

**Issue by dfroger** [onivim/oni2#556]
I was experimenting with text object, and pressing `<C-v>A"` make the editor freeze (this is actually not a valid Vim key combination) . Hope you can reproduce.

**Comment by bryphe** [comment]
Thanks for the issue @dfroger ! I believe this may be a dup of #471

**Comment by dfroger** [comment]
Indeed, this is clearly a duplicate, so I +1 the other and close this one. Thanks!
