### ISSUE TITLE
Bug: undefined symbol: hb_blob_create_from_file

### ISSUE THREAD

**Issue by nganhkhoa** [onivim/oni2#56]
Hi, I stumble upon this problem in the recent build of Oni2. It works some commits after `revery` update, but then it just broke and yields `symbol lookup error`.

I believe the problem resides to `esy-harfbuzz` from `reason-fontkit` as the symbol missing is `hb_blob_create_from_file`.

esy x Oni2 log
```bash
Starting oni from binary path: /home/luibo/APP/oni2/vendor/neovim-0.3.3/nvim-linux64/bin/nvim
starting request: 1550432417.65
ending request: 1550432417.66|0.0130469799042
/home/luibo/APP/oni2/_esy/default/store/i/oni2-609ac505/bin/Oni2: symbol lookup error: /home/luibo/APP/oni2/_esy/default/store/i/oni2-609ac505/bin/Oni2: undefined symbol: hb_blob_create_from_file
```

esy x OniUnitTestRunner
[OniUnitTestRunner.log](https://github.com/onivim/oni2/files/2873335/OniUnitTestRunner.log)

```bash
$ esy --version
0.5.6
$ esy ls-build
info ls-builds 0.5.6 (using package.json)
Oni2@0.2.0 [build pending]
├── @esy-ocaml/reason@3.4.0 [built]
├── @opam/camomile@opam:1.0.1 [built]
├── @opam/dune@opam:1.7.1 [built]
├── @opam/lwt@opam:4.1.0 [built]
├── @opam/merlin@opam:3.2.2 [built]
├── @opam/msgpck@opam:1.4 [built]
├── @opam/ocamlbuild@opam:0.12.0 [built]
├── @opam/ppx_deriving@opam:4.2.1 [built]
├── @opam/ppx_deriving_yojson@opam:3.3 [built]
├── @opam/yojson@opam:1.5.0 [built]
├── @opam/zed@opam:1.6 [built]
├── @reason-native/rely@1.0.1 [built]
├── ocaml@4.7.1004 [built]
├── rench@1.2.0 [built]
└── revery@0.7.0 [built]
```

**Comment by romgrk** [comment]
`hb_blob_create_from_file` is in harfbuzz since 1.7.7. What version of libharfbuzz is installed on your system? What system are you running on?

**Comment by nganhkhoa** [comment]
Thanks for the information.

I am using deepin and the libharfbuzz-dev is 1.7.6. I will install the newer libharfbuzz and see if it works.

**Comment by nganhkhoa** [comment]
I have installed libharfbuzz-dev 2.3.1 and it works perfectly. But I think that this should be a warning for debian users. The main debian repo have libharfbuzz at 1.4 for stretch [link](https://packages.debian.org/search?keywords=libharfbuzz-dev). Either to use sid or to download the debian packages from [here](https://debian.pkgs.org) using the debian 10 section. Installing libharfbuzz breaks many dependencies because it requires exact version.

The following below should be install to get oni2 works.

```
libicu-dev/now 60.2-6 amd64
libicu63/now 63.1-6 amd64
libfreetype6-dev/now 2.9.1-3 amd64
libfreetype6/now 2.9.1-3 amd64
gir1.2-harfbuzz-0.0/now 2.3.1-1 amd64
libharfbuzz-dev/now 2.3.1-1 amd64
libharfbuzz-gobject0/now 2.3.1-1 amd64
libharfbuzz-icu0/now 2.3.1-1 amd64
libharfbuzz0b/now 2.3.1-1 amd64
```

Thank you for your support, @romgrk .
