### ISSUE TITLE
Bug: Search discards queued commands

### ISSUE THREAD

**Issue by Phaen** [onivim/oni2#560]
My issue (with caret to indicate cursor)
```python
from tqdm import tqdm
^
```
Actions: cursor is placed on the first character (`f` of `from`). The follow keystroke is entered: `d/import` followed by ENTER.

Expected result: the delete command executes until the marker received from the search query
```python
import tqdm
^
```
Onivim 2.0.2.0 result: the delete command is discarded and the jump to the first marker is executed as normal
```python
from tqdm import tqdm
          ^
```

**Comment by bryphe** [comment]
This should be fixed now with latest libvim (picked up fix in https://github.com/onivim/oni2/pull/2680)
![search-motion](https://user-images.githubusercontent.com/13532591/99137565-8e958e00-25e0-11eb-9e51-c604d6fb2c4b.gif)
