### ISSUE TITLE
Bug: ndd deletes n squared lines

### ISSUE THREAD

**Issue by Phaen** [onivim/oni2#561]
When you use `ndd` to delete n amount of lines, Onivim instead deletes n squared amount of lines.
Example: `2dd` deletes 4 lines, `3dd` deletes 9 lines, `5dd` deletes 25 lines

**Comment by despairblue** [comment]
This is probably a bug in libvim, right?

**Comment by CrossR** [comment]
I've had a quick poke around, and a test case of this in libvim exhibits the same behaviour, and I've narrowed it down to this specific line causing the issue:

https://github.com/onivim/libvim/blob/f01c98716d556375a96d8da38f1d9a3d520418c8/src/normal.c#L708-L711

We end up in the `*=` case, giving up n squared, not n. I'm going to take a look and see if I can see why that bit of code would do that. In some case, both `count0` and `opcount` shouldn't both be set.
