### ISSUE TITLE
Commands: Window movement

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#565]
In the same vein as #564 , we should have bindable commands for the window splits:

Commands to be referenced in `keybindings.json`:
- `window.moveLeft`
- `window.moveRight`
- `window.moveUp`
- `window.moveDown`

These won't need defaults, per-se, since we'd inherit the Vim behavior for these movements via `<C-w>` bindings. But at least we'd have an ability to re-bind these.

Use case: Binding `<c-h>, <c-j>, <c-l>, <c-k>` for window motions

**Comment by KevinSjoberg** [comment]
I'd be happy to take a stab at this one. 🙂

**Comment by KevinSjoberg** [comment]
@bryphe I guess we can close this one. 🙂

**Comment by bryphe** [comment]
@KevinSjoberg - oh, ya - thank you for fixing this! 🎉
