### ISSUE TITLE
Crash: Insert register in insert mode

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#566]
__Repro:__
- Go to insert mode `i`
- `<C-r>a`

Expected: Contents of a register should be insert
Actual: Crash

This is hitting a blocking input mode in `libvim` - we'll have to fix it there

**Comment by Phaen** [comment]
Clarification: no register needs to be supplied. `i<C-r>` by itself causes Onivim to hang for several seconds before crashing. The hanging misleadingly causes you to attribute it to the register.
```
[INFO] Input::handle - sending raw input: i
[DEBUG] VimStoreConnector - handling key: i
[DEBUG] VimStoreConnector - handled key: i
[INFO] Input::handle - sending raw input: <C->
[INFO] Input::handle - sending raw input: <C-R>
[DEBUG] VimStoreConnector - handling key: <C-R>
```
