### ISSUE TITLE
Chinese Character support 

### ISSUE THREAD

**Issue by gongqian** [onivim/oni2#571]
When type in or open Chinese text, it displayed as question mark inside a square(rectangle). Don't know if additional encoding need to be set. Didn't try other languages.

<img width="343" alt="Screen Shot 2019-08-02 at 6 22 55 PM" src="https://user-images.githubusercontent.com/86469/62401765-a0b9fd00-b552-11e9-9d08-151d72385794.png">

**Comment by CrossR** [comment]
Going to close out in favour of #868.
