### ISSUE TITLE
[Feature Request] Drag and Drop Support for Opening Files

### ISSUE THREAD

**Issue by praveenperera** [onivim/oni2#586]
It would be nice to be able to open a file in Oni2 by either dragging and dropping the file into the dock icon or into the application window. 

My current daily editor is vscode but I also keep sublime around. I usually use sublime via this workflow to open and edit random files.

**Comment by bryphe** [comment]
@zbaylin has started working on the plumbing for this:

https://github.com/revery-ui/revery/pull/831
https://github.com/revery-ui/esy-sdl2/pull/13

**Comment by bryphe** [comment]
This is now in the latest OSX builds with @zbaylin 's work in #1759  - we support both dragging files onto the editor and into the dock now 🎉
