### ISSUE TITLE
i3 rendering problem on onivim2 focus

### ISSUE THREAD

**Issue by pkariz** [onivim/oni2#587]
I'm using i3 on debian buster and whenever i refocus onivim2 it doesn't render, i either have to press some buttons or make it go fullscreen (or exit fullscreen).

Steps to reproduce:
1. have i3 (i'll assume ALT is set as a mod key)
2. open onivim2 on workspace1
3. have onivim2 focused and press ALT+SHIFT+2 to move onivim2 to workspace2
4. press ALT+2 to go to the second workspace and you won't see much

**Comment by ciwchris** [comment]
Same experience, onivim2 is not rendered when navigating to the workspace. It does however render once you type a key.

**Comment by Aguay-val** [comment]
Same issue. I also use i3 on buster.

**Comment by gwijayas** [comment]
I have same issue on Windows 7. I have to execute 'show desktop', to be able to refocus on oni2

Intel i3-4130, RAM 16GB

**Comment by escorponox** [comment]
Same issue. Manjaro i3

**Comment by mjiricka** [comment]
Same issue, but with Xmonad.

**Comment by bryphe** [comment]
Got i3 setup on my Manjaro Linux box, and was able to reproduce this. Thanks @pkariz for the repro steps - helpful for an i3 n00b like me. 

I created this fix in Revery: https://github.com/revery-ui/revery/pull/604 and validated it fixed the issue for me when brought into Onivim 2.
