### ISSUE TITLE
Feature request: Option to disable dots between words

### ISSUE THREAD

**Issue by PopeRigby** [onivim/oni2#590]
Like these:
![Screenshot (49)](https://user-images.githubusercontent.com/20866468/62431827-fec81b00-b6df-11e9-9691-c2c74c7c8e0b.png)

**Comment by CrossR** [comment]
You can control this with the `editor.renderWhitespace` option, which can be `"all"`, `"boundary"` (ie start and end of lines, not inside), or `"none"`.

**Comment by PopeRigby** [comment]
Thanks.
