### ISSUE TITLE
Editor commands quit working after long time of use.

### ISSUE THREAD

**Issue by raguay** [onivim/oni2#591]
I've been using oni2 for most of my editing lately. But, after several hours and many file changes, I have to quit and restart it due to commands working very erratically. Mostly, the move command sometimes work and sometimes doesn't.

After relaunching, it works again for several more hours.

**Comment by bryphe** [comment]
Sorry, that's very frustrating! Definitely a daily editor blocker.

A couple of clarifying questions:
- Which platform are you using oni2 on?
- What type of files are you working with?

When you see this bug manifest - it's the move commands like `h`/`j`/`k`/`l` that stop working? Do other commands like switching modes work? Does opening the command palette work, like `Control+Shift+P`?

**Comment by raguay** [comment]
I'm on macos 10.14.6 Mojave. The h/j/k/l command intermittently work. Like
the system all of a sudden is processing too much stuff. My CPU meter
doesn't go up significantly during it. I guess the better description would
be sluggish to the point it doesn't process some of the keys.

I didn't try the command pallete (I actually didn't know about it), but `/`
brings up the search box, but not every key press goes into it.

**Comment by bryphe** [comment]
Thanks @raguay ! This is helpful.

What file types are you working with? I wonder if perhaps our current (slow) syntax highlighting is getting bogged down and blocking.

In the meantime, I'll look at wiring up the messages from Vim to show (might give hints if there is any issue on the way we're integrating with Vim), and beefing up our logging to see if we can diagnose this.

**Comment by raguay** [comment]
I’m working on a Svelt project using the Svelt code highlighting I download
from a repo for VSCode. So, I would imagine that could be the issue here. I
don’t think it ever happened before I installed it, but I also wasn’t doing
that much editing then either. So, it’s hard to tell.

**Comment by bryphe** [comment]
Thanks for the details, @raguay !

A few things I've been thinking about looking into this:
- I found one case where we are continuing to add work over time in Revery (a bug with one of our effects) - I need to address this as it is a general problem. I don't think it is the case here but will be nice to rule out.
- Our syntax highlighting is indeed sub-optimal at the moment, which could be a contributing factor

Lastly, I'd like to improve our logging by having the ability to turn on file-logging mid run so we can get a trace and some clues about the performance degradation

**Comment by raguay** [comment]
Sounds good. Looking forward to helping to debug it. I'm using Onivim2 all
the time now, even with the quirks!

**Comment by CrossR** [comment]
I've not noticed this recently, and I leave Oni2 running on my work machine for days/weeks at a time (university machines can't be turned off for various reasons, but provides a nice check for any issues like this or memory leaks etc).

This is on CentOS 7, so its possible its still an issue on mac.

**Comment by raguay** [comment]
yes, I haven't had the issue in quit a few builds. I didn't realize this one was still open. I'll close it.
