### ISSUE TITLE
Support for traditional Vim buffer/tab behavior

### ISSUE THREAD

**Issue by mhanberg** [onivim/oni2#592]
Oni2 currently implements tabs similar to other GUI text editors.

This is _not_ behavior that I find valuable and would find it beneficial to return to the traditional Vim behavior. (I am fine with this being opt in.)

**Comment by yunti** [comment]
Likewise intellij/webstorm etc... has a great similar feature where you can turn the tabs off just let the editor manage opening closing files.

**Comment by bryphe** [comment]
This is (one of) our top feature requests - the concept of Vim tab-pages to manage splits. Some details here: https://vim.fandom.com/wiki/Using_tab_pages

@glennsl , do you think you could take a look at this? This would involve handling the vim `tabpage` commands, like:
- `tabnew`
- `tabedit`.

We actually get these commands (at least the 'tabedit' / 'tabnew') commands here: https://github.com/onivim/oni2/blob/401bc02467d3a3d3aa27acc6bd7f70342a4492ef/src/Store/VimStoreConnector.re#L266

But we don't do anything with them; we treat it as if the user is just editing a file.

Vim 'tab pages' group together window splits; this is really nice to jump between window layouts. With our current `State`, we only have a root-level set of window splits, defined here: https://github.com/onivim/oni2/blob/401bc02467d3a3d3aa27acc6bd7f70342a4492ef/src/Model/State.re#L42

We'd basically want a new concept of `tabPages`, that could either reference a window manager, or contain window managers, something like: 
```
module TabPage {
   type t = { 
        tabName: option(string); 
        windowSplits: WindowManager.t 
    }
}

module TabPages = {
    type t = {
        activeTabId: int,
        idToPage: IntMap.t(TabPage.t)
     }
};
```

When there are multiple tabpages, we'd show these as an _additional_ tab bar, above the editor group tab bars. If a `TabPage` does not have a name set - we'd use the name and icon of the current buffer. The dirty icon would be shown based on all the buffers in the editor group (if any is dirty - we will show the dirty icon). 

When there is only a single tabpage, we could show nothing - this would be the default case for 'non-tab' users. A boolean option like `workbench.editorShowVimTabPages`  would be helpful for users who have a tab-first workflow - this could show the tabpages even when there is a single tabpage.

For a power-Vim-tab-user, they'd want to set both:
- `workbench.editorShowTabs` to `false`
- `workbench.editorShowVimTabPages` to `true`

Then - we'd update our `<EditorView />` to pick the _current active tabpage_ to render.

Ideally we could handle the following Vim commands to start:
- `tabnew`
- `tabedit`

Then, we could handle some other interesting ones (although - we may need additional hooks in `libvim`/`reason-libvim` for these):
- `tabprevious`
- `tabnext`
- `tabclose`
- `tabmove`
- `tabfirst`
- `tablast`
- `gt`
- `gT`

This would be very impactful, as users coming from Vim are accustomed to this workflow!

**Comment by mhanberg** [comment]
I'd like to clarify my request based on what I have read in @bryphe's comment.

My request is not "I want to to use Vim style tabs in Oni2". It is more "I want Oni2 to support Vim style buffer behavior". 

With what I am envisioning, the UI for "vim style buffers/tabs" is exactly the same as it is now, but with the tabs being Vim tabs and no UI for buffers (with the behavior for closing them the same as Vim). If there is only 1 tab open, there would be no tab bar.

Thanks for your effort on this and let me know if there is anything else I can clarify 👍 .

**Comment by glennsl** [comment]
As I understand, that's what you'd get with `workbench.editorShowTabs = false` and `workbench.editorShowVimTabPages = true`. Is it not?

**Comment by mhanberg** [comment]
Currently if you hide the tabs, all it does is hide the tabs. You still get the same behavior when closing buffers. If I open file1, open file 2, then close file2, it would then pop file1 into the foreground instead of quitting the whole editor. 

The fact that there would be two setting to change implies that they are not mutually exclusive.

**Comment by glennsl** [comment]
Alright, I see what you mean. Thanks for the clarification!

**Comment by lourenci** [comment]
Hi, is there some roadmap for that?

I'm looking forward to trying onivim in my daily routine, I'm just waiting for that.

Thanks.

**Comment by glennsl** [comment]
No roadmap, but I really should get started on this. I need to finish up some SCM features first though, so it's probably still not going to happen for another few weeks.

**Comment by glennsl** [comment]
Finally, with #2013, #2030, and #2032 merged, Oni2 should now fully support this behaviour. Apologies for taking so long! It required a major refactor of the layout system, which also aimed (and succeeded) at enabling other features such as window/split resizing with both keyboard and mouse, and keyboard navigation to/from non-editor windows such as the side bar and bottom pane.

To get the UI and behaviour you are familiar with from vim, add this to your configuration:

```
  "oni.layout.singleTabMode": true,
  "oni.layout.layoutTabPosition": "top",
```

Hope this meets your expectations. But if not, please let us know!

**Comment by mhanberg** [comment]
I’ll check it out, thanks!
