### ISSUE TITLE
Allow for non admin install for Windows

### ISSUE THREAD

**Issue by ronniec95** [onivim/oni2#593]
Please add local user install (similar to Visual studio code), so that we can install on work PCs where admin access is generally restricted.

**Comment by Dom-R** [comment]
Would this work for you? https://github.com/onivim/oni2/issues/558#issuecomment-517774107

**Comment by CrossR** [comment]
#558 does in fact look like the same issue, so I'll close this one out.

Currently it should work, we just need a config option such that we don't try to load from `%APPDATA%`.
