### ISSUE TITLE
Performance - Startup: Slow startup on Mac

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#599]
Reported on twitter: https://twitter.com/Fenntasy/status/1158406575314354181

Some potential culprits:
- Perhaps there is still some runtime-path-resolution happenign in `libvim`?
- Perhaps there is some heavy file I/O going in when we are discovering extensions?
- Is the initial file explorer population taking time?

**It seems like there must be something specific in the environment, as the majority of reports on Mac have been that the startup is very fast.**

Similiar to #523 , we should add some timestamped logging so it is easier to get a profile of where the bottleneck is on startup.

**Comment by Fenntasy** [comment]
To illustrate, here is a screencast of startup with all my plugins and with my plugins tucked inside a `if has('nvim')`

![onivim](https://user-images.githubusercontent.com/1764664/62512735-7baae000-b819-11e9-8a14-98c31f29ef31.gif)

The top is with plugins, as you can see, I can type at second 5 without plugins and 8 with plugins, so there's at least some things happenings.

For completeness here is my plugin list but I'll be happy to do some more tests if there is timestamped logging.

```
  Plug 'kana/vim-textobj-user'
  Plug 'andyl/vim-textobj-elixir'
  Plug 'chaoren/vim-wordmotion'
  Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
  Plug 'google/vim-jsonnet'
  Plug 'jeetsukumaran/vim-buffergator'
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'itchyny/vim-qfedit'
  Plug 'mileszs/ack.vim'
  Plug 'NLKNguyen/papercolor-theme'
  Plug 'ntpeters/vim-better-whitespace'
  Plug 'SirVer/ultisnips'
  Plug 'honza/vim-snippets'
  Plug 'sheerun/vim-polyglot'
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-eunuch'
  Plug 'reedes/vim-litecorrect'
  Plug 'tpope/vim-repeat'
  Plug 'tpope/vim-sensible'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-unimpaired'
  Plug 'w0rp/ale'
  Plug 'wellle/targets.vim'
```

**Comment by bryphe** [comment]
Hi @Fenntasy ,

Sorry for the delayed response - thank you for the screencasts! It's very helpful, asI just checked this out, and I realized your screencasts are from our ['v1'](https://github.com/onivim/oni) (which is indeed _much slower_ to  startup than our v2 in this repo!)

In fact, part of the reason we embarked on creating a new tech stack for our v2 was exactly due to this sort of slowness - you can read more about the motivation here in our original [v2 design doc](https://onivim.github.io/docs/other/motivation). Switching from Electron to a native solution has resulted in much improved startup performance.

I anticipate that the v2 should startup much faster - if you're up for trying it, you can [build from source](https://onivim.github.io/docs/for-developers/building) or [pre-ordering and downloading at our early access portal](https://v2.onivim.io/early-access-portal)

I'll close this out, since this is related to our v1 and not our v2. There are a few issues we're tracking related to startup perf for our v2 - most notably this one: https://github.com/onivim/oni2/issues/602 - but on the whole, reports have been that the v2 OSX application starts up very fast / almost instantly.

**Comment by Fenntasy** [comment]
I can confirm, it's really fast with the 2 version. Sorry for the misunderstanding.

To avoid that in the future, is there a way to launch it via `oni .` in the console like the previous one ? I couldn't find it in the user manual :/
