### ISSUE TITLE
Splits: Handle navigation to more than one horizontal split

### ISSUE THREAD

**Issue by dmartmont** [onivim/oni2#603]
When you open more than one horizontal split (I tried with 3 and 4 horizontal splits), you cannot navigate to the new splits using neither `<C-w>j` nor `<C-w>k`. This doesn't happen with vertical splits.
Oni version: 2.0.2.0 [commit 71e6e3b](https://github.com/onivim/oni2/commit/71e6e3b67c58c40a91293daf9784a28ae123654b)
OS: MacOS Mojave 10.14.5

**Comment by bryphe** [comment]
Thanks for reporting, @dmartmont ! Indeed, I'm able to reproduce (seems just 3 `:sp`s are needed to reproduce - marked as a daily editor blocker.
