### ISSUE TITLE
Input: Home / End / Insert buttons aren't working

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#608]
Likely similar issue as #606 - Home / End / Insert keys aren't working as expected (reported on Discord).

**Comment by bryphe** [comment]
And PageUp / PageDown too!

**Comment by tatchi** [comment]
Would be happy to take this one :)

**Comment by bryphe** [comment]
Sweet! Thanks for the help, @tatchi !

**Comment by dineshKumar777** [comment]
@bryphe @tatchi When I clicked Insert button state changes to Insert and working. Again clicking Insert button in Insert mode, Oni changes to Visual state but works as in insert mode and breaks till i click escape button.

double clicking Insert button in Neovim, cycles through insert and replace mode.

Please check this from your end.
