### ISSUE TITLE
Non letter keys don't work

### ISSUE THREAD

**Issue by eljuanchosf** [onivim/oni2#638]
Sytem info:
```
System:    Host: spectre Kernel: 4.15.0-55-generic x86_64 (64 bit)
           Desktop: Cinnamon 3.6.7  Distro: Linux Mint 18.3 Sylvia
Machine:   System: HP (portable) product: HP Spectre x360 Convertible 13-ac0XX
           Mobo: HP model: 827E v: 94.60
           Bios: American Megatrends v: F.31 date: 04/27/2017
```

Version tested:
```
Version: 2.0.2.0
Date: 8/11/2019, 4:20:10 AM
Commit: 6ff689a
Type: AppImage
```

Behavior:

1. Open the editor
2. Switch to insert mode
3. Type something
4. Try Backspace, or Return, or Delete keys. None working.

Additional notes:

Please let me know if there is something else I can do to help you debug this issue.

Thank you!

**Comment by karlc1** [comment]
+1, I get the same behavior on Ubuntu 18.04

**Comment by JasoonS** [comment]
I only get this behaviour when I am not using my laptops primary layout. When I don't change layouts I get it. See #698 .

**Comment by CrossR** [comment]
I have tested this as part of #698 and was able to swap back and forth between layouts and use a non-default layout at startup and always got the correct key.

I'll close this out, but can be reopened if needed.
