### ISSUE TITLE
Feature: Workspace Persistence

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#640]
I'd like to add the concept of a _session_ to Onivim 2, which would include the following:

- The working directory the user was in
- Open splits / window configuration (which buffers are in which editor group)
- Window size & location
- Opt-in hooks for various features to persist (ie, like Zen mode)

We'd save this information to a specific location in the user's folder, likely as JSON.

On load, we'd pick up this persisted info and restore the user's workspace / session.

__Related:__

- Once we have these basics configured, we should extend the format to handle hot exit: https://github.com/onivim/oni2/issues/639
- Should integrate with https://github.com/onivim/oni2/issues/440 (when changing workspaces, we persist the current state of the 'old' workspace, and load the persisted state of the 'new' workspace)

**Comment by tcoopman** [comment]
> We'd save this information to a specific location in the user's folder, likely as JSON.

Do you mean, save this in the workspace folder, or in the user's config folder?

**Comment by raguay** [comment]
I would rather save this at the top of the project directory. Just like VSCode and Sublime Text does. That way, I can save it in my repo, wipe and reinstall from the repo and still have the same configuration for editing the project.

**Comment by despairblue** [comment]
> I would rather save this at the top of the project directory. Just like VSCode and Sublime Text does. That way, I can save it in my repo, wipe and reinstall from the repo and still have the same configuration for editing the project.

Usually that just ends up in the gitignore file since not everyone on the team uses the same settings or even editor.

I like how atom does it which saves it somewhere in the config directory.

**Comment by glennsl** [comment]
Labeled `good-first-issue` for the basic persistence and restore logic for simple properties like working directory and window size/location. The rest requires a bit more know-how, but can also be added later.
