### ISSUE TITLE
Language support for F# and Elixir?

### ISSUE THREAD

**Issue by Kavignon** [onivim/oni2#647]
I'm about to purchase a License for onivim2 :D 

Looks so interesting off the bat but I have some questions such as support for 2 FP languages that  I use. 

Count on me to chip in helping for issues, I like the ReasonML/Ocaml language ;)

**Comment by CrossR** [comment]
Currently, the only real language support we have is syntax highlights. We don't bundle any for F# or Elixir, but it is just as simple as copying the VSCode ones over in the extensions folder.

Once we start to get LSP and code extension support, then it will broadly be the same. There won't be any out of the box support, but there will be the (hopefully) full set of code extensions that work over there, as well as some of the vim ones, so installing a plugin will give as much support as you'd reasonably expect from those two editors.
