### ISSUE TITLE
Oni2 chokes on rapid key-repeat input

### ISSUE THREAD

**Issue by omginbd** [onivim/oni2#651]
Hi! I'm running the August 13th nightly on Ubuntu 19.10. I have my key repeat rate set pretty high (`gsettings set org.gnome.desktop.peripherals.keyboard delay 200`) and when editing a file of any size if I hold down any navigation key (`hjkl`) for about a second or longer the cursor continues to scroll for awhile after releasing the key. Holding the key for longer before releasing increases the how long the cursor will scroll after release, so I suspect whatever is processing input events is choking up when too many are fired. Happy to provide more detail if needed, thanks!

**Comment by bryphe** [comment]
I'm not able to reproduce this in the latest, even with a higher key repeat rate (`50` instead of `200`). I suspect it was due to latency in our previous RPC implementation.
