### ISSUE TITLE
Unable to click in fuzzy finder or command menu

### ISSUE THREAD

**Issue by mhanberg** [onivim/oni2#665]
If you open the menu, and attempt to click an item, it will actually click through the menu and click whatever is behind it. I noticed this when it opened a file that was in the sidebar.

![click-through](https://user-images.githubusercontent.com/5523984/63219707-cdbb0200-c145-11e9-83bf-ca4bbbd0c173.gif)

**Comment by bryphe** [comment]
Looks like a Revery bug where we're not handling the mouse events properly (we're not picking up the cursor in the menu's flatlist region).

**Comment by bryphe** [comment]
![debug-visualization](https://user-images.githubusercontent.com/13532591/63226678-97a36f80-c191-11e9-82ba-ab8bd9374560.gif)

I set up a debug visualizer in Revery to show where it 'thinks' we're hovering over... and it's clear it's not the menu. Seems like a bug in our logic there to get the mouse-over-node

**Comment by bryphe** [comment]
It seems like there is a bug in our algorithm that hit-tests the mouse - it's getting the _deepest_ Node in the hierarchy that intersects with the mouse, as opposed to the _topmost_ element that intersects with the mouse.
