### ISSUE TITLE
ETA in the past on the website FAQ

### ISSUE THREAD

**Issue by dbarnett** [onivim/oni2#666]
The "FAQ > When can I download a build?" entry on https://v2.onivim.io/ has an "ETA" in the past. It needs to be updated, either just deleted or updated to give an ETA for the next upcoming milestone instead.

**Comment by dbarnett** [comment]
FWIW I was strongly considering backing it and assumed it was already abandonware when I saw the date, until I looked closer and saw there were other updates with more recent dates elsewhere.

**Comment by tcoopman** [comment]
I can't find this here: https://onivim.github.io/docs/other/faq ?
Where do you see it?

**Comment by CrossR** [comment]
Its at the verrry bottom of the main website, which isn't a good look when thats where people back from!

![image](https://user-images.githubusercontent.com/10038688/63223167-69ca2500-c1a9-11e9-85f4-acf3fde34df8.png)

We should definately update this to point out that the master commit is currently available and refer back to the schedule to see what is in there. Could also probably do with a bit more from the other FAQ, or just link to it.

**Comment by bryphe** [comment]
Thanks for the heads up and taking the time to give the feedback @dbarnett ! Yes, this FAQ on the main page is out-of-date (I moved everything to the new FAQ: https://onivim.github.io/docs/other/faq)

My plan is to remove this FAQ section on the website, and then add links to documentation, faq, and early access portal where this FAQ previously was on the main page.

**Comment by bryphe** [comment]
In the latest revision, I replaced that old FAQ section with a new Learn More section:
![image](https://user-images.githubusercontent.com/13532591/63597333-0efe4800-c572-11e9-974a-6dfe3af90917.png)

Updated here: https://v2.onivim.io (but  might need a cache refresh)

Hopefully this is better - thank you again for taking the time to give this feedback, @dbarnett !

I'll close this, but of course I'm still open to any additional feedback 😎

**Comment by dbarnett** [comment]
Looks nice! Thanks for following up.
