### ISSUE TITLE
Using The ultimate Vim configuration

### ISSUE THREAD

**Issue by BackOrder** [onivim/oni2#674]
Is it possible to use [The ultimate Vim configuration](https://github.com/amix/vimrc) with OniVim2?

OniVim2 doesn't seem to use my .vimrc on CentOS/Linux.

**Comment by CrossR** [comment]
Oni2 doesn't support loading a `.vimrc` yet, but its on our radar!
We are aiming to support as much as makes sense when loading a `vimrc` and plugins.

By that we mean we'll support stuff where the vim stuff is better than any alternative, but where its not we aren't going to focus on it. A good example of stuff we want to support is stuff like `targets.vim` / `vim-surround` etc, whereas say a theme plugin (we use VSCode themes), powerline bar (we'll most likely have our own with integration with the VSCode extensions) or completion managers (where the VSCode options should be better) we will defer to native solutions or VSCode extensions.

I'll close this out for now, and any specific concerns can be raised over in #150.

**Comment by BackOrder** [comment]
Thank you for this very comprehensive answer. Keep up the good work!
