### ISSUE TITLE
Bug: macOS in view mode, pressing Control + Command would insert weird characters

### ISSUE THREAD

**Issue by mrvicadai** [onivim/oni2#675]
By pressing the key combination `Control` + `Command` at the same time in view mode, this following sequence of characters are inserted into the active buffer:

```
<D-C->
```

Platform: macOS Mojave

### Impact

While using Spectacle.app or some other window resizer, the default shortcut is something like `Control + Command +←`. Whenever the shortcut is pressed, these characters will appear in the editor.

Related:

#657 
#673

**Comment by bryphe** [comment]
Not able to reproduce this on latest `master`, so I'll close out. Please let me know if you still are able to reproduce it-
