### ISSUE TITLE
Bug: OSX-specific shortcuts don't work

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#680]
Some specific ones called out on Discord:

- `cmd+shift+]` (and `[`) to shift through open tabs
- `cmd + ,` to open settings

We should definitely hook up these; as they don't conflict with Vim bindings, and should just work.

**Comment by mrvicadai** [comment]
Can I add a few other ones?

- `Command + W`: Close tab / buffer.
- `Command + 1-8`: Jump to the nth tab.
` `Command + 9`: Jump to the last tab.

**Comment by yunti** [comment]
The change tabs shortcuts for macos now work. (I can't seem to find the commit where they got added.

**Comment by glennsl** [comment]
Thanks @yunti. Also `Cmd+W` should work. I've updated #1423 with `Cmd+,`, and will close this in favor of that.
