### ISSUE TITLE
Zen-Mode: Exit zen mode when creating a split

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#686]
__Issue:__ When in Zen-mode, if the user explicitly creates a split, it's a jarring experience - no split is created. This feels broken.

__REPRO:__
- Open a file in Onivim 2
- Press `Control+Shift+P` or `Command+Shift+P` to open command palette
- Select 'Enable Zen Mode'
- Run `:vsp<CR>` to create a vertical split

__Expected:__ The user should be taken out of Zen mode
__Actual:__ The user is still in Zen mode, and nothing changed

__Implementation:__

The logic for controlling ZenMode is here (`state.zenMode`): https://github.com/onivim/oni2/blob/460232a518d9ed134e0ecbf017047dcc2da3e79e/src/editor/Model/Reducer.re#L38

We'd want to add some additional behavior - the `AddSplit` (https://github.com/onivim/oni2/blob/460232a518d9ed134e0ecbf017047dcc2da3e79e/src/editor/Model/Actions.re#L70) and `RemoveSplit` (https://github.com/onivim/oni2/blob/460232a518d9ed134e0ecbf017047dcc2da3e79e/src/editor/Model/Actions.re#L70) actions are dispatched when a new split is created. We should update our reducer to set `zenMode: false` whenever those actions are dispatched.

__Testing:__

We should have an integration test for this to verify we don't regress this behavior.

A good example test case is:
https://github.com/onivim/oni2/blob/master/integration_test/AddRemoveSplitTest.re

We'd want a similar test, just prior to creating a split - we'd dispatch the `EnableZenMode` action, and validate that `state.zenMode` is true. Then, we'd create a split, and validate that `state.zenMode` switches back to false.

Note that we'd need to add two entries in the `dune` file for the new test: https://github.com/onivim/oni2/blob/master/integration_test/dune

**Comment by r281GQ** [comment]
Hi @bryphe

I can start investigating and create test for this issue, if not done already.

**Comment by bryphe** [comment]
Awesome! Thanks for the help @r281GQ !

**Comment by bryphe** [comment]
Fixed by #713
