### ISSUE TITLE
Input cursor overlaps with minimap

### ISSUE THREAD

**Issue by Spirarel** [onivim/oni2#687]
### What?
When the cursor reaches the edge where the editing pane intersects with the minimap it continues further until it overlaps with the minimap. Further character entry is occluded by the minimap.

See circled:
<img width="912" alt="Screen Shot 2019-08-24 at 00 27 05" src="https://user-images.githubusercontent.com/10119394/63633053-40752300-c607-11e9-9b77-6b9ff5372250.png">

Of note is that the last character before the minimap is also getting occluded.

**Comment by bryphe** [comment]
This is fixed now with #2597
