### ISSUE TITLE
Multiple different keyboard layouts on ubuntu causing issues with function keys (shift, ctrl, enter etc)

### ISSUE THREAD

**Issue by JasoonS** [onivim/oni2#698]
On ubuntu when you have more than 1 keyboard layout, Oni2 doesn't detect function keys anymore when it is started with the non-primary keyboard layout. All other keys seem to work 100%, including letters, symbols

My exact setup if there are problems reproducing:
OS - ubuntu 19.04
My layouts in order:
1. 'programmers dvorak' (US)
2. Turkish (Alt-Q)
3. US intl. with dead keys

When oni is started with programmers dvorak there is no problem (all keys work as expected). When it is started with one of the other 2 function keys (esc, enter, etc) don't work.

Switching Turkish to be my primary layout was enough of a fix for me, because it is the layout I use 99% of the time with my external keyboard.

This may be a Revery issue, I'm not sure.

**Comment by karlc1** [comment]
This is probably connected to this issue: https://github.com/onivim/oni2/issues/638 
Or at least it was for me. I thought no non-alphanumeric keys just did't work, but when I start onivim with swedish layout enabled, it works, but with english enables it produces this behavior. Ubuntu 18.04

**Comment by JasoonS** [comment]
Thanks @karlc1, I was going to close this issue, but I am not sure if it is different, because for me it works 100% ok on my primary layout. If they say that it is the same thing on the other thread then I'll close this.

**Comment by geier** [comment]
I have the same issue with the [neo](https://neo-layout.org), which makes heavy use of modifiers.

**Comment by CrossR** [comment]
We are working towards moving to SDL2, which will help with supporting non-QWERTY layouts, but also has events for keyboard layout changing. (Though I don't know if we will need to use those events if we always get the correct key regardless of layout).

**Comment by geier** [comment]
The latest version (from Oct 7th) fixes this issue for me. Thanks!

**Comment by CrossR** [comment]
Going to close this out, because the move to SDL2 was finished a while back and as I'm able to swap back and forth between keyboard layouts fine on my machine with no issues (I could swap between UK -> US Dvorak -> AZERTY -> QWERTZ with no issues without ever leaving insert mode).
