### ISSUE TITLE
CentOS 7: Unable to start Onivim 2

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#721]
Some information from Discord thread:
```
Running with the -f and --checkhealth options produces the following output:
/tmp/.mount_OnivimyqQcEG/usr/bin/Oni2: /lib64/libstdc++.so.6: version CXXABI_1.3.8' not found (required by /tmp/.mount_OnivimyqQcEG/usr/lib/libmirclient.so.9)
/tmp/.mount_OnivimyqQcEG/usr/bin/Oni2: /lib64/libstdc++.so.6: versionCXXABI_1.3.9' not found (required by /tmp/.mount_OnivimyqQcEG/usr/lib/libmirclient.so.9)
/tmp/.mount_OnivimyqQcEG/usr/bin/Oni2: /lib64/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /tmp/.mount_OnivimyqQcEG/usr/lib/libmirclient.so.9)
/tmp/.mount_OnivimyqQcEG/usr/bin/Oni2: /lib64/libstdc++.so.6: versionGLIBCXX_3.4.20' not found (required by /tmp/.mount_OnivimyqQcEG/usr/lib/libmircommon.so.7)
/tmp/.mount_OnivimyqQcEG/usr/bin/Oni2: /lib64/libstdc++.so.6: version CXXABI_1.3.9' not found (required by /tmp/.mount_OnivimyqQcEG/usr/lib/libmircommon.so.7)
/tmp/.mount_OnivimyqQcEG/usr/bin/Oni2: /lib64/libstdc++.so.6: versionGLIBCXX_3.4.21' not found (required by /tmp/.mount_OnivimyqQcEG/usr/lib/libmircommon.so.7)
Plus more lines that are very similar. I can't paste all of them as I exceed the message size limit.
```

It looks like that CentOS 7 bundles GCC 4.8, but some of the dependencies bundled by the AppImage kit require libstdc++ 6 >= 5.2. For example, `libmirclient9` seems to require `libstdc++6` >= 5.2: https://packages.ubuntu.com/xenial/libmirclient9

Checking distrowatch - it seems that Ubuntu / Arch / Mint / Manjaro all ship with newer versions of GCC, which is why we haven't hit this issue before.

I saw some similiar issues with other AppImages:
- https://github.com/shadowsocks/shadowsocks-qt5/issues/534
- https://github.com/shadowsocks/shadowsocks-qt5/issues/687

And there's a section in the AppImage docs about potentially handling this:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by adrian5** [comment]
As a band aid, the user could try installing [Developer Toolset 6](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/)-[8](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/), so as to get a more recent GCC version. Not a proper solution of course.

**Comment by t-wiser** [comment]
@adrian5 Good idea. Unfortunately, at least for Developer Toolset 7, the result is the same. I was the one that found this issue and had tried using the Developer Toolset then. That information didn't make it into the bug report though.

**Comment by bryphe** [comment]
Saw a report that a user on RHEL 7.2 hit this as well (which also bundles GCC 4.8.x)

There are two potential solutions I see:
- Investigate if we can _down-grade_ our Azure CI Ubuntu machines to use GCC 4.8.x (or use another CI provider / distro that uses an GCC 4.8.x) - and release builds from there
- Incorporate the custom `AppRun` solution here: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by t-wiser** [comment]
Maybe it's worth checking how other projects do it? For example, the latest KDevelop appimage (see https://www.kdevelop.org/download) works just fine on CentOS 7.

**Comment by t-wiser** [comment]
Actually, I just checked and it looks like they are using a CentOS 6.10 docker image to build the appimage file.

**Comment by bryphe** [comment]
Thanks @t-wiser ! 

Yeah, I think our main problem is that the Azure CI is limited to the Ubuntu 16.04 image. I just opened a PR to see if I could down-grade GCC there: https://github.com/onivim/oni2/pull/783

Otherwise, we could look at building on a VM or dockerfile to use either CentOS 6 or RHEL 7

**Comment by bryphe** [comment]
FYI, with #784 , the builds we are producing for Linux are now built on CentOS 7 - which means we should have better compatibility. 

@CrossR mentioned that the builds now work for him on CentOS 7 🎉

**Comment by t-wiser** [comment]
I have finally gotten around to verifying that this works for me as well on CentOS 7. This issue could probably be closed now, no?

**Comment by bryphe** [comment]
Thanks for the confirmation @t-wiser ! Closing 👍
