### ISSUE TITLE
Command Palette input cursor movements don't match character widths

### ISSUE THREAD

**Issue by Spirarel** [onivim/oni2#726]
## What
In the command palette, characters take varying amounts of space when entered. The input cursors, however, does not always move according to their widths. This is demonstrated in the video.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10119394/64058371-d52fd180-cb6f-11e9-8d49-9dbcff9434d2.gif)
## Comments
The command-palette likely doesn't use mono-space fonts like the editing pane. The cursor may just be configured to move by a fixed unit whenever a character is entered. A solution here may also resolve #687

**Comment by CrossR** [comment]
I believe this is being worked on over in revery-ui/revery#550.

**Comment by glennsl** [comment]
FYI, I'll probably address this in the menu renovation project

**Comment by bryphe** [comment]
This was fixed in #1231 - thanks @fanantoxa !
