### ISSUE TITLE
Feature: Add `Open folder` button

### ISSUE THREAD

**Issue by fanantoxa** [onivim/oni2#730]
For windows users usual flow in file browser and mount. Using command line usually uncommon.
Editor already have button to add file, adding button to change folder might help to test editor easier.

**Comment by jaredly** [comment]
Yes pleeease. Also cmd+p "open folder" should do something useful. I'd be happy for it to take me to the ex cmdline with `:cd `prefilled or something.

**Comment by CrossR** [comment]
Would also be good to surface this through the Menu interface when we get that in Revery.

**Comment by glennsl** [comment]
We've been talking about exposing all vim commands through the command palette. We also want to provide help text for every command in the wild menu, and with that in place it would be really easy to expose it for fuzzy search too.
