### ISSUE TITLE
Pre-Order: Accept BTC as payment

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#751]
Had a request for a BTC payment option for pre-ordering the beta. Is this something that would be easier than the Stripe payment for some users? 

We had a BTC donation link, but it wasn't ever used, so I took it down and de-prioritized it. But would be happy to revisit if this would be useful.

**Comment by adamski** [comment]
I once paid for some software using BTC. A few months later (after it went up in value considerably), I regretted it..! :)

**Comment by joWeiss** [comment]
IMHO: Especially for international users, BTC could be a useful payment option. 

If you're really interested, have a look at https://btcpayserver.org/ for a community supported payment processing project.

**Comment by bryphe** [comment]
I'll close this as out-of-scope - since we're relying on Paddle / Patreon for payments, we'll stick with the options they provide to keep things simple
