### ISSUE TITLE
Highlighting at line level of VCS file changes

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#755]
This is one for a bit further down the road (but hopefully not too far :) ), but it would be great to have some simple feedback for changes to a file. (currently at this early stage it's just the tab icon changing from a cross to a circle).
If we could have the usual gutter highlights per line to signal changes since the last commit that would be really helpful.

(a follow on issue could be a change of colour to a filename in the file tree to indicate changes)

**Comment by CrossR** [comment]
I think a lot of this will come as part of the extension host from VSCode.

**Comment by bryphe** [comment]
This is in now, with @glennsl 's work on #1262 ! 🎉 

![image](https://user-images.githubusercontent.com/13532591/73755488-f26a5c80-471a-11ea-9a0f-9dc85f6619da.png)

**Comment by bryphe** [comment]
And @glennsl also implemented file tree decorations here: https://github.com/onivim/oni2/pull/1282

**Comment by yunti** [comment]
That was quick!  :)

**Comment by bryphe** [comment]
@glennsl is a rockstar 😎 

Unfortunately they aren't in the early access portal builds yet - working on unblocking them. Hopefully tonight's release will include both #1262 and #1282

**Comment by yunti** [comment]
rockstar indeed. It's really nice seeing how well you two are working together onivim is on fire right now.
