### ISSUE TITLE
Nordic characters offsets cursor display

### ISSUE THREAD

**Issue by brouer** [onivim/oni2#765]
If there are any Nordic characters (e.g. æ, ø, and å) on a line before the current cursor position, the cursor is displayed the corresponding number of cells too far right.

Normal mode commands work on the character the cursor is "really" on rather than the one it's displayed at.

Multiple æ's are truncated a few pixels too, so it's likely related to wide character support.

**Comment by miyalys** [comment]
Was just about to report this, suspecting it could be multibyte character related.

Made a short demonstration of it in this unlisted video:
https://youtu.be/M3gdvT6GMas
