### ISSUE TITLE
Text aliasing is all funky

### ISSUE THREAD

**Issue by HarrisonB** [onivim/oni2#774]
![image](https://user-images.githubusercontent.com/8454804/65087849-1267d200-d96c-11e9-9db3-2b8f5d25c062.png)

I can provide more information but unsure of what would be most helpful (maybe there should be a Issue template...) 🙂

**Comment by CrossR** [comment]
Not sure what would cause that...Is the behaviour the same with the default font?

This (potentially) will be helped with the move to skia I think.

**Comment by HarrisonB** [comment]
Looks okay with the normal font.

![image](https://user-images.githubusercontent.com/8454804/65267322-9daaaa00-dac9-11e9-9c06-90b42eeb63f1.png)

I'll note that isn't really an issue my HiDPI display.

**Comment by bryphe** [comment]
This looks like a case where subpixel-rendering would significantly improve the quality of the rendered text (in other words - our move to use [Skia](https://github.com/revery-ui/revery/projects/1) should help!)

**Comment by jokeyrhyme** [comment]
Is this why [Cascadia Code](https://github.com/microsoft/cascadia-code) looks weird on Windows? 
![image](https://user-images.githubusercontent.com/479816/65823099-304e0480-e293-11e9-859f-68bbed0b44ff.png)
Almost like the dimensions of each glyph is wrong? Squished or stretched? Or clipped by not having enough line-height? 🤷‍♂

**Comment by kitten** [comment]
This may be a lot or a little better in the latest  build due to a small change in Revery 👍

**Comment by bryphe** [comment]
Definitely worth a try! @kitten 's fix for Revery here was a significant improvement: https://github.com/revery-ui/revery/pull/570 (and it's in the latest builds now)

**Comment by jokeyrhyme** [comment]
Yep, Cascadia Code is looking as good as it does in Windows Terminal now, great work!
![image](https://user-images.githubusercontent.com/479816/66288201-04caba00-e924-11e9-8859-29a974f4f2cf.png)

**Comment by bryphe** [comment]
We just integrated Skia (#1206), which should significantly improve our text rendering quality. Would you mind checking on the latest build? Also, which platform was this occurring on?

**Comment by bryphe** [comment]
I'll close this out, since Skia should have fixed this - giving us much better text rendering fidelity (subpixel / LCD rendering). Feel free to open a new issue if you're still experiencing issues, though!
