### ISSUE TITLE
Input: Add Control+PageUp/Control+PageDown to switch between open files

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#778]
Feedback from discord - we should add `Control+PageUp` / `Control+PageDown` as default bindings for switching between opened files.

Is this the same default on OSX?

**Comment by dereknelson** [comment]
I personally would prefer `cmd+shift+[` / `cmd+shift+]` to move left and right, this behavior is shared with chrome and discord

**Comment by bryphe** [comment]
@jordwalke mentioned the same request on Discord - have `cmd+shift+[` switch between tabs.

**Comment by paskausks** [comment]
In case of discord, I use `ctrl+alt+arrow up` / `ctrl+alt+arrow up` to switch servers, but for firefox/chrome I'm, personally in the `ctrl+pgup` / `ctrl+pgdn` crowd, so, personally, I'm for that as default, instead of `ctrl+shift+[` / `ctrl+shift+]`.

**Comment by jamesgecko** [comment]
`ctrl+pgup` / `ctrl+pgdown` is a Windows shortcut. The macOS convention for switching tabs is `cmd+shift+[` / `cmd+shift+]`. Ideally both would work; Firefox supports both keybindings on macOS.

**Comment by leavengood** [comment]
I have this working, with both shortcuts, I will open a PR today.
