### ISSUE TITLE
Bug: `=` deletes instead of reformatting

### ISSUE THREAD

**Issue by luator** [onivim/oni2#785]
Instead of formatting the selected range `=` deletes it.  For example `==` deletes the current line, `gg=G` deletes the whole buffer.

**Comment by CrossR** [comment]
I have done a bit of research into this, and have noticed a few things:

 - The deletions seem to happen on my Windows machine, but not my Mac.
 - On my mac, I instead get inline errors from what looks like the `indent` command (BSD `indent` on Mac).

I think there is a few issues around this:

 - There is some form of dependence on the `indent` command, which obviously doesn't exist on Windows. I think this means that when ran, it just fails and deletes the text. This is mainly based on the fact the errors it puts inline are nowhere to be found in the vim repo, but do exist in the `indent` command.
 - We don't include any runtime files, which includes all the `indent/` files, which are needed for these formatters (I would assume at least...)

I think the missing files mean we fall back to just a default, and then fail on that default in an awful lot of cases. I thought `vim` had a built in C-indenter, so should look why its not being ran as well.
