### ISSUE TITLE
H, M, L Commands - strange behaviour

### ISSUE THREAD

**Issue by Akin909** [onivim/oni2#79]
Given the new strategy for v2 its a given(:laughing:) that some things don't work and some *won't*, some though similar to `zb`, `zt`, `c-d` etc. are important ways to navigate a buffer without your keyboard.

I think when we encounter cases which mean that a user will have to resort to the mouse, which I think breaks the spirit of `*real* vim bindings` or the goal of avoiding `subpar vim bindings` then we should look into fixes.

Now that the super long intro is over, the issue I believe is that the __High__, __Middle__ and __Low__ commands as I call them don't move a user to the right place in a buffer, it could be that theres some `init.vim` settings missing but I think in this case its more likely that somehow our control of the view layer means that somehow vim isn't aware of what is currently in view so the command doesn't know where to correctly place the cursor.

I think these are good candidates to replace with `Oni` commands, which equate to `H` - position at the top of the view port, `M` - position in the Middle of viewport and `L` position at the bottom

**Comment by bryphe** [comment]
Thanks for opening the issue - yes, this definitely something we need to handle! 👍 

It should be relatively straightforward to add (we can easily get the high/low/middle positions and push those to nvim with custom mappings - like we did with `zz`, `zb`, and `zt`).
