### ISSUE TITLE
No minimum window size

### ISSUE THREAD

**Issue by glennsl** [onivim/oni2#791]
On Linux there is no minimum window size. The window can therefore be resized to disappear, which is a bit inconvenient.

![Peek 2019-09-28 23-07](https://user-images.githubusercontent.com/5207036/65822476-04a42d80-e245-11e9-9031-9e81065b5c2d.gif)

**Comment by CrossR** [comment]
Is this sorted now?

**Comment by glennsl** [comment]
It is! Thanks for the bump @CrossR
