### ISSUE TITLE
Filetree doesn't update for deleted files

### ISSUE THREAD

**Issue by yunti** [onivim/oni2#792]
I couldn't find this listed elsewhere but the file tree doesn't update when files are removed (from the command line).

**Comment by bryphe** [comment]
Thanks for logging it, @yunti ! We should have a watcher to pick up these events.

@ulrikstrid was helping us with a `libfswatch` that we can pick up via `esy` cross-plat, which will help here.

**Comment by ulrikstrid** [comment]
The repo is here: https://github.com/ulrikstrid/esy-fswatch, I will probably pick it up again next week or so. 

It should basically work on all platforms but we're having some issues with the dependencies on Linux and macOS. A solution for this is to just have different builds for the different platforms and just take the built artifacts in the end and publish that as a package.

**Comment by raguay** [comment]
I just rebuilt it today and it doesn't show adding or deleting files or directories.

**Comment by ulrikstrid** [comment]
Update from my side on `esy-fswatch`, it can build on all platforms but we currently have a `windows.json` that does a few other things and also has some dependencies.
Windows takes 40+ minutes to build currently which is not really acceptable.

I have worked a bit on "prebuilts" which now should work on macOS and Linux so there is not build time at all. The next step is to see if I can remove `gettext` from Windows as that is the thing that takes the longest time to build and it also adds more runtime dependencies which is bad.

**Comment by benridley** [comment]
Is there any way to do a manual file tree refresh at the moment? I often remove/add files outside OniVIm2 and even a manual reload would do for now. Cheers!
