### ISSUE TITLE
Unable to open file if all tabs have been closed

### ISSUE THREAD

**Issue by AndreasNasman** [onivim/oni2#803]
After closing all open tabs, opening files (through clicking, `:e` or `quickOpen.open`) stops working.

**Comment by bryphe** [comment]
Was able to reproduce this:

![image](https://user-images.githubusercontent.com/13532591/75503053-749c1880-5989-11ea-8c0a-f268e45812b1.png)

**Comment by bryphe** [comment]
This is fixed now with #1776 👍
