### ISSUE TITLE
Oni won't quit after forcefully closing tab

### ISSUE THREAD

**Issue by AndreasNasman** [onivim/oni2#804]
The default behaviour when closing the last open tab seems to be to quit Oni all together. However, if a tab has been forcefully quit (with `q!`) at some point, Oni will stay open after all tabs are closed and is put in a state where new tabs can't be opened (see issue #803).

**Comment by millnitzluan** [comment]
I mentioned this same behavior on #questions from discord. @bryphe You think it's hard to implement this feature? I was thinking to use this feature/bug to learn Reason :p

**Comment by bryphe** [comment]
Hmm, I'm not able to reproduce this anymore - I believe this was fixed with some changes in the buffer lifecycle (and adding the confirmation modal). Let me know if you're still seeing this-
