### ISSUE TITLE
Handling initial [No Name] Buffer

### ISSUE THREAD

**Issue by Akin909** [onivim/oni2#81]
This issue is more of a brain dump regarding what I've found about this buffer since it has proven to be non-trivial to handle. This issue relating to it first came up in #72. Currently once #76 is merged, it will show its modified status correctly and close when the cross is clicked.

If it is navigated away from on start, it is discarded. If it is modified then a user tries to return to it, currently it silently fails in Oni2.

I've found that actually this is the same behavior as terminal neovim which is actually errorring with `E499: Empty file name for '%' or '#', only works with ":p:h"`. Essentially we're not allowed to navigate to a file without a name, which this file does not have nor does using its id work.

It can still be closed though. I think as what it does is default vim behavior this is fine for now, It  makes me think though that even at this early stage it might be worth considering a splash screen and only opening buffers a user has chosen to open. 

Either way we aren't doing anything that differs from neovim, but it highlights the fact that we aren't rendering errors which is confusing but should be fixed once we pick up the `ext_messages` change in nvim 0.4.0

**Comment by bryphe** [comment]
> It makes me think though that even at this early stage it might be worth considering a splash screen and only opening buffers a user has chosen to open.

I like this idea a lot! Sort of like the 'Welcome' screen we prototyped in Oni1 that didn't make it in
