### ISSUE TITLE
Can't navigate around suggestions with arrow keys, only with tab that always goes down.

### ISSUE THREAD

**Issue by m-kru** [onivim/oni2#815]
![sugg](https://user-images.githubusercontent.com/26227737/66254342-34878f80-e775-11e9-8e6e-6a9dc72b6fd3.png)

I would like to be able to navigate with up and down arrow keys. Right now, I can only hit tab, and it always gets down, so it looks like there is no option to go up.

**Comment by glennsl** [comment]
I'm actually working on this right now, more generally to get this and the ´Ctrl+P´ menu to look and feel identically. Right now you can navigate up and down in both with `Ctr+P` and `Ctrl+N´, which is standard vim behaviour.
