### ISSUE TITLE
<S-A><ESC> leaves cursor on not existing character

### ISSUE THREAD

**Issue by woeps** [onivim/oni2#831]
I just built from the master branch (6ca3646b571476c95209c1b210e28e4b3fae8f40). When I open a reason file and press `<S-A><ESC>` the cursor is positioned on the last character of the current line +1. The behaviour is the same if I press `<S-A>`, enter some text and then `<ESC>`.

![2019-10-10 09_11_37-Oni2-cursorAfterAdd](https://user-images.githubusercontent.com/225755/66547737-2c966980-eb40-11e9-9f35-26528c1b6a24.png)

**Comment by CrossR** [comment]
This looks to general be when we enter insert mode with `a`, since doing repeated calls (`a<ESC>a<ESC>....`) will walk the cursor across the screen.

I'm assuming we pick up the insert mode location difference vs using `i` and then set the cursor there, and slowly walk the cursor across the line.

**Comment by CrossR** [comment]
This seems to be much better now - The cursor doesn't walk on `a<ESC>a<ESC>...` for me anymore, and `<S-A><ESC>` only puts the cursor in the wrong place when we enter the buffer (possibly we set the cursor up incorrectly at the start?)
