### ISSUE TITLE
[bug] ?/<backspace> causes error

### ISSUE THREAD

**Issue by gitbugr** [onivim/oni2#834]
![oni](https://user-images.githubusercontent.com/6732567/66601275-72cee580-eb9f-11e9-8b3b-b6c962f31e01.gif)

**Comment by glennsl** [comment]
Looks like a duplicate of #727

**Comment by CrossR** [comment]
Thanks for raising! If you could :+1: the linked issue (#727) that would help us prioritise stuff a bit more.
