### ISSUE TITLE
Files are not formatted with Prettier

### ISSUE THREAD

**Issue by imbsky** [onivim/oni2#838]

**Comment by imbsky** [comment]
Probably [husky](https://github.com/typicode/husky) and [pretty-quick](https://github.com/azz/pretty-quick) are good solution.

**Comment by CrossR** [comment]
The Reason code is actually passed through a formatter already: https://github.com/onivim/oni2/blob/master/package.json#L180

Which is then checked in the CI: https://github.com/onivim/oni2/blob/master/.ci/esy-check-hygiene.yml#L32

Potentially some of the `scripts/` folder should be formatted, but I think most are manually passed through when editing.

**Comment by imbsky** [comment]
At least I recommend add `.editorconfig` file.

https://editorconfig.org

**Comment by imbsky** [comment]
and we can check with Prettier as well as refmt using the `--check` flag.

Reason: refmt
Other files(JavaScript, CSS, Markdown, JSON, YAML, etc...): Prettier
