### ISSUE TITLE
UI: Notification experience improvements

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#849]
@jordwalke had some great ideas around improving our notifications story in the Discord.

A persistent number of 'new messages' that are 'unread' in the statusbar. 
![image](https://user-images.githubusercontent.com/13532591/66783220-53c8a000-ee8c-11e9-8c94-21ef893027ed.png)

Message animates in when a new notification comes in:
![image](https://user-images.githubusercontent.com/13532591/66783234-59be8100-ee8c-11e9-99ae-b5c8dc0cae40.png)

Messages are shown in the bottom:
![image](https://user-images.githubusercontent.com/13532591/66783313-8377a800-ee8c-11e9-849b-6d0285a938d0.png)

And can expand the pane:
![image](https://user-images.githubusercontent.com/13532591/66783342-912d2d80-ee8c-11e9-901a-5b2c7b00da12.png)

**Comment by bryphe** [comment]
The UX for notifications is very spammy and not very friendly right now. I really like the proposal here - maybe something we can explore @glennsl ?

A few things we'd have to consider:
- How long do messages 'stay' in the status bar?
- Do they cover up the items in the status bar? Or fit in between them?

I think the 'search pane' + the diagnostics pane in #1034 would be a natural place we could surface these.

**Comment by jordwalke** [comment]
Only problem with the search pane position as the sole locations that I can see, is that many of these messages are intended to be very lightweight, and should be visible even in a minimalist windowing configuration. I think the search pane would be a great place to see the entire history of logs though. You definitely want a place to go explore old logs and that pane seems like the right place.

**Comment by bryphe** [comment]
> Only problem with the search pane position as the sole locations that I can see, is that many of these messages are intended to be very lightweight, and should be visible even in a minimalist windowing configuration.

Definitely! I like the idea of using the status bar for the showing of the notifications - the experience seems much better than what we have now. 

I think my comment above made it sound like I only wanted them in the 'search pane', so I edited it a bit to clarify-
