### ISSUE TITLE
UTF8 parsing of NeovimExtType

### ISSUE THREAD

**Issue by Akin909** [onivim/oni2#85]
Neovim returns a custom `ExtType` from `MsgPck` when we receive or request `window`,`buffer` or `tab` information, currently we convert this using `Camomile` in `Utility.re` however the parsing atm only works for single digits, so will need to be revisited so it can parse larger digits

Options I've found
* [Camomile's UTF8 Module interface file](https://github.com/yoriyuki/Camomile/blob/deed007c43a67fb581917631e376e727f42ceb44/Camomile/public/uTF8.mli) - aka figure it out
* [Batteries](http://batteries.forge.ocamlcore.org/doc.preview:batteries-beta1/html/api/UTF8.html) - has a method which seems like it would do the trick but is a ?big? library but comes up a lot as the solution to a lot of problems in ocaml so might be a good investment

**Comment by tcoopman** [comment]
I'm probably missing some information here to answer correctly, but looking at the code, maybe a naive implementation could be to loop over `CamomileLibraryDefault.Camomile.(UChar.code(UTF8.get(str, 0)))` multiple times for larger digits?

It seems a bit weird to get batteries only for this kind of thing?

Also, if parsing is needed, maybe having a look at https://github.com/inhabitedtype/angstrom could be helpful as well?

**Comment by Akin909** [comment]
@tcoopman that's a good idea, haven't tried that yet was futzing with using the `length` or `last` methods. Yeah batteries is an excessive solution, I only mentioned it in case it might be the sort of thing we'd use for other reasons my oversimplification is that it has a lot of utilities we might want anyway but it definitely isn't the first thing I was planning to try

**Comment by tcoopman** [comment]
@Akin909 If you look at batteries for somethings, I think having a look at [core](https://ocaml.janestreet.com/ocaml-core/latest/doc/core/index.html) would also be good.

**Comment by bryphe** [comment]
This is no longer an issue with the `libvim` work, as we no longer have the Msgpck transport layer - we get these ids directly as integers / pointer references.
