### ISSUE TITLE
Crash on Startup: Windows 7

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#850]
Reported on Discord - there was a report of a crash on startup:

> I downloaded the Windows version, and it crashes on startup. Any way I can get more information to feed back rather than "it crashes"  and what's in the "view details"  windows of the crash reporter?

> I saw above about setting ONI2_DEBUG and starting -f, but apart from "creating window", there's still not much of help.

Some additional information that would be helpful:
- What version of Windows is the crash occurring?
- Is it x86 or x64 Windows?
- What graphics card is being used?

In addition, running the editor via the command line with the `-f` flag would be very helpful in getting the logs - letting us know how far we get:
```
C:\Program Files\Onivim2\Oni2_editor.exe -f
```

**Comment by bryphe** [comment]
I've tested on two Windows 10 machines and haven't seen the issue - but I'm wondering if replaces it's occurring on an earlier Windows version? We use some specific APIs for handling DPI awareness and scaling, that may be problematic on earlier Windows versions.

**Comment by kevintts** [comment]
Thanks for Creating the Ticket.
Using Windows 7 Pro,  64-bit,  16Gb RAM.
Graphics Card is Intel(R) HD Graphics 3000 On a Lenovo T520 Laptop
```
C:\Program Files\Onivim2>set ONI2_DEBUG = 1
C:\Program Files\Onivim2>"C:\Program Files\Onivim2\Oni2_editor.exe" -f
[INFO] [Revery]: Window: Starting window creation...
[INFO] [Revery]: Window: Using vsync: true
[INFO] [Revery]: Window: Creating window Oni2 width: 800 height: 600
```
From the Windows "has stopped working"  window, 
```
Problem signature:
  Problem Event Name:	BEX64
  Application Name:	Oni2_editor.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5da287dc
  Fault Module Name:	StackHash_3df4
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	0000000000000003
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	3df4
  Additional Information 2:	3df44c82c3453b9d2ef6eb266b5962c2
  Additional Information 3:	ec83
  Additional Information 4:	ec83d3a522412845c1ec492327d652fe
```
Downloaded yesterday, think it's v. 2.0.2.0
Oni2_editor.exe digitally signed ‎13 ‎October ‎2019 03:11:52

**Comment by bryphe** [comment]
I brought in some additional logging to get some more details; unfortunately I don't have access to a Win7 machine to test, though!

**Comment by kevintts** [comment]
Downloaded Version: 2.0.2.0 Date: 10/17/2019, 3:28:45 AM
 Still the same
C:\Program Files\Onivim2>set ONI2_DEBUG = 1

C:\Program Files\Onivim2>"C:\Program Files\Onivim2\Oni2_editor.exe" -f
[INFO] [Revery]: Window: Starting window creation...
[INFO] [Revery]: Window: Using vsync: true
[INFO] [Revery]: Window: Creating window Oni2 width: 800 height: 600

If I can help test your version with more logging, I'd be glad to help

**Comment by bryphe** [comment]
Thanks for the update @kevintts ! Interesting - it's failing at creating the SDL2 window - didn't hit any of the new logging.

I saw this thread: https://steamcommunity.com/app/262390/discussions/1/527273452875796792/ where a user hit a similar crash for a game with SDL2 on Windows 7. After updating their drivers - it worked.

Just wondering - what GPU are you using? Maybe that can give us some clues too. 

If you're up for building from source - building and running this project: https://github.com/revery-ui/reason-sdl2 could be helpful! We could add logging there to track down the issue.

Still trying to hunt down a Win7 machine to test on

**Comment by kevintts** [comment]
I'm using an intel HD 3000 with latest drivers.

reason-sdl2 crashed in what appeared to be the same way as onivim.

```
C:\Development\reason-sdl2>esy x test_sdl2
←[0;1mFile "dune", line 1, characters 17-31:←[0m
1 | (ignored_subdirs (node_modules))
                     ^^^^^^^^^^^^^^
←[1;35mWarning←[0m: ignored_subdirs is deprecated in 1.6. Use dirs to specify visible
directories or data_only_dirs for ignoring only dune files.
←[0;1mFile "dune", line 1, characters 17-31:←[0m
1 | (ignored_subdirs (node_modules))
                     ^^^^^^^^^^^^^^
←[1;35mWarning←[0m: ignored_subdirs is deprecated in 1.6. Use dirs to specify visible
directories or data_only_dirs for ignoring only dune files.
```

Windows 7 machines for testing - https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ ?
Technically it's for testing different versions of Internet explorer, but they're Windows 7 machines.

**Comment by bryphe** [comment]
Thanks @kevintts for all the help - much appreciated!

> Windows 7 machines for testing - https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ ?
Technically it's for testing different versions of Internet explorer, but they're Windows 7 machines.

Ah I actually saw this... but unfortunately the VMs are only x86 , and Onivim 2 / the toolchain only supports x64. Still working on tracking something down!

**Comment by bryphe** [comment]
I created a branch of `reason-sdl2` called `windows-7-logging` - might give us a bit more info if you're up for trying that. Sorry about the back and forth. Hopefully I can get my hands on a machine to repro soon.

**Comment by kevintts** [comment]
FYI, I added a couple of other `prinf`s 
```  
printf("Calling create window with title: %s width: %d height: %d\n", String_val(vName), width, height);

  SDL_Window *win = (SDL_CreateWindow(
      String_val(vName), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, width,
      height,
      SDL_WINDOW_OPENGL | SDL_WINDOW_ALLOW_HIGHDPI | SDL_WINDOW_RESIZABLE));
  printf("Called create window\n");
  value vWindow = (value)win;
  printf("Set value of Window\n");
  CAMLreturn(vWindow);
```
and they all worked before the crash:
```
SDL_INIT returned: 0
Setting SDL_GL_CONTEXT_PROFILE_MASK
Setting SDL_GL_CONTEXT_MAJOR_VERSION
Setting SDL_GL_CONTEXT_MINOR_VERSION
Setting SDL_GL_DOUBLEBUFFER
Calling create window with title: test width: 100 height: 100
Called create window
Set value of Window
```

**Comment by bryphe** [comment]
Since Windows 7 is EOL now - we'll remove this from our support matrix, and focus on better support for Windows 8/10 (the biggest issue being moving from OpenGL -> DirectX)
