### ISSUE TITLE
Crash: Inserting code in visual mode

### ISSUE THREAD

**Issue by kacperkapusciak** [onivim/oni2#854]
### Steps to reproduce:

1. Opened a file
2. Opened visual mode `v`
3. Selected a few lines `2j`
4. Pressed `Shift`+`i` and tried to type something
5. Oni completely freezes

### Repeatable?
Yes.
### OS
Ubuntu 19.04
<hr>
Bought Oni yesterday and I'm so happy - it's blazing fast! Great job so far :heart:

**Comment by bryphe** [comment]
Hi @kacperkapusciak ,

Thanks for logging the issue! I believe this to be a dup of #471 - if that's the case, would you mind 👍 'ing that issue? Helps me prioritize

> Bought Oni yesterday and I'm so happy - it's blazing fast! Great job so far ❤️

So great to hear! Thank you for supporting the project ❤️ I think we have a nice technical foundation with native ReasonML - once we fix these sorts of issues and getting the language integration... we'll be in good shape 😎
