### ISSUE TITLE
Edit buffer crashes

### ISSUE THREAD

**Issue by romgrk** [onivim/oni2#86]
**Steps**:
 - Run `esy x Oni2`
 - Type `:e Oni.install`

**Result**: Oni2 crashes
**Expected**: buffer is opened

Terminal log:
```
Raw Notification: redraw | [[wildmenu_show,
  [[Oni2.install, Oni2.opam, OniBench.install, OniBench.opam,
    OniUnitTestRunner.install, OniUnitTestRunner.opam, Oni_Core.install,
    Oni_Core.opam, Oni_Neovim.install, Oni_Neovim.opam, Oni_UI.install,
    Oni_UI.opam]]], [wildmenu_select, [0]],
 [cmdline_show, [[[0, e Oni2.install]], 14, :, , 0, 1]], [flush, []]]
[DEBUG - STATE] Mode: commandline editor font measured width: 8 editor font measured height: 16
[DEBUG - STATE] Mode: commandline editor font measured width: 8 editor font measured height: 16
[DEBUG - STATE] Mode: commandline editor font measured width: 8 editor font measured height: 16
[DEBUG - STATE] Mode: commandline editor font measured width: 8 editor font measured height: 16
[DEBUG - STATE] Mode: commandline editor font measured width: 8 editor font measured height: 16
Protocol Notification: unknown
Raw Notification: redraw | [[wildmenu_hide, []], [flush, []]]
Fatal error: exception Failure("hd")
```

**Comment by Akin909** [comment]
@romgrk I can't reproduce this error on master :thinking:, are you seeing or doing anything else also did you run the bootstrap command? What system are you on?

**Comment by romgrk** [comment]
Yes, I've ran `esy install && esy bootstrap && esy build && esy x Oni2` with the master branch just now.

![screenshot from 2019-02-25 17-58-08](https://user-images.githubusercontent.com/1423607/53374660-f399e380-3926-11e9-9e5c-15494f48fe23.png)

Not sure how to debug esy's ocaml, but if you have some tips I'd be happy to.

**Comment by bryphe** [comment]
Thanks for logging the issue, @romgrk ! Usually this exception comes from here:
https://github.com/onivim/oni2/blob/8cf65cdf657c852f7d76f37d985bd7746ebf6c13/src/editor/Neovim/NeovimApi.re#L137

And it means that we didn't get a response from a request we sent to the Neovim API, but we were expecting one. It'd be helpful to log out the `methodName` in this case to see which request it is failing at (we should also have better logging in general for th is 🤔 )

We saw cases where when it picked up an `init.vim` and hit issues, but I don't think that is the case here.

It'd be interesting too to run the tests and see if those pass  - `esy x OniUnitTestRunner`.

**Comment by tcoopman** [comment]
Wouldn't it be interesting to use another list library that doesn't throw on an empty list but returns options, so you are required to handle these cases explicitly. Even though you probably have no very good options here to handle the empty list

**Comment by bryphe** [comment]
Yes, was just thinking about this - we should at the very least check `List.length` prior to `List.hd` (or we could create a wrapper `List.hd_opt` that returns an option), and provide more information here. At the very least - if it could give more details, like "Request 'nvim_open_buf' failed", it might help narrow downt he investigation.

**Comment by Akin909** [comment]
Think we could definitely do this without a new dependency, by wrapping the call in a `try` and returning None if Not found is raised or returning the values

**Comment by tcoopman** [comment]
Wouldn't a patternmatch also be a good alternative? `switch (list) { | [] => ... | [hd] => ...}`

**Comment by romgrk** [comment]
@bryphe here is the result of the tests: https://gistpreview.github.io/?a07cbe32ba939e9f968e6f1ea157deb4
