### ISSUE TITLE
Experimental autoClosingPairs feature cursor offset

### ISSUE THREAD

**Issue by necabo** [onivim/oni2#876]
When using `"experimental.autoClosingPairs": true` automatically closing pairs works just fine. However when deleting the first element of the pair (e.g. an opening brace) the cursor gets offset by a character to the left. 

Since I can't seem to explain it any better here's an example using `<|>` as the cursor position: 
```
foo<|>
foo(<|>)  // insert an opening parenthesis; auto-closes the parenthesis
fo<|>o  // backspace the opening parenthesis; closing parenthesis is auto-removed
```

Since this only happens at the end of a line it might actually be related to another issue mentioned in discord earlier:

> also, i was wondering why the cursor trails off instead of staying at the last character of the line?
![](https://cdn.discordapp.com/attachments/417774914645262341/635269300973994004/unknown.png)

**Comment by bryphe** [comment]
Nice find, @necabo ! I believe this should be fixed now with https://github.com/onivim/oni2/pull/965 - made some fixes for auto-closing pairs in `reason-libvim` and pulled in. So I'll close this out, but let me know if you're still seeing any issues.

Going to work on having this on-by-default soon...
