### ISSUE TITLE
Feature: Additional variables for titlebar

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#880]
PR #879 adds a custom titlebar, that can be specified via the `window.title` configuration setting.

VSCode supports a rich set of configuration settings:
```
  // Controls the window title based on the active editor. Variables are substituted based on the context:
  // - `${activeEditorShort}`: the file name (e.g. myFile.txt).
  // - `${activeEditorMedium}`: the path of the file relative to the workspace folder (e.g. myFolder/myFileFolder/myFile.txt).
  // - `${activeEditorLong}`: the full path of the file (e.g. /Users/Development/myFolder/myFileFolder/myFile.txt).
  // - `${activeFolderShort}`: the name of the folder the file is contained in (e.g. myFileFolder).
  // - `${activeFolderMedium}`: the path of the folder the file is contained in, relative to the workspace folder (e.g. myFolder/myFileFolder).
  // - `${activeFolderLong}`: the full path of the folder the file is contained in (e.g. /Users/Development/myFolder/myFileFolder).
  // - `${folderName}`: name of the workspace folder the file is contained in (e.g. myFolder).
  // - `${folderPath}`: file path of the workspace folder the file is contained in (e.g. /Users/Development/myFolder).
  // - `${rootName}`: name of the workspace (e.g. myFolder or myWorkspace).
  // - `${rootPath}`: file path of the workspace (e.g. /Users/Development/myWorkspace).
  // - `${appName}`: e.g. VS Code.
  // - `${remoteName}`: e.g. SSH
  // - `${dirty}`: a dirty indicator if the active editor is dirty.
  // - `${separator}`: a conditional separator (" - ") that only shows when surrounded by variables with values or static text.
  "window.title": "${dirty}${activeEditorShort}${separator}${rootName}${separator}${appName}",
```

However, we only support the following right now:
- `${activeEditorShort}`
- `${separator}`
- `${rootName}`
- `${dirty}`

This is tracking adding the additional variables. The place these would be added is here: https://github.com/onivim/oni2/blob/d99801e4c3c7a8e00c774d7befd2e0449c1d26b6/src/Store/TitleStoreConnector.re#L15

The `getTemplateVariables` takes our application state as a function, and returns a list of template variables -> values.  We have both the workspace path as `state.workspace.rootName` and the active buffer file path available in that method, which should allow us to derive most of those.

**Comment by shulhi** [comment]
I have some of the variables implemented and some that I'm not sure of how to proceed. Is it fine to do a PR for those variables I have implemented?

**Comment by bryphe** [comment]
@shulhi - opening a PR would be great! Thank you for implementing some more of these 👍

**Comment by marcagba** [comment]
Hi!
This is just to let you know that I'm currently working on exposing `${folderName}` and `${folderPath}` !

**Comment by marcagba** [comment]
So, it turns out that, as long as #729 isn't implemented, `${rootName}` `${rootPath}`and `${folderName}` `${folderPath}` should return the same values !

From what I've seen, in vscode `rootName` and `rootPath` are related to the workspace's settings file. `folderName` and `folderPath` are related to the folders declared within the workspace settings (see [Multi-root Workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces))

And `${remotePath}`doesn't make sense for Oni2 for the time being, since there's currently no Remote development possibilities with Oni2.

PR coming soon !

**Comment by bryphe** [comment]
I believe these are mostly implemented now - we can look at implementing any remaining ones in a separate issue :+1:
