### ISSUE TITLE
Mac app appears as Onivim2.App.app

### ISSUE THREAD

**Issue by mikl** [onivim/oni2#881]
A small eyesore from the latest nightly, the app bundle appears to be called `Onivim2.App.app` 

<img width="660" alt="Screenshot 2019-10-22 at 02 20 08" src="https://user-images.githubusercontent.com/10263/67252297-9b45c200-f472-11e9-9f31-2ca04d667931.png">

This is on macOS “Catalina” 10.15 (19A602)

**Comment by CrossR** [comment]
I've noticed this as well, it also pops up in spotlight.

**Comment by mikl** [comment]
Here’s how it looks from the CLI

```
[mikl:/Volumes/Onivim 2] % ls -lah
total 40
drwxr-xr-x  6 mikl  staff   272B 21 Oct 03:40 .
drwxr-xr-x  7 root  wheel   224B 22 Oct 10:37 ..
-rw-r--r--  1 mikl  staff    15K 21 Oct 03:40 .DS_Store
drwxr-xr-x  3 mikl  staff   102B 21 Oct 03:40 .background
lrwxr-xr-x  1 mikl  staff    13B 21 Oct 03:40 Applications -> /Applications
drwxr-xr-x  3 mikl  staff   102B 21 Oct 03:40 Onivim2.App
```

My guess is that `.App` (capital A) is not recognized as the proper extension for an app bundle, and macOS then “helpfully” adds `.app` to ensure the bundle works properly.

**Comment by bryphe** [comment]
Thanks for reporting this, @mikl !

> My guess is that .App (capital A) is not recognized as the proper extension for an app bundle, and macOS then “helpfully” adds .app to ensure the bundle works properly.

I think you're right. What's strange is I don't see this on Mojave (10.14.5) - might be something new in Catalina. I need to do some testing on Catalina-

**Comment by mikl** [comment]
Can confirm that this is fixed in the latest nightly:

<img width="660" alt="Screenshot 2019-10-27 at 19 29 46" src="https://user-images.githubusercontent.com/10263/67639462-251ce180-f8f0-11e9-8362-4505d14aa312.png">

**Comment by bryphe** [comment]
Thank you @mikl !
