### ISSUE TITLE
Font loading has bad defaults

### ISSUE THREAD

**Issue by CrossR** [onivim/oni2#884]
If an invalid font is given in the user config, or more likely a misspelling/not the expected formatting, we default back to other fonts currently.

This is particularly bad on Windows, which `reason-font-manager` has this code in it (specifically in the Windows `cpp` file):

```cpp
    // ok, nothing. shouldn't happen often. 
    // just return the first available font
    if (fonts->size() == 0) {
      delete fonts;
      fonts = getAvailableFonts();
    }
``` 

This means that we start using Arial for the editor, which isn't monospaced, but also we aren't even aware there was an issue since we just get given back a font.

This is made worse since from Oni2s perspective it sees Arial, measures it and realises it is not monospace, and then alerts the user....but since it doesn't know a default font was loaded we tell the user that the font they gave had an error, not that we are using a bad default font.

I think the fix here should be that we return back nothing rather than an incorrect font. We can then deal with this in the Reason layer, by either allowing a second font (a default) to be used directly in `reason-font-manager`, or in the Oni2 level. Unless I'm mistaken, dealing with this in the C++ layer seems harder, since Revery can vendor fonts and I don't know if that will complicate a search for a default in the C++ layer vs just dealing with it in Reason (which is already solved since we load vendoreed fonts already).

**Comment by bryphe** [comment]
Thanks for the great write-up @CrossR !

> This is made worse since from Oni2s perspective it sees Arial, measures it and realises it is not monospace, and then alerts the user....but since it doesn't know a default font was loaded we tell the user that the font they gave had an error, not that we are using a bad default font.

Ouch!

> I think the fix here should be that we return back nothing rather than an incorrect font.

This makes sense. For example, on Windows, we could fallback to `Consolas` or our vendored Fira-Code. We'd have to tweak the bindings a bit:
https://github.com/revery-ui/reason-font-manager/blob/21050a0e7b58aa4da61b08f937a049a039cd20a2/src/FontManager.re#L5

Such that we return a `result(FontDescriptor.raw)` instead. We could start by having OSX / Linux just return `Ok(..), but fix this on Windows to return `Error` in the case you called out 👍 

For Onivim 2, it'd be pretty easy to fallback - we could just load our bundled FiraCode
