### ISSUE TITLE
Kudos to your hard works!

### ISSUE THREAD

**Issue by sangdth** [onivim/oni2#887]
Hi, this is not a real issue, I just do not know where to say.

It's super exciting to see the notifications from oni flood my mailbox everyday. Kudo to your hard works!

Feel free to close this "issue" <3

**Comment by bryphe** [comment]
Hi @sangdth ! Really appreciate this - so nice to wake up and find an 'issue' like this 😄  Thank you!

We still have a lot of work ahead to get to our complete release - but we're working hard to get there! Making steady progress.... I'm excited about our tech stack and the potential for us to realize the goals of the project and really level up compared to our v1.

Feel very fortunate for all the support from the community and all the help from our collaborators to make it happen!
