### ISSUE TITLE
make titlebar themeable

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#895]
As of now under macOS the titlebar is the default titlebar of the OS. Especially on macOS darkmode the light titlebar is really irritating and I think the whole editor look would benifit from a themable titlebar.

VSCode has the titlebar in the same style as the editor, see this screenshot for comparison:

![titlebar](https://user-images.githubusercontent.com/8280409/67480272-e53fcb00-f65f-11e9-95f2-17b86786f444.png)

**Comment by CrossR** [comment]
Related to this over in Revery: https://github.com/revery-ui/revery/pull/521
