### ISSUE TITLE
Editorwindow black on window resize

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#896]
This definitely didn't occur in previous releases. As of now, if I resize the window under macOS the window will turn black and only renders again if I release the mouse.

**Comment by bryphe** [comment]
Thanks for logging the issue, @kinglouie !

Indeed - this is a regression from our move from GLFW -> SDL2. The way resize events are handled are a bit different (the event queue gets 'blocked' while the resize is in progress).

We'll need to hook up a listener to catch resize events while they are in-progress and re-render, like: https://stackoverflow.com/questions/32294913/getting-contiunous-window-resize-event-in-sdl-2

**Comment by bryphe** [comment]
It looks like we no longer show a black window on resize - however, we still are hitting the default SDL2 resize behavior (which is to squish / shrink until the resize gesture is complete - described in #1318 ).

I'll use #1318 to track improving the SDL2 resize behavior
