### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Mike-Now** [onivim/oni2#90]
Due to many missing (I presume implicit system) dependencies the project does
not compile when one tries to follow steps outlined in the README. 
I tried to install them, but finally got stuck on the harfbuzz error.  That was on a Linux Mint system.
On a different Fedora machine I managed to compile it, but it crashes due to hardcoded dependency on the harfbuzz library expected on the specified path. 

Please provide, if possible, working Dockerfile that describes minimal system necessary to compile and run the project.

**Comment by nganhkhoa** [comment]
Please reference my issue. #56.

**Comment by Mike-Now** [comment]
It's actually an issue with the reason libraries. Those should be update in the esy.lock after they are fixed as per:
https://github.com/revery-ui/revery-quick-start/issues/5

**Comment by alexmironof** [comment]
@Mike-Now first of all try to delete `~/.esy` and `.../oni2/_esy` folders and then run `esy install`
also you need `libgtk-3-dev` - that dependency doesn't lists in docs

**Comment by Akin909** [comment]
is this resolved @Mike-Now ?

**Comment by Akin909** [comment]
@Mike-Now I'm going to close this out please let me know if its still an issue, we've also tweaked the `README.md` as that the likely source of confusion re. the required dependencies to run this in dev
