### ISSUE TITLE
Asking refund possible?

### ISSUE THREAD

**Issue by dalisoft** [onivim/oni2#900]
Hi @onivim team!

I today purchased Oni2, downloaded, seems doesn't support macOS Sierra!

There some cons:
- OS X and macOS Sierra support doesn't exist
- Fuzzy-search at left panel does not exist (also not able to search how to enable)
- VSCode themes does not work
- VSCode extensions does not work

I am sorry, but for me (only for me), does not worth its price.

Also I asked in Discord, none of them are replied.

Mail: dalisoft@mail.ru, check your DB for payments, I today purchased.

**Comment by bryphe** [comment]
Hi @dalisoft !

Sorry about the issues!

> OS X and macOS Sierra support doesn't exist

OSX 10.13+ is supported, but unfortunately 10.12 isn't supported. Will track it here: https://github.com/onivim/oni2/issues/902 . In addition, I'll add a 'System Requirements' page to our documentation and link to it on the main page.

> Fuzzy-search at left panel does not exist (also not able to search how to enable)

Ya, I can see how this would be misleading - we have that in our screenshot but it was a placeholder at the time. I'll update the screenshot with what we have on `master` - and hopefully we'll have it enabled for me soon.

> VSCode themes does not work

We actually support VSCode themes today, but the entry point isn't very straightforward (they have to be manually installed). Hopefully we can smooth that out soon.

> VSCode extensions does not work

Indeed - this is what we're actively working on this milestone.

> I am sorry, but for me (only for me), does not worth its price.

Sorry to hear that! We'll keep working on it and addressing these gaps - hopefully down the road as we get more complete you'll check it out again.

**Comment by taskindrp** [comment]
@bryphe so is refund possible or not?

**Comment by dalisoft** [comment]
@bryphe As a development is stopped i am also want refund again
@taskindrp previous time refund was did but i am wanted to support project development
