### ISSUE TITLE
OSX Sierra (10.12) support

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#902]
Unfortunately today we don't support OSX Sierra (10.12) - this should be doable, we just need to set up our CI to work with 10.12. 

The earliest build available for the Microsoft-hosted CI is 10.13. We have a couple options:
- Use an alternate CI provider that can use 10.12
- Stand up our own CI agent for 10.12

**Comment by bryphe** [comment]
This has been asked for a few times - something we need to find a solution for-

**Comment by CrossR** [comment]
Travis seems to support 10.12 (Well, it supports back to 10.10 apparently): https://docs.travis-ci.com/user/reference/osx/#macos-version
