### ISSUE TITLE
Use a better default working directory

### ISSUE THREAD

**Issue by glennsl** [onivim/oni2#906]
Currently it seems to default to the directory it is launched from interactively, which the user might not have permission to write to, and which probably isn't where the user wants to edit files anyway.

Better defaults might be:
- The OS-specific Documents directory
- The user/home directory
- A dedicated workspace directory created initially and in whatever OS-specific directory is appropriate.
- Nothing
- To ask

**Comment by CrossR** [comment]
The only thing that gives me pause with setting it to the Home dir is the potentially bad experience people have with relation to the QuickOpen.

No matter how fast its made, its still going to be pretty slow to recurse a full user directory, and on macOS the user also gets annoying prompts (well annoying and worrying "Oni2 is trying to access your calendar").

Documents makes sense I think, or just none at all like VSCode defaults to. However, I think currently we maybe don't have the option for "Nothing".

**Comment by glennsl** [comment]
Home dir seems like a good starting point for navigating to where you actually want to be though. Do you mean it currently recurses the entire workspace for the file explorer?

"Nothing" is a great suggestion. Added that to the top post.

**Comment by CrossR** [comment]
>Home dir seems like a good starting point for navigating to where you actually want to be though. Do you mean it currently recurses the entire workspace for the file explorer?

The explorer is smart enough to go 2 folders deep and stop I think, its the `Cmd/Ctrl-P` that will just go through every file and folder the user has. On macOS, if you try to acess `~/Library/Calendars/` or similar, the user starts getting security pop-ups of "Oni2 is trying to access your calendar, is this okay?" which understandably will cause some people to go "Why is my text editor reading my calendar!".

We could add a custom filter list to avoid some places people are unlikely to want to quick open over from the home folder, then that becomes less of an issue.

**Comment by ashton** [comment]
I would like to help with this one, the idea is to start inside the home folder and avoid the `Cmd/Ctrl-P` to freeze going too deep inside user file's ?

**Comment by glennsl** [comment]
Awesome @ashton, thanks for wanting to help!

I'm not entirely sure which option would be best here, but I think the two easiest ones to implement would be

- The Documents folder, but that's platform-specific and configurable, so we need some way to figure out which exact folder that is.
- The Home folder, but we'll need a blacklist of some kind to exclude "special" folders when searching. We could implement that using either the `--glob` or `--ignore-file` options for ripgrep. The former would require a new configuration value I think, while the latter could use a separate ignore file that we bundle.

Whichever of those sound easiest to you seems like a good enough choice to me.

**Comment by zeux** [comment]
This is sort of related - apologies if this is already tracked elsewhere - but having a quick way to *change* the folder would be great. Every time I launch onivim from the Windows Start menu I'm stumped - it opens Onivim2 folder (which I'm not interested in) and offers me no way that I can find to change the folder, so I must close it, and launch it again from the correct folder manually.

**Comment by glennsl** [comment]
You can use `:cd` to change the folder. It autocompletes and everything. We should definitely have a more discoverable way to do it as well, but that might involve some native integration to open the systems file open dialog.

**Comment by glennsl** [comment]
I made a PR to add a section to the documentation with some useful ex commands here: https://github.com/onivim/oni2/pull/1312

**Comment by lessp** [comment]
Just to throw my vote in, it'd be for either nothing, which I think is a good default, or the home-directory. 🙂

**Comment by bryphe** [comment]
FYI, the challenge with `~` (home) on OSX is the default is that we hit https://github.com/onivim/oni2/issues/619 - as we recurse to populate the file explorer, we get permissions dialogs come up saying 'Onivim 2 wants to access your calendar' and 'Onivim 2 wants to access your contacts' - it's a horrible first experience! At least on OSX - I think the `Documents` folder would be a reasonable default, though.
