### ISSUE TITLE
Crash on search `/i` followed by `//`

### ISSUE THREAD

**Issue by canadaduane** [onivim/oni2#916]
When in an empty file (immediately after starting Onivim2), I press `/i` [ESC] followed by `//` and Onivim2 crashes. Sometimes I need to repeat `//` a few times to get the same behavior.

Running on Windows, latest nightly.

**Comment by paskausks** [comment]
Yeah, reproduction is inconsistent on Windows 10.

At first, I reproduced on first try. `oni2 --nofork` output attached - [oni2-log.txt](https://github.com/onivim/oni2/files/3792153/oni2-log.txt).

After continuous tries (`//<ESC>//<ESC>` rinse and repeat) I got a libvim error "E35: No previous regular expression". In one instance after dismissing the libvim error with ESC, pressing `//` again crashed oni2.

**Comment by bryphe** [comment]
Thanks @paskausks and @canadaduane ! I'm able to repro as well. Doesn't seem to reproduce on Mac - just Windows (I was running Win10).

It's crashing in `libvim` - between when we send the `/` key and when it returns back. Need to add some logging to trace where in the middle it is failing.

**Comment by bryphe** [comment]
I believe this is fixed by some libvim changes (https://github.com/onivim/libvim/pull/228) - I tried to reproduce this again on Windows 10 and was unable to, on latest `master`.
