### ISSUE TITLE
esy bootstrap throwing error in Windows

### ISSUE THREAD

**Issue by dineshKumar777** [onivim/oni2#959]
I am trying to build Oni2 in windows os. But getting following error when running esy bootstrap command.

```
D:\oni2_2\oni2>esy install
info install 0.5.8 (using package.json)

D:\oni2_2\oni2>esy bootstrap
error: Undefined variable 'esy-sdl2.bin'
  processing esy.install
  creating task for Oni2@link-dev:./package.json
esy: exiting due to errors above

```

**Comment by CrossR** [comment]
I've not seen that before (that I can remember, though it can be hard to keep track).
We build on Windows as part of CI and my main dev machine is Windows, so it should work fine.

I can see your `esy` version is `0.5.8`, but could you tell us the `node` version as well as the Windows OS version?

I'll give it a try when I'm back home tonight and just check if mine still work and what versions of things I have.

**Comment by dineshKumar777** [comment]
node -v => v12.3.1
Windows os build numb => 18362.356

Please share ci or your local version details incase if you are not able to reproduce to update and recheck it from my end. Thanks

**Comment by CrossR** [comment]
So its happy enough on my machine, and I've got node 10.16.3 and the same OS version as you.

The Windows CI also uses Node 10.X by the looks of it, but I see no reason that the node version would be causing this issue (I don't think so at least). I'll try updating and see...

**Comment by dineshKumar777** [comment]
@CrossR 
I didn't faced this issue when I tried building the application freshly in my spare system. 
Still I dont know why I am getting this error in my work machine. Anyway you can close this issue since we are not able to reproduce. 
Thanks

**Comment by ManasJayanth** [comment]
Just a note for future readers: across esy upgrades, the `~/.esy`  store might get stale/incompatible. If someone runs into this again, and absolutely nothing else helps, please clear `~/.esy` and retry. This helped someone on Discord today.
