### ISSUE TITLE
cmd + w kills the whole app instead of closing a tab

### ISSUE THREAD

**Issue by chriskrycho** [onivim/oni2#992]
When working with tabs, it's pretty common to close one. Unfortunately, at the moment, <kbd>⌘</kbd><kbd>w</kbd> current results in the entire app closing. And I don't *yet* know how to close tabs any other way (though I'm poking and I'm sure I'll figure it out soon).

Related, but not identical: #759

**Comment by bryphe** [comment]
Fixed by #1178

**Comment by chriskrycho** [comment]
Thank you!
