### ISSUE TITLE
Blank Blue Screen When Launched

### ISSUE THREAD

**Issue by bigredjoe** [onivim/oni2#994]
When I launch Onivim2, All that get's displayed is a blank blue screen. I can execute vim commands, but I don't see anything.

OniVim2 Version: 0.2.0
Operating System: Windows 10 running on Parallels 15 VM

![Screen Shot 2019-12-02 at 11 29 20 AM](https://user-images.githubusercontent.com/145475/69982125-5abd7780-14f9-11ea-94ec-425f6b26f773.png)

**Comment by CrossR** [comment]
Could you try running from the command line with `-f` and the `ONI2_DEBUG` environment variable set? I believe that should be `$env:ONI2_DEBUG = 1; oni2 -f` in powershell.

Would be helpful to get some logs to see if anything is happening.

I've seen similar behaviour before when the scaling was off.

**Comment by bigredjoe** [comment]
Hmm...my windows display scaling is set to 100%

Here is the log output when running:
`[INFO] Startup: Parsing CLI options complete
[INFO] Starting Onivim 2.
[INFO] Calling App.start
[INFO] Init
[INFO] [Revery]: Window: Starting window creation...
[INFO] [Revery]: Window: Creating window Oni2 width: 800 height: 600
[INFO] [Revery]: Window: Window created successfully.
[INFO] [Revery]: Window: Window id: 1
[INFO] [Revery]: Window: Setting window context
[INFO] [Revery]: Window: GL setup. Checking GL version...
[INFO] [Revery]: Window: Checking GL vendor...
[INFO] [Revery]: Window: Checking GL shading language version...
[INFO] [Revery]: Window: OpenGL hardware info - version: 2.1 ATI-2.11.20 vendor: Parallels and ATI Technologies Inc. shadingLanguageVersion: 1.20

[INFO] [Revery]: Window: Loading icon from: C:\Program Files\Onivim2\logo.png
[INFO] [Revery]: Window: Icon loaded successfully.
[INFO] [Revery]: Window: Icon set successfully.
[INFO] [Revery]: Window: Getting window metrics
[INFO] [Revery]: Window: _getScaleFactor - from getWin32ScaleFactor: 1.
[INFO] [Revery]: Window: Metrics: DevicePixelRatio: 1.000000 ScaleFactor: 1.000000 Zoom: 1.000000 Raw Dimensions: 800x600px Framebuffer: 800x600px
[INFO] [Revery]: Window: setScaledSize - calling with: 800x600
[INFO] [Revery]: Window: setRawSize - dimensions adjusted after scaling: 800 x 600
[INFO] [Revery]: Window: Using vsync: Immediate
[INFO] [Revery]: Window: _getScaleFactor - from getWin32ScaleFactor: 1.
[INFO] [Revery]: Window: _updateMetrics - new metrics: DevicePixelRatio: 1.000000 ScaleFactor: 1.000000 Zoom: 1.000000 Raw Dimensions: 800x600px Framebuffer: 800x600px
[INFO] Initializing setup.
[INFO] Startup: Parsing CLI options
[INFO] Startup: Changing folder to: C:\
[INFO] Startup: Starting StoreThread
[INFO] Searching for user extensions in: C:\Users\joseph.doty.HCSS\AppData\Local\Oni2\extensions
[PERF] Discover extensions took 0.0199825763702s
[INFO] -- Discovered: 29 extensions
[INFO] Themes: 
 - One Dark Pro
 - One Dark Pro Vivid
 - One Dark Pro Bold
 - Abyss
 - Dark+ (default dark)
 - Light+ (default light)
 - Dark (Visual Studio)
 - Light (Visual Studio)
 - High Contrast
 - Gruvbox Dark Medium
 - Gruvbox Dark Hard
 - Gruvbox Dark Soft
 - Gruvbox Light Medium
 - Gruvbox Light Hard
 - Gruvbox Light Soft
 - Kimbie Dark
 - Monokai
 - Monokai Dimmed
 - Nord
 - Quiet Light
 - Solarized Dark
 - Solarized Light
 - Tomorrow Night Blue
[INFO] Startup: StoreThread started!
[INFO] Vim - Buffer update: 1
[INFO] Vim - Buffer update: 1
[INFO] ConfigurationStoreConnector - Loading configuration: C:\Users\joseph.doty.HCSS\AppData\Local\Oni2\configuration.json
[INFO] loadAndValidateEditorFont filePath: C:\Program Files\Onivim2\FiraCode-Regular.ttf | size: 14
[INFO] Checking font rendering - glyph1: 43 glyph2: 178
[INFO] Got glyph for firstShape
[INFO] Got glyph for secondShape
[INFO] Font loaded! Measured width: 8. Measured height: 17.
[INFO] Loading 0 keybindings
[INFO] [Revery]: UI: Mouse entering window
[INFO] [Revery]: UI: Mouse leaving window
[INFO] [Revery]: UI: Mouse entering window
[INFO] Buffer metadata changed: 1
[PERF] exthost.bufferUpdate took 0.s
[INFO] Creating model for filetype: plaintext
[PERF] exthost.bufferUpdate took 0.s
[INFO] FontStoreConnector::synchronizeConfiguration
[INFO] loadAndValidateEditorFont filePath: C:\Program Files\Onivim2\FiraCode-Regular.ttf | size: 14
[INFO] Checking font rendering - glyph1: 43 glyph2: 178
[INFO] Got glyph for firstShape
[INFO] Got glyph for secondShape
[PERF] theme.load took 0.00400638580322s[INFO] Font loaded! Measured width: 8. Measured height: 17.

[INFO] [Revery]: Window: _getScaleFactor - from getWin32ScaleFactor: 1.
[INFO] [Revery]: Window: _updateMetrics - new metrics: DevicePixelRatio: 1.000000 ScaleFactor: 1.000000 Zoom: 1.000000 Raw Dimensions: 800x600px Framebuffer: 800x600px
[INFO] Creating model for filetype: plaintext
[INFO] [Revery]: App: Upshifting into active state.
[INFO] [Revery]: App: Upshifting into active state.
[INFO] [Revery]: App: Upshifting into active state.
[INFO] [Revery]: App: Downshifting into idle state...
[INFO] [Revery]: UI: Mouse leaving window
[INFO] ext host closed
[INFO] [Revery]: App: _tryToClose: Window canQuit is true - closing window: 1
[INFO] [Revery]: App: Quitting`

**Comment by bryphe** [comment]
Thanks for the details, @bigredjoe !

The log actually looks good... I suspect it might be related to this issue:
https://kb.parallels.com/en/115487

We're picking up a compatibility profile here: https://github.com/revery-ui/reason-sdl2/blob/07a409745d11e1b625fc63bd62b2481e1c135d0b/src/sdl2_wrapper.cpp#L940 - which it sounds like isn't supported in Parallels, from that KB post. 

I wonder if there is a way for us to detect if we are in a Parallels environment - or remove that version restriction to better support OpenGL Core.

**Comment by bryphe** [comment]
With the move to support ANGLE renderer - Onivim loads on Parallels for me:

![image](https://user-images.githubusercontent.com/13532591/90424913-c2115c80-e073-11ea-9ea1-a9964703588e.png)

So this this should be fixed now with #2283
